### ISSUE TITLE
ICMPv6 not parsing

### ISSUE THREAD

**Issue by 2stacks** [pfelk/pfelk#10]
I was having some issues with ICMPv6 messages parsing correctly.  It appears to be related to missing protocol data.  Changing the grok to below seems to have fixed it but I need more time to verify.  I'm not sure the last match pattern is necessary.  If it looks like a solid fix I can submit a pull request.

Example Message
> 11,,,1000000107,vtnet0,match,pass,in,6,0x00,0x00000,255,ICMPv6,58,32,fe80::201:5cff:fe74:d046,ff02::1:ffbb:5484,

Grok Change
```
grok {
  patterns_dir => ["/etc/logstash/conf.d/patterns"]
  match => [ 
    "message", "%{PFSENSE_LOG_DATA}%{PFSENSE_IP_SPECIFIC_DATA}%{PFSENSE_IP_DATA}%{PFSENSE_PROTOCOL_DATA}",
    "message", "%{PFSENSE_LOG_DATA}%{PFSENSE_IP_SPECIFIC_DATA}%{PFSENSE_IP_DATA}",
    "message", "%{PFSENSE_IPv4_SPECIFIC_DATA}%{PFSENSE_IP_DATA}%{PFSENSE_PROTOCOL_DATA}",
    "message", "%{PFSENSE_IPv6_SPECIFIC_DATA}%{PFSENSE_IP_DATA}%{PFSENSE_PROTOCOL_DATA}",
    "message", "%{PFSENSE_IPv6_SPECIFIC_DATA}%{PFSENSE_IP_DATA}"
  ]
}
```

**Comment by plague-doctor** [comment]
:+1:  
You do not need last match.
