### ISSUE TITLE
Error importing v4.2 (042020) Suricata Dashboard.ndjson.ndjson 121KB 23rd april 2020

### ISSUE THREAD

**Issue by myrsecurity** [pfelk/pfelk#101]
**Describe the bug**
in Kibama Saved Objects - import

select the new file : v4.2 (042020) Suricata Dashboard.ndjson.ndjson 121KB 23rd april 2020

Kibana stalls for 8 minutes, throws the following 

 Sorry, there was an error

The file could not be processed.

**Comment by a3ilson** [comment]
Please reference #98 

If that does not provide insight to solve your issue. Please provide additional details:
- Screenshot
- Details list of steps to reproduce the error
-- How did you download the dashboard 
-- How did you import the dashboard

**Comment by myrsecurity** [comment]
![image](https://user-images.githubusercontent.com/53452334/80099230-6f64df80-856e-11ea-8e1b-49b638721fa5.png)

details list of steps to reproduce the error
-- How did you download the dashboard
on https://github.com/3ilson/pfelk/tree/master/Dashboard
chrome, hover over the new dashboard file ( v4.2 (042020) Suricata Dashboard.ndjson.ndjson ) save as to local
-- How did you import the dashboard
On kibana,  stalls for 8 minutes
![image](https://user-images.githubusercontent.com/53452334/80099578-f5812600-856e-11ea-8be7-514c3ff7ecf8.png)

then throws
![image](https://user-images.githubusercontent.com/53452334/80099602-029e1500-856f-11ea-9410-8281809bbb94.png)

**Comment by a3ilson** [comment]
Please download the file again, it was improperly named (corrected) and just tested w/o issue.

**Comment by myrsecurity** [comment]
sorry same error - another reason this time: 
the downloaded file has HTML content instead reporting dashboard specific code ( if you rename it to html displays this page )

**Comment by myrsecurity** [comment]
ok I see.... I was importing it in a different manner - building the file was different.

Still I got an error500 now.. server non  responsive

cheers

**Comment by rrosson** [comment]
> Still I got an error500 now.. server non responsive

Yeah GitHub is acting sketchy in my area of the internet too.   :(

**Comment by myrsecurity** [comment]
it worked, thank you

**Comment by revere521** [comment]
excellent, closing
