### ISSUE TITLE
Suricata Alert Dashboard doesnt show any alerts

### ISSUE THREAD

**Issue by myrsecurity** [pfelk/pfelk#104]
![image](https://user-images.githubusercontent.com/53452334/80144240-727fc000-85ae-11ea-8e8d-e09093b02de4.png)
VS

![image](https://user-images.githubusercontent.com/53452334/80144439-c5f20e00-85ae-11ea-998b-51b127d18e99.png)

Ive adhered to the guide to the (.) - had some issues importing the dashboards etc but they are now there. Problem is I cant see the alerts in Kibana. 

Thank you

**Comment by a3ilson** [comment]
@myrsecurity - Looks like the old dashboard which will not work with the latest version.  Please use the updated dashboard --> https://github.com/3ilson/pfelk/blob/master/Dashboard/v4.2%20(042020)%20Suricata%20Dashboard.ndjson

**Comment by revere521** [comment]
i'm also going to close this one as asked and answered as well, to keep focus on the suricata alerts issue. It seems you have the correct dashboard installed there.
