### ISSUE TITLE
What do we use this 'dashboard' for: GeoIP(Template)

### ISSUE THREAD

**Issue by myrsecurity** [pfelk/pfelk#106]
the file GeoIP(Template) is available in the dashboards folder - still you cant uploaded to Kibana as a valid dashboard ( missing extension). Trying to rename extensionless to .ndjson and import... doesnt like it.

question is, what is this file for?. seems to be useless there must be a reason though is there

cheers

**Comment by a3ilson** [comment]
@myrsecurity - that was a legacy import to identity the GeoPoint fields.  The process involved coping the contents and pasting into the Kibana Counsel (Dev Tools). Disregard all the items in the archive folder - they are no longer needed with the current version.

**Comment by revere521** [comment]
i'm going to close this to keep focus on the other suricata issue, since its asked and answered
