### ISSUE TITLE
Is 8.8.8.8 hard-coded somewhere in this configuration? 

### ISSUE THREAD

**Issue by myrsecurity** [pfelk/pfelk#108]
192.168.0.11 is the ELK Server

We dont use 8.8.8.8 in any shape or form in the office

Still I can see lots of queries to 8.8.8.8 from the ELK Server. 
This behavior is observed in both local and cloud deployments we are wokring on. 

![image](https://user-images.githubusercontent.com/53452334/80193320-dfc83b00-8618-11ea-9ad1-aec00672efe2.png)
\
I dont understand why 192.168.0.11 would DNS query Google, when it is instructed to go to the local DNS server. 

timestamp": "2020-04-24T10:44:38.156231+0200", "flow_id": 1988692897309960, "in_iface": "em1", "event_type": "dns", "src_ip": "192.168.0.11", "src_port": 32889, "dest_ip": "8.8.8.8", "dest_port": 53, "proto": "UDP", "dns": {"type": "query", "id": 12499, "rrname": "8.8.8.8.in-addr.arpa", "rrtype": "PTR", "tx_id": 14}}

In fact we have a rule in the office that redirects all DNS traffic to the local DNS Server.

Cheers

**Comment by myrsecurity** [comment]
More insights: 
![image](https://user-images.githubusercontent.com/53452334/80193924-e7d4aa80-8619-11ea-8062-e9a6638f53d7.png)


The firewall rule has processed 500MB of content since ELK installed!

**Comment by myrsecurity** [comment]
![image](https://user-images.githubusercontent.com/53452334/80194883-5bc38280-861b-11ea-8c9e-acc93061bea6.png)

ELK is flooding my system with DNS queries to 8.8.8.8 

Any idea on why is this doing this?

**Comment by a3ilson** [comment]
@myrsecurity - delete 40-dns.conf.  It uses 8.8.8.8 to conduct a reverse lookup of the IP address.   However, this is not required for the dashboard or any other operation within pfELK.

**Comment by rrosson** [comment]
@a3ilson I know this is closed. But instead of deleting 40-dns.conf I changed the dns to use my DNS servers.  :)

**Comment by a3ilson** [comment]
Than work too - thanks

**Comment by myrsecurity** [comment]
Yes that works, the flooding is out. 

Why do you conduct a reverse lookup of the IP address? Are you populating the results in a file or elsewhere ( itcould be useful to build a list on who is attempting to get in)

**Comment by a3ilson** [comment]
The 40-dns.conf file creates two fields if successful.  These fields are destination.dns and source.dns which enrich the data.  However, these fields are not required for any current dashboards and create ~double the dns queries.  It is an optional filter and if it yields little value, I would remove to improve overall efficiency.
