### ISSUE TITLE
Debian 9/10 Installation 

### ISSUE THREAD

**Issue by a3ilson** [pfelk/pfelk#109]
**Describe the bug**
Installing on Debian 9/10 requires additional configuration beyond what is provided in the instructions.

**To Reproduce**
Follow the instructions and pfELK will not work on Debian 9/10 without additional configuration

**Firewall System (please complete the following information):**
N/A
 
**Operating System (please complete the following information):**
 - OS Debian 9/10
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK 7.6.2
 
 **Elasticsearch, Logstash, Kibana logs:**
N/A

**Additional context**

**Comment by revere521** [comment]
From my experience with Debian 10.3 (just for documentation purposes here): 
the dependencies are:
`wget apt-transport-https gnupg2 software-properties-common dirmngr lsb-release ca-certificates`

for Java:
` openjdk-11-jre` is installable

GeoIP update must be installed from their amd64 deb:
`wget https://github.com/maxmind/geoipupdate/releases/download/v4.3.0/geoipupdate_4.3.0_linux_amd64.deb; sudo dpkg -i ./geoipupdate_4.3.0_linux_amd64.deb`

for Debian 10.3, thats all i needed beyond the existing instructions (its what we did for the ez installer)

**Comment by a3ilson** [comment]
I'm testing the install now with Debian 10.3.

I plan to revise pfELK in the next week or so.  My thought is to consolidate the necessary files to one location for the sake of troubleshooting:
e.g.
install path = /data/pfELK
conf files = /data/pfELK/configurations
patterns = /data/pfELK/patterns
templates = /data/pfELK/templates 
GeoIP = /data/pfELK/GeoIP
Logs = /data/pfELK/logs
*Will need to adjust the pipelines.yml to point to the alternate location
*Add a script to combine logs and conf for error reporting
-Thoughts?

**Comment by revere521** [comment]
I will follow your lead on that, it might be easier to find everything in one directory, for sure

what would the error reporting script do?

**Comment by a3ilson** [comment]
grab the logs from logstash (tail); list (print) all files within the
installation directory; grab the conf files

**Comment by revere521** [comment]
yes please

**Comment by a3ilson** [comment]
Debian tested on both script and manual methods with fresh vanilla install of Debian 10.3
