### ISSUE TITLE
Test of troubleshooting script (error.pfelk)

### ISSUE THREAD

**Issue by revere521** [pfelk/pfelk#113]
this is not a real issue, i was just testing the output of the new error script 

take a look and see if this is good

[error.pfelk.log](https://github.com/3ilson/pfelk/files/4535600/error.pfelk.log)

**Comment by a3ilson** [comment]
@revere521 - That's much easier to read (i.e. delineation); Thanks for enhancing!

**Comment by revere521** [comment]
closing as not a real issue

**Comment by a3ilson** [comment]
@revere521 - Thanks...it's much better.  I added the pipelines.yml and the logstash.yml log path to the output.
