### ISSUE TITLE
pkg: No packages available to install matching have been found in the repositories

### ISSUE THREAD

**Issue by AgalazMYR** [pfelk/pfelk#115]
Hi, I'm trying to install ELK stack on a PFSense from the shell, but when I put the command for install, it returns "No packages available to install matching 'elasticsearch' have been found in the repositories". With Kibana and Logstash it shows the same error. My PFSense version is 2.4.4, I updated repositories with "pkg update" but didn't updated anything, so I tried to force it with "pkg update -fq", in case this was the error, but nothing worked. I have also edited "/usr/local/etc/pkg/repos/FreeBSD.conf" and changed the value from "FreeBSD: {enabled:   }" to yes.

**Comment by CinoNY** [comment]
@AgalazMYR You wouldn't install this on your pfSense firewall but on a seprate Ubuntu or Debian box

**Comment by a3ilson** [comment]
@AgalazMYR - pfelk was not intended to be installed in conjunction with pfSense or OPNsense.  Please install on separate instance.
