### ISSUE TITLE
Could not locate that index-pattern-field (id: source.geo.country_name.keyword)

### ISSUE THREAD

**Issue by AndreLFSMartins** [pfelk/pfelk#117]
On the Firewall Dashboard for pfSense at the right up box instead of a graphic I have Could not locate that index-pattern-field (id: source.geo.country_name.keyword).

I refresh the log a couple of times and nothing. the geoip data is there I can see the files on the directory.

Not sure if it's been loaded or not. 

I'm also not getting info on Top IPs Blocked (Bar Graph).

**Comment by revere521** [comment]
In Kibana go to Management (gear icon) -> Index Patterns -> choose the pf-* pattern and refresh it by clicking the icon in the upper right. 

Did you also follow the steps in the guide to configure GeoIP?

**Comment by AndreLFSMartins** [comment]
Yes, I did refresh. I have 152 fields, not sure how many should I have. 
I can see in the template index that the GeoIP is created and associated with pf*. In theory I follow the steps in the guide line by line. 
I'm not seeing the Top IPs Blocked too. Not sure if it's related or not.

**Comment by a3ilson** [comment]
@andrema2 - can you provide a screen shot of the issue.  Additionally, can you provide a couple of raw messages?

**Comment by AndreLFSMartins** [comment]
Sure, how do I get the raw messages ?

**Comment by a3ilson** [comment]
Reply with the contents from the event.original field from a few of your messages.

**Comment by revere521** [comment]
you can also look at the troublesh0ooting section and post the output of the troubleshooting script here (as an attached file) https://github.com/3ilson/pfelk/blob/master/install/ubuntu.md#troubleshooting

**Comment by AndreLFSMartins** [comment]
Here some msgs

`event.action:block ttl:4 tags:pf, Rule_Description, dns @version:1 ip.flags:DF tos:0x0 reason:match @timestamp:May 12, 2020 @ 11:47:49.030 event.id:134 event.original:<134>May 12 11:47:49 filterlog: 5,,,1000000103,igb0,match,block,in,4,0x0,,4,0,0,DF,17,udp,316,192.168.15.1,239.255.255.250,1900,1900,296 event.created:May 12 11:47:49 host:10.2.2.1 observer.type:pfSense destination.port:1900 destination.user.ip:private destination.ip:239.255.255.250 packet.id:0 packet.length:316 rule_number:5 transport.data_length:296 offset:0 tracker:1000000103 pf_message:5,,,1000000103,igb0,match,block,in,4,0x0,,4,0,0,DF,17,udp,316,192.168.15.1,239.255.255.250,1900,1900,296 source.port:1900 source.user.ip:private source.ip:192.168.15.1 rule.description:no match labels:filterlog interface.alias:WAN interface.name:igb0 network.name:WAN network.direction:inbound network.transport:udp network.type:ipv4 network.iana_number:17 _id:mV5bCXIB39NG0Ym1LGjY _type:_doc _index:pf-2020.05.12 _score: -`

`@timestamp:May 12, 2020 @ 11:34:29.303 event.id:187 event.original:<187>May 12 11:34:29 dhcpd: uid lease 10.2.2.238 for client 64:a5:c3:62:6a:77 is duplicate on 10.2.2.0/24 event.created:May 12 11:34:29 host:10.2.2.1 labels:dhcpd observer.type:pfSense @version:1 tags:pf, dhcpdv4, _grokparsefailure, dns pf_message:uid lease 10.2.2.238 for client 64:a5:c3:62:6a:77 is duplicate on 10.2.2.0/24 _id:YlhOCXIB39NG0Ym19ojk _type:_doc _index:pf-2020.05.12 _score: -`

`source.ip:10.2.2.245 ttl:64 ack_number:411516786 tags:pf, GeoIP_Destination, Rule_Description, dns @version:1 ip.flags:DF tos:0x0 reason:match window_size:351 @timestamp:May 12, 2020 @ 11:41:11.604 event.id:134 event.original:<134>May 12 11:41:11 filterlog: 5,,,1000000103,igb1,match,block,in,4,0x0,,64,15298,0,DF,6,tcp,52,10.2.2.245,31.13.85.8,51648,443,0,FA,150138517,411516786,351,,nop;nop;TS event.action:block event.created:May 12 11:41:11 sequence_number:150138517 host:10.2.2.1 observer.type:pfSense destination.dns:edge-star-shv-01-gru2.facebook.com destination.port:443 destination.as.number:32,934 destination.as.ip:31.13.85.8 destination.as.organization.name:FACEBOOK destination.ip:31.13.85.8 destination.geo.timezone:Europe/Dublin destination.geo.longitude:-6.244 destination.geo.latitude:53.347 destination.geo.country_iso_code:IE destination.geo.country_name:Ireland destination.geo.location:{ "lat": 53.3472, "lon": -6.2439 } destination.geo.ip:31.13.85.8 destination.geo.country_code3:IE destination.geo.continent_code:EU packet.id:15298 packet.length:52 rule_number:5 transport.data_length:0 tcp_options:nop;nop;TS offset:0 tracker:1000000103`

**Comment by AndreLFSMartins** [comment]
![Screen Shot 2020-05-12 at 11 33 38](https://user-images.githubusercontent.com/17053282/81707084-c4499680-9446-11ea-8076-4a54ed40ce60.png)
![Screen Shot 2020-05-12 at 11 33 06](https://user-images.githubusercontent.com/17053282/81707116-c90e4a80-9446-11ea-8838-83bdae55e5a4.png)

**Comment by AndreLFSMartins** [comment]
Looking at the logstash plain log I found it is not loading the country file. 
 At the Geoip.conf I double checked and the country file is declared. The file is also at the folder.

Not sure why it's not loaded

`[2020-05-12T12:47:14,332][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"pf-*", ">
[2020-05-12T12:47:14,675][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/data/pfELK/GeoIP/GeoLite2-ASN.mmdb"}
[2020-05-12T12:47:14,987][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/data/pfELK/GeoIP/GeoLite2-City.mmdb"}
[2020-05-12T12:47:14,994][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/data/pfELK/GeoIP/GeoLite2-City.mmdb"}
[2020-05-12T12:47:15,334][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/data/pfELK/GeoIP/GeoLite2-ASN.mmdb"}
`

**Comment by revere521** [comment]
you can delete the databases and run geoipupdate again to see if its a corruption

**Comment by AndreLFSMartins** [comment]
Hi, so I did it. 

Now is shows no results found.

**Comment by AndreLFSMartins** [comment]
Ok, it now started to show
Thanks

**Comment by AndreLFSMartins** [comment]
Great work by the way. Do you have other dashboards for metrics about DHCP, Traffic, netflow ?

Thanks

**Comment by revere521** [comment]
The dashboards focus more on collecting event based data from IDS/IPS and firewall logging, so the data collected would probably fall short of netfolw-like packet data. 

You could experiment with the others.conf and the grok patterns to see what kinds of data you can get from the logs - or you could run ntopng or somthing similar alongside the ELK stack (there is an ntopng package for pfsense) and you can get the free version installed on either another server; of if you have the resources, alongside the ELK stack. 

The ELK stack has packetbeat that pipes netflows into the SEIM built into Kibana/ELK - but i don't know what you would need to do to install it on pfsense.

**Comment by AndreLFSMartins** [comment]
Funny, it stopped again. It shows no results found.

**Comment by AndreLFSMartins** [comment]
> The dashboards focus more on collecting event based data from IDS/IPS and firewall logging, so the data collected would probably fall short of netfolw-like packet data.
> 
> You could experiment with the others.conf and the grok patterns to see what kinds of data you can get from the logs - or you could run ntopng or somthing similar alongside the ELK stack (there is an ntopng package for pfsense) and you can get the free version installed on either another server; of if you have the resources, alongside the ELK stack.
> 
> The ELK stack has packetbeat that pipes netflows into the SEIM built into Kibana/ELK - but i don't know what you would need to do to install it on pfsense.

Thanks for the info. I'll look into it. I know that softflowd on pfSense is able to send it to another collector I was able to do it with splunk

**Comment by revere521** [comment]
make sure logstash isn't crashing and restarting over and over again

there are multiple avenues to get the data you are looking for, its just a matter of sussing out the best choices, or using this config of ELK as a starting point to go deeper

**Comment by revere521** [comment]
still having issues?

**Comment by revere521** [comment]
Its been 7 days with no response, closing this one
