### ISSUE TITLE
Send logs via syslog from PFSense to ELK stack

### ISSUE THREAD

**Issue by AgalazMYR** [pfelk/pfelk#118]
Hi, I have configured PFElk to receive logs via syslog, but it only works locally. When I do the configuration for my PFSense, PFElk don't return any logs.

**Comment by revere521** [comment]
Can you describe the setup more specifically?  are pfELK and pfsense on the same subnet?

follow this guide and attach the pfelk.error.log output here: 

https://github.com/3ilson/pfelk/blob/master/install/ubuntu.md#troubleshooting

**Comment by AgalazMYR** [comment]
Yes, PFSense's IP is 10.10.10.1 and PFElk is 10.10.10.20. They can see each other with pings. Okay, I will follow this, thank you

**Comment by jahodaradek** [comment]
Do you actually get some data on the port on pfelk? Try "tcpdump port xx" probably xx is 5140  on pfelk machine.

**Comment by revere521** [comment]
@AgalazMYR did you resolve your issue?

**Comment by revere521** [comment]
no response for more than 7 days, i'm closing this one
