### ISSUE TITLE
Translate filter

### ISSUE THREAD

**Issue by chris-ana** [pfelk/pfelk#119]
Hello,
Is there any chance to create a translate conf as you have 35-rules-desc.conf.
I am trying to associate  dhcpv4.client_mac to a BYOD policy and i have made the following conf but it doesn't work.

44-translate.conf 
filter {
 if [dhcpv4.client.mac] {
    translate {
      field => "[dhcpv4.client.mac]"
      destination => "[dhcpv4.client.translated]"
      dictionary => {
        "a8:7d:12:5f:6c:a4" => "TEST"
      }
    }
  }
}

Thank you.

**Comment by revere521** [comment]
i'm not as knowledgeable in this case as @a3ilson, but the first step is to translate a field that is already being collected.  Im not sure if the reference to  `[dhcpv4.client.mac]` is being collected already.

The firewall (pfsense or opnsense) has to be sending the mac address over in a log context, and then the existing configs/grok have to be parsing the mac address field first. 

It looks like the filter pattern of dhcp/dhcpd collects `[dhcpv4][client_mac]` so if you tested with it this way it might be a step in the right direction: 

```
#44-translate.conf
filter {
  if [dhcpv4][client_mac] {
    translate {
       field => "[dhcpv4][client_mac]"
       destination => "[dhcpv4][client_translated]"
       dictionary => {
       "0" => "null"
       "a8:7d:12:5f:6c:a4" => "TEST"
      }
    }
  }
}
```

**Comment by a3ilson** [comment]
@chris-ana - I haven't pursued it yet....but I planned to experiment with a MAC OUI lookup.  The databases are widely available. My plan was to utilize an external dictionary file but haven't got around to it as it was more a curiosity thing - I haven't found a reason to use it.  

I don't mind helping but @revere521 has provided you with a good template to build upon.  I am curious as to what your intent is and how your network is configured?  Many devices utilize MAC randomization to deter tracking.  Additionally, you could utilize other methods to authentic users.

**Comment by chris-ana** [comment]
Thank you it is working now.

My network is actually 3 PfSense serving DHCP to Cisco access points. Clients that connect to AP take ip address from PfSense.I have access policy mac address  to access point and i want to track the place that the mobile devices are connected warehouse, labs , etc.
