### ISSUE TITLE
Cannot ad pf-* pattern to kibana

### ISSUE THREAD

**Issue by solaris04** [pfelk/pfelk#120]
I have the same issue with the pf-* pattern.
I did the manual install first, didnt work. deleted all files and configs and used the script.
Still having the same issue.

Firewall System (please complete the following information):
OPNSense
V 20.1.7
IP of firewall: 192.168.1.1
VM running ELK is on same subnet and can reach other clients

Operating System:
Virtual Machine GNU/Linux 4.15.0-99-generic x86_64
NAME="Ubuntu"
VERSION="18.04.4 LTS

Elasticsearch, Logstash, Kibana (please complete the following information):
(dpkg -l elasticsearch|logstash|kibana)
Elastic search 7.7.0
logstash 1:7.7.0-1
Kibana 7.7.0

cat /etc/logstash/pipelines.yml

    pipeline.id: main
    path.config: "/data/pfELK/configurations/*.conf"

No packets are captured with tcpdump -A port 5140

Status of services:
elasticsearch: active
kibana: active
logstash: active with error, see log journalctl

[sudo journalctl -u logstash -n 50 -f.txt](https://github.com/3ilson/pfelk/files/4669369/sudo.journalctl.-u.logstash.-n.50.-f.txt)
[01-inputs.conf.txt](https://github.com/3ilson/pfelk/files/4669370/01-inputs.conf.txt)

error log cannot be generated:
vmuser@vm:/data/pfELK$ sudo ./error-data.sh
pfELK: Generating pfELK Error Data
tail: cannot open '/data/pfELK/logs/logstash-plain.log' for reading: No such file or directory

Please let me know if you need any more information.
Thank you

**Comment by revere521** [comment]
Ok, it looks like you did the basic install, now you have to doublecheck the configure (and troubleshoot to move the standard log) settings

in your 01-inputs.comf make sure the IP you set for pfsense looks like this: 

`[host] =~ /192\.168\.1\.1/`

you may have double backslashes in there based on the logstash error

then run through the instructions starting here: https://github.com/3ilson/pfelk/blob/master/install/ubuntu.md#22-navigate-to-logstash

and then check if you are getting data

then look at these configs: https://github.com/3ilson/pfelk/blob/master/install/configuration.md

**Comment by revere521** [comment]
here is my 01-inputs.conf for your reference (since we are both pretty much doing the same thing)

you could probably just copy and paste

```
# 01-inputs.conf
input {
  udp {
     port => 5140
  }
}

filter {
#########################################################
# Adjust to match the IP address of pfSense or OPNsense #
#########################################################
  if [host] =~ /192\.168\.1\.1/ {
    mutate {
      add_tag => [ "pf", "Ready" ]
      add_field => [ "[observer][type]", "firewall" ]
    }
  }
##########################################################################################
# To enable or ingest multiple pfSense or OPNsense instances uncomment the below section #
#########################################################################################
#if [host] =~ /172\.2\.22\.1/ {
#  mutate {
#    add_tag => ["pf", "Ready"]
#    add_field => [ "[observer][type]", "firewall" ]
#  }
#}
#########################################################################################
  if "pf" in [tags] {
    grok {
      # OPNsense - Enable/Disable the line below based on firewall platform
      #match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{SYSLOGHOST:[observer][name]} %{DATA:labels}(?:\[%{POSINT:pf_pid}\])?: %{GREEDYDATA:pf_message}" }
      # pfSense - Enable/Disable the line below based on firewall platform
      match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
      remove_tag => "Ready"
    }
  }
}
```

**Comment by solaris04** [comment]
Thank you!

found the culprit:
{ was missing after the ip address

But in the suricata dashboard I only see the map and either nor results found or 
Could not locate that index-pattern-field (id: suricata.alert.signature.keyword)
Is this maybe caused due to the fact that no logs of events have been sent to elk yet, e.g. since pfelk is runnining there havent been any suricata events so far?

**Comment by solaris04** [comment]
Furthermore the map does not show any paths or any information, see attachement.
I have attached my suricata dashboard as well
![suricata dashboard](https://user-images.githubusercontent.com/46383179/82711008-8b9a9000-9c84-11ea-90ca-08739c325d7f.png)
![maps firewall](https://user-images.githubusercontent.com/46383179/82711013-8c332680-9c84-11ea-80b5-0c3520da5ae6.png)

**Comment by revere521** [comment]
That could mean no events have been sent yet, or it could mean you have to refresh the index pattern. 

Go to Management in kibana (gear icon) then Index patterns, then select the pf-* index and click the refresh button in the upper right.  you should see about 230 or so fields as a result.    

I know there have been some issues with suricata specifically due to pfsense truncating the eve json logs at 1024 bytes as well.... but try to refresh the index pattern and see if you get at least some of the data.

One of the other guys here may have to chime in if you have suricata specific issues beyond that, I use snort.

**Comment by a3ilson** [comment]
@solaris04 you need to adjust the file to properly filter OPNsense:

```
# 01-inputs.conf
input {
  udp {
     port => 5140
  }
}

filter {
#########################################################
# Adjust to match the IP address of pfSense or OPNsense #
#########################################################
  if [host] =~ /192\.168\.1\.1/ {
    mutate {
      add_tag => [ "pf", "Ready" ]
      add_field => [ "[observer][type]", "firewall" ]
    }
  }
##########################################################################################
# To enable or ingest multiple pfSense or OPNsense instances uncomment the below section #
#########################################################################################
#if [host] =~ /172\.2\.22\.1/ {
#  mutate {
#    add_tag => ["pf", "Ready"]
#    add_field => [ "[observer][type]", "firewall" ]
#  }
#}
#########################################################################################
  if "pf" in [tags] {
    grok {
      # OPNsense - Enable/Disable the line below based on firewall platform
      match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{SYSLOGHOST:[observer][name]} %{DATA:labels}(?:\[%{POSINT:pf_pid}\])?: %{GREEDYDATA:pf_message}" }
      # pfSense - Enable/Disable the line below based on firewall platform
      # match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
      remove_tag => "Ready"
    }
  }
}
```

Note: the pfSense line was commented out while the OPNsense line was uncommented.  Once you made the change, reboot and try again.

**Comment by solaris04** [comment]
Thx again.
Suricata dashboard works now after I refreshed the index pattern.
On the firwall dashboard I do not see any information, just a blank map

**Comment by a3ilson** [comment]
> Thx again.
> Suricata dashboard works now after I refreshed the index pattern.
> On the firwall dashboard I do not see any information, just a blank map

Redownload the dashboard and try again.  The previous dashboard contained a snort which only displayed snort traffic.  The Dashboard was update and removed this error...the map now displays all traffic (unfiltered).

If this corrects your issue, please close.

**Comment by solaris04** [comment]
Redownload did the job.
Thx again.
