### ISSUE TITLE
Logstash can run and receive log with issue "java.lang.IllegalStateException"

### ISSUE THREAD

**Issue by n0th1nt0lOOz** [pfelk/pfelk#123]
Hi, my logstash log show it not runs. Search about problem "java.lang.IllegalStateException" for logstash and it say this issue relate to pipelines.yml. And it shows some other issue too

My logstash server:
OS: CentOS 7
Ram: 4GB
IP: 192.168.1.21

My ES + Kibana Server:
OS: CentOS 7.5
Ram: 6GB
IP: 192.168.1.17

My pfSense:
Version: 2.4.5
IP: 192.168.1.23

If you know how to make it work please share with me
Thanks
[error.pfelk.log](https://github.com/3ilson/pfelk/files/4679679/error.pfelk.log)
![image](https://user-images.githubusercontent.com/28757980/82856375-02ab7f00-9f38-11ea-942e-12fb79ff9578.png)

**Comment by a3ilson** [comment]
@tientmse62290 
I have not tested for CentOS but I did note a few issues with your configuration:
- (1) # 01-inputs.conf
-- This `"pfSense2.cashwagon.local"` must be `"[pfSense2][cashwagon][local]"`
-- Your second instance is all commented out but I see you've updated...do you have two OPNsense firewalls sending traffic? If so you'll need to uncomment and correct the second instance from `"fw1.cashwagon.local"` to `"[fw1][cashwagon][local]"`
- (2) # 10-others.conf
-- Not sure what you have going on here but the file contains other additional filtering.
-- Delete everything to include from the 2nd filter to the end (duplicative)  
- (3) # 50-outputs.conf 
-- Change this `template => "/etc/logstash/templates/pf-geoip-template.json"` to `template => "/data/pfELK/templates/pf-geoip-template.json"`

**Comment by n0th1nt0lOOz** [comment]
Hi, I changed and wget new 10-others.conf file. But now logstash just start then shutdown without clearly problem. I run error-data again and attach below.
From Logstash server I can telnet to ES server, but don't know why logs said ES is dead
Thanks
[error.pfelk.log](https://github.com/3ilson/pfelk/files/4679769/error.pfelk.log)
![image](https://user-images.githubusercontent.com/28757980/82858255-8ddb4380-9f3d-11ea-92a1-a535c3b6e612.png)

**Comment by a3ilson** [comment]
@tientmse62290 
Are you running pfSense or OPNsense?
- (1) # 01-inputs.conf
--You have the filter for OPNsense uncommented out 
--If you are using pfSense comment out the OPNsense line and uncomment the pfSense 
--These both start with match =>.....

- (2) # 10-others.conf
--This file still contains a bunch of unknown filtering 
--Remove everything after line 72
--The first filter is on line two, remove the second filter (line 72 and all renaming lines)

**Comment by n0th1nt0lOOz** [comment]
Hi I'm using pfsense and fixed the 01-inputs.conf
With the 10-others.conf, the file only have 72 lines count from the second line, I don't see any other lines. I just download the new 10-others.conf not old file anymore

**Comment by a3ilson** [comment]
@tientmse62290 
Remove file: 11-pfsense.conf which is not part of pfELK. It appears you are using other files in conjunction with the pfELK files.  If it does not work after removing the 11-pfsense.conf, I would highly suggest starting over and stick to a configuration method/repository.

**Comment by n0th1nt0lOOz** [comment]
Hi, deleted it. Restarted and wait but logstash till shutdown
![image](https://user-images.githubusercontent.com/28757980/82859950-6aff5e00-9f42-11ea-8dc5-eadca07cdd5d.png)

[error.pfelk.log](https://github.com/3ilson/pfelk/files/4679867/error.pfelk.log)

**Comment by a3ilson** [comment]
@tientmse62290 
Try adjusting your 50-outputs.conf with http vs https.  Logstash is unable to connect to your Elasticsearch instance.

**Comment by n0th1nt0lOOz** [comment]
Hi, I changed to HTTP but it got same issue.
Question: I use filebeat to ship logstash log to ES. Do I need to config this anymore?
![image](https://user-images.githubusercontent.com/28757980/82860269-42c42f00-9f43-11ea-9e22-cfe2d2d1ad94.png)

**Comment by a3ilson** [comment]
@tientmse62290 
I made a lot of changes today in preparation for a new script installer.  The newly downloaded 10-others.conf file contains references you'll need to corrected based on your current setup.
- (1) replace all references from `patterns_dir => ["/etc/logstash/conf.d/patterns"]` to `patterns_dir => ["/data/pfELK/patterns"]`

That should fix your two errors.

**Comment by n0th1nt0lOOz** [comment]
I changed. Current problem is connection. Do we need logstash directly send log to ES? As I mention, I'm using filebeat instead
![image](https://user-images.githubusercontent.com/28757980/82861012-933c8c00-9f45-11ea-9b87-8c2cf6678d55.png)
[error.pfelk.log](https://github.com/3ilson/pfelk/files/4679915/error.pfelk.log)

**Comment by a3ilson** [comment]
It is still trying to connect via https 

Unfortunately, pfELK does not rely or utilize filebeat. Furthermore, I am unable to provided additional assist as I am unaware of your setup/configuration. If it was a vanilla install of pfELK,, we could be of more assistance but not knowing the various variables (setup/configuration). I would suggest a forum to further assist with your unique setup/configuration.
