### ISSUE TITLE
New Install Script Feedback / Results

### ISSUE THREAD

**Issue by revere521** [pfelk/pfelk#124]
Thinking from a novice end-user point of view, and trying to error-proof the script, this is my feedback. 
I'm still digesting the script, its very welll written and works very well; but might take me a while to figure out where to edit....props to a3ilson and pilotboy72!

Ubuntu 18.04.04 VM
8GB Ram, 40GB virtual disk

install: 
1. instead of asking for maxmind password, should it ask for maxmind license key (to avoid confusion)
2. the script hangs for a bit after inputting the maxmind info - maybe a popup statement to ask the user to wait while its configuring things? or if possible, show the progess in some way. 
3. after specifying IP address, should there be a heading asking to select between OPNsense and pfsense?  the choices pop up, but its not specific to what you are being asked to do. 
4. the progress messages during ELK installs are nice, for those of us with slower internet connections - its good to know its running and not stalled :)
5. the script hung on the Kibana install message untill i hit enter, then it started normally

post install:
6. we may want a reinder at the end of the script to complete the manual configuration portions in the configure guide, since those steps get missed sometimes
7. the configuration files are in `/etc/logstash/conf.d` rather than `/data/pfELK/configurations`  the same for the patterns and templates folders (they are under /conf.d)
8. the logs are in `/etc/pfELK/logs` and error-data.sh is in `/etc/pfELK` rather than `/data/pfELK`
9. we should consider explaining how to configure interface names `05-firewall.conf` in the post configuration readme

[ubuntu_test.error.pfelk.log](https://github.com/3ilson/pfelk/files/4683592/ubuntu_test.error.pfelk.log)

**Comment by a3ilson** [comment]
@revere521 
- (1) Updated to ask for license key vs password
- (2) Reduced the sleep time and added a task to add a message to the corresponding [project](https://github.com/3ilson/pfelk/projects/9)
- (3) Added message
- (4) Thanks
- (5) This is a previously known issue captured in the project...looking into correcting when time is available.

For post install.  All were added to the project for future implementation feel free to make, add, or revise as need - just update the [project](https://github.com/3ilson/pfelk/projects/9)

**Comment by revere521** [comment]
ok, quick question, are we going back to the default locations for the files `/etc/logstash/conf.d` or staying with then under the consolidated path `/data/pfELK/*` ?

I see you put the repo structure back to default... If thats the case, cool - just wanted to make sure i'm on the same page

**Comment by a3ilson** [comment]
@revere521 - yes...I revised the error script and all associated files to account for the default locations vs a consolidated location.  Sorry for the confusion (back/forth) on this one...just trying to keep things simple with the intent that the new script will alleviate a lot of the common issues and/or overlooked various instruction tweaks.

**Comment by revere521** [comment]
ok, no worries at all, it was a good idea, but i think it tripped up a few folks recently to use non-default locations.  I think it also helps with google search based help to have them back in their standard spots

**Comment by revere521** [comment]
For Debian, sudo isn't installed by default, and curl may not be either.   For sudo, the instructions may need to be updated to include installing that as a first step/prerequisite (unfortunately it cant be scripted).   I'm not sure if the curl command being missing has any impact yet, I am still running the script.

**Comment by a3ilson** [comment]
The script accounts for those and installs if not present.  However, the initial download (download of the script itself) will need to specify (i.e. for Debian users omit sudo).  I'll update that now - thanks!

**Comment by revere521** [comment]
i am testing with sudo installed (just dropping to root with su, then `apt install sudo` does the trick).   I may have to go back and test running the script without sudo to see how that goes afterward

EDIT: adding myself to the sudoers file was also necessary.... running the script under root was successful, re-running it as my user with sudo was also successful.  I think you can call debian 10 successful

**Comment by a3ilson** [comment]
Thanks for testing and validating!
