### ISSUE TITLE
Missing instructions / installer suggestion

### ISSUE THREAD

**Issue by southwood** [pfelk/pfelk#128]
Great work, this project is really useful. The easy install script made this deployment relatively painless.

**Is your feature request related to a problem? Please describe.**
I may have missed it, but I don't think the latest instructions cover uncommenting one of [these lines](https://github.com/3ilson/pfelk/blob/master/etc/logstash/conf.d/01-inputs.conf#L29-L33).

**Describe the solution you'd like**
Could this be added to the script after a selection between pfsense or opnsense is made?

**Describe alternatives you've considered**
Manually uncommenting the correct line works. But, I wasn't aware of the requirement until I searched through the issue tracker. I initially thought I was blocked due to ipv6 support in my firewall due to one of the threads about `_grokparsefailure`'s occurring. I see this too - but until I fixed `01-inputs.conf` DNS logs were the only ones showing in kibana.

**Additional context**
 - I suggest changing `#pf# match` to `# match` to avoid confusion when uncommenting. The comment above each line clarifies that the section is either opnsense or pfsense.
 - Also, the script checks disk availability but doesn't consider the size of the `/tmp` volume. It ended up filling my `/tmp` partition and crashing until I realized the issue.

**Comment by a3ilson** [comment]
@southwood - thanks for the feedback!  Later this week, I'll conduct another test installation utilizing both pfSense and OPNsense.  However, the script should have prompted an input for pfSense or OPNsense and as a result removed either the preceding #pf# or #OPN# via sed.

**Comment by a3ilson** [comment]
@southwood - I added a project task to validate the /tmp size and will update in the near future.  

Thanks!

**Comment by southwood** [comment]
Great, thank you for the prompt response! I wonder if my issue with `/tmp` filling up left things in a weird state that somehow avoided triggering sed update. I remember seeing the prompt to select between pfSense and OPNsense.

**Comment by southwood** [comment]
Got it, that makes a lot of sense. The script is really helpful, I really appreciate all the effort that went into this.

For what it's worth, the only changes I made after running the script were to relocate the index to my `/data` volume, some log rotation updates, some ufw updates, and uninstalling netcat. I see that the script attempts this but I noticed it was still around. Probably related to my issue with `/tmp` filling up.

**Comment by dsantanu** [comment]
One thing I suggest, as an addition to installation script, to put a symbolic link in `/etc/rc6.d` for _elasticsearch_ to shutdown properly on any shutdown  event. something like: 

```
cd /etc/rc0.d && ln -sf ../init.d/elasticsearch K02elasticsearch
cd /etc/rc6.d && ln -sf ../init.d/elasticsearch K02elasticsearch
```
Otherwise it takes ages to shutdown/reboot the machine saying it's still waiting for ES to quit. What I found out, when directly shutting down, ES waits for a 1min, thinking it will come back (as it didn't know about my `shutdown -h ...`) and then when it doesn't, according to the documentation, it starts allocating the shards from that node t others and finally ends up with the waiting time for a lots of I/O. I was keep forgetting about this and was keep doing `shutdown -r now` and in one occasion it took around 24 mins to shutdown.

**Comment by a3ilson** [comment]
Fixed the Kibana hang-up. Working on refining and addressing the remaining issues.

- [x] Kibana hang-up during install - Fixed
- [x] Check tmp space to ensure sufficient size prior to install
- [x] Create symbolic link to aid with proper/promptly shutdowns (this will also address issue #170)

**Comment by a3ilson** [comment]
With the latest setup/installation - I have not been able to reproduce nor replicate this issue (elasticsearch latency when shutting down and/or rebooting)...Can someone confirm and/or confirm this is still problematic?

**Comment by a3ilson** [comment]
script updated addressing and completing this issue.
