### ISSUE TITLE
pfelk docker 7.7 dashboard missing index pattern fields.

### ISSUE THREAD

**Issue by Fetakungen** [pfelk/pfelk#131]
**Describe the bug**
Hi, Dunno what i'm doing wrong or if the pf doesn't log several fields but i'm getting "Could not locate that index-pattern-field (id: *" , e.g. "Could not locate that index-pattern-field (id: network.name.keyword)"

In the firewall dashboard i see blocked actions and the map, and in the surricata dashboard all fields give "Could not locate that index-pattern-field (id: *")
![kibana](https://user-images.githubusercontent.com/56397651/84808161-94bf1880-b008-11ea-8cd3-b43bfc7d96ce.PNG)
![Edit saved objects](https://user-images.githubusercontent.com/56397651/84810842-3300ad80-b00c-11ea-8cb9-e40fcecaf142.PNG)

**To Reproduce**
ELK: Config input file, Setup Docker containers using Docker compose. - Git cloned 2020-06-15
[01-inputs.conf.txt](https://github.com/3ilson/pfelk/files/4788287/01-inputs.conf.txt)
Pfsense: Configure Syslog and surricata to EVE/SYSLOG. 

Kibana:
Setup index pattern pf-*
Import Dashboards from https://github.com/3ilson/pfelk/tree/master/Dashboard

**Screenshots**

**Firewall System (please complete the following information):**
PFSENS 2.4.5
 
 **Installation method (manual, ansible-playbook, docker, script):**
 Docker
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)

ELK VERSION 7.7
 
**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file

**Comment by Fetakungen** [comment]
Solved by recreating index pattern after the logs had filled.

**Comment by Fetakungen** [comment]
Edit: The firewall is solved but surricata still show: 

Could not locate that index-pattern-field (id: suricata.eve.alert.signature.keyword)

Could not locate that index-pattern-field (id: suricata.eve.alert.signature.keyword)
![Surricata](https://user-images.githubusercontent.com/56397651/84812405-a9061400-b00e-11ea-998b-f9403ccf6fa1.PNG)

I suppose this is due to the face that hasn't been logged when the pattern is created ?

My surricata log is set like this:
![Logging](https://user-images.githubusercontent.com/56397651/84813392-35650680-b010-11ea-88e9-73932b692227.PNG)

**Comment by a3ilson** [comment]
@Fetakungen - This is a known issue with pfSense.  See #111 for more details - Unlikely you'll see a complete suricata message.

**Comment by a3ilson** [comment]
Issue already captured within issue #111
