### ISSUE TITLE
Scripted Install issues on Ubuntu 20.04

### ISSUE THREAD

**Issue by tpurner** [pfelk/pfelk#132]
On a fresh install of Ubuntu 20.04, the scripted installation hangs at the Kibana installation. It has not made progress for over 30 minutes. 

error-data.sh copied below:

echo "pfELK: Generating pfELK Error Data"
#create log folder
sudo mkdir /etc/pfELK/logs
#remove any old pfelk error outputs
sudo rm /etc/pfELK/logs/error.pfelk.log
#create the new file
sudo touch /etc/pfELK/logs/error.pfelk.log
#add system information
echo "#####################################" >> /etc/pfELK/logs/error.pfelk.log
echo "# pfELK System Information ##########" >> /etc/pfELK/logs/error.pfelk.log
echo "#####################################\n" >> /etc/pfELK/logs/error.pfelk.log
printf "$(uname -srm)\n$(cat /etc/os-release)\n$(free -hm)\n" | cat >> /etc/pfELK/logs/error.pfelk.log
#capture directory and files structure
echo "\n#####################################" >> /etc/pfELK/logs/error.pfelk.log
echo "# Listing pfELK Directory Structure #" >> /etc/pfELK/logs/error.pfelk.log
echo "#####################################\n" >> /etc/pfELK/logs/error.pfelk.log
find /etc/logstash/ | cat >> /etc/pfELK/logs/error.pfelk.log
find /usr/share/GeoIP/ | cat >> /etc/pfELK/logs/error.pfelk.log
#capture all config files
echo "\n#####################################" >> /etc/pfELK/logs/error.pfelk.log
echo "# pfELK Config File Details #########" >> /etc/pfELK/logs/error.pfelk.log
echo "#####################################\n" >> /etc/pfELK/logs/error.pfelk.log
cat /etc/logstash/conf.d/*.conf >> /etc/pfELK/logs/error.pfelk.log
echo "\n#####################################" >> /etc/pfELK/logs/error.pfelk.log
echo "# Listing Logstash Pipelines.yml #" >> /etc/pfELK/logs/error.pfelk.log
echo "#####################################\n" >> /etc/pfELK/logs/error.pfelk.log
cat /etc/logstash/pipelines.yml >> /etc/pfELK/logs/error.pfelk.log
echo "\n#####################################" >> /etc/pfELK/logs/error.pfelk.log
echo "# Listing Logstash Logstash.yml Log Path #" >> /etc/pfELK/logs/error.pfelk.log
echo "#####################################\n" >> /etc/pfELK/logs/error.pfelk.log
cat /etc/logstash/logstash.yml | grep path.logs* >> /etc/pfELK/logs/error.pfelk.log
#attach logstash logs
echo "\n#####################################" >> /etc/pfELK/logs/error.pfelk.log
echo "# Appending Logstash Logs ###########" >> /etc/pfELK/logs/error.pfelk.log
echo "#####################################\n" >> /etc/pfELK/logs/error.pfelk.log
tail -20 /var/log/logstash/logstash-plain.log | cat >> /etc/pfELK/logs/error.pfelk.log
#attach Java version
echo "\n#####################################" >> /etc/pfELK/logs/error.pfelk.log
echo "# Java Version ######################" >> /etc/pfELK/logs/error.pfelk.log
echo "#####################################\n" >> /etc/pfELK/logs/error.pfelk.log
java -version 2>> /etc/pfELK/logs/error.pfelk.log
#capture systemctl status outputs to validate services running
echo "\n#####################################" >> /etc/pfELK/logs/error.pfelk.log
echo "# ELK Services Check ################" >> /etc/pfELK/logs/error.pfelk.log
echo "#####################################\n" >> /etc/pfELK/logs/error.pfelk.log
echo "\n###Elasticsearch.service:###\n" >> /etc/pfELK/logs/error.pfelk.log
systemctl status elasticsearch.service -q | cat >> /etc/pfELK/logs/error.pfelk.log
echo "\n###Logstash.service:###\n" >> /etc/pfELK/logs/error.pfelk.log
systemctl status logstash.service -q | cat >> /etc/pfELK/logs/error.pfelk.log
echo "\n###Kibana.service:###\n" >> /etc/pfELK/logs/error.pfelk.log
systemctl status kibana.service -q | cat >> /etc/pfELK/logs/error.pfelk.log
echo "Error Data Collected Successfully"
echo "Attach the contents of /etc/pfELK/logs/error.pfelk.log as a file to attache and include with your issue in github"

**Comment by a3ilson** [comment]
Is a know issue.... press enter and it should continue.  Sorry for the
inconvenience.

**Comment by tpurner** [comment]
Pressing enter did get the install to complete, but there appears to be some issue with the final configuration provided by the script. I can access Kibana, but there are no logs or indexes. 

I have confirmed that the Elasticsearch, Logstash, and Kibana services are all running. I have also confirmed via tcpdump that logs are hitting port 5104. I should also mention that I had pfELK running without any issues prior to doing the first fresh install of 20.04, so I assume the issue is not logging. 

After a few hours trying to troubleshoot, I performed another fresh install of Ubuntu 20.04 and tried the scripted install again. Same results. Services are running. Logs being received. Nothing in Kibana. 

The 01-inputs.conf was configured correctly by the script. Anything else I can check before I resort to manual install? 

Thanks in advance.

**Comment by a3ilson** [comment]
Can you confirm the port is 5140 vs 5104?

Can you provide a copy of Kibana.yml?

**Comment by tpurner** [comment]
Sorry, that should have read 5140. 

The issue was finally resolved by manually running geoipupdate. As soon as I ran it, an index was created and I have now data in Kibana.

**Comment by a3ilson** [comment]
Excellent.... sometimes maxmind (geoipupdate)  updates promptly while other
times it can take a few minutes.

Glad to hear it was resolved and appreciate your feedback.   The Kibana
issue is noted and hopefully it will beresolved in the near future.
