### ISSUE TITLE
Sending Geo-IP and data to Azure Log Analytics

### ISSUE THREAD

**Issue by noodlemctwoodle** [pfelk/pfelk#135]
Thanks for this awesome stack I've set this up and I have configured the 50-output.conf to send the data to an Azure Log Analytics workspace. 

Currently I am sending pf_message to Azure which gives me some some IP & port information, however I'd really like to get the Geo-IP, Snort and Suricata information up there too. 

Are you able to give any pointers how this might be done?

**Comment by a3ilson** [comment]
@noodlemctwoodle - The pfELK configuration should enrich this (snort, suricata and Geo-IP routable addresses) and if configured properly will output accordingly.  However, it sounds like you are attempting to adjust the output (50-outputs.conf) to point to an Azure instance?  If this is correct, you'll need a compatible format for Azure to ingest (Elasticsearch and Azure are not interchangeable).  Azure does not support half_float or geo_point data types and as such you'll need to convert the various data fields to a support type for Azure utilization.


[pfelk Overview](https://github.com/3ilson/pfelk/blob/master/Images/pfELKOverview.png)

**Comment by noodlemctwoodle** [comment]
@a3ilson I modified 50-output.conf to the following, I'm not entirely sure if this is the correct way, I am very new to Elk and I have just been fumbling my way through it :)

```
# 50-outputs.conf
output {
    elasticsearch {
        id => "pf"
        hosts => ["http://localhost:9200"]
        index => "pf-%{+YYYY.MM.dd}"
        manage_template => true
        template => "/etc/logstash/conf.d/templates/pf-geoip-template.json"
        template_name => "pf-geoip"
        template_overwrite => false
  }
    microsoft-output-azure-loganalytics {
        workspace_id => "someid"
        workspace_key => "somekey"
        custom_log_table_name => "PFSense"
        key_names => ['event','id','created','tags','pf_message']
    }
}
```

Using this config the event are going to azure,however it has broken being able you view the in coming logs in Kibana when you go to Logs, However you can see them in Discover. Im still going through a number of Issues to try and configure syslog-ng as I am getting Grok errors on the Surricata logs, which I'm assuming is due to the bug already raised. Both the PfSense Dashboard and Snort Dashboard are working without issue. 

Any guidance you can give me will be greatly received, with regards to sending the logs to Azure.

**Comment by a3ilson** [comment]
@noodlemctwoodle - for the truncated issues with suricata please take a look at #111 in which @TehMuffinMoo provided a solution. I also extracted his solution and placed it within the wiki page: https://github.com/3ilson/pfelk/wiki/How-To:-Suricata-on-pfSense

As for Azure, I'm not overly familiar but I would pay particular attention to the field types. For instance, the template (pf-geoip-template.json) tells elasticsearch to utilize the Geo-ip values as half_float and geo_point. Those along with other fields are not compatible with Azure.

I may need to signup for Azure's Always Free account and give it a whirl...not a huge fan of MS but something new to dabble with.

Give the wiki page a review and see if it resolves your first issue.  Azure will take some assistance and/or time for me to get up to speed.

**Comment by a3ilson** [comment]
No response from author
