### ISSUE TITLE
Missing "suricata.eve.alert.signature.keyword" and the "Suricate - Time object, Suricata"

### ISSUE THREAD

**Issue by a3ilson** [pfelk/pfelk#136]
**Describe the bug**
When importing the current dashboard, the following two elements are missing: 
-suricata.eve.alert.signature.keyword
-Suricate - Time object, Suricata

**To Reproduce**
1. Go to import the suricata dashboard
2. Click on navigate to the suricata dashboard
3. See error

**Firewall System (please complete the following information):**
 - pfSense or OPNsense
 
**Additional context**
Must add a filter to the visualisation for suricata.eve.alert.signature exists - reference #111 solution by @TehMuffinMoo

![85925065-07908500-b88e-11ea-96f0-029fb2c79348](https://user-images.githubusercontent.com/16884679/85925840-2af50900-b869-11ea-9edf-0b595d41108d.jpg)

**Comment by noodlemctwoodle** [comment]
@a3ilson @TehMuffinMoo `suricata.eve.alert` doesnt exist, so I am unable to add the filter `suricata.eve.alert.signature exists` is there some configuration needed to create that event type?

**Comment by TehMuffinMoo** [comment]
Hey,

So the suricata processing is mainly JSON, meaning if those fields don't exist but the rest do then I'd imagine you don't have any alert events yet, or the time window you're selecting has no alert events in.

What do you get if you use this search on your discover page?

` suricata.eve.event_type.keyword : alert `

![image](https://user-images.githubusercontent.com/51195492/85930842-746c4500-b8b7-11ea-96fc-980fc145cd45.png)

**Comment by noodlemctwoodle** [comment]
@TehMuffinMoo It doesnt display anything for the last week

![image](https://user-images.githubusercontent.com/15075388/85930891-ee043300-b8b7-11ea-9c32-ccfb5a8fc41c.png)


Just scanning through the events `suricata.eve.event_type.keyword : * ` I can only see `DNS` and `netflow`

**Comment by TehMuffinMoo** [comment]
Well there’s our problem!

Is there any alerts shown in the logs on pfsense?

And is the “Output alerts via Eve” checkbox ticked?
![0C88EFAB-42AB-41B9-B7EB-583BF95A80B7](https://user-images.githubusercontent.com/51195492/85931383-1130e180-b8bc-11ea-983a-607feea965f4.jpeg)

**Comment by noodlemctwoodle** [comment]
@TehMuffinMoo These are the alerts in from the WAN
![image](https://user-images.githubusercontent.com/15075388/85931617-851fb980-b8bd-11ea-8f60-6da753b04498.png)


These setting look the same as you have posted. 
![image](https://user-images.githubusercontent.com/15075388/85931535-0fb3e900-b8bd-11ea-8dcb-e6de11082eda.png)


Also I have just noticed that the Suricata - Count has stopped working at some point too, leaving only the Map working. All other objects now say no data.

**Comment by TehMuffinMoo** [comment]
You have discord?

TehMuffinMoo#2107

**Comment by noodlemctwoodle** [comment]
@TehMuffinMoo Sent a request :)

**Comment by a3ilson** [comment]
Is this still an issue or was it resolved?

**Comment by TehMuffinMoo** [comment]
@a3ilson 

Ah this was resolved on Discord. You can probably close this!

**Comment by a3ilson** [comment]
Resolved

**Comment by Fetakungen** [comment]
Hi, i've the same problem. Getting no "alerts" to the indexpattern. How was this resolved ? The Eve settings are correct.

**Comment by a3ilson** [comment]
@Fetakungen - Are you getting alerts within pfSense or OPNsense?

If using pfSense have you followed the following: https://github.com/3ilson/pfelk/wiki/How-To:-Suricata-on-pfSense

**Comment by TehMuffinMoo** [comment]
From memory I think this was down to the host field not matching what was added to the inputs.conf.

Might be worth opening another issue, but on your discover page do you have events with _grokparsefailure in the tags?

**Comment by Fetakungen** [comment]
yes, same as above. Se attached files



![Alerts](https://user-images.githubusercontent.com/56397651/91659670-92317280-ead1-11ea-9b04-9176b559c9b8.PNG)
![Alterts Sur](https://user-images.githubusercontent.com/56397651/91659673-93fb3600-ead1-11ea-870d-277c14bf9aac.PNG)
![settings](https://user-images.githubusercontent.com/56397651/91659686-b0976e00-ead1-11ea-9c8e-3514e736c042.PNG)

**Comment by Fetakungen** [comment]
> 
> 
> From memory I think this was down to the host field not matching what was added to the inputs.conf.
> 
> Might be worth opening another issue, but on your discover page do you have events with _grokparsefailure in the tags?

Well not since i've setup the names of the interfaces in the conf.

**Comment by a3ilson** [comment]
@Fetakungen - Based on your screen shot above, the alert field is nested within suricata.eve...search for suricata.eve.alert

**Comment by Fetakungen** [comment]
> suricata.eve.alert

The search includes anything that contains alert , suricata.eve.alert gives the same.

**Comment by a3ilson** [comment]
Your correct, do you have any suricata fields?

**Comment by Fetakungen** [comment]
> 
> 
> Your correct, do you have any suricata fields?

yes , many about 8 pages or (79 fields). 

I also have could not locate that index-pattern-field (id: event.id.keyword) , not sure if it's related.

**Comment by a3ilson** [comment]
The only event.id.keyword I have is squid.event.id.keyword

Could you provide a screenshot for one of the suricata tables?
![suricata](https://user-images.githubusercontent.com/16884679/91660240-3c45d600-eaa3-11ea-8a6b-d7db21a025f3.PNG)

**Comment by Fetakungen** [comment]
I've just found this guide, is this "mandatory" ? I've not done this.

https://github.com/3ilson/pfelk/wiki/How-To:-Suricata-on-pfSense

**Comment by a3ilson** [comment]
For pfSense it is otherwise, the Suricata messages are truncated and do not parse out in their entirety

**Comment by Fetakungen** [comment]
> 
> 
> For pfSense it is otherwise, the Suricata messages are truncated and do not parse out in their entirety

Adding the inputs conf results in "configuration error" from logstash resulting on no parse at all.
Config is as below 

# 00-inputs.conf
input {
  tcp {
    port => 5141
  }
}

filter {
  if [host] == "10.0.6.2" {
    mutate {
      add_tag => [ "pf", "Ready" ]
    }
  }
  if "pf" in [tags] {
    grok {
      match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]}\s+(%{HOSTNAME:[hostname]}\s+)?%{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }
    }
  }
}

**Comment by Fetakungen** [comment]
> 
> 
> For pfSense it is otherwise, the Suricata messages are truncated and do not parse out in their entirety

enabling the inputs by the guide results in double tagging and break interface alias etc.

![double](https://user-images.githubusercontent.com/56397651/91661609-687e4880-eadd-11ea-8322-3361a8cbb333.PNG)

**Comment by TehMuffinMoo** [comment]
Not sure why you would be getting duplicate fields, something off with your config if that's happening.

Out of interest, have you unchecked the send events to system in Suricata?

https://github.com/3ilson/pfelk/raw/master/Images/wiki/pfSense-Suricata%2310.png

**Comment by Fetakungen** [comment]
> 
> 
> Not sure why you would be getting duplicate fields, something off with your config if that's happening.
> 
> Out of interest, have you unchecked the send events to system in Suricata?
> 
> https://github.com/3ilson/pfelk/raw/master/Images/wiki/pfSense-Suricata%2310.png

yeah send to syslog is unchecked, as soon as i remove inputs 00 its back to normal. Worth to notice, it's the firewall logs no the suricatalogs that get duplicated. So probably it's the syslog-ng config that is wrong sending all logs and not only suricatalogs ?

Also in the guide, you create an listner for surricata only port 5141. Should this be the case ?

**Comment by a3ilson** [comment]
Awe...give me a minute and I'll send a revised inputs.conf file

**Comment by a3ilson** [comment]
I don't recall the reasoning for sending suricata to a different port...Can you send me a few raw outputs from suricata?

**Comment by TehMuffinMoo** [comment]
The reason for the alternate port was the limitation in log length with UDP was 1024 bytes. Syslog-NG works around this by using TCP, so the second input can share the same port but it must use TCP not UDP.

This means standard log traffic from pfsense comes in via UDP, and events from Suricata come in via Syslog-NG using TCP.

**Comment by a3ilson** [comment]
@Fetakungen - Give this a try:

- Remove 00-inputs.conf
- Amend 01-inputs.conf as follows:
```
# 01-inputs.conf
input {
  udp {
    type => "firewall"
    port => 5140
  }
  tcp {
    type => "firewall"
    port => 5141
  }
  udp {
    type => "haproxy"
    port => 5145
  }
  beats {
    type => "beats"
    port => 5044
  }
}
```

**Comment by Fetakungen** [comment]
that works, no double tag and surricata messeges getting in. not correctly but.., ill give you an update soon..

**Comment by a3ilson** [comment]
What's not working correctly? Share your output and I'll take a look/assist and/or share the solution.

**Comment by Fetakungen** [comment]
> 
> 
> What's not working correctly? Share your output and I'll take a look/assist and/or share the solution.
The suricata logs look like this, only tagged with pf. 
![1](https://user-images.githubusercontent.com/56397651/91669117-dbee7d00-eb12-11ea-994a-8acb5f92b8bd.PNG)
![2](https://user-images.githubusercontent.com/56397651/91669118-ddb84080-eb12-11ea-8e68-4d23e35bed30.PNG)

**Comment by a3ilson** [comment]
Thanks!  Can you provide the raw text from the event.original field.

**Comment by Fetakungen** [comment]
> Thanks! Can you provide the raw text from the event.original field.

{
  "_index": "pfelk-2020.08.30",
  "_type": "_doc",
  "_id": "6P8hQXQBIDmHQFMb82rO",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-08-30T20:49:38.149Z",
    "application": "VA-R1 suricata",
    "event": {
      "created": "Aug 30 22:49:38",
      "original": "<13>Aug 30 22:49:38 VA-R1 suricata: {\"timestamp\":\"2020-08-30T22:49:38.019978+0200\",\"flow_id\":1347962864417450,\"in_iface\":\"vmx0\",\"event_type\":\"flow\",\"src_ip\":\"X.X.X.X\",\"src_port\":9953,\"dest_ip\":\"40.90.4.205\",\"dest_port\":53,\"proto\":\"UDP\",\"app_proto\":\"dns\",\"flow\":{\"pkts_toserver\":1,\"pkts_toclient\":1,\"bytes_toserver\":108,\"bytes_toclient\":149,\"start\":\"2020-08-30T22:44:36.277162+0200\",\"end\":\"2020-08-30T22:44:36.322603+0200\",\"age\":0,\"state\":\"established\",\"reason\":\"timeout\",\"alerted\":false}}"
    },
    "priority": {
      "id": "13"
    },
    "port": 47228,
    "@version": "1",
    "type": "firewall",
    "host": "10.0.6.2",
    "observer": {
      "type": "firewall"
    },
    "tags": [
      "pf"
    ]
  },
  "fields": {
    "@timestamp": [
      "2020-08-30T20:49:38.149Z"
    ]
  },
  "sort": [
    1598820578149
  ]
}

**Comment by a3ilson** [comment]
Can you check line 4 within 03-filter.conf

Should look like this

```
# 03-filter.conf
filter {
  grok {
    match => {"message" => "<(?<[priority][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]}\s+(%{SYSLOGHOST:[observer][name]]}\s+)?%{GREEDYDATA:filter_message}"}
  }
  mutate {
    rename => {"message" => "[event][original]"}
  }
}
filter {
### PF ###
  if [type] == "firewall" {
    if "pf" in [tags] {
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => ["filter_message", "%{PF}"]
      }
      mutate {
        remove_tag => "Ready"
        strip => ["application"]
      }
    }
  }
### HAPROXY ###
  if [type] == "haproxy" {
    if "haproxy" in [tags] {
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => ["filter_message", "%{HAPROXY}"]
        }
      mutate {
        remove_field => ["filter_message"]
        remove_tag => "Ready"
        strip => ["application"]
      }
    }
  }
  if [type] == "beats" {
    if "beats" in [tags] {
      grok {
        match => { "[event][original]" => "%{SYSLOGLINE}" }
      }
      date {
        match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
      }
    }
  }
}
```

When I run your message through the grok debugger it separates the observer.name ```VA-R1``` and application ```suricata``` but your previous screenshot has both fields as one preventing further enrichment.

Once the application field equals ```suricata``` the remainder of the grok pattern will parse out correctly.

**Comment by Fetakungen** [comment]
> 
> 
> Can you check line 4 within 03-filter.conf
> 
> Should look like this
> 
> ```
> # 03-filter.conf
> filter {
>   grok {
>     match => {"message" => "<(?<[priority][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]}\s+(%{SYSLOGHOST:[observer][name]]}\s+)?%{GREEDYDATA:filter_message}"}
>   }
>   mutate {
>     rename => {"message" => "[event][original]"}
>   }
> }
> filter {
> ### PF ###
>   if [type] == "firewall" {
>     if "pf" in [tags] {
>       grok {
>         patterns_dir => ["/etc/logstash/conf.d/patterns"]
>         match => ["filter_message", "%{PF}"]
>       }
>       mutate {
>         remove_tag => "Ready"
>         strip => ["application"]
>       }
>     }
>   }
> ### HAPROXY ###
>   if [type] == "haproxy" {
>     if "haproxy" in [tags] {
>       grok {
>         patterns_dir => ["/etc/logstash/conf.d/patterns"]
>         match => ["filter_message", "%{HAPROXY}"]
>         }
>       mutate {
>         remove_field => ["filter_message"]
>         remove_tag => "Ready"
>         strip => ["application"]
>       }
>     }
>   }
>   if [type] == "beats" {
>     if "beats" in [tags] {
>       grok {
>         match => { "[event][original]" => "%{SYSLOGLINE}" }
>       }
>       date {
>         match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
>       }
>     }
>   }
> }
> ```
> 
> When I run your message through the grok debugger it separates the observer.name `VA-R1` and application `suricata` but your previous screenshot has both fields as one preventing further enrichment.
> 
> Once the application field equals `suricata` the remainder of the grok pattern will parse out correctly.

Testing now, the line did not look like that but the line you show is the orginal for opensense, should this be the case ? Are they the same now ?

**Comment by Fetakungen** [comment]
That gives , _grokparsefailure

**Comment by a3ilson** [comment]
I revised the line to eliminate the need to specify OPNsense or pfSense...the output is the same for both.  @TehMuffinMoo solved this and I just incorporated. After you make that change and restart logstash, it should be working...

**Comment by Fetakungen** [comment]
took your complete file, now it works!

Edit: this also solved the original error!! Great Thanks!

![Solved!](https://user-images.githubusercontent.com/56397651/91669548-fb3ad980-eb15-11ea-8926-1762e3fd5acf.PNG)

**Comment by a3ilson** [comment]
No worries and thank you!  I was able to make a few corrections with pfELK and hopefully mitigate others having similar issues.

**Comment by Fetakungen** [comment]
hmm, dunno why but all of a sudden it stopped and gives "pf, _grokparsefailure" again.. =/  Tried to restart logstash and edit filters again. output is this:
```
{
  "_index": "pfelk-2020.08.30",
  "_type": "_doc",
  "_id": "5wRBQXQBIDmHQFMbMGD_",
  "_version": 1,
  "_score": null,
  "_source": {
    "@version": "1",
    "event": {
      "original": "<13>Aug 30 23:23:45 VA-R1 suricata: {\"timestamp\":\"2020-08-30T23:23:44.735182+0200\",\"flow_id\":1377740026556766,\"in_iface\":\"vmx0\",\"event_type\":\"dns\",\"src_ip\":\"77.97.121.151\",\"src_port\":30885,\"dest_ip\":\"213.1XXXXXX\",\"dest_port\":53,\"proto\":\"UDP\",\"dns\":{\"version\":2,\"type\":\"answer\",\"id\":26058,\"flags\":\"8180\",\"qr\":true,\"rd\":true,\"ra\":true,\"rrname\":\"peacecorps.gov\",\"rrtype\":\"ANY\",\"rcode\":\"NOERROR\",\"answers\":[{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":12708},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":12708},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":1891},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"DS\",\"ttl\":1891},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"DS\",\"ttl\":1891},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"NS\",\"ttl\":12708},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":127909},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":127909},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":127909},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"DNSKEY\",\"ttl\":127909},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"DNSKEY\",\"ttl\":127909},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"DNSKEY\",\"ttl\":127909}],\"grouped\":{}}}",
      "created": "Aug 30 23:23:45"
    },
    "port": 35328,
    "type": "firewall",
    "host": "10.0.6.2",
    "observer": {
      "type": "firewall"
    },
    "tags": [
      "pf",
      "_grokparsefailure"
    ],
    "@timestamp": "2020-08-30T21:23:45.308Z",
    "priority": {
      "id": "13"
    }
  },
  "fields": {
    "@timestamp": [
      "2020-08-30T21:23:45.308Z"
    ]
  },
  "sort": [
    1598822625308
  ]
}
```

**Comment by a3ilson** [comment]
Can you run the following and attached the log file here:

/etc/logstash/pfelk-error.sh

**Comment by a3ilson** [comment]
The original event parses out fine on my end...

**Comment by a3ilson** [comment]
Delete the 45-cleanup.conf file and restart logstash.  That should preserve the ```pf_message``` and ```filter_message``` - I am curious as to what those fields reveal.

**Comment by Fetakungen** [comment]
> 
> 
> Delete the 45-cleanup.conf file and restart logstash. That should preserve the `pf_message` and `filter_message` - I am curious as to what those fields reveal.

Removing that file gives no working logstash with:


[2020-08-30T21:41:46,680][WARN ][logstash.filters.grok    ][main][89a99e289f9a0ece2df323ba2a6eb0f9cddb5df9e700b0ca5196e00ba6fd5e4a] Grok regexp threw exception {:exception=>"Invalid FieldReference: `[observer][name]]`", :backtrace=>["org/logstash/ext/JrubyEventExtLibrary.java:107:in `get'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.3.0/lib/logstash/filters/grok.rb:412:in `handle'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.3.0/lib/logstash/filters/grok.rb:372:in `block in match'", "(eval):7:in `block in compile_captures_func'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/jls-grok-0.11.5/lib/grok-pure.rb:202:in `capture'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.3.0/lib/logstash/filters/grok.rb:372:in `block in match'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.3.0/lib/logstash/filters/grok.rb:367:in `match'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.3.0/lib/logstash/filters/grok.rb:353:in `match_against_groks'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.3.0/lib/logstash/filters/grok.rb:343:in `match'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.3.0/lib/logstash/filters/grok.rb:307:in `block in filter'", "org/jruby/RubyHash.java:1415:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.3.0/lib/logstash/filters/grok.rb:306:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:178:in `block in multi_filter'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:175:in `multi_filter'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:134:in `multi_filter'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:293:in `block in start_workers'"], :class=>"RuntimeError"}

**Comment by Fetakungen** [comment]
> 
> 
> Delete the 45-cleanup.conf file and restart logstash. That should preserve the `pf_message` and `filter_message` - I am curious as to what those fields reveal.

gives this:

{
  "_index": "pfelk-2020.08.30",
  "_type": "_doc",
  "_id": "dJ9UQXQBg-jk5JiKQoIL",
  "_version": 1,
  "_score": null,
  "_source": {
    "port": 10902,
    "tags": [
      "pf",
      "_grokparsefailure"
    ],
    "@timestamp": "2020-08-30T21:44:34.955Z",
    "@version": "1",
    "event": {
      "created": "Aug 30 23:44:34",
      "original": "<13>Aug 30 23:44:34 VA-R1 suricata: {\"timestamp\":\"2020-08-30T23:44:34.934239+0200\",\"flow_id\":1708959396411612,\"in_iface\":\"vmx0\",\"event_type\":\"dns\",\"src_ip\":\"91.241.49.50\",\"src_port\":58521,\"dest_ip\":\"213.115.56.89\",\"dest_port\":53,\"proto\":\"UDP\",\"dns\":{\"version\":2,\"type\":\"answer\",\"id\":18645,\"flags\":\"8180\",\"qr\":true,\"rd\":true,\"ra\":true,\"rrname\":\"peacecorps.gov\",\"rrtype\":\"ANY\",\"rcode\":\"NOERROR\",\"answers\":[{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":11458},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":11458},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":641},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"DS\",\"ttl\":641},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"DS\",\"ttl\":641},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"NS\",\"ttl\":11458},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":126659},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":126659},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"RRSIG\",\"ttl\":126659},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"DNSKEY\",\"ttl\":126659},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"DNSKEY\",\"ttl\":126659},{\"rrname\":\"peacecorps.gov\",\"rrtype\":\"DNSKEY\",\"ttl\":126659}],\"grouped\":{}}}"
    },
    "type": "firewall",
    "observer": {
      "type": "firewall"
    },
    "priority": {
      "id": "13"
    },
    "host": "10.0.6.2"
  },
  "fields": {
    "@timestamp": [
      "2020-08-30T21:44:34.955Z"
    ]
  },
  "sort": [
    1598823874955
  ]
}

**Comment by Fetakungen** [comment]
> 
> 
> Can you run the following and attached the log file here:
> 
> /etc/logstash/pfelk-error.sh

Where can i find this script ? It's not located there and cannot find it in the repo.

**Comment by a3ilson** [comment]
https://raw.githubusercontent.com/3ilson/pfelk/master/error-data.sh

**Comment by Fetakungen** [comment]
> 
> 
> https://raw.githubusercontent.com/3ilson/pfelk/master/error-data.sh

[error.pfelk.log](https://github.com/3ilson/pfelk/files/5147524/error.pfelk.log)

**Comment by a3ilson** [comment]
Are you sending suricata logs to port 5141?

**Comment by Fetakungen** [comment]
> Are you sending suricata logs to port 5141?

Yeah, 

![dest](https://user-images.githubusercontent.com/56397651/91670327-a8185500-eb1c-11ea-9fe5-daec9f1c415f.PNG)

**Comment by a3ilson** [comment]
Dang...had an extra bracket in the 03-filter.conf file...

update as follows:
```
# 03-filter.conf
filter {
  grok {
    match => {"message" => "<(?<[priority][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]}\s+(%{SYSLOGHOST:[observer][name]}\s+)?%{GREEDYDATA:filter_message}"}
  }
  mutate {
    rename => {"message" => "[event][original]"}
  }
}
filter {
### PF ###
  if [type] == "firewall" {
    if "pf" in [tags] {
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => ["filter_message", "%{PF}"]
      }
      mutate {
        remove_tag => "Ready"
        strip => ["application"]
      }
    }
  }
### HAPROXY ###
  if [type] == "haproxy" {
    if "haproxy" in [tags] {
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => ["filter_message", "%{HAPROXY}"]
        }
      mutate {
        remove_field => ["filter_message"]
        remove_tag => "Ready"
        strip => ["application"]
      }
    }
  }
  if [type] == "beats" {
    if "beats" in [tags] {
      grok {
        match => { "[event][original]" => "%{SYSLOGLINE}" }
      }
      date {
        match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
      }
    }
  }
}
```

**Comment by a3ilson** [comment]
Restart and it should be good-to-go

**Comment by Fetakungen** [comment]
> 
> 
> Restart and it should be good-to-go

Great that did it, While we are at it the new suricata tempate is refering to a random ID that should not be ? 

[lens_merge_tables] > [esaggs] > Could not locate that index-pattern (id: 3e18b6e0-e856-11ea-8dd1-41abf3edff64), [click here to re-create it](management/kibana/indexPatterns)

**Comment by a3ilson** [comment]
Just updated the suricata dashboard...try importing again.

**Comment by Fetakungen** [comment]
> 
> 
> Just updated the suricata dashboard...try importing again.

Worked like a charm!

**Comment by a3ilson** [comment]
Great/Thanks for working through this and making the project a little better (remedied a few issues)

**Comment by Fetakungen** [comment]
> 
> 
> Great/Thanks for working through this and making the project a little better (remedied a few issues)

Nono, it is I who should thank! Great tool, all i need now is to get the kibana Alerts up and running =). Thanks!
