### ISSUE TITLE
Manual install

### ISSUE THREAD

**Issue by brohan** [pfelk/pfelk#139]
I have attempted to manually set up pfELK. I have installed Elasticsearch, Logstash and Kibana. On my pfSense instance, I have sent the logs to my Elasticseach IP and port 5140.  On my Elasticseach instance I have opened the firewall port 5140. "tcpdump -i any port 5140" command shows input coming from the pfSense instance. I have edited the logstash.yml line to read:

```
# The HTTP API web server will listen on an available port from the given range.
# Values can be specified as a single port (e.g., `9600`), or an inclusive range
# of ports (e.g., `9600-9700`).
#
 http.port: 5140
```

I have restarted my Elasticsearch stack, yet I am not seeing any new indices in Elasticsearch.  Can someone help me understand why I am not seeing the data from pfSense going into Elasticsearch?

FWIW I am using Cerebro to monitor my Elasticsearch instance which is not showing any indices.

Thank you!

**Comment by brohan** [comment]
For clarification in the 01-inputs.conf file, how does one Enable/Disable for pfsense? I removed the single # symbol at the start of the line leaving: pf# match => { like so:

`#########################################################################################
  if "pf" in [tags] {
    grok {
      # OPNsense - Enable/Disable the line below based on firewall platform
      #OPN# match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{SYSLOGHOST:[observer][name]} %{DATA:labels}(?:\[%{POSINT:pf_pid}\])?: %{GREEDYDATA:pf_message}" }
      ########################################################################################################################################
      # pfSense - Enable/Disable the line below based on firewall platform
      pf# match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
      remove_tag => "Ready"
    }
  }
}`

**Comment by a3ilson** [comment]
@brohan - adjust your 01-inputs.conf as below...and input your pfSense IP address in line 11.

```
# 01-inputs.conf
input {
  udp {
    port => 5140
  }
}
filter {
#########################################################
# Adjust to match the IP address of pfSense or OPNsense #
#########################################################
  if [host] == "192.168.0.1" {
    mutate {
      add_tag => [ "pf", "Ready" ]
      add_field => [ "[observer][type]", "firewall" ]
    }
  }
#########################################################################################
#To enable or ingest multiple pfSense or OPNsense instances uncomment the below section #
#########################################################################################
#if [host] == "10.0.0.1" {
#  mutate {
#    add_tag => ["pf", "Ready"]
#    add_field => [ "[observer][type]", "firewall" ]
#  }
#}
#########################################################################################
  if "pf" in [tags] {
    grok {
      # OPNsense - Enable/Disable the line below based on firewall platform
      #OPN# match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{SYSLOGHOST:[observer][name]} %{DATA:labels}(?:\[%{POSINT:pf_pid}\])?: %{GREEDYDATA:pf_message}" }
      ########################################################################################################################################
      # pfSense - Enable/Disable the line below based on firewall platform
      match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
      remove_tag => "Ready"
    }
  }
}
```

**Comment by a3ilson** [comment]
> 
> 
> I have attempted to manually set up pfELK. I have installed Elasticsearch, Logstash and Kibana. On my pfSense instance, I have sent the logs to my Elasticseach IP and port 5140. On my Elasticseach instance I have opened the firewall port 5140. "tcpdump -i any port 5140" command shows input coming from the pfSense instance. I have edited the logstash.yml line to read:
> 
> ```
> # The HTTP API web server will listen on an available port from the given range.
> # Values can be specified as a single port (e.g., `9600`), or an inclusive range
> # of ports (e.g., `9600-9700`).
> #
>  http.port: 5140
> ```
> 
> I have restarted my Elasticsearch stack, yet I am not seeing any new indices in Elasticsearch. Can someone help me understand why I am not seeing the data from pfSense going into Elasticsearch?
> 
> FWIW I am using Cerebro to monitor my Elasticsearch instance which is not showing any indices.
> 
> Thank you!

I would not append your logstash.yml file...restore and once you start receiving logs feel free to dabble around with logstash.yml however, I would recommend you take a look at the following before making adjustments to that file: https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html

**Comment by a3ilson** [comment]
No response from author
