### ISSUE TITLE
Dashboard dont show data

### ISSUE THREAD

**Issue by darvinrivera** [pfelk/pfelk#140]
After i imported the dashboard all data dont show. Only in Firewall section show date data and tags data, when i click in Expanded document all data is there.
The colection of log are fine.

Screenshots of Dashboard

![imagen](https://user-images.githubusercontent.com/17580342/87087613-6b596d00-c201-11ea-8c16-0fdbe6553f2f.png)

i use pfsense 2.4.5-RELEASE-p1
Debian 10 Buster 10.4

**Comment by darvinrivera** [comment]
Solved!!!! i modify the tags, when i fix it all data show!!!!

**Comment by revere521** [comment]
you all set then?

**Comment by revere521** [comment]
no response in 17 days closing
