### ISSUE TITLE
Mapping Conflict: suricata.rule.id

### ISSUE THREAD

**Issue by rrosson** [pfelk/pfelk#141]
**Describe the bug**
After fresh install of pfELK and importing the Firewall Dashboard and Suricata dashboard and running the system for a few days I get this message in Kibana when refreshing Index:
```
Mapping conflict
A field is defined as several types (string, integer, etc) across the indices that match this pattern. You may still be able to use these conflict fields in parts of Kibana, but they will be unavailable for functions that require Kibana to know their type. Correcting this issue will require reindexing your data.
```
**Screenshots**
![Screen Shot 2020-07-10 at 7 50 26 AM](https://user-images.githubusercontent.com/2329/87161653-11e55280-c282-11ea-9e81-58d87161a563.png)

**Firewall System (please complete the following information):**
 - OPNsense
 - Version: 20.1.8 
 
[error.pfelk.log](https://github.com/3ilson/pfelk/files/4903434/error.pfelk.log)

**Comment by a3ilson** [comment]
@rrosson - I haven't been able to replicate...but it appears the field type changed and contains multiple types.  You may need to re-index.

**Comment by fktkrt** [comment]
@rrosson, were you able to solve this by reindexing?

**Comment by rrosson** [comment]
re-indexing did not work.  :( I am going to close this since I am on a newer version of OPNsense (20.7.1) which has suricata 5 now plus some other changes. Couple that with day job taking a higher priority I do not want to have this hanging open on my account on not being able to respond in a timely manner.

**Comment by a3ilson** [comment]
Copy/let us know if the issue still exist with the upgrade.
