### ISSUE TITLE
index pattern doesn't match any indices

### ISSUE THREAD

**Issue by samcallen** [pfelk/pfelk#143]
@a3ilson i followed your installation guide to the end, but when i try to create index pattern  pf-*
i get a response "your index pattern does not match any indices" but you have 1 index which look similar ( kibana- sample-data-ecommerce)
can you help me? what am i doing wrong?

**Comment by a3ilson** [comment]
What installation method did you use?
OPNsense or pfSense?
Can you provide the output of your 01-inputs.conf file?
What is the ip address of your OPNsense/pfSense?
What is the ip address of your pfelk?

**Comment by samcallen** [comment]
@a3ilson i used pfsense.
01-input.conf output
![Screenshot from 2020-07-26 00-44-34](https://user-images.githubusercontent.com/65163697/88467764-df229780-ceda-11ea-83f2-f393b45a9e96.png)
![Screenshot from 2020-07-26 00-44-51](https://user-images.githubusercontent.com/65163697/88467770-f3669480-ceda-11ea-990f-b7c1064fbd81.png)
pfsense ip address: 192.168.2.1 (lan)
pfelk ip address:192.168.2.32

**Comment by a3ilson** [comment]
Simply remove "pf#" from 01-inputs.conf, save, and restart logstash.

The line should read:
```match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }```

**Comment by samcallen** [comment]
@a3ilson thanx👍
