### ISSUE TITLE
how do you visualise pf firewall logs in kibana?

### ISSUE THREAD

**Issue by samcallen** [pfelk/pfelk#144]
@a3ilson after installation how do i visualise only (not suracata or snort) pfsense firewall logs?

**Comment by revere521** [comment]
Install the firewall dashboard ndjson file from the repo following the post install guide in the readme.  Im on mobile, ill post a link when I get back if needed.On Jul 28, 2020 12:40 PM, samcallen <notifications@github.com> wrote:
@a3ilson after installation how do i visualise only (not suracata or snort) pfsense firewall logs?

**Comment by samcallen** [comment]
thanx
