### ISSUE TITLE
Missing Fields in Index, Script Install

### ISSUE THREAD

**Issue by fastxl** [pfelk/pfelk#145]
Only getting 27 Fields when creating the pf-* index, seems like their should be more. No source.port, source.IP and many others. Used the script install on fresh Ubuntu Server 20.0. No other custom configs.

 - pfSense 
 - 2.4.4-RELEASE-p3

**Comment by revere521** [comment]
what does your 01-inputs.conf look like?

You could also run the troubleshooting script detailed here https://github.com/3ilson/pfelk/blob/master/install/ubuntu.md#troubleshooting, and post the log output (basically the entire install config) in text so we can take a look

Did you go through all the configuration items post install? https://github.com/3ilson/pfelk/blob/master/install/configuration.md

**Comment by fastxl** [comment]
Yes, I ran through the post install config and I ran the script. 

Here is the 01-inputs.conf

```
# 01-inputs.conf
input {
  udp {
    port => 5140
  }
}
filter {
#########################################################
# Adjust to match the IP address of pfSense or OPNsense #
#########################################################
  if [host] == "172.16.48.1" {
    mutate {
      add_tag => [ "pf", "Ready" ]
      add_field => [ "[observer][type]", "firewall" ]
    }
  }

```
Error Log file
[error.pfelk.log](https://github.com/3ilson/pfelk/files/5007807/error.pfelk.log)

**Comment by revere521** [comment]
is the pfelk server on the same subnet as pfsense? 172,16.48.X?  in the default config like we have it setup they need to be on the same subnet.   If they aren't @3ilson I think has a method of altering the 01-inputs.conf...

Also; have a look at 05-firewall.conf and see if the interfaces listed (ibg0, ibg1, etc.) match the interfaces in pfsense under interfaces -> assignments.... if not, you can change them in between the "/^" and "$/" so they maych like /^re0$/ or /^em0$/.

Later you can also change the "[interface][alias]" and "[network][name]" to whatever you need/want inside the quotation marks. 

After you check those things, try refreshing the index in Kibana

**Comment by fastxl** [comment]
Thanks for the tips.

The pfelk server is on a different subnet than pfsense. Hopefully @a3ilson  can point me in the right direction.

My interface names are WAN = mvneta2, LAN = mvneta1, VLAN100 = mvneta1.100 (I have other vlans that follow suit) So in the 05-firewall.conf do I need to make a section for each interface I have? Like this?

```
    # Change interface as desired
      if [interface][name] =~ /^mvneta2$/ {
        mutate {
          add_field => { "[interface][alias]" => "WAN" }
          add_field => { "[network][name]" => "FiOS" }
      }
    }
     # Change interface as desired
      if [interface][name] =~ /^mvneta1$/ {
        mutate {
          add_field => { "[interface][alias]" => "LAN" }
          add_field => { "[network][name]" => "Lan Network" }
      }
    }
    # Change interface as desired
      if [interface][name] =~ /^mvneta1.100$/ {
        mutate {
          add_field => { "[interface][alias]" => "VLAN100" }
          add_field => { "[network][name]" => "VLAN 100" }
      }
    }
```

**Comment by revere521** [comment]
As long as the interface labels under interface->assignments align with "mvneta0, mvneta1, etc. then that would be correct - What you posted above looks correct as well.  that should help pick up some more recognized field data.  

you can add more or remove the entire sections to/from the config like: 

```
# Change interface as desired
      if [interface][name] =~ /^INTERFACE$/ {
        mutate {
          add_field => { "[interface][alias]" => "ALIAS NAME" }
          add_field => { "[network][name]" => "Friendly Name" }
      }
}
```

If you look at some of the closed issues, you may see some methods of altering the inputs.conf; I cant remember if this iteration accounts for for the issue or not - but i think it has to do with removing or modifying the `if [host]` statement to be less specific in the intake of log traffic.

**Comment by revere521** [comment]
I beleive the solution looks like the config below, rename your existing 01-inputs.conf to

**Comment by fastxl** [comment]
I figured the subnet thing out. Currently the pfELK server is on VLAN 10 of my pfSense. So I just changed the 01-inputs.conf to an ip  (192.168.10.1) that is in the range of VLAN 10. Now everything seems to be working.

**Comment by revere521** [comment]
for some reason my longer comment got cutoff, but if you got it working - awesome!

the input conf that may work without specifying the IP is something like this, in case someone else comes looking, or you want to play with it: 

```
# 01-inputs.conf
input {
  udp {
     port => 5140
     add_tag => [ "pf", "Ready" ]
     add_field => [ "[observer][type]", "firewall" ]
  }
  if "pf" in [tags] {
    grok {
      match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
      remove_tag => "Ready"
    }
  }
}
```
That has the initial pfsense grok pattern and not opnsense, so someone with opnsense would need to change the `match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }` line

**Comment by a3ilson** [comment]
@fastxl - The solution by @revere521 or your amendment works.  Additionally and if needed, you can add multiple instances by amending the 01-inputs file as follows:

```
input {
  udp {
     port => 5140
     tags => ["pf", "firewall-1"]
  }
  udp {
     port => 5141
     tags => ["pf", "firewall-2"]
  }
  udp {
     port => 5142
     tags => ["pf", "firewall-3"]
  }
}
```
or amend line 11 to point to the router vs pfSense if ELK & pfSense are on different networks

or you can remove lines 11-16, which just limits traffic from the specified port on line 4 and to the specified ip address...essentially it just filters out other traffic which would result in grok_failures.

**Comment by revere521** [comment]
@fastxl are you all set here?

**Comment by fastxl** [comment]
Yes, all set. Thanks for the help.
