### ISSUE TITLE
how to upgrade? 

### ISSUE THREAD

**Issue by samcallen** [pfelk/pfelk#146]
@a3ilson how to upgrade pfelk installed via a script installer.

**Comment by a3ilson** [comment]
What are you attempting to upgrade? If your upgrading Elastic/Kibana/Logstash - I would recommend upgrading those separately while maintaining your original configuration files.

**Comment by revere521** [comment]
I have had success just upgrading on a schedule with the package manager as needed; the only need to change the configs on a working install is if you want to try something new that was changed in the repo. 

to that point, i have primarily just made manual changes so far - comparing the configs in the repo and changing things to match as needed; I'm not sure if the scripted install would work without leaving behind artifact.  that would be an interesting test.

**Comment by samcallen** [comment]
@a3ilson iam trying to upgrade Elastic/Kibana/Logstash. okay i get it👍

**Comment by a3ilson** [comment]
I'll annotate an upgrade option within a future script - thanks
