### ISSUE TITLE
Couldn't find any Elasticsearch data

### ISSUE THREAD

**Issue by madix5** [pfelk/pfelk#147]
Hi! I have tried installing using the script and manually and each time I get the same results. I am on Ubuntu 20.04 and all services are started. I cannot get any data to ingest from pfsense 2.4.5. Any help would be appreciated. Thanks
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
Linux 5.4.0-42-generic x86_64
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
 
 **Installation method (manual, ansible-playbook, docker, script):** script
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
elasticsearch/now 7.7.0 amd64
logstash/now 1:7.7.0-1 all 
kibana/now 7.7.0 amd64

[kibana.txt](https://github.com/3ilson/pfelk/files/5023331/kibana.txt)
[logstash.txt](https://github.com/3ilson/pfelk/files/5023332/logstash.txt)
[elastic.txt](https://github.com/3ilson/pfelk/files/5023333/elastic.txt)

[error.pfelk.log](https://github.com/3ilson/pfelk/files/5023110/error.pfelk.log)

**Comment by a3ilson** [comment]
@madix5 - give it another try. I revised the 50-outputs.conf file

**Comment by madix5** [comment]
> @madix5 - give it another try. I revised the 50-outputs.conf file

That worked thanks. I first edited the existing 50-outputs.conf file and that didnt change anything for me. After running a new install i am now receiving data but I have 2 pf indexes but i will figure this out. Thanks for the help!

**Comment by a3ilson** [comment]
No worries and thanks for the inquiry.
