### ISSUE TITLE
Anyone doing this with multi-node setup? Cluster?

### ISSUE THREAD

**Issue by fastxl** [pfelk/pfelk#148]
First off, awesome work here and well supported. Just curious is anyone is doing this with a multi-node setup? I am playing around with a 3 node cluster and just wondering how you get the data to replicate to all 3. Do you have pfSense send the data to all 3 nodes? That doesn't seem right to me. Anyone care to share info or point me in a direction that could help?

**Comment by a3ilson** [comment]
@fastxl Thanks!
Multiple systems are supported. I actually ordered some new hardware in which I plan to setup a multiple setup with the purpose of expanding on the dashboards (i.e. toggle between instances and/or comparison).

Let me know if you need help with the triple setup.  You'll need to amend the 01-inputs.conf, to accommodate your three instances. 

Example:
```
# 01-inputs.conf
input {
  udp {
     port => 5140
     tags => ["pf", "Ready", "firewall-1"]
  }
  udp {
     port => 5141
     tags => ["pf", "Ready", "firewall-2"]
  }
  udp {
     port => 5142
     tags => ["pf", "Ready", "firewall-3"]
  }
}
```

**Comment by fastxl** [comment]
@a3ilson Thanks for the reply. I saw that you can send data from multiple Firewalls. I am talking more of a multi-node/High Availability ELK setup

**Comment by a3ilson** [comment]
@fastxl - I kept this setup simple but you can absolutely expand to suite your needs/requirements. Are you familiar with dockers? I have my setup on a one VM running Ubuntu with Logstash and Kibana and on separate VM have three instances of Elasticsearch running via Docker Containers. Let me know what type of setup your looking to configure and I'll help as needed.

**Comment by fastxl** [comment]
@a3ilson I figured it out. I have 3 Full ELK servers running in a "node", probably overkill but I wanted to see how they worked. I am sending the data from pfSense to all three and it looks like they "figure" out how to deal with the data. I am not familiar with Dockers yet, it's on my list of things to learn. I will let you know if I have further questions. Thanks

**Comment by fktkrt** [comment]
Hi @fastxl,
What is the current configuration of your cluster, and what is goal you want to achieve, resilience to data loss? 
With 3 nodes, it makes sense to have all 3 as data nodes: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html#data-node

These are master-eligible by default, so it can take 2 of them to elect a master, this way you are protected against the failure of any single node.

I can recommend these slides to get familiar with common use cases and the related best practices: https://www.elastic.co/pdf/architecture-best-practices.pdf

**Comment by fastxl** [comment]
@fktkrt Thanks for the direction. Currently I have 3 full nodes, all master-eligible, as I am just learning the "cluster" thing. Resilience to data loss would probably be the primary objective.
