### ISSUE TITLE
snort

### ISSUE THREAD

**Issue by samcallen** [pfelk/pfelk#149]
@a3ilson snort saved object gives an error (Could not locate that index-pattern-field (id: snort.rule.description.keyword) when i try to view it. what am i missing?

**Comment by a3ilson** [comment]
@samcallen - First, is pfelk running and receiving logs? Next, is snort configured and setup to send logs?  

Sometimes you'll have to wait for logs to be ingested before the data fields are defined.  Based on your question, it appears you have it running and configured.  I would go back to where you configured the pattern and refresh to define new fields.

**Comment by samcallen** [comment]
🤔👍
