### ISSUE TITLE
Parse Openvpn Logs also 

### ISSUE THREAD

**Issue by ronantme** [pfelk/pfelk#15]
Would it also be able to parse Openvpn logs in these confs? I would like to monitor (from a Openvpn server) failed login attempts (usernames) also along with country of these failed logins (geoip) 

I attempted to give this a shot but failed miserably.

**Comment by a3ilson** [comment]
Yes it is possible.... Can you provide a sample of your output openvpn
logs.  It'll be a few months until I return home. Then I'll mimic a similar
setup to replicate and post.

**Comment by swedishmike** [comment]
This is a very simple pattern I added to my setup, this one logs out the connection so at least I can alert/see when connections are made. I get src_ip, src_port and clientname from this. Something which then can be used with geo_ip etc to further enrich the data.

A possible start? 

`PFSENSE_OPENVPN_CONNECTION %{IP:vpn_src_ip}\:%{INT:vpn_src_port}%{SPACE}\[%{DATA:vpn_client}\]%{SPACE}Peer%{SPACE}Connection%{SPACE}Initiated%{SPACE}with%{GREEDYDATA}`

**Comment by a3ilson** [comment]
Incorporated within the configuration file and grok pattern - thanks!
