### ISSUE TITLE
Count of Rules Description

### ISSUE THREAD

**Issue by s7thamon** [pfelk/pfelk#152]
**Describe the bug**
Getting 'null' from the "Count of Rules Description" metric in the dashboard

**Firewall System (please complete the following information):**
OPNsense 20.7-amd64
 
**Operating System (please complete the following information):**
Ubuntu 20.04
 
 **Installation method (manual, ansible-playbook, docker, script):**
pfelk-install-1.0.0.sh

**Elasticsearch, Logstash, Kibana (please complete the following information):**
elasticsearch 7.7.0
logstash 1:7.7.0-1
kibana 7.7.0

I have a 'Description' set on each rule in opnsense, is there anything else that would need to be configured? Unsure if I'm missing anything, all the other metrics appear fine. In Kibana it appears that each event Tracker is set as 0.

**Comment by revere521** [comment]
That function may only apply to pfsense; but the setup is in the readme here: https://github.com/3ilson/pfelk/blob/master/install/configuration.md

If it can't be configured for OPNsense, you can remove the visulization for the dashboard.

**Comment by s7thamon** [comment]
Ah, thank you for that.
