### ISSUE TITLE
Grok Filter for Opensense does not match anything

### ISSUE THREAD

**Issue by new-gen23** [pfelk/pfelk#153]
**Describe the bug**
The pfelk Grok filter for the Opensense messages in 01-inputs.conf looks like this:
`match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{SYSLOGHOST:[observer][name]} %{DATA:labels}(?:\[%{POSINT:pf_pid}\])?: %{GREEDYDATA:pf_message}" }`

However, a typical opensense filterlog message looks like this:
`<134>Aug 16 11:43:57 fw.localdomain filterlog[71793]: 71,,,0,igb1,match,pass,out,4,0x0,,63,41792,0,DF,17,udp,70,192.168.1.2,208.67.222.222,55301,53,50`

Honestly, I have given up to find a working grok filter in the internet that works with the current opensense. I also find it very hard to debug such match rules. Perhaps someone else with grok filter syntax experience knows where the bug is or can point me to a solution to debug it myself?

**Screenshots**
Result in ES/Kibana:
![kibana](https://user-images.githubusercontent.com/1741662/90333143-8323ce00-dfc3-11ea-836d-15cfe2aaeaf9.png)

**Firewall System (please complete the following information):**
 - OPNsense 20.7 (2020-07-30)
 
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components : 7.8.1 (logstash: 7.8.1-1)

**Comment by a3ilson** [comment]
![OPNsense GROK Example Breakdown](https://user-images.githubusercontent.com/16884679/90334878-b011ba00-df9e-11ea-80e4-2758bfa677f3.png)

@new-gen23 - What is it that you are attempting to accomplish?  That GROK patter will successfully parse out the provided message.

**Comment by new-gen23** [comment]
Wow, thank you for the illustration. I think I will print it as a cheat sheet. Thank you.

It looks right. But shouldn't a follow up step parse the pf_message into separate fields?

**Comment by a3ilson** [comment]
Thanks and yes...the following *.conf files further enrich the message based on various variables.

**Comment by new-gen23** [comment]
Ok, I think you solved my call for help. I will have to figure out the rest. So I will close the issue. Thank you again for the explanation!

**Comment by new-gen23** [comment]
Actually, I think I am now more confused. If you are correct, I should have fields like pf_message, pf_pid and labels. But my screenshot shows no such fields holding the parsed data. I thought the grok syntax would be: %{variable_type:variable_name}.
Or are these variable_names only available in Logstash and would need to be add_field'd to be accessible in ES/Kibana ?

**Comment by new-gen23** [comment]
I think I answered my question myself :) I can see the add_field in 05_firewall.conf, so it seems to be stuck somewhere in my broken setup. Anyway, this issue is solved.

**Comment by a3ilson** [comment]
have your refreshed your index? are you getting any grokfailures?
