### ISSUE TITLE
Squid-Proxy data onboarding (OPNsense)

### ISSUE THREAD

**Issue by BeNeDeLuX** [pfelk/pfelk#155]
Here is the feature request for the Squid-Proxy Logs as discusses :)
My config and logs are generated under OPNsense 20.7.1

Here is a part of the squid config. I use my own CA for certificates on the OPNSense and play "Man-in-the-middle" with ssl interceptions inside squid. I also use Clam-AV via ICAP to scan for Viruses. If needed, i can describe the whole setup.

Here is the need information for the output and some settings for the log:
![squid-log](https://user-images.githubusercontent.com/1895086/90932404-e320d700-e3fe-11ea-8270-2661cb991e83.PNG)

These settings are not the default settings. I adjusted them to my needs (but should fits to the most setups if you want collect the data)

** 1.) RAW Squid Event in default Syslog:**
`<166>Aug 21 22:08:13 myfirewall.my-domain.tld (squid-1)[6802]: 1598040493.253    325 172.16.17.119 TCP_MISS/304 2912 GET https://github.com/3ilson/pfelk/file-list/master - HIER_DIRECT/140.82.121.4 -`

**GROK Pattern for the default Syslog format**
`<%{NUMBER:number}>%{SYSLOGTIMESTAMP:timestamp} %{DATA:hostname} %{GREEDYDATA:squid_process} %{NUMBER:epoch_timestamp}\s+%{NUMBER:response_time} %{IPORHOST:src_ip} %{NOTSPACE:squid_request_status}/%{NUMBER:http_status_code} %{NUMBER:transfer_size} %{NOTSPACE:http_method} (%{URIPROTO:url_scheme}://)?(?<url_host>\S+?)(:%{INT:url_port})?(/%{NOTSPACE:url_path})?\s+%{NOTSPACE:client_identity}\s+%{NOTSPACE:peer_code}/%{NOTSPACE:peerhost}\s+%{NOTSPACE:content_type}`

Beware, the grok patterns is as bad as my first haproxy pattern. Means, without  naming scheme to conform to ECS or extra tags.

**2.) RAW Squid Events in Syslog JSON** (-> a lot more fields and my preferred Version)
`<166>Aug 21 22:30:02 myfirewall.my-domain.tld (squid-1)[38379]: {"@timestamp":"2020-08-21T20:30:02+0000","ecs":{"version":"1.0.0"},"event":{"id":"-","dataset":"squid.access","duration":"92"},"http":{"version":"1.1","request":{"method":"GET","referrer":"-"},"response":{"body":{"bytes": 1115, "status_code": 301}}},"host":{"hostname":"DESKTOP-BBHCLCR.my-domain.tld"},"service":{"name":"proxy","type":"squid"},"source":{"ip":"172.16.17.119"},"url":{"original":"https://netflix.com/"},"user":{"name":"-"},"user_agent":{"original":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Brave Chrome/84.0.4147.135 Safari/537.36"},"labels":{"request_status":"TCP_MISS","hierarchy_status":"HIER_DIRECT"},"message":"GET https://netflix.com/ HTTP/1.1"}`

I´m not sure if the JSON output also needs a default GROK pattern (since the fields are defined) or just a template.

I prefer the Syslog JSON format (2.) because it has a lot more fields and they are in a structured JSON Format.
But that´s just my personal opinion and i don´t want to set such default settings for logging on your project here.

Please tell me if you need more information.
Thanks.

**Comment by BeNeDeLuX** [comment]
Works also fine for me. I close this issue.
Thank you!

**Comment by a3ilson** [comment]
@BeNeDeLuX - Curious about your setup?  Are you capturing the SSL traffic to/from squid and decrypting with your SSL? I'm looking to build a setup that'll allow for PCAP capture, decrypt and analysis.

**Comment by BeNeDeLuX** [comment]
I enabled SSL inspection inside squid which replace all SSL Certs with my own SSL Certs from the OPNSense CA.
Here is an example from github.com:
![ssl_intercept](https://user-images.githubusercontent.com/1895086/91604086-57fb9000-e96e-11ea-9845-f101001813f0.PNG)

Here are some screenshots about my configuration. I use this method to scan the ssl traffic for viruses via the ICAP Server and ClamAV. But it should be possible to decrypt this TLS Traffic again since you have the private key for. I have Moloch (https://molo.ch/) as PCAP capture and analysis still on my todo list.

![Proxy_SSL_CA](https://user-images.githubusercontent.com/1895086/91604418-e5d77b00-e96e-11ea-8a13-80ea7be6b889.PNG)
![squid_icap](https://user-images.githubusercontent.com/1895086/91604415-e53ee480-e96e-11ea-8385-ae7da72670c9.PNG)
![icap](https://user-images.githubusercontent.com/1895086/91604412-e4a64e00-e96e-11ea-920b-af8b00de86b0.PNG)
![icap_clamav](https://user-images.githubusercontent.com/1895086/91604410-e3752100-e96e-11ea-8abc-2582725553c5.PNG)

You could try to capture the traffic on the OPNsense directly for a test as PCAP under Interfaces -> Diagnostic -> Packet Capture and try to decrypt it in wireshark. Hope that helps you out.

**Comment by a3ilson** [comment]
Thanks! I have a similar setup and was hoping for a way to offload (unencrypted) traffic but I'll stick with my tap (mirrored) port sitting between the firewall.  I'm running Moloch and was looking for a solution to send/store the data unencrypted.
