### ISSUE TITLE
50-outputs.conf and logstash.conf bug

### ISSUE THREAD

**Issue by Hams3c** [pfelk/pfelk#156]
**Describe the bug**
`logstash.conf` and `50-outputs.conf` conflict.  My ES server runs on 192.168.10.10.  If I update `logstash.conf` to use 192.168.10.10, I still get a "cannot find server at localhost:9200' error.  See detail below.

**To Reproduce**
the default install of `logstash.conf` contains the following code

```
  1 input {
  2   beats {
  3     port => 5044
  4   }
  5 }
  6 filter {
  7   if [type] == "syslog" {
  8      grok {
  9         match => { "message" => "%{SYSLOGLINE}" }
 10   }
 11      date {
 12         match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
 13      }
 14   }
 15 }
 16 output {
 17   elasticsearch {
 18     hosts => ["localhost:9200"]
 19     index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
 20   }
 21 }
 22
```

`50-outputs.conf` contains the following code

```
  1 # 50-outputs.conf
  2 output {
  3   elasticsearch {
  4     id => "pf"
  5     hosts => ["http://localhost:9200"]
  6     index => "pf-%{+YYYY.MM.dd}"
  7     manage_template => true
  8     template => "/etc/logstash/conf.d/templates/pf-geoip-template.json"
  9     template_name => "pf-geoip"
 10     template_overwrite => false
 11   }
 12 }
```

Because `50-outputs.conf` overwrites what's in `logstash.conf`, updating `logstash.conf` doesn't work.  See the following error without updating `50-outputs.conf`
```
[2020-08-22T10:58:07,496][WARN ][logstash.outputs.elasticsearch][main] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://localhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://localhost:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
```

**Screenshots**
N/A

**Firewall System (please complete the following information):**
 - pfSense Version | 2.4.5-RELEASE-p1 (arm64) built on Tue Jun 02 17:44:41 EDT 2020 FreeBSD 11.3-STABLE

**Operating System (please complete the following information):**
Linux 4.15.0-112-generic x86_64
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
**Installation method (manual, ansible-playbook, docker, script):**
apt install elasticsearch
apt install logstash
apt install kibana
apt install filebeat
./pfElk-your-install-script.sh

 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
kibana-oss/stable,now 7.9.0 amd64 [installed]
filebeat/stable,now 7.9.0 amd64 [installed]
logstash-oss/stable,stable,now 1:7.9.0-1 all [installed]
elasticsearch-oss/stable,now 7.9.0 amd64 [installed]

**Comment by a3ilson** [comment]
Let me more of this is still an open issue otherwise the issue will be closed.

**Comment by Hams3c** [comment]
Go ahead and close.  Thank you.

**Comment by a3ilson** [comment]
Closed
