### ISSUE TITLE
Kibana, Bar Graphs Stacked

### ISSUE THREAD

**Issue by s7thamon** [pfelk/pfelk#159]
**Describe the bug**
Bar Graphs for _Top Ten Countries_ and _Top IPs Blocked_ appear to always be stacked, despite the setting off in the visualization.

**Screenshots**
![image](https://user-images.githubusercontent.com/66268528/91346165-6c912a00-e7ae-11ea-8636-6cc378671b7e.png)
![image](https://user-images.githubusercontent.com/66268528/91346186-74e96500-e7ae-11ea-9dfc-edef1a6877f9.png)

**Firewall System (please complete the following information):**
OPNsense
 
**Operating System (please complete the following information):**
Ubuntu 20.04
 
 **Installation method (manual, ansible-playbook, docker, script):**
 bash install script

**Elasticsearch, Logstash, Kibana (please complete the following information):**
kibana 7.9.0

**Comment by a3ilson** [comment]
@s7thamon - This may be related to the 7.9.0 release.  I am currently building new dashboards.

[New Firewall Dashboard](https://raw.githubusercontent.com/3ilson/pfelk/master/Dashboard/v5.5/v5.5%20Firewall%20Dashboard.png)

**Comment by s7thamon** [comment]
I rolled back to 7.8.1 and it does appear to work fine with that version. Still tinkering with trying to figure out the issue in 7.9, not able to find anything yet.

I like some of the new stats on the dashboard. The top 10 countries/ips blocked are pretty key on this end.

**Comment by a3ilson** [comment]
I would delete the visualization from your dashboard.  Then create a new visualization...I'd recommend 'Lens-beta' and drag the destination.geo.country_name.keyword field into the area and select the bar graph. You'll also need to adjust the display number by selecting the x-axis value.

![overview](https://user-images.githubusercontent.com/16884679/91355316-f98eb000-e7bb-11ea-9edc-345cb03766de.PNG)


Then go back and edit the dashboard and insert the new visualization.

**Comment by a3ilson** [comment]
Thanks for the input... below is the dashboard for the updated pfelk.

![v5 5 Firewall Dashboard](https://user-images.githubusercontent.com/16884679/91357327-11b3fe80-e7bf-11ea-941d-9fb6c731b4bf.PNG)

**Comment by s7thamon** [comment]
Appreciate it, looks like this will work for now using the lens feature. Not as nice since it's missing the legend - will wait for the updated dashboard. Cheers!

**Comment by a3ilson** [comment]
@s7thamon - New Dashboard and setup files were updated/posted...it will require re-indexing, due to a number of changes.

**Comment by s7thamon** [comment]
`[lens_merge_tables] > [esaggs] > Could not locate that index-pattern (id: 7f897d10-e551-11ea-8dd1-41abf3edff64), [click here to re-create it](management/kibana/indexPatterns)`

Using the new dashboards, getting a lot of index-pattern errors. I removed the old index and dashboards, and imported everything as new. Conf files all updated and overwritten. The data coming into 'Discover' in Kibana looks fine.

![image](https://user-images.githubusercontent.com/66268528/91469272-2a74f080-e861-11ea-9de4-c99ea97ff45a.png)

![image](https://user-images.githubusercontent.com/66268528/91469283-2f39a480-e861-11ea-8a5c-ede91ea8d97e.png)

![image](https://user-images.githubusercontent.com/66268528/91469324-3e205700-e861-11ea-88c7-727689f588fd.png)

**Comment by a3ilson** [comment]
@s7thamon - I realized this earlier today. All but the firewall dashboard was rebuilt.  Give me a  few and I'll have it correct.

**Comment by a3ilson** [comment]
Updated.  Give the Firewall Dashboard another try and sorry for the inconvenience.

**Comment by s7thamon** [comment]
Thanks, looks like all is working but the last panel for: "Firewall - Map (Lines)"
![image](https://user-images.githubusercontent.com/66268528/91483773-3919d280-e876-11ea-9f78-67719c441db9.png)

![image](https://user-images.githubusercontent.com/66268528/91484085-ae85a300-e876-11ea-9d48-92cfb5493b0b.png)

![image](https://user-images.githubusercontent.com/66268528/91484289-fd333d00-e876-11ea-9f53-074227e02941.png)


The "Firewall - Map (Country)" seems okay

**Comment by a3ilson** [comment]
Please check to see if the template (pf-geoip) was installed.

Management>Stack Management>>Data>>Index Management>>Index Template
![Capture](https://user-images.githubusercontent.com/16884679/91487561-ee02be00-e87b-11ea-8fe6-ff06b3be3bf2.PNG)

**Comment by revere521** [comment]
ive deleted and removed the index template, and also removed anything old from the ingest pipelines, and this is still happening for me as well.  I'm continuing to dig.

**Comment by s7thamon** [comment]
![image](https://user-images.githubusercontent.com/66268528/91487893-7719f500-e87c-11ea-899b-6c3257dbf1ee.png)

Can confirm it's installed

**Comment by a3ilson** [comment]
Can you confirm the contents of pf-geoip.conf

```
{
  "index_patterns" : "pfelk-*",
  "version" : 80001,
  "settings" : {
    "index.refresh_interval" : "5s",
    "number_of_shards": 2
  },
  "mappings" : {
    "dynamic_templates" : [ {
      "message_field" : {
        "path_match" : "message",
        "match_mapping_type" : "string",
        "mapping" : {
          "type" : "text",
          "norms" : false
        }
      }
    }, {
      "string_fields" : {
        "match" : "*",
        "match_mapping_type" : "string",
        "mapping" : {
          "type" : "text", "norms" : false,
          "fields" : {
            "keyword" : { "type": "keyword", "ignore_above": 256 }
          }
        }
      }
    } ],
    "properties" : {
      "destination": {
        "properties": {
          "geo": {
            "dynamic": true,
            "properties": {
              "ip": { "type": "ip" },
              "location" : { "type" : "geo_point" },
              "latitude" : { "type" : "half_float" },
              "longitude" : { "type" : "half_float" }
            }
          }
        }
      },
      "source": {
        "properties": {
          "geo": {
            "dynamic": true,
            "properties": {
              "ip": { "type": "ip" },
              "location" : { "type" : "geo_point" },
              "latitude" : { "type" : "half_float" },
              "longitude" : { "type" : "half_float" }
            }
          }
        }
      }
    }
  }
}
```

**Comment by s7thamon** [comment]
Yes it exists and is identical to what is posted above

**Comment by a3ilson** [comment]
Give the previous one (below) a try... I only update the index pattern.  The original contains the "as" fields which do not contain GeoIP data:

```
{
  "index_patterns" : "pfelk-*",
  "version" : 80001,
  "settings" : {
    "index.refresh_interval" : "5s",
    "number_of_shards": 2
  },
  "mappings" : {
    "dynamic_templates" : [ {
      "message_field" : {
        "path_match" : "message",
        "match_mapping_type" : "string",
        "mapping" : {
          "type" : "text",
          "norms" : false
        }
      }
    }, {
      "string_fields" : {
        "match" : "*",
        "match_mapping_type" : "string",
        "mapping" : {
          "type" : "text", "norms" : false,
          "fields" : {
            "keyword" : { "type": "keyword", "ignore_above": 256 }
          }
        }
      }
    } ],
    "properties" : {
      "destination": {
        "properties": {
          "geo": {
            "dynamic": true,
            "properties": {
              "ip": { "type": "ip" },
              "location" : { "type" : "geo_point" },
              "latitude" : { "type" : "half_float" },
              "longitude" : { "type" : "half_float" }
            }
          },
          "as": {
            "dynamic": true,
            "properties": {
              "ip": { "type": "ip" },
              "location" : { "type" : "geo_point" },
              "latitude" : { "type" : "half_float" },
              "longitude" : { "type" : "half_float" }
            }
          }
        }
      },
      "source": {
        "properties": {
          "geo": {
            "dynamic": true,
            "properties": {
              "ip": { "type": "ip" },
              "location" : { "type" : "geo_point" },
              "latitude" : { "type" : "half_float" },
              "longitude" : { "type" : "half_float" }
            }
          },
          "as": {
            "dynamic": true,
            "properties": {
              "ip": { "type": "ip" },
              "location" : { "type" : "geo_point" },
              "latitude" : { "type" : "half_float" },
              "longitude" : { "type" : "half_float" }
            }
          }
        }
      }
    }
  }
}
```

**Comment by s7thamon** [comment]
Confirmed 'pf-geoip' now contains "as" in Kibana and logstash conf. Location still appears missing, destination.geo.latitude and destination.geo.longitude appear fine


![image](https://user-images.githubusercontent.com/66268528/91495499-9d459200-e888-11ea-8854-9e7f2968dc2a.png)

![image](https://user-images.githubusercontent.com/66268528/91495536-acc4db00-e888-11ea-95be-720259de75e5.png)

**Comment by a3ilson** [comment]
You'll need to purge your index when updating/revising the templates

**Comment by revere521** [comment]
going back an deleting the new pfelk-* index and then waiting and refreshing the index pattern a few times resolved my issue.

**Comment by a3ilson** [comment]
Cool beans!

So to remedy in the future:
- stop logstash ```systemctl stop logstash.service```
- delete the Kibana Index Pattern
- delete the Elastic Indices 
- start logstash ```systemctl start logstash.service```

**Comment by s7thamon** [comment]
That did the trick. I had deleted the index pattern but didn't flush the indices. Looks good now :)

**Comment by a3ilson** [comment]
Issue resolved
