### ISSUE TITLE
Question about - Revise/Update w/pfsense IP address (10-syslog.conf)

### ISSUE THREAD

**Issue by xefil** [pfelk/pfelk#16]
Hello,

I've a simply question about the doc:
In '10-syslog.con' I need to replace my pfSense IP address.
The Same pfSense has more than one IP, It has different interfaces. Should I put in all the pfSense IP adresses?
And why is this task needed?

Thanks a lot!

Simon

**Comment by uhlhosting** [comment]
this is how it communicates and know from where the data comes from.

**Comment by xefil** [comment]
thanks for the answer. So, in case my pfSense has 3 IP addresses, should I insert all them here?
Thank you!

**Comment by a3ilson** [comment]
That depends.  You would reference all three if you have three pfSense instances.  However, if you have one pfSense instance with multiple NICs managing multiple subnets (i.e. one pfSesne instance with three NICs [10.x.x.x; 172.22.x.x; 192.168.x.x) then only one would be needed.

**Comment by xefil** [comment]
Ok, many thanks!!!
Simon
