### ISSUE TITLE
Snort Dashboard for v5.5

### ISSUE THREAD

**Issue by a3ilson** [pfelk/pfelk#160]
**Is your feature request related to a problem? Please describe.**
Need a new and/or updated SNORT dashboard for v5.5.  The previous version is not supported with the recent updates/revision.

**Describe the solution you'd like**
Update/New SNORT dashboard for the latest pfELK

**Comment by revere521** [comment]
Sorry, i've been AWOL.. I have had a big deployment in the day job that's taken a lot my time up.

I'll get something together asap; I did notice some visualizations being wonky after 7.9.  I'll update tonight and take a look

**Comment by a3ilson** [comment]
No worries, take your time.... I’d open for anyone, I just tagged you done
I knew you’re sporting pfSense.

Hope all is well.  Apologize for all the recent changes but it’ll help with
further enrichment.

**Comment by revere521** [comment]
no reason to apologize, i saw all the activity...progress!

I'm nearly out of the woods, i go to prod in early Sept....thank goodness

**Comment by revere521** [comment]
i'm having some issues with the maps saying the destination.geo.location field no longer exists and some other small wonkyness; i will try to pick this up tomorrow and see if i need to just start from scratch

**Comment by revere521** [comment]
I have the Snort Dashboard essentially ready, and everything else working - but for all the maps i'm seeign an error that source.geo.location and destination.geo.location are missing fields. 

Is that a setup issue on my part, or a template change for the geoip?

**Comment by a3ilson** [comment]
The template was changed/updated.  You'll need to remove the previous template and download the new one.  Additionally, the index pattern was changed from ```pf``` to ```pfelk```

Navigate to Management>>Stack Management>>Data>>Index Management and remove the old Index Templates under Index Templates. 

![Capture](https://user-images.githubusercontent.com/16884679/91464438-956ef900-e85a-11ea-8382-de12a51432ca.PNG)

**Comment by revere521** [comment]
thanks, i didn't think of deleting the old geoip template; that's gone now. 

I did delete all my old pf-* indices, create the new pfelk-* index, and update all the config files (even just the chnages a few minutes ago)... and the map is the only thing not working. 

source.geo.location and destination.geo.location are still missing, i have all the other geo fields including: 
source.geo.location.lat
source.geo.location.lon
destination.geo.location.lat
destination.geo.location.lon

its being wierd

**Comment by revere521** [comment]
regardless of my issue, i setup the Snort Dashboard and will upload it shortly

**Comment by a3ilson** [comment]
Snort Dashboard configured w/v5.5
