### ISSUE TITLE
event.id no longer exists.

### ISSUE THREAD

**Issue by ShagoY** [pfelk/pfelk#161]
**Describe the bug**
With the last update 5.5.0, [event][id] has been changed to [priority][id] (See 03-filter.conf).

But the 45-cleanup.conf file has not been changed accordingly.

By the way, what is the reason for this change? I don't find it "understandable".

**Comment by a3ilson** [comment]
Thanks!  I updated the 45-cleanup.conf file and apologize for the inconvenience.

The field was renamed to align with RFC 5424 - syslog-ng supports both RFC 3164 and 5424.  

Reference:
https://tools.ietf.org/html/rfc5424
Paragraph 6.2.1 (i.e. prival or priority)

**Comment by ShagoY** [comment]
Ok I'm fine with it ^^ Thanks.

**Comment by ShagoY** [comment]
ah! I've also just seen that you already remove the "filter_message" in 03-filter.conf.
It's probably redundant with 45-cleanup.conf, isn't it?

**Comment by a3ilson** [comment]
Sweet! Nice catch. I overlooked this as I was tweaking a few things.

Remove the one from 03-filter.conf otherwise the priority.id is stripped and 45-cleanup.conf is unable to drop those messages. I just updated within the distro - Thanks!
