### ISSUE TITLE
Syslog-ng still needed?

### ISSUE THREAD

**Issue by wanderernxa** [pfelk/pfelk#166]
Hi,
Great work btw.
Is syslog-ng still required to send the suricata eve logs to ELK or by turning on syslog remote logging replace it? Or do I need both?

thankss

**Comment by a3ilson** [comment]
@wanderernxa - Is this is regards to pfSense or OPNsense?

pfSense - Take a look at https://github.com/3ilson/pfelk/wiki/How-To:-Suricata-on-pfSense

OPNsense - 
![opnsense](https://user-images.githubusercontent.com/16884679/91640443-94b99c80-e9eb-11ea-8969-72fb6ee9e560.PNG)

Not sure if that answered your question? But if your looking to send suricata logs directly to pfELK, it'll likely need a tweak or two.

**Comment by wanderernxa** [comment]
thank you...everything is working like a charm! FANTASTIC work btw!

**Comment by a3ilson** [comment]
I take it the above solved your question?

**Comment by wanderernxa** [comment]
yes, thanks
