### ISSUE TITLE
Nit in /etc/pfELK/error-data.sh

### ISSUE THREAD

**Issue by MandyBaxter** [pfelk/pfelk#168]
**Describe the bug**

cat /etc/logstash/conf.d/patterns*.grok >> /etc/pfELK/logs/error.pfelk.log
should be
cat /etc/logstash/conf.d/patterns/*.grok >> /etc/pfELK/logs/error.pfelk.log

**Comment by a3ilson** [comment]
Thanks! Script was updated.
