### ISSUE TITLE
web doc nits

### ISSUE THREAD

**Issue by MandyBaxter** [pfelk/pfelk#169]
**Describe the bug**

Recommend you touch up the documentation --
https://github.com/3ilson/pfelk/blob/master/install/configuration.md

At 1b:
The sed regex is out of step with your new code. It produces the guts of a hash, whereas the user needs CSV for /etc/logstash/conf.d/databases/rule-names.csv.

At 1c:
sudo nano /etc/logstash/conf.d/35-rules-desc.conf
Paste the the results from pfSense into the first blank line after "0"=> "null"
Adjust to point the user at rule-names.csv.

Also, maybe edit /etc/logstash/conf.d/05-firewall.conf
to match the network layout of the firewall interfaces.

At 6b:
HTTP 404, all five URLs. (Seems you've moved on github.)

**Comment by a3ilson** [comment]
Thanks for the feedback and apologize for the inconvenience.  2/3 issues were fixed and one I'll defer to someone running pfSense.

- [x] 1b - Pending validation 
- [x] 1c - Fixed
- [x] 6b - Fixed

**Comment by revere521** [comment]
this command in pfsense:
`pfctl -vv -sr | grep USER_RULE | sed 's/@\([^(]*\).*"USER_RULE: *\([^"]*\).*/\1,\2/' | sort -t ' ' -k 1,1 -u`

should generate a list of user rules that keys on the "rule number" rather than the "tracking ID"

giving an output that's ready to be pasted into the csv like this: 

```
55,NAT Redirect DNS
56,NAT Redirect DNS
57,NAT Redirect DNS TLS
58,NAT Redirect DNS TLS
60,BypassVPN
```

**Comment by a3ilson** [comment]
@MandyBaxter - Thanks again and looks like all the identified issues were resolved.
