### ISSUE TITLE
Elastic Search Timeout on Startup

### ISSUE THREAD

**Issue by FullThrottleIT** [pfelk/pfelk#170]
**Describe the bug**
ElasticSearch timeout during load

**To Reproduce**
installed from default ubuntu 20.04 and utilized scripted pfELK installer, possible this only happens when the elasticsearch already has a considerable amount of data.

**Firewall System (please complete the following information):**
 - pfSense
 - 2.4.5
I'm thinking firewall doesn't matter at this point as elasticsearch is not even loading on the virtual machine (Note:  Virtual Machine is VirtualBox and I'm running in single node mode.
 
 **Installation method (manual, ansible-playbook, docker, script):**
 script

**Additional context**
The following URL explains the problem and resolution far better than I can.
https://blog.sleeplessbeastie.eu/2020/02/29/how-to-prevent-systemd-service-start-operation-from-timing-out/

**Comment by a3ilson** [comment]
@FullThrottleIT - How much ram do you have allocated?  I'm not sure this is a pfELK issue.

**Comment by FullThrottleIT** [comment]
8GB is allocated to the ELK VM in Virtual Box.  I previously had an issue with memory allocation on the Suricata interfaces in PFsense but this has already been resolved by multiply the default number by 10.  Then the suricata interfaces on pfsense started without issue.  Issues to be aware of not so much a pfELK problem directly but will affect anyone following your guide.  

P.S. Its been a bit of a challenge getting this all going so far, had to follow your directions on another page concerning Syslog-ng and trucated log entries.  So far I'm still getting grokparsefailure errors as well but I suspect that relates to IPV6.  Still working through the issues but your solution has made it possible for me to get this far.  Will update when I get closer to resolving some of the other issues.

**Comment by ShagoY** [comment]
It's weird because I encountered the same problem with a 1go VM... But by increasing it to 4go (without ballooning or other) it worked :-s

**Comment by a3ilson** [comment]
@FullThrottleIT - Here's the guide for Suricata on pfSense: https://github.com/3ilson/pfelk/wiki/How-To:-Suricata-on-pfSense

**Comment by revere521** [comment]
I also set the service timeout in systemd to a longer value becasue I occasionally had issues at boot with elasticsearch timing out:

run `sudo systemctl edit --full elasticsearch.service`

under the Service heading set the timeout value to 120 seconds or something slightly higher than default

```
[Service]
TimeoutStartSec=120
```

I think you can also set a value "NoLimit" if you need.   It makes the boot take a little longer, but the percentage of issues I've had on a lower powered homelab 'server' decreased significantly. 

Edit: I see thats what your link is essentially directing you to do, I can only say it worked for me.  Completely disabling Swap is important too for the performance boost.   My 'server' is an old elitedesk 8300 mini desktop, with an i5 and 8gb of ram.  utilization is usually 12 to 15% CPU all the time and 50% or more ram utilization.

**Comment by FullThrottleIT** [comment]
So at this point maybe we should have a feature request have the installer script and manual install instructions address this potential issue as I am not the only one that has experienced this issue and will save new pfelk users considerable time.

**Comment by a3ilson** [comment]
@FullThrottleIT - I'll add it to the project list but concerned that the hardware variables will present a separate challenge.  I currently have my Elasticsearch running in a cluster (i.e. docker) separate from logstash and kibana. I'd be happy to share the setup if desired.

**Comment by a3ilson** [comment]
Issue closed as it was identified and being worked via issue #128 

Elastic Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/stopping-elasticsearch.html

**Comment by a3ilson** [comment]
@FullThrottleIT - ILM and Datastreams will likely minimize this issue.  I'm looking to leverage Datastreams in the future and wanted to follow-up as this issue is still being pursued.
