### ISSUE TITLE
IP´s in 02-types.conf are not changed by installer

### ISSUE THREAD

**Issue by BeNeDeLuX** [pfelk/pfelk#171]
**Describe the bug**
The sed command in the installer script only change the IP 192.168.9.1 --> https://github.com/3ilson/pfelk/blob/master/pfelk-install-5.5.0.sh#L1218

So the IP for the HAProxy and BEATS host in 02-types.conf are not changed during the installation

**Additional context**
Change the IP's for HAProxy and Beats also to 192.168.9.1 or add additional sed command for the other two IP's

**Comment by a3ilson** [comment]
Updated/Fixed - thanks!
