### ISSUE TITLE
Breakdown by VLAN

### ISSUE THREAD

**Issue by Hams3c** [pfelk/pfelk#174]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
I would like to see a dashboard with breakdown by VLAN.

**Describe alternatives you've considered**
None at this time.

**Additional context**
N/A

**Comment by revere521** [comment]
The dashboards included shouldn't necessarily be considered an end-all solution; but rather a starting point for your customization. 

One way you could solve for something similar, is if each of your VLANs has an "interface" you could filter the Firewall - Dashboard per each one and save it as a unique new dash: 

1. Open the Firewall-Dashboard and select Edit at the top
2. Click +Add Filter
3. In the Edit Filter Box, choose the field "interface.alias.keyword", the operator "is" and then in the Drop-down you should get you interface aliases configured in 05-firewall.conf - choose the one you want to filter by, then click Save. 
4. All the visualizations will now filter to just show the data for the alias you selected
5. Click Save at the top, toggle the "Save as a new dashboard" switch 'on' and add the name of the Alias to the Title (so Firewall-Dashboard is now Firewall-Dashboard-VLAN0 or whatever you want)

you can repeat the process for each VLAN interface; and you will then have the original Firewall-Dashboard as an overview, and one for each VLAN filtered.

**Comment by a3ilson** [comment]
@Hams3c - I agree with the enhancement but see it more practical as @revere521 depicts.  Unless your envisioning a different end state.  If so, please feel free to build out and post an alternative Dashboard incorporating the VLAN toggle/pivot or expand upon your initial proposal.

**Comment by a3ilson** [comment]
No response from author
