### ISSUE TITLE
Bypassing 'Exponential Backoff'

### ISSUE THREAD

**Issue by Hams3c** [pfelk/pfelk#176]
**Is your feature request related to a problem? Please describe.**
pfELK can send some large requests to ES.  This results in the following error message in logstash
```
[2020-09-08T22:58:26,193][ERROR][logstash.outputs.elasticsearch][main][pfelk] Encountered a retryable error. Will Retry with exponential backoff  {:code=>403, :url=>"https://localhost:9200/_bulk"}
```

**Describe the solution you'd like**
It may be beneficial as part of the pfELK setup to add a prompt/adjust the following settings in `/etc/elasticsearch/elasticsearch.yml`

```
http.compression_level: 9
http.max_content_length: "500mb"
http.max_header_size: "16kb"
```

**Describe alternatives you've considered**
I'm still learning the nuances to 7.9.0 and how ES works under the hood.  I will update this section as necessary.

**Additional context**
For reference
  * https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html
  * https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/823
  * https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/937

**Comment by revere521** [comment]
I added these flags to my elasticsearch.yml for testing, i will advise if i see any issues

**Comment by revere521** [comment]
I reverted the changes, the immediately pegged cpu usage on my machine... i also do not see these errors in my logstash-plain.log

Is this a size issue, is your environment very large?   or is this a server spec issue where you are compensating for a low power server?

**Comment by a3ilson** [comment]
@Hams3c - can you provide some examples?  pfELK utilizes pfSense and OPNSense both of which conform to RFC5424 and RFC 3164; I can't imagine a log reaching 500mb and not entirely sure the proposed settings add any value/enhancement for a pfELK environment

**Comment by Hams3c** [comment]
@revere521 it's an ubuntu vm with 200gb hd space, 6 vCPUs, and 20gb of ram.  I doublechecked `htop` and consumption is fairly low.

![image](https://user-images.githubusercontent.com/1238762/93685921-de445700-fa80-11ea-86a6-de27b751e757.png)

@a3ilson I'm still new to ELK and Logstash, so I'll post what I can see from syslog.  I also have the ELK SIEM "application" and a few ElasticSearchAgents reporting to ELK (not not through Logstash).

```
Sep 19 14:04:22 ubuntu logstash[968]: [2020-09-19T14:04:22,818][ERROR][logstash.outputs.elasticsearch][main][pfelk] Encountered a retryable error. Will Retry with exponential backoff  {:code=>403, :url=>"https://192.168.20.20:9200/_bulk"}

Sep 19 14:04:27 ubuntu kibana[1054]: {"type":"response","@timestamp":"2020-09-19T18:03:26Z","tags":[],"pid":1054,"method":"post","statusCode":200,"req":{"url":"/api/ingest_manager/fleet/agents/ab2246bf-3b36-42df-8d3d-a638ecc79173/checkin","method":"post","headers":{"host":"192.168.20.20:5601","user-agent":"Elastic Agent v7.9.0","content-length":"1074","accept":"application/json","content-type":"application/json","kbn-xsrf":"1","accept-encoding":"gzip"},"remoteAddress":"192.168.20.58","userAgent":"192.168.20.58"},"res":{"statusCode":200,"responseTime":60713,"contentLength":9},"message":"POST /api/ingest_manager/fleet/agents/ab2246bf-3b36-42df-8d3d-a638ecc79173/checkin 200 60713ms - 9.0B"}

Sep 19 14:04:46 ubuntu kibana[1054]: {"type":"response","@timestamp":"2020-09-19T18:03:45Z","tags":[],"pid":1054,"method":"post","statusCode":200,"req":{"url":"/api/ingest_manager/fleet/agents/b5394091-1e10-48e9-9a9d-123e6eec3b29/checkin","method":"post","headers":{"host":"192.168.20.20:5601","user-agent":"Elastic Agent v7.9.0","content-length":"547","accept":"application/json","content-type":"application/json","kbn-xsrf":"1","accept-encoding":"gzip"},"remoteAddress":"192.168.20.27","userAgent":"192.168.20.27"},"res":{"statusCode":200,"responseTime":60916,"contentLength":9},"message":"POST /api/ingest_manager/fleet/agents/b5394091-1e10-48e9-9a9d-123e6eec3b29/checkin 200 60916ms - 9.0B"}

Sep 19 14:04:57 ubuntu logstash[968]: [2020-09-19T14:04:57,856][ERROR][logstash.outputs.elasticsearch][main][pfelk] Encountered a retryable error. Will Retry with exponential backoff  {:code=>403, :url=>"https://192.168.20.20:9200/_bulk"}
Sep 19 14:04:57 ubuntu logstash[968]: [2020-09-19T14:04:57,856][ERROR][logstash.outputs.elasticsearch][main][pfelk] Encountered a retryable error. Will Retry with exponential backoff  {:code=>403, :url=>"https://192.168.20.20:9200/_bulk"}
Sep 19 14:04:57 ubuntu logstash[968]: [2020-09-19T14:04:57,857][ERROR][logstash.outputs.elasticsearch][main][pfelk] Encountered a retryable error. Will Retry with exponential backoff  {:code=>403, :url=>"https://192.168.20.20:9200/_bulk"}
Sep 19 14:04:57 ubuntu logstash[968]: [2020-09-19T14:04:57,856][ERROR][logstash.outputs.elasticsearch][main][pfelk] Encountered a retryable error. Will Retry with exponential backoff  {:code=>403, :url=>"https://192.168.20.20:9200/_bulk"}
Sep 19 14:04:57 ubuntu logstash[968]: [2020-09-19T14:04:57,858][ERROR][logstash.outputs.elasticsearch][main][pfelk] Encountered a retryable error. Will Retry with exponential backoff  {:code=>403, :url=>"https://192.168.20.20:9200/_bulk"}

Sep 19 14:05:26 ubuntu logstash[968]: [2020-09-19T14:05:26,861][ERROR][logstash.outputs.elasticsearch][main][pfelk] Encountered a retryable error. Will Retry with exponential backoff  {:code=>403, :url=>"https://192.168.20.20:9200/_bulk"}

Sep 19 14:05:29 ubuntu kibana[1054]: {"type":"response","@timestamp":"2020-09-19T18:04:28Z","tags":[],"pid":1054,"method":"post","statusCode":200,"req":{"url":"/api/ingest_manager/fleet/agents/ab2246bf-3b36-42df-8d3d-a638ecc79173/checkin","method":"post","headers":{"host":"192.168.20.20:5601","user-agent":"Elastic Agent v7.9.0","content-length":"1074","accept":"application/json","content-type":"application/json","kbn-xsrf":"1","accept-encoding":"gzip"},"remoteAddress":"192.168.20.58","userAgent":"192.168.20.58"},"res":{"statusCode":200,"responseTime":60920,"contentLength":9},"message":"POST /api/ingest_manager/fleet/agents/ab2246bf-3b36-42df-8d3d-a638ecc79173/checkin 200 60920ms - 9.0B"}

```

**Comment by a3ilson** [comment]
You could increase the JVM size for both logstash and elasticsearch which may improve overall performance.  

My current setup:
- Elasticsearch running in a cluster (i.e. three dockers).
- Logstash and Kibana are running on the a separate VM with the Java size increased on logstash to 4GB

What type of environment are you running this in or intended for?

**Comment by Hams3c** [comment]
> What type of environment are you running this in or intended for?

The VM is intended to ingest SIEM information from various sources, including pfSense FW/Suricata logs.

**Comment by Hams3c** [comment]
I've adjusted the settings inside jvm.options to
```
-Xms5g
-Xmx5g
```
but still receive the 'exponential backoff' error.

**Comment by a3ilson** [comment]
Did you set this within logstash and or elasticsearch?

**Comment by revere521** [comment]
the code 403 may indicate it could be a permissions issue rather than performance?  I was just looking around for your error and saw this: https://discuss.elastic.co/t/issues-sending-monitoring-data-from-logstash-to-elasticsearch/215103/5

It references the code 403 as a standard forbidden error.

**Comment by Hams3c** [comment]
> Did you set this within logstash and or elasticsearch?

This was within `/etc/elasticsearch/jvm.options`

> It references the code 403 as a standard forbidden error.

Good catch!  Thanks a bunch for the assist! 👍 I must have overlooked this entry after pouring over so many search results.
