### ISSUE TITLE
v5.5 Snort dashboard seems to be broken

### ISSUE THREAD

**Issue by narkisr** [pfelk/pfelk#179]
**Describe the bug**
v5.5 Snort dashboard seems to be broken, when I try to import the dasboard I get:

```
# json response from Kibana
{"errors":[{"id":"d6f03350-e85d-11ea-8f20-c10618fa077e","type":"dashboard","title":"Snort - Dashboard","error":{"type":"missing_references","references":[{"type":"search","id":"b61b3e30-e85e-11ea-8f20-c10618fa077e"}],"blocking":[]}}]}
```

Iv tried to remove the missing search and was able to import but notice that all the visualization were missing.

Looking at the actual [file](https://github.com/3ilson/pfelk/blob/master/Dashboard/v5.5/v5.5%20Snort%20Dashboard%20(082820).ndjson) iv noticed:

``` 
{"exportedCount":1,"missingRefCount":0,"missingReferences":[]}
```

I'm only guessing here but I think that the original export was not successful (I would expect to see more items in exported count) comparing this to the older [version](https://github.com/3ilson/pfelk/blob/master/Dashboard/v5.0/v5.0%20(042020)%20Snort%20Dashboard.ndjson):

```
{"exportedCount":11,"missingRefCount":0,"missingReferences":[]}
```
**To Reproduce**
1. Download the snort v5.5 [dashboad](https://raw.githubusercontent.com/3ilson/pfelk/master/Dashboard/v5.5/v5.5%20Snort%20Dashboard%20(082820).ndjson)
2. Try to import it
3. import fails with an endless loop of errors (see the above error).

**Comment by revere521** [comment]
try this one (remove the ".txt" from the filename first. 
[removed]

When you import the dashboard, it should prompt you to replace the UUID of the index with your Index.

**Comment by pwallace10** [comment]
Hi, yes, I am seeing this too, was just about to post and ask "help", glad I am not alone on this. I tried the file linked above but mine still sits there bouncing the Elastic icon up and down..Its recognising the file because it asks to match the indexes but thats about all..

**Comment by revere521** [comment]
what version of the ELK stack?  I am exporting that from a working 7.9.1 install.

**Comment by revere521** [comment]
try this one, there was an issue with the filter on the basic search panel at the bottom that I didn't see

[removed again and more coffee consumed]

**Comment by narkisr** [comment]
Hi @revere521 I'm using the 7.9.1 install (firewall dashboard works just fine) as for the new file I'm getting a similar error:

```
{"successCount":0,"success":false,"errors":[{"id":"d6f03350-e85d-11ea-8f20-c10618fa077e","type":"dashboard","title":"Snort - Dashboard","error":{"type":"missing_references","references":[{"type":"search","id":"b61b3e30-e85e-11ea-8f20-c10618fa077e"}],"blocking":[]}}]}
```

During import it asked me to use my index (which I did) 

Thanks

**Comment by pwallace10** [comment]
I just did an install from scratch using the script install, it still fails on the import

**Comment by revere521** [comment]
did you try the new dashboard i linked just above your post (the second one i uploaded to this thread that is) - I just exported it with a fix. 

You may want to try refreshing your index, then checking to make sure the "basic-snort" search object loads ok (that panel had an issue)

**Comment by pwallace10** [comment]
I did try the last one you uploaded. tell me if I am doing something wrong, I go to Kibana Index patters, click on the pfelk-* one and then click on refresh field list on the top right?

Once thats done I go to saved objects and import, choose my pfelk-* index pattern and confirm all changes?

then it starts boucing the icon and it just sits there..

**Comment by revere521** [comment]
that sounds like the correct process, I'm really not sure whats happening.  I might need @a3ilson to chime in and see if there is something else wrong as well.

**Comment by pwallace10** [comment]
Thankyou.. I am trying to solve a different issue, can I just post that as a new issue, what is the process (correct one)

**Comment by revere521** [comment]
No, it was my fault - i just realized i wasn't checking enough boxes when I exported the dashboard...its Monday

[v5.5 Snort Dashboard (091420).ndjson.txt](https://github.com/3ilson/pfelk/files/5219727/v5.5.Snort.Dashboard.091420.ndjson.txt)

use that one, it actually has ALL the visualizations included, sorry about that

**Comment by pwallace10** [comment]
Yes!! working, thank you...

**Comment by revere521** [comment]
i will drink coffee then operate my computer in the future, and upload that last one to the repo

**Comment by pwallace10** [comment]
Hi, something not as it should be, just want to make sure its not my installation, I have two pfELKs running, one at home and one at work, i uploaded the Snort Dashboard to both but on both I see the map but the next 5 tiles all have an error saying   ....
[lens_merge_tables] > [esaggs] > Could not locate that index-pattern (id: 4d365ee0-e809-11ea-8f20-c10618fa077e), [click here to re-create it](management/kibana/indexPatterns)

This is on two installs on two different firewalls and ELK's.

what could be the problem?

Peter

**Comment by a3ilson** [comment]
@pwallace10 - did you try with the updated 5.5.1 Snort Dashboard?

A quick remedy would be to edit the ndjson file and replace all instances of ```4d365ee0-e809-11ea-8f20-c10618fa077e``` with ```pfELK``` as specified in [step 6a](https://github.com/3ilson/pfelk/blob/master/install/configuration.md) 

@revere521 - might need to rebuild the snort dashboard and make sure the index pattern is set for ```pfELK``` to prevent the randomized index patterns.

**Comment by narkisr** [comment]
Hi @a3ilson and @revere521 I was able to fix the issue by changing the Id to pfelk and created a pull request to fix it https://github.com/3ilson/pfelk/pull/180

**Comment by a3ilson** [comment]
@narkisr - Thanks!  @pwallace10 if this works, please confirm and close.

**Comment by revere521** [comment]
perfect, thanks!

**Comment by pwallace10** [comment]
Hi, I am a bit lost now, I tried the latest dashboard file 5.5.1 but then I go back to the issue where the dashboard does not import into KIibana. If I go back to the file from last night it imports but I have this error. I did notice that the json file last night was 48k, the new one today is 193k not sure it means anything..

**Comment by pwallace10** [comment]
OK... here is what I did.... I edited the downloaded dashboard 5.5.1 file in Textedit, it seemed to be a mix of txt and html, so I copied out the dashboard section into a new txt document and then saved, renamed and imported that. All working.. If you tell me where I can upload the changed file..

**Comment by pwallace10** [comment]
on this.... is there a way to add a top IP list for snort? the port pie charts are great but it would be nice if I could see a pie chart or a list of the top IP's

**Comment by revere521** [comment]
you can modify or create additional visualizations, the dashboard should be a place to start your customization. 

here is an export of just 3 new visualizations so you can reverse engineer them for your needs (or add them to the dash) - you will still have to replace my UUID with yours again (because my index is pfelk-* not pfELK-* i still need to fix the existing dashboard now that i see that issue)

Edit, i replaced my UUID with "pfELK"

[Snort IP Visulizations.ndjson.txt](https://github.com/3ilson/pfelk/files/5225538/Snort.IP.Visulizations.ndjson.txt)

**Comment by pwallace10** [comment]
Thankyou so much, I am still very new at this ELK configuration, so its all a bit of trial and error, pfElk has been a fantastic find though. Thank you for your contributions..

**Comment by revere521** [comment]
Since this appears to be straightened out, and I also understand the need to change the UUID in the future, I will close this
