### ISSUE TITLE
2.4.4-p3  unable to create index pattern

### ISSUE THREAD

**Issue by TurBoss** [pfelk/pfelk#18]
Hello

by following the github steps but on centos7 elk 7
I'm unable to create an index pattern
index exist but its only 283b

![Captura de pantalla de 2019-05-28 06-01-57](https://user-images.githubusercontent.com/184088/58450209-35951a00-810e-11e9-9404-88e39f881fd9.png)

**Comment by a3ilson** [comment]
Jose,

Check the status of logstash by typing "systemctl status logstash.service"

If it is green and active with no errors check the log file

nano, vi, or cat the following:
/var/log/logstash*
I'm away and not sure the exact file name but it should provide an output
of logstash.

Feel free to attach/post your outputs for both and I'll take a look.

-Andrew

**Comment by TurBoss** [comment]
Hello,
I'm pasting the logs

systemctl status logstash.service"
```
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,127][INFO ][logstash.filters.geoip   ] Using geoip database {:path=>"/etc/logstash/GeoLite2-City.mmdb"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,210][INFO ][logstash.filters.geoip   ] Using geoip database {:path=>"/etc/logstash/GeoLite2-City.mmdb"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,243][INFO ][logstash.javapipeline    ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, :thread=>"#<Thread:0x1ba10cab run>"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,590][INFO ][logstash.javapipeline    ] Pipeline started {"pipeline.id"=>"main"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,615][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:5140", :ssl_enable=>"false"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,735][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"0.0.0.0:5140"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,788][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,835][INFO ][logstash.inputs.udp      ] UDP listener started {:address=>"0.0.0.0:5140", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
may 26 15:46:40 elk.lan logstash[5043]: [2019-05-26T15:46:40,188][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
```
/var/log/logstasg/logs

```
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,127][INFO ][logstash.filters.geoip   ] Using geoip database {:path=>"/etc/logstash/GeoLite2-City.mmdb"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,210][INFO ][logstash.filters.geoip   ] Using geoip database {:path=>"/etc/logstash/GeoLite2-City.mmdb"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,243][INFO ][logstash.javapipeline    ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, :thread=>"#<Thread:0x1ba10cab run>"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,590][INFO ][logstash.javapipeline    ] Pipeline started {"pipeline.id"=>"main"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,615][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:5140", :ssl_enable=>"false"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,735][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"0.0.0.0:5140"}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,788][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
may 26 15:46:39 elk.lan logstash[5043]: [2019-05-26T15:46:39,835][INFO ][logstash.inputs.udp      ] UDP listener started {:address=>"0.0.0.0:5140", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
may 26 15:46:40 elk.lan logstash[5043]: [2019-05-26T15:46:40,188][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
```
they give the same result

pfsense got updated recently to 2.4.4p3 and i was worried about some breakage on the grokk

I don't know :D


thanks

**Comment by yoeldiaz** [comment]
I have a similar issue with pfsense 2.4.3-RELEASE-p1, the index pattern recognize log data of pfsense but not show all the fields. I review the configuration of data source and all look be fine.

![Captura de pantalla -2019-06-06 08-46-39](https://user-images.githubusercontent.com/51446507/59035131-99b88c00-883a-11e9-9bd7-32f8125f8b59.png)

**Comment by a3ilson** [comment]
yoeldiaz - is this a new or upgraded install? I am running the latest version of OPNsense + ELK but would be happy to help troubleshoot.  If you have it (ELK) running and receiving data, check the Discover within Kibana.  If the grok pattern is broken as a result of pfsense, it should still display the data but fail to parse.  I've tweaked the grok pattern before in the past by utilizing a grok debugger but typically saw issues within the logstash logs.  Please check your timing (correct timezone), provide a screen shot of the discover if your receiving logs and confirm pfsense is passing the logs.

**Comment by yoeldiaz** [comment]
Thanks for your quick response. Finally I think I have found a solution. I was reviewing problem # 4 and in your explanation I could understand a lot about the code. In the Discover section, when I searched, the records did not have the pfsense flag, so I added that tag in 10-syslog.conf to get into the condition and then all fields were added. I can already see the logs ok ;-)

**Comment by TurBoss** [comment]
Hello @a3ilson

this is how my index looks 
its always 283b

![Captura de pantalla de 2019-06-11 07-05-41](https://user-images.githubusercontent.com/184088/59245260-36eb3a00-8c18-11e9-8ad8-fb74eedc2b7a.png)



also  tcpdump shows  lots
 tcpdump -Xni eth0 port 5140
```
07:15:16.593358 IP 192.168.10.1.syslog > 192.168.10.7.5140: SYSLOG local0.info, length: 139
	0x0000:  4500 00a7 649c 0000 4011 8051 c0a8 0a01  E...d...@..Q....
	0x0010:  c0a8 0a07 0202 1414 0093 b1d5 3c31 3334  ............<134
	0x0020:  3e4a 756e 2031 3120 3037 3a31 353a 3136  >Jun.11.07:15:16
	0x0030:  2066 696c 7465 726c 6f67 3a20 3838 2c2c  .filterlog:.88,,
	0x0040:  2c31 3030 3030 3035 3931 312c 6370 7377  ,1000005911,cpsw
	0x0050:  302c 6d61 7463 682c 7061 7373 2c6f 7574  0,match,pass,out
	0x0060:  2c34 2c30 7830 2c2c 3634 2c35 3836 3034  ,4,0x0,,64,58604
	0x0070:  2c30 2c6e 6f6e 652c 3137 2c75 6470 2c36  ,0,none,17,udp,6
	0x0080:  372c 3139 322e 3136 382e 312e 382c 3139  7,192.168.1.8,x
	0x0090:  xxxxx xxxxxxxxx xxxxx xxxxx xxxxx xxx 3732  xxx.xxx.xx.30,3472
	0x00a0:  xxxxx 3533 2c34 37                        2,53,47

**Comment by TurBoss** [comment]
Hurray I just fixed my issue

was the centos firewall

its enabled by default

thanks
