### ISSUE TITLE
Unbound 5.5.1 Dashboard is broken

### ISSUE THREAD

**Issue by BeNeDeLuX** [pfelk/pfelk#181]
**Describe the bug**
The Unbound 5.5.1 Dashboard shows an Error in 4 of the 5 visualization inside the dashboard:

`[lens_merge_tables] > [esaggs] > Could not locate that index-pattern (id: pfELK), [click here to re-create it](management/kibana/indexPatterns)
`

The visualization "Unbound - Discover" (which is just a table) is working fine.

**To Reproduce**
1. Import v5.5.1 Unbound Dashboard (082820).ndjson
2. Open dashboard
3. See error

**Screenshots**
![overview](https://user-images.githubusercontent.com/1895086/93252595-fe7cc900-f795-11ea-85ef-2997fba108d7.PNG)
![dashboard_unbound](https://user-images.githubusercontent.com/1895086/93251419-71854000-f794-11ea-8e8b-390a85a97d55.PNG)

![import_unbound_dashboard](https://user-images.githubusercontent.com/1895086/93251421-71854000-f794-11ea-8a74-a17678360b72.PNG)
![index_pattern](https://user-images.githubusercontent.com/1895086/93251416-70541300-f794-11ea-9b88-c1d37009acee.PNG)

**Firewall System (please complete the following information):**
 - OPNsense 20.7.2
 
**Operating System (please complete the following information):**
Linux 5.4.44-2-pve x86_64
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
 
 **Installation method (manual, ansible-playbook, docker, script):**
Fresh installation with the install script

**Elasticsearch, Logstash, Kibana (please complete the following information):**
```
~# dpkg -l elasticsearch
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=====================================================
ii  elasticsearch  7.9.0        amd64        Distributed RESTful search engine built for the cloud

```
```
:~# dpkg -l kibana
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=============================================
ii  kibana         7.9.0        amd64        Explore and visualize your Elasticsearch data

```

```
:~# dpkg -l logstash
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  logstash       1:7.9.0-1    all          An extensible logging pipeline

```
Fresh installation with the install script without any changes.
Thanks for any help!

**Comment by a3ilson** [comment]
@BeNeDeLuX - Just restored a fresh install and was unable to duplicate the issue.  However, based on the detailed response, please check the following and reply back if the issue is still present or close if resolved:

(1) Please confirm [step 5h](https://github.com/3ilson/pfelk/blob/master/install/configuration.md) was accomplished
(2) Please confirm pfELK has received logs specific to unbound (based on the screenshot, this looks correct)
(3) Please navigate to Stack Management>>Kibana>>Index PAtterns; click on ```pfelk-*``` and then click on the refresh field list button (located in the upper right corner).

Check the dashboard and confirm if this resolved and/or the issue is still present.

**Comment by BeNeDeLuX** [comment]
Thanks for your quick response!

(1) Please confirm step 5h was accomplished ->  **Confirm!**
(2) Please confirm pfELK has received logs specific to unbound (based on the screenshot, this looks correct) -> **Confirm!**
Here is a screenshot from the last event:
![unbound_fields](https://user-images.githubusercontent.com/1895086/93348307-53701c00-f836-11ea-8ee8-d27418417666.png)
(3) Please navigate to Stack Management>>Kibana>>Index PAtterns; click on pfelk-* and then click on the refresh field list button (located in the upper right corner). -> **Confirm!**
![unbound_index_pattern](https://user-images.githubusercontent.com/1895086/93348547-a5b13d00-f836-11ea-9fb7-a7ea0a54fab4.png)

I deleted all saved object from unbound and imported the Dashboard again -> same behaviour.
Where should i find the index pattern "pfELK" ? I only have the index pattern "pfelk-*" of what I can see.

Thanks.

**Comment by a3ilson** [comment]
Please confirm [step 6a](https://github.com/3ilson/pfelk/blob/master/install/configuration.md) was accomplished.  If not, you can delete the index pattern and recreate the index pattern.  Additionally, you can view a quick video (0.29second mark) [here](https://www.youtube.com/watch?v=a1no6AlXP-k)

![pfelk-initial-pattern](https://user-images.githubusercontent.com/16884679/93398005-be2a5300-f848-11ea-9099-00dc7435c984.PNG)
![Capture](https://user-images.githubusercontent.com/16884679/93398006-bec2e980-f848-11ea-8f41-3f914e695280.PNG)

**Comment by rrosson** [comment]
The custom index id is case sensitive. I think some guys f the dashboards were made with pfELK and some where made with you pfelk.

**Comment by a3ilson** [comment]
@rrosson - I'll change it in the near future as I believe it to be a point of confusion.

**Comment by revere521** [comment]
I admit that i have contributed to that by not reading the manual, i apologize. 

@a3ilson I will wait for you to revise that, then re-export my dashboard to match if needed

**Comment by BeNeDeLuX** [comment]
Step 6a with "pfELK" in the correct notation fixed the problem for me!
Thanks.
Can I close this issue or should I leave it open as a reminder?

**Comment by a3ilson** [comment]
Please close
