### ISSUE TITLE
How many xxxSense's are possible to monitor with pfelk

### ISSUE THREAD

**Issue by JBBERLIN** [pfelk/pfelk#182]
Hello,

how many xxxSense's are possible to monitor with pfelk ?
I know if more then I need better hardware but how many are the PF ELK Stack can processing ?
Because I not find any information about this.

Is it possible montior 2 or 10 or 10000 ?

Many thanks and best regards
JBBERLIN

**Comment by a3ilson** [comment]
@JBBERLIN - I haven't tested the limit but you may certainly have more than one. 

You'll just need to amend 02-types.conf

**Comment by a3ilson** [comment]
@JBBERLIN - Closing this issue but if you need assistance in setting up pfELK with multiple instances let me know.
