### ISSUE TITLE
Can installation script be supported on kali-rolling please ?

### ISSUE THREAD

**Issue by spicyKo0l** [pfelk/pfelk#183]
Fantastic job! Team. Few days ago I had come across your blog http://pfelksuricata.3ilson.com/ from 2017 and I followed it, it worked very great on Kali Linux as-well which is based on Debian-Testing.  Today I had come across this github and I tried all manual installation as per this https://github.com/3ilson/pfelk/blob/master/install/debian.md  most of the things worked except some minor changes that I did manually.  
For example Typo in 
1. Step number 15 "50-outputs.conff" ('f' at the end extra)
2. Step number 16b cd to patterns but mentioned as 'templates'
3. Step number 9 I have to manually create _/data/pfelk/GeoIP_ directory before I said _'sudo geoipupdate'_
3. I have to create symbolic links manually inside _/usr/share/GeoIP/*mmdb_ towards the actual location of files which are located at _/data/pfelk/GeoIP/_

**Is your feature request related to a problem? Please describe.**
May I kindly request is it possible to adapt the install script for supporting Kali-rolling ?

**Describe the solution you'd like**
Changes in the pfelk-install-5.5.0.sh.  My OS details looks like as follows.
_gcc (Debian 10.2.0-5) 10.2.0
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2020.3
Codename:       kali-rolling_

**Describe alternatives you've considered**
Alternative is manual installation.

**Additional context**

**Comment by a3ilson** [comment]
@manchili - Thanks!  I've corrected the typos/errors in step 1-4 of the Debian manual installation. 

I also made note to add a reference to github from those previous guides (pfelk.3ilson.com and pfelksuricata.3ilson.com)

I'll add Kali to the list...would you be willing to test?  It may be a few weeks before I get to it.

**Comment by spicyKo0l** [comment]
Hi Andrew
Thank you very much for quick reply. Sure I will be able to test on Kali. I have to uninstall first manually or by script ( without uninstalling ELK. Logstash, Kibana and beats) and then run the new script that you will provide me.
![Import-Error_pfelk](https://user-images.githubusercontent.com/27067446/93685534-56764100-fab0-11ea-9d51-86e414d41ee9.png)

I am having ELK 7.9.1  
Just now I am trying to import the Dashboards from v5.5 into Kibana. Any hints please ?
For example when I tried "v5.5.1 Unbound Dashboard (082820).ndjson" I am getting error like _"Failed to import 4 of 6 objects"_
![image](https://user-images.githubusercontent.com/27067446/93685042-ce903700-faaf-11ea-9ac7-af34dc983bd4.png)

**Comment by a3ilson** [comment]
Please take a look at [step 6a](https://github.com/3ilson/pfelk/blob/master/install/configuration.md) and also [this video](https://www.youtube.com/watch?v=a1no6AlXP-k&feature=youtu.be) specifically at the 29 second mark.

**Comment by spicyKo0l** [comment]
Yes exactly! I followed the same video before I encountered the problem.   Now again to double check I deleted the pfelf-* index and recreated it with @timestamp and pfELK(in advanced options) but still I have the same problem while importing.  Not just "unbound..." but also other json files. Not all objects getting imported some are failing.
Thank you for your time.

**Comment by a3ilson** [comment]
How are you importing (i.e. how are you saving the file)? The file extension should be .ndjson

**Comment by a3ilson** [comment]
You may also need to refresh the index pattern.
- Use the 5.5.1 not the 5.5 variants 

![Capture](https://user-images.githubusercontent.com/16884679/93686625-64fb3300-fa85-11ea-8f70-2a6c5e18aba8.PNG)

You can download all dashboard files [here](https://github.com/3ilson/pfelk/files/5250427/dashboards.zip)

**Comment by spicyKo0l** [comment]
I did refresh pattern. I also tried that earlier.
The only difference between video you had 283 fields and my index is number of fields, I got only 221. I do not know why this difference  and it significance.
![image](https://user-images.githubusercontent.com/27067446/93686620-a7d5fe80-fab7-11ea-9012-37d1ec7f5d03.png)

**Comment by a3ilson** [comment]
The field values may change as you receive more data. I just refreshed with
increased to 282.

**Comment by spicyKo0l** [comment]
Yes I did not chance any files names. They are all *.ndjson. 
From the file name sent earlier"v5.5.1 Unbound Dashboard (082820).ndjson"  it is evident that I am using only 5.5.1 and ndjson.

**Comment by a3ilson** [comment]
Do the other dashboards import?  Do you have any unbound logs?

**Comment by a3ilson** [comment]
The dashboards require the referenced fields. Navigate to Kibana>>Discover.  Next, filter to the specified application to check that you have the required fields/logs.

![Capture](https://user-images.githubusercontent.com/16884679/93687100-151e6b00-fa89-11ea-9c2b-6a7391fb0a9d.PNG)

**Comment by a3ilson** [comment]
After you apply the filter you should see something similar to:
![unbound](https://user-images.githubusercontent.com/16884679/93687106-22d3f080-fa89-11ea-98f2-673e526c026c.PNG)

**Comment by a3ilson** [comment]
Change the filter and check suricata.

**Comment by a3ilson** [comment]
By default the firewall dashboard will work via the script install or manual method.  The ubbound, snort, suricata and haproxy, dashboards require additional configuration from your firewall.

**Comment by spicyKo0l** [comment]
Thank you with the filter _"application.keyword"  "is"_ I have only the following in drop down list for value. 
![image](https://user-images.githubusercontent.com/27067446/93687206-2d5bad80-fabc-11ea-9d6d-22061b4c3131.png)
Do I have to add value "unbound" and save it ?

I am new to this. I had however saved by adding value "unbound". After this I did not have any data in last 30 days with this filter.  Is that the reason it is failing to import some of the objects ?
I have Pfsense / suricata.

**Comment by manchili** [comment]
On PFsense I have suricata for each interface.  I have not installed snort but I used the rules in configuring suricata as shown in the picture.
![image](https://user-images.githubusercontent.com/27067446/93687343-647e8e80-fabd-11ea-846b-b24f7b834c8e.png)

**Comment by spicyKo0l** [comment]
On PFsense I have suricata for each interface. I have not installed snort but I used the rules in configuring suricata as shown in the picture.
![image](https://user-images.githubusercontent.com/27067446/93687377-c939e900-fabd-11ea-93eb-96f55b449e90.png)

**Comment by manchili** [comment]
In my earlier reply I had put picture with some sensitive information, I deleted it.  Will it be deleted  or is it still visible to someone?

**Comment by a3ilson** [comment]
Ok, 
- [x] so the firewall dashboard is working for you correct?
- [x] there are no suricata logs as depicted in your filter screenshot above.
  - Dashboard will not work until/unless configured 
- [x] there are no unbound logs as depicted in your filter screenshot above.
  - Dashboard will not work until/unless configured 
- [ ] did you configure suricata as described [here](https://github.com/3ilson/pfelk/wiki/How-To:-Suricata-on-pfSense) <- pfSense

**Comment by spicyKo0l** [comment]
Hi Andrew,
Thank you for your support.  Firewall dashboard also had problems in importing
![image](https://user-images.githubusercontent.com/27067446/93688391-cfcc5e80-fac5-11ea-8f39-1acbaa7cb399.png)

I get suricata logs, ofcourse some percentage of grokparsefailures, sometimes I see the same flowid multiple times and in one no parse failure but in other parse failure, so I did not take it seriously this percentage of grokparsefailure at the moment.
![image](https://user-images.githubusercontent.com/27067446/93688501-921c0580-fac6-11ea-81ba-cd13439694a5.png)

Yes, I do not have any unbound logs. That is right.

I did not configure Suricata at per your link but differently.  I can try the  same procedure in the above link. I feel the only difference is EVE Output type is mentioned by you as "FILE" but I had configured as SYSLOG. 
I had also different configuration for Syslog-ng  that what your described in your link. 
I can try that and update you tomorrow.

**Comment by a3ilson** [comment]
Yep - your suricata failures are likely a result of pfSense truncating those logs.  The previously provided instructions are a workaround by sending the logs as a file via TCP - reference #111. To properly work, please utilize the previously provided instructions. 

When did you download/install pfelk?  I made changes earlier today and you should not have ```pf``` in the tags

I installed a fresh instance of pfelk, imported the firewall dashboard and was unable to replicate your issue.  I noted you also have two additional indexes....ossec and logstash.

**Comment by spicyKo0l** [comment]
I downloaded pfelk on 19.Sep morning CEST.  May be you have done update later during your day.
Now I followed to configure Suricata and Syslog-ng as per the [link](https://github.com/3ilson/pfelk/wiki/How-To:-Suricata-on-pfSense) given but facing a new problem!
![image](https://user-images.githubusercontent.com/27067446/93692136-94468a00-faef-11ea-8901-4779143ccb73.png)

**Comment by spicyKo0l** [comment]
OOPs!  It was my mistake sorry. I selected Object Type as Destination by mistake!

**Comment by spicyKo0l** [comment]
Yes now I did update of configuring suricata and syslog-ng as per your instructions here[https://github.com/3ilson/pfelk/wiki/How-To:-Suricata-on-pfSense](url). Even after doing that importing of *ndjson files are still not importing 100%.  Even the firewall dashboard has still the same problem.
Am I missing any other configuration related to firewall on pfsense ?
![image](https://user-images.githubusercontent.com/27067446/93693098-88f95b80-fafb-11ea-8a9e-711792364734.png)

**Comment by a3ilson** [comment]
@spicyKo0l - Two of those are the maps which require GeoIP.  I'd have to dig deeper for the other ones but suspect your logs are not being enriched as they should.

I'd have to take a look at your configuration and would also be interested in seeing what data is being received and how it is being enriched.

**Comment by spicyKo0l** [comment]
Thank you for your inputs.

Can you please clarify, Is  the success of importing of the FW.ndjson objects depends on the data that is present in logstash at the time of import or  independent of data  that is present in logstash, can the particular FW .ndjson import all the objects ?

I had used same files as you had given in github of conf.d directory.
![image](https://user-images.githubusercontent.com/27067446/93714507-6ef36380-fb63-11ea-9203-e7d46eed7be3.png)

I am trying to build like small SoC at home network with all opensource tools. Yesterday I was having 25% of traffic with grokparsefailures, but after updating as per this [link](https://github.com/3ilson/pfelk/wiki/How-To:-Suricata-on-pfSense), there are no more grokparsefailures. 
![image](https://user-images.githubusercontent.com/27067446/93714579-f93bc780-fb63-11ea-8bd2-7a92d05ebacb.png)

Geo-IP is being resolved.  But the dashboards are not showing the maps like you had shown in your *.png files.
![image](https://user-images.githubusercontent.com/27067446/93714732-efff2a80-fb64-11ea-8323-094ab4621632.png)

**Comment by a3ilson** [comment]
Would you be able to share a screen shot of discover?  I don't need the contents but would like to see all the parsed fields (e.g. filter based on application = filterlog).

It appears the majority of your traffic is from suricata. I am curious as to what firewall traffic you are receiving and if it is parsing out correctly.

The dashboards are dependent upon the fields.  Those fields are enriched via the pfelk files (i.e. *.conf) and if not properly working and refreshed will result in this and/or a similar issue.

- I also noticed a OSSEC-logstash.conf file.  All *.conf files located in /etc/logstash/conf.d/ are utilized and it's possible that file may be causing issues (I am unable to say as I do not know the contents).  Again, pfELK was tested and working but when other variables are at play (modifications/variations), it becomes difficult to troubleshot. I'm happy to help but will need a clean install to better assist (e.g. a working starting point).

- I would also remove 02a-types.conf as that file is duplicated with 02-types.conf and only one should be used not both.  The 02a version does not filter based on the IP address which is useful with passing logs through a router.

**Comment by spicyKo0l** [comment]
Thank you for your valuable help. 
Sure, I can share the Discover.  Do you need full screen of the discover ?

![image](https://user-images.githubusercontent.com/27067446/93715876-50459a80-fb6c-11ea-81d0-40ce2bde7819.png)

![image](https://user-images.githubusercontent.com/27067446/93715956-cb0eb580-fb6c-11ea-9775-f544686252ea.png)

My default index is pfelk-*.  I have OSSEC-logstash.conf sending   at the moment not much traffic from agents. I can also turn it off by moving that file to oldconf directory and turning off the  server aswell. My config for ossec is as per this [link](https://snehpatel.com/index.php/2019/10/12/getting-ossec-server-logs-into-elk-stack/) except the port is 5044.

All the fields are here.
![image](https://user-images.githubusercontent.com/27067446/93715450-98af8900-fb69-11ea-8cbf-5ee084afb31b.png)

![image](https://user-images.githubusercontent.com/27067446/93715468-ac5aef80-fb69-11ea-8815-d4b566097529.png)

![image](https://user-images.githubusercontent.com/27067446/93715475-ba107500-fb69-11ea-81a1-1c1cb3da6454.png)

![image](https://user-images.githubusercontent.com/27067446/93715478-c5fc3700-fb69-11ea-8830-1745af16ba33.png)

![image](https://user-images.githubusercontent.com/27067446/93715491-de6c5180-fb69-11ea-8a6a-f82de27e67d2.png)

![image](https://user-images.githubusercontent.com/27067446/93715497-e75d2300-fb69-11ea-915b-9d94eb707ac4.png)

**Comment by a3ilson** [comment]
You have a number of Suricata logs which should not present if filtering by "application = filterlog"

Additionally, the number of suricata logs with the question mark means you need to refresh your index however, the suricata logs/fields should not impact your firewall dashboard.

**Comment by a3ilson** [comment]
Based on the pfSense firewall instructions those logs should be sent via TCP to port 5141 - please confirm. I would recommend deleting the pfelk-* index pattern and elasticsearch (i.e. purge pfelk-*)

Next, I would recommend that the OSSEC-logstash.conf be modified as follows (added id/index pattern to output):

```
input {
# stdin{}
  udp {
     port => 5001
     type => "ossec"
  }
}

filter {
  if [type] == "ossec" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_host} %{DATA:syslog_program}: Alert Level: %{NONNEGINT:Alert_Level}; Rule: %{NONNEGINT:Rule} - %{DATA:Description}; Location: %{DATA:Location}; (user: %{USER:User};%{SPACE})?(srcip: %{IP:Src_IP};%{SPACE})?(user: %{USER:User};%{SPACE})?(dstip: %{IP:Dst_IP};%{SPACE})?(src_port: %{NONNEGINT:Src_Port};%{SPACE})?(dst_port: %{NONNEGINT:Dst_Port};%{SPACE})?%{GREEDYDATA:Details}" }
      add_field => [ "ossec_server", "%{host}" ]
    }
    mutate {
      remove_field => [ "message","syslog_timestamp", "syslog_program", "syslog_host", "syslog_message", "syslog_pid", "@version", "type", "host" ]
    }
  }
}

output {
  elasticsearch { 
    id => "OSSEC"
    hosts => ["localhost:9200"] 
    index => "OSSEX-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
``` 

- Delete 02a-types.conf 

Once accomplished, restart logstash and rebuild the pfelk index pattern.  You will also need to create/build the OSSEC index pattern. Then navigate to discover and filter type = firewall and provide a screenshot of one of your logged entries.

**Comment by spicyKo0l** [comment]
Yes, as per the configuration on pfSense step 4c, ObjectType "destination" it is configured to send to 5141.  As per logstash config 01-inputs.conf listening on 5141 tcp6.  This is working correctly, connection established. Right ? or Am I missing something.
OK, I will delete index pfelk-*. I did not understand delete elasticsearch ?

Other changes that you recommended I will take it in ossec and deleting 02a* file.

**Comment by spicyKo0l** [comment]
My ossec conf looks like this
```<input {
# stdin{}
  udp {
     port => 5044
     type => "osseclogs"
  }
}

filter {
  if [type] == "osseclogs" {
    grok {
      match => { 'message' => '%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_host} %{DATA:syslog_program}: Alert Level: %{NONNEGINT:Alert_Level}; Rule: %{NONNEGINT:Rule} - %{DATA:Description}; Location: %{DATA:Location}; (user: %{USER:User};%{SPACE})?(srcip: %{IP:Src_IP};%{SPACE})?(user: %{USER:User};%{SPACE})?(dstip: %{IP:Dst_IP};%{SPACE})?(src_port: %{NONNEGINT:Src_Port};%{SPACE})?(dst_port: %{NONNEGINT:Dst_Port};%{SPACE})?%{GREEDYDATA:Details}' }
      add_field => [ "ossec_server", "%{host}" ]
    }
    mutate {
      remove_field => [ "message","syslog_timestamp", "syslog_program", "syslog_host", "syslog_message", "syslog_pid", "@version", "type", "host" ]
    }
  }
}

output {
  elasticsearch { 
        id => "OSSEC"
        hosts => ["localhost:9200"] 
        index => "OSSEC-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
#  stdout { codec => json }
}>
```

**Comment by spicyKo0l** [comment]
Should the ID  => "OSSEC" or "OSSECLOG" ?

**Comment by a3ilson** [comment]
it can be anything and is not the same as ```type```

**Comment by spicyKo0l** [comment]
Now deleting the index
![image](https://user-images.githubusercontent.com/27067446/93716972-0613e780-fb73-11ea-8a73-3916edc31e8d.png)

**Comment by a3ilson** [comment]
Yes - I would stop logstash first (```systemctl stop logstash.service```). Then delete the pfelk-* index pattern and then the pfelk-* indices as show below:

![Capture](https://user-images.githubusercontent.com/16884679/93717024-0f845c00-fb41-11ea-9313-8626022820f2.PNG)

Next, restart logstash and recreate the index pattern.
Note: you will also need to create an index pattern for OSSEC

**Comment by spicyKo0l** [comment]
Stopped logstash.
Index Management is part of ELK ?   I do not have browser on machine where ELK LOGSTASH KIBANA are running.
Therefore I am not able to access ELKIP:9200, inorder to delete Indices. 
Where as kibana I started on IP:port. When I change network.host in elasticsearch.yml to IP address instead of 127.0.0.1, ELK is not starting.  
I am having some troubles too access indicies and delete.
I will come back to you.

**Comment by spicyKo0l** [comment]
Sorry for the delay and troubling you.
Except deleting indicies, I followed every thing you suggested but still importing fw*.ndjson has same affect as it was. Failed to import 9 of 20 Objects.

After deleting and creating the index it looks as follows.
![image](https://user-images.githubusercontent.com/27067446/93720730-31a2cc00-fb8b-11ea-922e-80003079fb9a.png)

Indicies I could not deleted because I could not access IP:9200 port, I am assuming that I can see the picture as you showed me only if I access ELK.  I am using all OSS ELK stack.
My GUI looks like this
![image](https://user-images.githubusercontent.com/27067446/93720804-abd35080-fb8b-11ea-8ed9-9fb41ada295a.png)

**Comment by a3ilson** [comment]
I suspect the fields utilized by pfelk were indexed (i.e. wrong data type) incorrectly as a result of your other inputs (OSSEC), which is the culprit of he importing errors. 

- You need to stop logstash (```systemctl stop logstash.service```)
- Deleted the index pattern (kibana)
  - Navigate to the  ```≡``` equivalent symbol (located in the upper left corner)
  - Click on ```Stack Management```
  - Click on ```Index Patterns``` (under the ```Kibana``` label)
- Deleted the indices (elasticsearch) 
  - Navigate to the  ```≡``` equivalent symbol (located in the upper left corner)
  - Click on ```Stack Management``` 
  - Click on ```Index Management``` (under the ```Data``` label)
  - Delete all pfelk-* indices 
- Deleted the ```Saved Objects``` (kibana) 
  - Navigate to the  ```≡``` equivalent symbol (located in the upper left corner)
  - Click on ```Stack Management```
  -  Click on ```Saved Objects``` (located under the ```Kibana``` label)
  -  Delete all
- Start logstash (```systemctl start logstash.service```) (make sure OSSEC is being indexed into its own pattern as previously mentioned or disable*)

## *NOTE
You are running other variables not associated with pfelk which has been validated on multiple configurations.  It is highly recommended you stop those and focus on pfelk.  Once running, feel free to introduce and dabble with other data sets.

**Comment by spicyKo0l** [comment]
Since I have ELK OSS (open source ) version and not a paid version, I do not have all the menu that you mentioned.
Also described [here](https://discuss.elastic.co/t/index-management-tab-is-not-visible/223787)
I can do everything except the step you mentioned "Delete all pfelk-* indicies.
I will try that tomorrow.

**Comment by spicyKo0l** [comment]
![image](https://user-images.githubusercontent.com/27067446/93721916-59962d80-fb93-11ea-8aa3-435cb6a4bd78.png)

![image](https://user-images.githubusercontent.com/27067446/93721902-48e5b780-fb93-11ea-8ecd-283c1a0824f8.png)

**Comment by spicyKo0l** [comment]
I stopped logstash.
Remove everything as I mentioned above as per your suggestion (except indicies). Created pfelk-* Index pattern, refreshed and then under "Saved Objects"  imported firewall dashboard but unfortunately I had hit the same problem! By they ways I also stopped ossec-server and moved the OSSEC-*.conf file away. 

![image](https://user-images.githubusercontent.com/27067446/93722054-4e8fcd00-fb94-11ea-995c-0a763a441028.png)

**Comment by a3ilson** [comment]
Well that may be the problem and would have been nice to know that earlier... pfELK hasn't been tested to run on an OSSEC instance.  The components are the same (Elastic Stack) and in theory it should work. I suspect that if your able to purge the elasticsearch data, you may be able to get it working but would leave any troubleshooting and/or issues to you as they are not necessarily pfELK specific issues.

I would also suggest installing pfELK as intended.

**Comment by spicyKo0l** [comment]
Hello,
I found the way from forums to list and delete indicies from Elastic
![image](https://user-images.githubusercontent.com/27067446/93815747-c292a980-fc56-11ea-95e0-4edb9d54d0ca.png)
<curl -XDELETE 'localhost:9200/_all'>

Then again I had created the index
![image](https://user-images.githubusercontent.com/27067446/93815929-143b3400-fc57-11ea-804a-f67b5bd52523.png)
Followed all the steps as you mentioned yesterday in [https://github.com/3ilson/pfelk/issues/183#issuecomment-695830720](url)
and then imported FW*ndjson but then I again I hit the same problem failed 9 Objects to import out of 20!
![image](https://user-images.githubusercontent.com/27067446/93816377-bb1fd000-fc57-11ea-87ae-ea7ba4d2970d.png)

When I filter application with "filterlog", I do not see any "suricata". I experimented as further searching by "suricata" No data available.
![image](https://user-images.githubusercontent.com/27067446/93817067-af80d900-fc58-11ea-83e1-97a1c3196bd2.png)

When I filter application with "filterlog", and further search for "firewall". I see same number of records including "firewall" or excluding "firewall" data.
![image](https://user-images.githubusercontent.com/27067446/93817157-d3dcb580-fc58-11ea-9208-a8dacc569d9e.png)

By this exercise I came to conclusion as you mentioned that my data is not enriched enough to  populate all those fields.
If there is a way to enrich my data, then may be I would be able to import all objects of Firewall dashboard.

Thank you for your support.

**Comment by a3ilson** [comment]
Your setup likely has the required data but you'll most likely need to build your own visualizations/dashboard or install pfELK as prescribed.  I may not be able to provide much help with your setup.

**Comment by a3ilson** [comment]
Kali support added to project
Issue not related to pfelk (conflict with OSSEC)
