### ISSUE TITLE
Help with ICMPv6/PIM grokparsefailure on pfSense 2.4.4-p3 

### ISSUE THREAD

**Issue by juicyroots** [pfelk/pfelk#19]
Thanks for putting this together. I really appreciate it.

I am getting _grokparsefailure and_geoip_lookup_failure for a few different messages, like ICMPv6 and PIM messages. Is this normal? Can I fix this or turn them off?

tags: pfsense, firewall, _grokparsefailure, _geoip_lookup_failure
message:    5,,,1000000003,em0,match,block,in,6,0xe0,0x00000,255,ICMPv6,58,32,fe80::2aa:6eff:fec1:5019,ff02::1,

tags: pfsense, firewall, _grokparsefailure, _geoip_lookup_failure
message: 5,,,1000000003,em0,match,block,in,6,0xe0,0x00000,1,PIM,103,334,fe80::2aa:6eff:fec1:5019,ff02::d,

Thanks!
JuicyRoots

**Comment by a3ilson** [comment]
JuicyRoots,

I haven't completed the grok patterns for IPv6 yet.  I utilized a grok
pattern debugger to tweak the patterns file (
https://grokdebug.herokuapp.com/) and haven't had much time to further
develop but plan to make additional process this fall.

-Andrew

**Comment by a3ilson** [comment]
@juicyroots 

I have no external IPv6 with my current ISP. However, I took the provided logs and walked them through the current configuration and received errors on both.  I made a slight modification to the GROK pattern and was able to get them parsed correctly.  

The following GROK pattern successfully parsed out both provided messages:
(?<ip_ver>(6)),%{BASE16NUM:IPv6_Flag1},%{WORD:IPv6_Flag2},%{WORD:flow_label},%{WORD:proto_type},%{INT:proto_id},%{INT:length},%{IP:src_ip},%{IP:dest_ip},

Based on the 10-pf.conf from lines 141-143 is where there the GROK patterns are linked.  I revised the GROK pattern to successfully match your provided logs.  Please update your pattern file with https://raw.githubusercontent.com/a3ilson/pfelk/master/pf-09.2019.grok, restart logstash and let me know if it successfully parses your ICMPv6 and PINv6 logs.
