### ISSUE TITLE
Squid Upload Logs visualization in kibana

### ISSUE THREAD

**Issue by vijaytejak** [pfelk/pfelk#190]
**Help wanted**

Hi,
Any idea how to get the squid upload logs i.e {I want to see each user upload logs (what file is uploaded, size of the file, the MIME type of the file, URL the file is uploaded into)}.

Did anyone try to get these details?

If anyone has tried and it's working please share with me the steps will follow and give it a try.

Thank you.

**Comment by a3ilson** [comment]
Do you have squid configured? And/or are you trying to enrich from the current dashboard squid configuration?

Reference: https://github.com/3ilson/pfelk/wiki/How-To:-Squid-on-OPNsense-pfSense

**Comment by vijaytejak** [comment]
I have a squid configured and running in pfsense, I am using Light squid and ELK to see the squid access logs, but I can't get the proper upload logs, I have uploaded 500mb data it is recording some 2mb or so, not sure what's wrong.

**Comment by a3ilson** [comment]
@vijaytejak - To confirm, you have pfSense with Squid running.  Plus pfELK with the associated Squid Dashboard but are requesting additironal details (i.e. uploaded files, size of files and MIME types)?

or

You have pfSense with Squid but it is not sending logs to pfELK?

**Comment by vijaytejak** [comment]
The first one:
I have pfSense with Squid running. Plus pfELK with the associated Squid Dashboard but are requesting additironal details (i.e. uploaded files, size of files and MIME types)?

**Comment by a3ilson** [comment]
@vijaytejak - Can you provide a referenced squid log?

I went through my logs (sent via syslog in json)... they do not provide the level of detail needed for enriching to the level of detail you're requesting. Next, I dug into the squid log format [here](http://www.squid-cache.org/Doc/config/logformat/) and it does not appear to be supported/feasible.

Alternatives:
- [Ntopng](https://www.ntop.org/products/traffic-analysis/ntop/) would provide additional details but perhaps not to the specificity you're look for
- [Network miner](https://www.netresec.com/?page=Networkminer)
  - I've used this in conjunction with [Moloch](https://molo.ch/), to drill down and analyze traffic

**Comment by vijaytejak** [comment]
yeah, same here, it became a nightmare for me for my project, was unable to get the upload logs till now.
I was using the same link you posted.

Any EDR which can get this level of details ?

**Comment by a3ilson** [comment]
I am unaware of any Endpoint Detection Response applications that would provide this level of detail. Especially with the level of encryption being employed and various means to transfer files. For example, a proxy sounds like the ideal solution (i.e. a ```man in the middle attack```) but I anticipate various legal/privacy hurdles that would require visiting prior to implementation. 

Issue #155 provided a means to scan various filetypes observed via Squid. 
- Revisiting the logs and looking at the ```squid.message``` field, there appears to be room for further refinement (i.e. filetypes/filenames) with the corresponding ```squid.http.response.bytes``` and ```squid.host.hostname``` fields may present a possible workaround.

I'll see if I can enrich and/or parse out various file types from the ```GET``` and ```PUT``` commands within the ```squid.message``` field(s).

**Comment by a3ilson** [comment]
@vijaytejak - After exploring Squid and the associated logs. This endeavor doesn't appear to be feasible. Filtering logs based on ```PUT``` doesn't necessarily yield files being uploaded.  I also looked into C-ICAP but was unable to yield anything useful to this request.

I would suspect a HIDS being better suited but my cursory review of [Wazuh](https://wazuh.com/) and [OSSEC](https://www.ossec.net/) wasn't promising.  I'll leave this issue open in hopes someone has a solution.

**Comment by a3ilson** [comment]
Not feasible with current squid log output.
