### ISSUE TITLE
Cloud Central Elk Stack server with Encrypted Syslog

### ISSUE THREAD

**Issue by TidalWave123** [pfelk/pfelk#191]
**Is your feature request related to a problem? Please describe.**
I want to turn this into hub for 15 client site PFsense boxes. I see below it is possible to have more than one pfsense instances inside one elk server. Is it also possible to have the elk server in the cloud and each pfsense box at a client site, just sending the data over the WAN to the cloud syslog server? 

**Describe the solution you'd like**
Ideally I'd like to use syslog-ng over vpn to encrypt over the WAN because if I use a vpn that would connect all 15 separated networks together. And over-complicate the security of each pfsense client site. So i'm hoping that encyrpted syslog messages can leave over the WAN but nothing can get back in. 

**Describe alternatives you've considered**
I've not really consider anything else, I just am really excited about graphing the firewall logs, and i'd love to have the ability to log into my digital ocean account on the cloud and scroll through each firewall to get a quick overview of what's going on at each client site. 

**Additional context**
I feel this feature would make me like a personal (human) SIEM system. For all my various client sites.

**Comment by a3ilson** [comment]
- [ ] Encrypt (VPN and/or TLS via syslog-ng 
  - install syslog-ng 
  - configure syslog-ng 
- [ ] Modify inputs.conf 
  - tag/label each instance as a unique tag/label
  - refine dashboard to view each instance separately and collectively for analysis
- [ ] Cloud hosting of pfELK 
  - need to define (I.e. Kubernetes)

**Comment by a3ilson** [comment]
@TidalWave123 - I’m currently away for the weekend and fortunately in between jobs (I.e. I have some free time). I’ll return tomorrow evening and will likely have a fair amount of free time to work on this during the week.

**Comment by a3ilson** [comment]
@TidalWave123 - Are you looking to host just Elastic or Logstash+Kibana?

Firewall --> Logstash --> Cloud (Elastic)
or
Firewall --> Cloud (Logstash+Elastic)

**Comment by TidalWave123** [comment]
I would say an all in one spot, we might not even use kubernetes just a
single VM hosted on digital ocean if you think that easy to do.

What ever is easier.

Best,
Kevin Kerr

**Comment by a3ilson** [comment]
@TidalWave123 - A VM hosted solution is easy!

The only concern I would have is the security of the logs traversing to/from.  
- Are you able to configure a VPN to/from each firewall instance?
  - Encapsulate all traffic within the encrypted VPN tunnel
- Are you able to connect to Kibana through a VPN?
  - Encapsulate remote connection to/from Kibana through a VPN

I have a few updates that I'm working on (ECS conformity, tweaks and new dashboards). Kubernetes are on my list and will make cloud hosting a cinch. However, if your able to fire-up a hosted VM with connectivity via VPN that would be the quickest solution (right now or until Kubernete solution is finalized).

**Comment by fktkrt** [comment]
Yes, I agree. 
I think having a Kubernetes solution would be beneficial, just not for this particular use-case. 
It can run on bare-metal, or use our current docker solution, both are fine and simple enough. 
Would leveraging the XPACK options be enough, or would we need additional measures?

**Comment by TidalWave123** [comment]
Is it not easy to setup syslog-ng to encrypt the log files? I have never
used syslog-ng but hoping it would be easy.

I could setup a vpn, but that would create a backdoor to each client site,
so that if one site is compromised, all sites are then compromised.Our
security policy is to keep each client site isolated from the other.

Best,
Kevin Kerr

**Comment by a3ilson** [comment]
You can configure syslog-ng to encrypt with TLS.  You’ll need a certificate on both the client and server side.  

Next, we’ll need to adjust the input file to accept the secure connection.

Let us know what you need help with:
- [ ] setting up syslog-ng with encryption 
- [ ] setting up logstash with encryption

Once those two items above are completed, you’ll be able to send logs securely to your server. Finally, you’ll need to make sure the connection from Kibana is secured which can be accomplished by following [these](https://www.elastic.co/guide/en/kibana/current/configuring-tls.html) instructions

**Comment by a3ilson** [comment]
Here's an example of configuring SSL for logstash:

```
input {
  tcp {
    port 514
    ssl => true
    ssl_certificate_authorities => ["/etc/logstash/ssl/YOURCAHERE.crt"]
    ssl_certificate => "/etc/logstash/ssl/SERVER.crt"
    ssl_key => "/etc/logstash/ssl/SERVER.key"
    ssl_verify_mode => "force_peer"
    type => "firewall"    
  }
}
```

Configuring Kibana can be accomplished via [here](https://www.elastic.co/guide/en/kibana/current/configuring-tls.html)

**Comment by fktkrt** [comment]
@TidalWave123 I just realized that I've missed very important requirements for your side.

So basically, you'd want to have multi-tenancy where you host the Elasticsearch platform and have your clients as tenants.
For this scenarios you will have to tackle the following issues:

- security (only part of it can be done with TLS and certs, as you'd have to isolate the data of tenants from each other as well)
- index design (1 index per tenant/shared index/alias, there are multiple options here)
- resource limits for the tenants
- how would they access the cluster, Kibana? Or will you be the only one having access?
- availability and upgrades

Some useful docs to start out: 
- https://www.elastic.co/guide/en/elasticsearch/guide/master/scale.html
- https://www.elastic.co/guide/en/elasticsearch/guide/master/faking-it.html

Unfortunately securing syslog is the easiest of all. :)

**Comment by fktkrt** [comment]
@TidalWave123 We are here to help to design (well, at least the pfelk indices) this infra, if needed.

**Comment by TidalWave123** [comment]
I'll be the only one to have access to the data. So no need to isolate the
data on the elk stack, just need to have each pfsense device on a separate
page of some kind or log file of some kind.

**Comment by a3ilson** [comment]
@TidalWave123 - the latest (revision from ~7-days ago) will better accommodate multiple instances.

You'll simply need to amend the [01-inputs.conf](https://github.com/3ilson/pfelk/blob/master/etc/logstash/conf.d/01-inputs.conf) and [02-types.conf](https://github.com/3ilson/pfelk/blob/master/etc/logstash/conf.d/02-types.conf).  The latest [dashbords](https://github.com/3ilson/pfelk/tree/master/Dashboard/v6.0) will allow you to select one, some or all interfaces for further log analysis. 

### 01-inputs.conf:
- Duplicate lines 3-13 for additional instances.
- Specify a different port number for each
```
  ### Firewall 1 ###
  udp {
    id => "pfELK-1"
    type => "firewall-1"
    port => 5140
    #ssl => true
    #ssl_certificate_authorities => ["/etc/logstash/ssl/YOURCAHERE.crt"]
    #ssl_certificate => "/etc/logstash/ssl/SERVER.crt"
    #ssl_key => "/etc/logstash/ssl/SERVER.key"
    #ssl_verify_mode => "force_peer"
  }
```
### 02-types.conf:
- Duplicate lines 3-12 for each additional instances.
- Amend the observer name, product and serial_number as desired
  - The dashboards will pivot based on the `observer.name` field
```
  ### PF-Firewall-1  ###
  if [type] == "firewall-1" {
    mutate {
      add_field => [ "[observer][type]", "firewall" ]
      ### Adjust the name, product and serial_number as desired ###
      add_field => [ "[observer][name]", "OPNsense" ]
      add_field => [ "[observer][product]", "Supermicro" ]
      add_field => [ "[observer][serial_number]", "001" ]
    }
  }
```

#### Additional Comments: 
Syslog-ng is capable of shipping logs with TLS/SSL.  This will require utilizing TCP vs UDP as defined in 01-inputs.conf line number 4 - simply amend from `udp` to `tcp`.  Additionally, you'll need to configure TLS/SSL within 01-inputs.conf lines 8-12 and duplicate for each instance.

Indices - we can help you define additional indices for each instance that will be compatible with the current templates/dashboards.  This will be adventurous if you plan to define retention (e.g. ILM) parameters.  

### Visualization 
![Capture](https://user-images.githubusercontent.com/16884679/97135437-a63ace80-1726-11eb-9775-2d042499b7e1.PNG)
- Red area denotes areas where encryption at a minimum should be employed
  -  e.g. data traversing outside/externally 
- Green area denotes server (internal)
- Encrypt logs being sent/ingested 
- Encrypt web client (i.e. Kibana)

Hopefully this helps.  Where at are you in this endeavor and what do you need assistance with?

**Comment by a3ilson** [comment]
This may be useful in configuring this setup: https://www.elastic.co/guide/en/logstash/7.10/connecting-to-cloud.html

**Comment by a3ilson** [comment]
@TidalWave123 - This issue was closed but if you still need assistance reach back out - we're happy to help.
