### ISSUE TITLE
Non-Xpack Lens Dashboards for OSS & Opendistro users

### ISSUE THREAD

**Issue by davidsielert** [pfelk/pfelk#193]
Would be immensely valuable to have dashboards which do not use XPack Lens features. All of the setup works in other than the dashboards.
Any possibility or community interest in this ?

**Comment by a3ilson** [comment]
@davidsielert - I'm open to it...I'm currently in the process of rebuilding the dashboards to conform to the adjusted naming scheme (i.e. ECS with templates and matching field types).

I'll build out without any _Lens_ Visualizations

**Comment by a3ilson** [comment]
@davidsielert - All dashboards were revised and no longer contain any lens elements.  However, be advised that the updated dashboards located [here](https://github.com/3ilson/pfelk/tree/master/Dashboard/v6.0) will require you to update the conf files, grok pattern, and templates. These updates were amended on 18 October 2020.

**Comment by a3ilson** [comment]
Latest dashboards are created utilizing non lens elements for use with OSS & Opendistro users
