### ISSUE TITLE
the index pattern you've entered doesn't match any indices

### ISSUE THREAD

**Issue by douglah13** [pfelk/pfelk#194]
tried to install it multiple times coudnt find any elasticsearch data and after adding pf-* it results : the index pattern you've entered doesn't match any indices tried to windows event they worked normally ... 

the 05 firewall file should i put the elk interfaces or pfsense though i tried both and still not working 

**Firewall System
 - pfSense 2.4.5-RELEASE-p1 (amd64) 

 
**Operating System (please complete the following information):**
tried different ubuntu versions and types
 
 **Installation method (manual, ansible-playbook, docker, script):**
 script 

**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
elasticsearch  7.8.1 
logstash       1:7.8.1-1
kibana         7.8.1

 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)

> [2020-10-18T19:24:37,185][INFO ][o.e.c.c.Coordinator      ] [node-1] cluster UUID [sO30B3xbSU2Ul0-pNxw8WA]
> [2020-10-18T19:24:37,563][INFO ][o.e.c.s.MasterService    ] [node-1] elected-as-master ([1] nodes joined)[{node-1}{_MJ95I1FQC-8qESpGANi5A}{CEXN5JnDTC25SHD9B_UV-A}{192.168.2.201}{192.168.2.201:9300}{dilmrt}{ml.machine_memory=4999282688, xpack.installed=true, transform.node=true, ml.max_open_jobs=20} elect leader, _BECOME_MASTER_TASK_, _FINISH_ELECTION_], term: 4, version: 225, delta: master node changed {previous [], current [{node-1}{_MJ95I1FQC-8qESpGANi5A}{CEXN5JnDTC25SHD9B_UV-A}{192.168.2.201}{192.168.2.201:9300}{dilmrt}{ml.machine_memory=4999282688, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]}
> [2020-10-18T19:24:38,179][INFO ][o.e.c.s.ClusterApplierService] [node-1] master node changed {previous [], current [{node-1}{_MJ95I1FQC-8qESpGANi5A}{CEXN5JnDTC25SHD9B_UV-A}{192.168.2.201}{192.168.2.201:9300}{dilmrt}{ml.machine_memory=4999282688, xpack.installed=true, transform.node=true, ml.max_open_jobs=20}]}, term: 4, version: 225, reason: Publication{term=4, version=225}
> [2020-10-18T19:24:38,415][INFO ][o.e.h.AbstractHttpServerTransport] [node-1] publish_address {192.168.2.201:9200}, bound_addresses {[::]:9200}
> [2020-10-18T19:24:38,416][INFO ][o.e.n.Node               ] [node-1] started
> [2020-10-18T19:24:39,528][INFO ][o.e.l.LicenseService     ] [node-1] license [0be4aaae-2969-442e-a99d-36499a8e5a63] mode [basic] - valid
> [2020-10-18T19:24:39,530][INFO ][o.e.x.s.s.SecurityStatusChangeListener] [node-1] Active license is now [BASIC]; Security is disabled
> [2020-10-18T19:24:39,539][INFO ][o.e.g.GatewayService     ] [node-1] recovered [10] indices into cluster_state
> [2020-10-18T19:24:59,216][INFO ][o.e.c.r.a.AllocationService] [node-1] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana_1][0]]]).
> [2020-10-18T19:25:36,778][INFO ][o.e.c.m.MetadataIndexTemplateService] [node-1] adding template [.management-beats] for index patterns [.management-beats]

 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
io.netty.channel.AbstractChannel.bind(io/netty/channel/AbstractChannel.java:248)
io.netty.bootstrap.AbstractBootstrap$2.run(io/netty/bootstrap/AbstractBootstrap.java:356)
io.netty.util.concurrent.AbstractEventExecutor.safeExecute(io/netty/util/concurrent/AbstractEventExecutor.java:164)
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(io/netty/util/concurrent/SingleThreadEventExecutor.java:472)
io.netty.channel.nio.NioEventLoop.run(io/netty/channel/nio/NioEventLoop.java:500)
io.netty.util.concurrent.SingleThreadEventExecutor$4.run(io/netty/util/concurrent/SingleThreadEventExecutor.java:989)
io.netty.util.internal.ThreadExecutorMap$2.run(io/netty/util/internal/ThreadExecutorMap.java:74)
io.netty.util.concurrent.FastThreadLocalRunnable.run(io/netty/util/concurrent/FastThreadLocalRunnable.java:30)
java.lang.Thread.run(java/lang/Thread.java:834)
[2020-10-18T19:43:11,362][INFO ][org.logstash.beats.Server][main][ed6931786a2b7e1c958814a9c991670ad89a70a55e628ddb3c3220f1abf020b2] Starting server on port: 5044

 - Kibana logs (`journalctl -u kibana.service`)
-- Logs begin at Sat 2020-10-17 18:52:38 UTC, end at Sun 2020-10-18 19:44:14 UTC. --
Oct 17 19:38:48 elksiem systemd[1]: Started Kibana.
Oct 17 19:38:50 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:38:50Z","tags":["warning","plugins-dis>
Oct 17 19:38:50 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:38:50Z","tags":["warning","plugins-dis>
Oct 17 19:39:41 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:41Z","tags":["info","plugins-servic>
Oct 17 19:39:41 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:41Z","tags":["info","plugins-servic>
Oct 17 19:39:41 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:41Z","tags":["info","plugins-servic>
Oct 17 19:39:41 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:41Z","tags":["info","plugins-servic>
Oct 17 19:39:45 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:45Z","tags":["warning","config","de>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["info","plugins-system>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["warning","plugins","e>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["warning","plugins","s>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["warning","plugins","s>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["warning","plugins","a>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["warning","plugins","a>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["info","plugins","moni>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["warning","plugins","m>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["info","plugins","cros>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["info","plugins","watc>
Oct 17 19:39:46 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:46Z","tags":["info","plugins","moni>
Oct 17 19:39:47 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:47Z","tags":["info","savedobjects-s>
Oct 17 19:39:47 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:47Z","tags":["info","savedobjects-s>
Oct 17 19:39:47 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:47Z","tags":["info","savedobjects-s>
Oct 17 19:39:47 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:47Z","tags":["info","savedobjects-s>
Oct 17 19:39:49 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:49Z","tags":["info","savedobjects-s>
Oct 17 19:39:50 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:50Z","tags":["info","savedobjects-s>
Oct 17 19:39:50 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:50Z","tags":["info","savedobjects-s>
Oct 17 19:39:50 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:50Z","tags":["info","savedobjects-s>
Oct 17 19:39:50 elksiem kibana[14586]: {"type":"log","@timestamp":"2020-10-17T19:39:50Z","tags":["info","plugins-system>

**Comment by a3ilson** [comment]
@douglah13 - the indices all start with `pfelk` if yours is `pf-*` it will not find any indices due to the hyphen.

Which script did you use to install (v5.5.5 or v6).  I'm recently updated a number of files.  Finally, can you provide (attach) the error log from the script. It should be located at `/etc/pfELK/error.data.sh`

**Comment by douglah13** [comment]
I tried the v5.5.5 I modifed another installation and ran the v6  and followed the new guide now the indicies and indexing is working but i can see no data it seems its not syncing , ill try a fresh install tomorrow incase the log file doesnt help 
am really thank full for your fast response and help  wish you all the luck with this wonderful project 

i uploaded the log file  
[error.pfelk.log](https://github.com/3ilson/pfelk/files/5398272/error.pfelk.log)

**Comment by douglah13** [comment]
what if the problem was from pfsense ? is their a way to check ?

**Comment by a3ilson** [comment]
@douglah13 - Thanks for providing the log file.

- I found one issue (my mistake) within the 50-outputs.conf file. I have since updated and you'll need to amend or download to match the latest version [here](https://raw.githubusercontent.com/3ilson/pfelk/master/etc/logstash/conf.d/50-outputs.conf)

- I also noted a file within your conf that was present but no contents were included in the log.  I would recommend removing this file, `sudo rm /etc/logstash/conf.d/main.conf`

- Otherwise, everything appears in order and if your pfSense/OPNsense is configured to send logs - everything should work. 
  - Did you complete the configuration settings [here](https://github.com/3ilson/pfelk/blob/master/install/configuration.md)

To check and see if pfSense/OPNsense is sending logs, you can run the following from the pfELK instance via command line:
`sudo tcpdump -i eth0 -nn -s0 -v port 5140`
- You'll need to replace `eth0` with the name of your network interface (`ip address`)
- You may need to let it run for a bit but it should output received logs

**Comment by douglah13** [comment]
same problem no data is showing on the dashbaord or discovery 
,i made a fresh install using debian , tcp dump is showing the firewall traffic , i just attached the new error log file 
[error.pfelk.log](https://github.com/3ilson/pfelk/files/5400580/error.pfelk.log)

**Comment by a3ilson** [comment]
@douglah13 - You need to ensure that the GeoIP databases have been installed/downloaded.  You are missing the following files:
```
/usr/share/GeoIP/GeoLie2-ASN.mmdb, GeoLite2-City.mmdb, GeoLite2-Country.mmdb
```

Ensure your credentials are contained within `/etc/GeoIP.conf` within lines 7&8
```
AccountID <Input Your Account ID>
LicenseKey <Input Your LicenseKey>
```
Then run `sudo geoipupdate` and check for the presence of the required GeoIP files located with `/etc/share/GeoIP/`

**Comment by a3ilson** [comment]
@massaquah - Which installation method did you utilize? 

The scripted method and manual method no longer contain outputs for `pfelk-YYYY.MM.DD` 

Please ensure and confirm that you have downloaded the latest files.  Additionally, if you've updated, be sure to restart logstash (e.g. `systemctl restart logstash.service`).  Lastly, make sure you follow the additional steps [here](https://github.com/3ilson/pfelk/blob/master/install/configuration.md). Paying particular attention to steps number 2 and 3.

**Comment by massaquah** [comment]
> @massaquah - Which installation method did you utilize?
> 
> The scripted method and manual method no longer contain outputs for `pfelk-YYYY.MM.DD`
> 
> Please ensure and confirm that you have downloaded the latest files. Additionally, if you've updated, be sure to restart logstash (e.g. `systemctl restart logstash.service`). Lastly, make sure you follow the additional steps [here](https://github.com/3ilson/pfelk/blob/master/install/configuration.md). Paying particular attention to steps number 2 and 3.

I set up MaxMind, (git)cloned the docker-pfelk directory and after making sure that all docker services went up without errors, I opened Kibana and followed the steps here:
https://github.com/3ilson/pfelk/blob/master/install/configuration.md

**Comment by massaquah** [comment]
I just realized that the files in your pfelk repo are much newer than in docker-pfelk.
Are you planning to update the files for docker installation method?

**Comment by a3ilson** [comment]
@massaquah - Gotcha... I haven't updated the Docker iteration. However, the prior version is still working (tested).  To utilize the docker instance, please utilize the installation method/instructions contained at the following [https://github.com/3ilson/docker-pfelk](https://github.com/3ilson/docker-pfelk)

**Comment by a3ilson** [comment]
Yes.  The main repo was updated yesterday and I'll have the other repo's updated this week.

**Comment by douglah13** [comment]
the issue was solved and its working properly 
Thank you so much

**Comment by a3ilson** [comment]
Issue resolved by initiator.
