### ISSUE TITLE
Security Detection Rules

### ISSUE THREAD

**Issue by rrosson** [pfelk/pfelk#200]
Any thought of adding a section for collecting Elastic Security Detection rules that are opnsense/pfsense centric. Looking at the rules from elastic seems to not be to applicable.

@a3ilson keep up the good work and I am enjoying the transition to using ECS.

**Comment by a3ilson** [comment]
@rrosson - Are you referring to the Security>>Detection>>Detection rules?

It would be beneficial but pf/OPNsense rules are unique (e.g. my rules will not match others) and this would vary from system to system.

@ShagoY - built two scripts to generate and sync pf/OPNsense rules for pfELK `pfelk_rule_generator.sh` and `pfelk_rule_sync.sh` which updates the `rule-names.csv` database and is captured in the `rule.alias` field.

**Comment by a3ilson** [comment]
@rrosson - We could reference the field from other fields (e.g. as an alias) but many of these rules are typically defined via SIEM>>Detection and require X-Pack.

We could revise the pfelk-firewall* template to add the `signal.rule.name` as an alias to `rule.alias` and as long as one of the scripts mentioned above is utilized, the rule number and description would be displayed and populate within the SIEM detection trend.  However, I'd be more inclined to defer this to the individual for customization and defining within SIEM via xpack.

Reference: https://www.elastic.co/blog/elastic-siem-detections

**Comment by a3ilson** [comment]
@rrosson - Are you referring to Suricata/Snort? or populating the Security>>Detection>>Detection rules from within the SIEM?

My next endeavor is to expand the Suricata dashboard...I plan to leverage what @ipworkx has with with their [ecs-surcata](https://github.com/ipworkx/ecs-suricata) repository (i.e. leveraging the Logstash enrichment configuration files). This will also make the Suricata ECS complianat (remove the current preceding Suricata nested objected).

**Comment by rrosson** [comment]
I was talking about "Security>>Detection>>Detection rules" with the idea of of having a community based source of rules that can take advantage of the work you have done here in pfelk. At  the least it would be a good starting point for other ideas.

Feel free to close this if you think it is out of scope.

**Comment by a3ilson** [comment]
Gotcha - I'll explore that too.  

I've only explored the built-in SIEM without X-PACK, thus far.

**Comment by a3ilson** [comment]
This would be a phenomenal addition to leverage Machine Learning for anomaly detection and notification but unfortunately this would required the Platinum or Enterprise subscription. The free and basic Machine Learning is limited to only Data Visualizer

Added [Wiki Page](https://github.com/pfelk/pfelk/wiki/How-To:-Kibana's-Built-in-SIEM)

Reference: https://www.elastic.co/subscriptions
