### ISSUE TITLE
Multiple Haproxy 

### ISSUE THREAD

**Issue by cihantunali** [pfelk/pfelk#205]
Hello,

At pfelk, we can monitor multiple pfsenses/opnsenses but is it possible to monitor multiple Haproxies or do i need to install pfelk for each of haproxy?

**Comment by BeNeDeLuX** [comment]
Hi @cihantunali 

shouldn´t be a problem in my eyes. You can normal filter via the host IP in Kibana.
The HAProxy Dashboard itself is not multiple (e.g. via a dropdown for the host) in the current version.

**Comment by a3ilson** [comment]
@cihantunali - A single install would be sufficient for handling multiple logs from multiple HAProxy instances. This could be accomplished a number of ways.  

Easiest: Filter based on the...
- `hostname` field value but would require them to be unique 
- `host` field 
  - This method would only require modifications to the dashboard or simply filtering based on those fields above

Easy: Send HAProxy logs to different ports identifying by different tags and observer fields (e.g. `observer.name`, `observer.product` and/or `observer.serial_number`)
- Modify `01-inputs.conf` and `02-types.conf` as needed
- Modify HAProxy dashboard as desired and/or simply filtering based on those fields above

I do not have any HAProxies but amending either above is fairly simple to accomplish...I'd be happy to help - just let me know.

**Comment by cihantunali** [comment]
Thank you for your answers, regarding my question, @BeNeDeLuX replied it. At dashboard only first Haproxy will be shown. Adding additional Haproxies, i will follow @a3ilson 's "Easy" way 😃 . Thank you so much.

**Comment by a3ilson** [comment]
Absolutely, please share any improvements!

**Comment by cihantunali** [comment]
Here you are.
```
03-filter.conf
filter {
  if [observer][type] == "firewall" or [observer][type] == "suricate" {
    grok {
      match => {"message" => "<(?<[log][syslog][priority]>.*)>%{SYSLOGTIMESTAMP:[event][created]}\s+(%{SYSLOGHOST:hostname}\s+)?%{DATA:[process][name]}(?:\[%{POSINT:[process][pid]}\])?:%{SPACE}%{GREEDYDATA:filter_message}"}
      }
    mutate {
      rename => {"message" => "[log][original]"}
      strip => ["[process][name]"]
    }
    mutate {
      add_field => {"pfname" => "%{host}"}
    }
    mutate {
      lowercase => ["pfname"]
    }
    ### BEATS ###
    if [observer][type] == "beats" {
      grok {
        match => { "[log][original]" => "%{SYSLOGLINE}" }
      }
      date {
        match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
      }
    }
  } else{
    grok {
      match => {"message" => "<(?<[log][syslog][priority]>.*)>%{SYSLOGTIMESTAMP:[event][created]}\s+(%{SYSLOGHOST:hostname}\s+)?%{DATA:[process][name]}(?:\[%{POSINT:[process][pid]}\])?:%{SPACE}%{GREEDYDATA:filter_message}"}
      }
    mutate {
      rename => {"message" => "[log][original]"}
      strip => ["[process][name]"]
    }
    mutate {
        split => ["[process][name]" , " "]
        add_field => {"haname" => "%{[process][name][0]}"}
    }
    mutate {
        update => {"[process][name]" => "haproxy"}
    }
}
    mutate {
      lowercase => ["haname"]
    }

    if [observer][type] == "beats" {
      grok {
        match => { "[log][original]" => "%{SYSLOGLINE}" }
      }
      date {
        match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
      }
   }
 }
```
With this configuration, 2 new field defined : haname and pfname . Based on these fields, you can filter your logs and can use multiple pfsense and haproxy from one port instead of creating multiple ports. Also;

If you add haname of pfname to 50-outputs.conf's index creation line, it will create indexes base on source name (index => "pfelk-haproxy-%{haname}-%{+YYYY.MM.dd}"). With this, you can track the source if logs are coming or not. I did this step via Grafana so that I can track if one of my resource stop sending logs, I will know it.

Hope this will help who have same problem with me. Thanks!

**Comment by a3ilson** [comment]
Update input and config files to sort based on host allowing multiple instances (pfsense/opnsense, haproxy) to be sent to one single port.
