### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by b4b857f6ee** [pfelk/pfelk#209]
Hello,

I just made Grafana Dashboard from your ELK stack 👍 
thank you for your pfelk by the way!!

https://github.com/b4b857f6ee/opnsense_grafana_dashboard

**Comment by a3ilson** [comment]
I'll update and add a reference to the provided link - thanks!

**Comment by b4b857f6ee** [comment]
Oh thank you! I do not expect that.

**Comment by a3ilson** [comment]
Updated finalization with Grafana as an alternate dashboard and point to provided link.
