### ISSUE TITLE
Download link for logstash/kibana/elasticsearch wrong

### ISSUE THREAD

**Issue by BeNeDeLuX** [pfelk/pfelk#210]
**Describe the bug**
Since the version change yesterday (7.9.3 -> 7.10.0) the install script fails to download the logstash package and end´s in an error. Elastic added the architecture to their download:

**Old Link** -> https://artifacts.elastic.co/downloads/logstash/logstash-7.9.3.deb
**New Link** -> https://artifacts.elastic.co/downloads/logstash/logstash-7.10.0**-amd64**.deb

**To Reproduce**
1. Use latest installer script

**Idea**
We could use dpkg to printout the variable inside the shellscript and add it to the filename:

```
elastic01:~# dpkg --print-architecture
amd64
```
I did not test it - just an idea

**Comment by a3ilson** [comment]
Thanks and updated.

**Comment by a3ilson** [comment]
Elasticsearch and Kibana already had the architecture included. No need to add architecture variable for logstash as the script was amended to mimic Elasticsearch and Kibana.

Thanks!
