### ISSUE TITLE
Problem with Grok

### ISSUE THREAD

**Issue by MattiaConversano** [pfelk/pfelk#22]
Hi,

first of all thanks for this fantastic solution.

I have a problem with the logstash grok, the message field is not changed ..
Surely it will be my mistake but I have followed the guide several times and I can't understand where I'm wrong.

This is my logstash log file:
[logstash-plain.log](https://github.com/a3ilson/pfelk/files/3573445/logstash-plain.log)

and this is my result in kibana:

```
{
  "_index": "pf-2019.09.04",
  "_type": "_doc",
  "_id": "hT9c-2wB3hlBxPd8ZQSS",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-09-04T08:20:32.169Z",
    "@version": "1",
    "tags": [
      "pfsense"
    ],
    "type": "syslog",
    "host": "192.168.100.1",
    "message": "<134>Sep  4 10:20:31 filterlog: 5,,,1000103483,em0,match,block,in,4,0x0,,128,2365,0,none,17,udp,78,10.0.101.173,10.0.101.255,137,137,58"
  },
  "fields": {
    "@timestamp": [
      "2019-09-04T08:20:32.169Z"
    ]
  },
  "sort": [
    1567585232169
  ]
}
```
I hope you can to help, thanks in advice,
Mattia

**Comment by a3ilson** [comment]
Mattia,

Thanks for the feedback. I recently updated the configuration files for utilization with both OPNsense and PFsense.  Based on the provided information the noted issue appears to within the 10-syslog.conf file.  

The file was updated and you can download the revision or simply change "pfsense" to "pf" on line 5.  Once updated restart logstash and it should work.  

Let me know if you have any other issues.
-Andrew

**Comment by MattiaConversano** [comment]
hi Andrew,
Thank you so much,
It seems to work properly,
Thank you again.

Mattia
