### ISSUE TITLE
Index Template import Broken

### ISSUE THREAD

**Issue by rrosson** [pfelk/pfelk#222]
Current git (master)

when importing index template get the following for all of the templates:

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "invalid_index_template_exception",
        "reason" : "index_template [pfelk] invalid, cause [index template [pfelk] specifies component templates [pfelk-settings, pfelk-mappings-ecs] that do not exist]"
      }
    ],
    "type" : "invalid_index_template_exception",
    "reason" : "index_template [pfelk] invalid, cause [index template [pfelk] specifies component templates [pfelk-settings, pfelk-mappings-ecs] that do not exist]"
  },
  "status" : 400
```

**Comment by a3ilson** [comment]
@rrosson - thanks and apologize but I failed to include the specifics (sequence) for the new templates.

I'm updating the repository now but to circumvent this error, the elements must be done in a particular order as they are dependent upon the component templates:

First - Install the `pfelk-settings`
Second - Install the `pfelk-mappings-ecs`
The remaining templates may be installed in any order after the two prerequisite components are installed.

**Comment by rrosson** [comment]
That worked. Thanks
