### ISSUE TITLE
Firewall Dashboard Issues

### ISSUE THREAD

**Issue by dw86uk** [pfelk/pfelk#227]
I've just followed the guide for a manual installation on Debian 10 which went well although I was only able to install Java v11 rather than 14. Everything went well, however, when I go to the firewall dashboard only the "Firewall - Discover" box is populated. I get numerous errors in the other ones, please see the attached screenshot. Any help in rectifying this would be much appreciated, I used the v6.1 templates btw.

Thanks,

Dan

![image](https://user-images.githubusercontent.com/28095779/102941736-5ae53800-44ab-11eb-8c62-8448b07594ce.png)

![image](https://user-images.githubusercontent.com/28095779/102941783-76504300-44ab-11eb-9fc7-79b05d21b0ba.png)

**Comment by a3ilson** [comment]
Dan, 

Thanks for your inquiry and before we dig into too much troubleshooting, give the following a try:
- Navigate to Kibana>>Management>>Stack Management>>Data>>Index Management and delete all indicies
- ![Screen Shot 2020-12-22 at 19 34 52](https://user-images.githubusercontent.com/16884679/102945823-e4394200-448c-11eb-8381-9c9552c6ebad.png)
- Once deleted, navigate back to your dashboard and see if the problem persist.
  - This is indicative when sending logs prior to installing the templates

As for Java...I've installed and tested OpenJDK 14 (Ubuntu) but have not been able to get it to work on Debian.

**Comment by dw86uk** [comment]
Thanks, I've deleted the indices and now have a slightly better looking dashboard, no errors but no data...

![image](https://user-images.githubusercontent.com/28095779/103018499-481b4380-453d-11eb-84f8-50e3dbf4cf1f.png)

I think this may be bacause some of my indicies when they were recreated have been created without the "-000001" suffix as per the screenshot below.

![image](https://user-images.githubusercontent.com/28095779/103018655-831d7700-453d-11eb-9d25-06deb2e58b61.png)

Any idea how to fix this issue now?

Thanks,

Dan

**Comment by a3ilson** [comment]
Dan,

Send (attach) your `50-outputs.conf` file.  The dashboards reference their respective indices via `pfelk-unbound-*` and your indices are missing the trailing dash. This is an easy fix and likely something within your `50-outputs.conf`. Send over and I'll take a look... once corrected, you'll need to restart logstash and purge your indices again.

**Comment by dw86uk** [comment]
Thanks, please find 50-outputs.conf (with .txt extension for comment support) attached. Interestingly I don't think I've modified this file (I could be wrong though). When I originally purged the indices all of them were correctly labelled with the -000001 suffix.

[50-outputs.txt](https://github.com/pfelk/pfelk/files/5736275/50-outputs.txt)

**Comment by a3ilson** [comment]
Thanks!  Everything looked good. Did you upload the pfelk-ilm policy?

![Screen Shot 2020-12-23 at 12 05 12](https://user-images.githubusercontent.com/16884679/103020833-2909bb00-4517-11eb-8df7-4a4b42dc30ef.png)

**Comment by dw86uk** [comment]
Yeah thats uploaded, interestingly I seem to be on version 1 compared to your version 2 though?

![image](https://user-images.githubusercontent.com/28095779/103021081-7bf86800-4541-11eb-8f2b-acc48651e96c.png)

**Comment by a3ilson** [comment]
The version isn't relevant...check your index template and make sure the policy is set.

![Screen Shot 2020-12-23 at 12 10 05](https://user-images.githubusercontent.com/16884679/103021329-f7452400-4517-11eb-99bc-3ecd75f64fec.png)

**Comment by dw86uk** [comment]
Yeah the index template looks to be set with the same settings as your screenshot...

![image](https://user-images.githubusercontent.com/28095779/103021713-85360480-4542-11eb-9d83-a6bd30b22955.png)

**Comment by a3ilson** [comment]
odd...

Give this a try:
1. Stop logstash 
2. Purge your indices 
3. Start logstash

**Comment by dw86uk** [comment]
That's got it, and the dashboard is now working correctly!

Thanks for your help - I can confirm that OpenJDK-11 seems to be the latests Java package available for Debian 10 and that seems to work fine!

Thanks,
Dan

**Comment by a3ilson** [comment]
That was an odd one but glad you got it!
