### ISSUE TITLE
DHCP Dashboard mostly empty

### ISSUE THREAD

**Issue by vecchiae** [pfelk/pfelk#228]
I have installed PFElk for some time, and I love it.

I have recently updated to 6.1 (I used the installation script on a new VM). Firewall, Suricata and Unbound dashboards work, however  the DHCP dashboard is mostly empty (see attached)
[Screen Shot 2020-12-22 at 6.25.09 PM.pdf](https://github.com/pfelk/pfelk/files/5732373/Screen.Shot.2020-12-22.at.6.25.09.PM.pdf)

I see that DHCP data gets parsed:
`tags:dhcp, dhcpdv4, dhcp, dhcpdv4 log.original:<190>Dec 22 18:17:20 OPNsense.VM.com dhcpd[67632]: DHCPACK on 192.168.10.40 to 6e:27:f2:bb:82:f4 (Applewatch) via vtnet1 log.syslog.priority:190 event.created:Dec 22, 2020 @ 18:17:20.000 @timestamp:Dec 22, 2020 @ 18:17:20.307 @version:1 observer.type:firewall observer.name:OPNsense observer.serial_number:001 observer.product:HP 730 observer.ip:192.168.10.1 host.name:OPNsense.VM.com process.name:dhcpd process.pid:67,632 _id:olS-jHYBH44shZlfJRCd _type:_doc _index:pfelk-dhcp-000001 _score:`

As I am on OPNSense,  I am wondering if the dashboard has been created for PFsense, eg. if PFsense DHCP syslog produces more detailed information than OPNSense, or if there is something wrong on my side that I need to investigate.

**Comment by a3ilson** [comment]
@vecchiae - Thanks and glad you found this useful! I just updated the script installer or essentially just added the ability to pick MaxMind or the built-in GeoIP database. Anyways, I'm running OPNsense and this particular dashboard was built utilizing OPNsense traffic but was also tested/validated on pfSense.

I just checked mine and noted the same problem and apologize for the inconvenience. This was the result of fixing another issue and I'm working on it now - I'll have an update/fix momentarily.

Thanks!

**Comment by a3ilson** [comment]
I'm also working to automate the template/dashboard installation via the scripted installation.

**Comment by vecchiae** [comment]
Thanks. I am using MaxMind, although do not think that's the problem. 
I actually tried to install without the script using Ubuntu.md (I noticed for example that the script installs Java 11 but manual installation suggests Java 14), but maybe I messed up somewhere  and thus used the script

**Comment by a3ilson** [comment]
The script method installs Java 11 as Java 14 did't work with Debian (the script installs on various Linux variants).

**Comment by a3ilson** [comment]
Alright, the GROK pattern was updated to fix this issue. Please download it [here](https://raw.githubusercontent.com/pfelk/pfelk/master/etc/logstash/conf.d/patterns/pfelk.grok) and replace your current one which should be located at `/etc/logstash/conf.d/patterns/pfelk.grok`. Once replaced simply restart logstash and confirm the dashboard is working (`systemctl restart logstash.service`)

**Comment by vecchiae** [comment]
It works now, thanks for fixing it so quickly

**Comment by a3ilson** [comment]
Resolved
