### ISSUE TITLE
DHCP JSON duplicate fields

### ISSUE THREAD

**Issue by vecchiae** [pfelk/pfelk#229]
**Describe the bug**
A number of DHCP fields are duplicate, and thus the dashboard shows them twice as well 

[DHCP Screenshot.pdf](https://github.com/pfelk/pfelk/files/5735757/DHCP.Screenshot.pdf)

Unfortunately I do not understand this process well enough to be able to diagnose and help

**Comment by a3ilson** [comment]
@vecchiae - Does this only occur on your vlan interfaces?

**Comment by a3ilson** [comment]
Here's a quick overview/explanation:

In this example we'll utilize the following message extracted from the `original.log` field:
```
<190>Dec 23 10:39:26 firewall.something.dev dhcpd[68124]: DHCPREQUEST for 172.22.33.100 from f0:9f:c2:00:00:00 via igb1
```

Here's the sequence of what files are applicable to this log:
**01-inputs.conf** - sets the listening port and defines the id and type
**02-types.conf** - adds user defined fields 
**03-filer.conf** - is the first applied filter (line 5) and would apply the following grok filter to the message above:
```
<(?<[log][syslog][priority]>.*)>%{SYSLOGTIMESTAMP:[event][created]}\s+(%{SYSLOGHOST:[host][name]}\s+)?%{DATA:[process][name]}(?:\[%{POSINT:[process][pid]}\])?:%{SPACE}%{GREEDYDATA:filter_message}
```

The output for the applied filter will yield the following:
```
{
  "[log][syslog][priority]": "190",
  "[event][created]": "Dec 23 10:39:26",
  "[host][name]": "firewall.something.dev",
  "[process][pid]": "68124",
  "filter_message": "DHCPREQUEST for 172.22.33.100 from f0:9f:c2:00:00:00 via igb1",
  "[process][name]": "dhcpd"
}
```

**05-apps.conf** - further filters messages this based on their `[process][name]` field and in this case we’ll go to the dhcp section within this file or lines 14-23 which further filers the message with the following grok filter:

```
grok {
      patterns_dir => ["/etc/logstash/conf.d/patterns"]
      match => [ "filter_message", "%{DHCPD}"]
}
```

To make the file easier to navigate (humans) various grok patterns are referenced and defined within the `/etc/logstash/conf.d/patterns` folder or the `pfelk.grok` file in this case.  Opening the `pfelk.grok` file you’ll note that it is grouped together with like sections. Lines 42-55 contains the dhcp patterns. Now this may get a bit confusing but I'll attempt to explain what’s going on.

First, you’ll note within the **05-apps.conf** file, it tells the grok pattern to match based on the `filter_message` field against the DHCPD grok pattern. So it is taking `DHCPREQUEST for 172.22.33.100 from f0:9f:c2:00:00:00 via igb1` and applying the DHCPD grok pattern.  We can replicate this within the *Dev Tools>>Grok Debugger* by inserting the message and the applicable grok filter (unfortunately, we cannot simply copy/paste this particular grok in its entirety).


However, line 44 is the first to be applied (note: that it equals our match request from **05-apps.conf** or DHCPD) and the other lines within the DHCPD section are extensions to DHCPD (e.g. DHCPD_XXXX). But the DHCPD line references those lines as it attempts to successfully match the message.  In this example it will match on the *DHCPD_REQUEST* line which we can copy into the grok debugger:

![Screen Shot 2020-12-23 at 11 26 15](https://user-images.githubusercontent.com/16884679/103017510-b518e400-4511-11eb-9bae-6c628567be6c.png)

This will yield the following output:
```
{
  "[dhcpv4][client][mac]": "f0:9f:c2:af:03:c4",
  "[dhcp][operation]": "REQUEST",
  "[dhcpv4][client][ip]": "172.22.33.6"
}
```

You’ll note that I omitted the end of that grok filter (e.g.`  %{DHCPD_VIA}`) as it referenced another line.  We can copy that line and add it to our filter as such:

![Screen Shot 2020-12-23 at 11 27 04](https://user-images.githubusercontent.com/16884679/103017611-dbd71a80-4511-11eb-9e90-45ee555b3dca.png)

And now our output is:

```
{
  "[interface][name]": "via",
  "[dhcpv4][client][mac]": "f0:9f:c2:af:03:c4",
  "[dhcp][operation]": "REQUEST",
  "[dhcpv4][client][ip]": "172.22.33.6"
}
```

Finally, **45-cleanup** removes a couple of duplicate fields and enriches one while **50-outputs.conf** sends the enriched message to Elasticsearch.

I’ll continue to dabble with the provide message (duplication) and see where and why it is getting duplicated.  

Thanks again for highlighting this issue as it’ll improve the overall utility of this project.

**Comment by a3ilson** [comment]
Awe, after going through the process and referencing some recent changes, I suspect you have additional files that are duplicating the logs.

Please check `/etc/logstash/conf.d/` which should contain the following:
- 01-inputs.conf
- 02-types.conf
- 03-filter.conf
- 05-apps.conf
- 30-geoip.conf
- 35-rules-desc.conf
- 36-ports-desc.conf
- 40-interfaces.conf
- 45-cleanup.conf
- 50-outputs.conf

If you have additional files, please delete and restart logstash.  I suspect that you might have the following:
- 05-firewall.conf -> this was merged with 05-apps.conf
- 10-apps.conf -> this was merged with 05-firewall.conf and renamed to 05-apps.conf
- 07-interfaces.conf -> this was renamed to 40-interfaces.conf
If these files are present, please remove and restart logstash.  

Sorry for the inconvenience and let me know if this resolves the issue.

**Comment by vecchiae** [comment]
Thanks for the good explanation, I'll need a bit to study it.
In fact the problem was a duplicate file, I still had 10-apps.conf. Deleted it and now it works properly.

Now I'll start investigating how I can add Interface_Alias to the DHCP extraction and Dashboard: little project to learn

**Comment by a3ilson** [comment]
Excellet!  

Feel free to submit a pull request and update the current Dashboard...your addition may be of interest to others.  Additionally, if you need help, let me know.

I'll close this as the matter was resolved.
