### ISSUE TITLE
Index Lifecycle Error

### ISSUE THREAD

**Issue by vecchiae** [pfelk/pfelk#233]
I noticed that from time to time the following errors appear
[Screen Shot 2020-12-24 at 10.37.10 AM.pdf](https://github.com/pfelk/pfelk/files/5740152/Screen.Shot.2020-12-24.at.10.37.10.AM.pdf)

the trace shows

```
java.lang.IllegalArgumentException:` setting [index.lifecycle.rollover_alias] for index [pfelk-suricata-000001] is empty or not defined
	at org.elasticsearch.xpack.core.ilm.WaitForRolloverReadyStep.evaluateCondition(WaitForRolloverReadyStep.java:65)
	at org.elasticsearch.xpack.ilm.IndexLifecycleRunner.runPeriodicStep(IndexLifecycleRunner.java:174)
	at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggerPolicies(IndexLifecycleService.java:327)
	at org.elasticsearch.xpack.ilm.IndexLifecycleService.triggered(IndexLifecycleService.java:265)
	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine.notifyListeners(SchedulerEngine.java:183)
	at org.elasticsearch.xpack.core.scheduler.SchedulerEngine$ActiveSchedule.run(SchedulerEngine.java:216)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

I did a bit of investigation and I believe that pfelk-suricata template needs to update with an alias , as below  (showing only top of file)
```
PUT _index_template/pfelk-suricata
{
  "version": 8,
  "priority": 20,
  "template": {
    "settings": {
      "index": {
        "lifecycle": {
          "name": "pfelk-ilm",
          "rollover_alias": "pfelk-ilm"
        }

```
Same for pfelk and pfelk-dhcp.

As I am not sufficiently knowledgeable on logstash, I am not sure if this is the right approach.

**Comment by vecchiae** [comment]
I tested my solution above and I now see it doesn't work, the indices get cancelled after a short while

**Comment by a3ilson** [comment]
@vecchiae - What does your 50-outputs.conf file look like? 

You should not be receiving that error if 50-outputs.conf has the following lines and you have the pfelk-ILM policy loaded:

Example for Firewall (see [50-outputs.conf](https://raw.githubusercontent.com/pfelk/pfelk/master/etc/logstash/conf.d/50-outputs.conf))
>ilm_rollover_alias => "pfelk-firewall" 
ilm_pattern => "000001"

**Comment by vecchiae** [comment]
My 50-outputs.conf has the references to the alias.
pfm-ILM policy should be loaded properly, I see it under the Index Lifecycle  Policies and it shows that there are 5 linked indices.

I can always create a new VM and start from scratch, if it is too complicated to diagnose

**Comment by a3ilson** [comment]
Depending on your setup, ILM may not be needed but the above ought to work without issues.  I'm running another instance while I test issue #232 - I'll see if I can replicate this issue and tackle both.

**Comment by a3ilson** [comment]
I've seen the error on my testing instance but it only appears momentarily before disappearing.  

I added this along with another ILM issue to the ILM Project...I'll chip away and get this working in the near future.

**Comment by vecchiae** [comment]
Same for me, the error appears and then disappears.

**Comment by a3ilson** [comment]
Well despite the momentary error, my ILM was partially successful after running for a one day test.  I made a minor tweak and awaiting another day to test the updated ILM, if successful I'll post and close out both issues related to the ILM.

**Comment by a3ilson** [comment]
@vecchiae 
## ILM Issue Resolved
### Solution
1. Stop logstash `systemctl stop logstash`
2. Delete the following templates
  - pfelk
  - pfelk-dhcp
  - pfelk-haproxy
  - pfelk-suricata
3. Amend the `/etc/logstash/conf.d/50-outputs.conf` with the latest/updated version [here](https://raw.githubusercontent.com/pfelk/pfelk/master/etc/logstash/conf.d/50-outputs.conf)
  - By default ILM will not be utilized but if desired, uncommit all instances of #ILM# within the 50-outputs.conf file
4. Download and install the templates 
a. Manual Method - Reaccomplish Step 2 [here](https://github.com/pfelk/pfelk/blob/master/install/configuration.md#templates)
b. Automated Method - Download [this script](https://raw.githubusercontent.com/pfelk/pfelk/master/pfelk-template-installer.sh)
    - e.g. `sudo wget https://raw.githubusercontent.com/pfelk/pfelk/master/pfelk-template-installer.sh`
    - Make the script executable, `sudo chmod +x https://raw.githubusercontent.com/pfelk/pfelk/master/pfelk-template-installer.sh`
    - Run, `sudo ./pfelk-template-installer.sh`


#### Background:
Elastic does not support ILM patterns for indices with multiple index patterns (e.g. pfelk). 

#### Solution:
- ILM settings were removed from all templates 
- ILM settings were amended to 50-outputs.conf
  - By default they are now disabled (i.e. committed out) but may be enabled by uncommitting and restarting logstash

**Comment by a3ilson** [comment]
Once confirmed, please reply and close out this issue.

**Comment by vecchiae** [comment]
Sorry for late response, got distracted with holiday and family. Made changes as per above, not seeing any errors, will let it run for a few more hours and then will close it
