### ISSUE TITLE
Error in conf.d

### ISSUE THREAD

**Issue by ShagoY** [pfelk/pfelk#242]
Hi a3ilson :)

I have just tested your version 6.7 (The automatic script), everything works perfectly except for an error that I will explain to you ! Another great job from you ;-)

But why did you remove the geomap ? (Firewall - Dashboard)

Otherwise there is an error in the layout in conf.d, your 40-interfaces.conf must be before the 35-rules-desc.conf. Because the result of the first one is used in the latter. The [rule][description] field is not correctly filled in.
So I changed its name to 20-interfaces.conf and everything is back in order.
I'll let you see what suits you best :)

Also maybe take the opportunity to add a fallback in XX-interfaces.conf :

```
# Fallback
if ![interface][alias] and [interface][name] {
	mutate {
	  add_field => { "[interface][alias]" => "%{[interface][name]}" }
	  add_field => { "[network][name]" => "%{[interface][name]}" }
  }
}
```
Regards.

**Comment by a3ilson** [comment]
@ShagoY - Thanks for identifying and enhancing this repo!

I'll update the file name shortly...Although I do not utilize the 35-rules-desc.conf, in my particular setup...Have you tested your fallback? Feel free to submit a PR and/or I'll include in the amended name change.

My goal with the script was to provide a single command to install everything...I believe it's there minus the pf/OPNsense configuration.

I can add the Geo Maps as an alternative dashboard...I personally didn't find those visualization useful.

Thanks!

**Comment by a3ilson** [comment]
@ShagoY - Thanks again!

By amending the 40-interfaces.conf to 20-interfaces.conf the issue is solved not sure the fallback is needed - thoughts?

**Comment by a3ilson** [comment]
I found this visualization to be more useful for analysis vs the map:
![Screen Shot 2020-12-29 at 16 41 26](https://user-images.githubusercontent.com/16884679/103315852-cf146400-49f4-11eb-9c5d-768b5686e448.png)

The "curve" is my firewall being pinged (various ports) which happens like clockwork but nothing making it through and nothing I can do (except unplug my WAN).  The next picture is the same thing but when I filter based on events that were allowed (pass):
![Screen Shot 2020-12-29 at 16 46 13](https://user-images.githubusercontent.com/16884679/103316082-6083d600-49f5-11eb-9056-db2e6709ebd1.png)

**Comment by a3ilson** [comment]
Status

- [x] Network interfaces updated by @ShagoY via pull request #245 
- [x] 40-interfaces.conf was renamed to 20-interfaces.conf
- [ ] Adding alternate visualization for dashboards (i.e. map) - WIP

**Comment by ShagoY** [comment]
@a3ilson 

For which request do you say "My goal with the script was to provide a single command to install everything...I believe it's there minus the pf/OPNsense configuration."?

For the heatmap source, yes it's really interesting and I'll add it on my dashboard.

For the geomap, I confess that I have customized the original a lot so I can't do without it anymore. So it's mostly for an aesthetic reason.
After I don't ask for its return, I just wanted to know the reason of its disappearance :)

If nobody asked for it, there's no reason to manage an alternative dashboard :)

Here is my geomap :
![pfelk-geomap](https://user-images.githubusercontent.com/25367500/103364428-0e5ab780-4abe-11eb-9d40-be06f70ee3cb.jpg)

**Comment by a3ilson** [comment]
@ShagoY 
- I'll add the GeoMap back...if you had a question, I'm sure others will/do too. It's an easy adjustment - thanks for the feedback! 
- The script no longer needs to accommodate for pf/OPNsense as the updated conf files accommodate both instances without modification
  - I also updated the 03-filter.conf file to accommodate the pfSesne optional log output (BSD/syslog). The filter should work for pfSense (both options) and OPNsense without changes. Feel free to take a peek at issue #243 and give the updated 03-filter.conf a try/test/validation

**Comment by ShagoY** [comment]
Ok, the addition of the fallback goes exactly in this direction. It simply takes the default value of pfsense/opnsense (like igb/vnet/etc...) if it doesn't exist in the 20-interfaces.conf.
Well I guess you already understood ^^

I'll look for a fork of the "geomap", currently mine is far too customized but there are some features that I liked.
Like the display which changes according to the zoom, the use of "EMS Boundaries" which allows to add country borders and thus to display the totality of the requests of a particular country (See the tooltip of Russia in my Screenshot above).

**Comment by a3ilson** [comment]
Here's a map, that I put together based on what you shared:
![Screen Shot 2020-12-30 at 12 03 08](https://user-images.githubusercontent.com/16884679/103369011-0dfaf600-4a97-11eb-9755-ad07da949e89.png)

Notes:
- Country borders are color coded (heat map) based on # of sources 
- Country fill are color coded (heat map) based on # of destination
- Blue circles are number of source events
- Red circles are number of destination events
- 
I wouldn't mind added your map to the mix either...
