### ISSUE TITLE
Troubleshooting pfSense+initial filter

### ISSUE THREAD

**Issue by saroyaj** [pfelk/pfelk#243]
Here is a sample firewall log: 

<134>1 2020-12-29T17:30:17.897251+00:00 heimdall-fw.localnet filterlog 35553 - - 97,,,1568496159,pppoe0,match,block,in,4,0x0,,243,734,0,none,6,tcp,40,x.x.x.x,y.y.y.y,40022,50752,0,S,1395699778,,1024,,

Looks like its not being parsed by 03-filter.conf probably ?

![image](https://user-images.githubusercontent.com/7500783/103303169-4f29d200-49d3-11eb-9fbe-45be2674ae36.png)

**Comment by a3ilson** [comment]
@jsinix - Thanks for providing the original message text which looks to have some additional characters (specifically the two dashes after the filterlog 35553).

Are all your logs resulting in grokparsefailures?
Are you running pfSense/OPNsense and what version?
I may reach out for additional specifics but devise a solution/remedy

Thanks for providing and contributing the this repo!

**Comment by saroyaj** [comment]
yes all of them are resulting in grokparsefailures

**Comment by a3ilson** [comment]
Okay, give me a few minutes to decipher...

I could easily fix this for your particular setup and provide you with the instructions on how to implement. This would be the quickest remedy until I amend the repo to accommodate for the extra syntax.

**Comment by saroyaj** [comment]
I think I know why this issue is triggered. I am using syslog format rather than the default BSD format. 

![image](https://user-images.githubusercontent.com/7500783/103306259-23aae580-49db-11eb-806d-7140c11e5ea5.png)

Once I switch to BSD, the parser(and eventually the dashboards) works. If the parse can account for both the formats that would be great I guess ? I will also try and see if i can make it work on my side.

**Comment by a3ilson** [comment]
Good to hear!

I figured it would have been the other way around (i.e. syslog working and BSD resulting in errors). 

So you're up and running?  

I'll leave this issue open as I built a filter to accommodate for the alternate message format (pfSense specific). The only differences are the number following the priority and the dashes following the program process id.

**Comment by saroyaj** [comment]
Yes its working with BSD. I was just looking at the SYSLOGTIMESTAMP grok pattern and looks like syslog format might be  better parsed using SYSLOGBASE2. I might be wrong as I have just recently started working with logstash. Thank you for your quick response on this issue.

**Comment by a3ilson** [comment]
Correct!  SYSLOGBASE2 would be better for the syslog output..

Here is an amended grok pattern from 03-filter.conf which will parse out both types. However, testing will be needed to determine if the 8601 format works with the index templates and dashboards.

```
<(?<[log][syslog][priority]>.*)>(?:%{SYSLOGTIMESTAMP:timestamp}|%{TIMESTAMP_ISO8601:timestamp})\s+(%{SYSLOGHOST:[host][name]}\s+)?%{DATA:[process][name]}(?:\[%{POSINT:[process][pid]}\])?:%{SPACE}%{GREEDYDATA:filter_message}
```

It still doesn't parse out your original log message...that precede digit and dashes will need to be accounted for...

**Comment by a3ilson** [comment]
@jsinix - I amended the 03-filter.conf grok pattern (below).  It should filter your initial message and anyone else desiring to utilize syslog on pfSense.  Additionally, I added optional filters allowing it to also filter BSD. I have it running on my instance of OPNsense without any issue.

Please give the following a try and let me know if it works for pfSense (both syslog[RFC5424] and BSD[RFC 3164]). 

```
# 03-filter.conf
####################################################################
# Version: 21.01                                                   #
# Description: Filters initial message from RFC3164 and RFC5424    #
# supporting both pfSense and OPNsense logging                     #
####################################################################
filter {
  if [observer][type] == "firewall" or [observer][type] == "haproxy" or [observer][type] == "suricata" {
    grok {
      match => {"message" => "<%{POSINT:[log][syslog][priority]}>(%{INT:version}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}\s*?(\[)?%{POSINT:[process][pid]}(\]:)?\s*(\-\s*\-)?\s*%{GREEDYDATA:filter_message}"}
      }
      date {
        match => [ "[event][created]", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss", "ISO8601" ]
        target => "[event][created]"
      }
    mutate {
      rename => {"message" => "[log][original]"}
      strip => ["[process][name]"]
    }
    ### BEATS ###
    if [observer][type] == "beats" {
      grok {
        match => { "[log][original]" => "%{SYSLOGLINE}" }
      }
    }
  }
}
```

I'll update the repo, once you've tested and validate on pfSesne for both BSD/syslog.

**Comment by revere521** [comment]
I need to review all the updates over the lat week or so, and make sure i'm up to date - then I can try testing this.  probably over the weekend

**Comment by saroyaj** [comment]
![image](https://user-images.githubusercontent.com/7500783/103413077-10685900-4b46-11eb-9d53-2e4215c4d10b.png)

Looks like something is not right ?

**Comment by a3ilson** [comment]
@jsinix - can you provide additional context? I am unable to understand what you are referring too.

**Comment by a3ilson** [comment]
> I need to review all the updates over the lat week or so, and make sure i'm up to date - then I can try testing this. probably over the weekend

Thanks @revere521 and apologize for number of changes over the past month...but plan to limit/mitigate breaking changes which should just be tweaks and improvements.

**Comment by saroyaj** [comment]
Oh sorry for not explaininig. So the pfelk-firewall-* index should only show logs that are firewall related and not IDS. So looks like the parser is not working right ?

**Comment by a3ilson** [comment]
Gotcha - Well... expand the IDS entry and provide the original.message. 

- 02-types.conf adds the observer.name (user definable) 
- 05-apps.conf adds the respective tags based on the process.name
- 50-outputs.conf send to elastic based on tags and/or process.name
  - Suricata and snort and sent to elastic based on the process.name
  - Firewall entries are sent to elastic based on them not containing the following tags:
    - unbound, Suricata, snort, haproxy, and dhcp

I'll be able to assist with the original.message(s) from those IDS entries.

**Comment by a3ilson** [comment]
Issues captured in #246 and project [26](https://github.com/pfelk/pfelk/projects/26)
