### ISSUE TITLE
Question: PFSense->multiple logstash port parsing 

### ISSUE THREAD

**Issue by saroyaj** [pfelk/pfelk#244]
So looks like there are couple of ports open to handle different kind of logs(firewall, IDS etc). But pfsense doesn't have an option to selectively send logs to multiple IP/Port remote server. Am I missing something ?

**Comment by a3ilson** [comment]
By default the 01-inputs.conf listens on ports 5140, 5141, 5040, 5190 and 5044.  You may add/remove as needed for your setup.  

However, if you plan to utilize Suricata on pfSense, you'll be able to specify the remote IP:port with the Suricata settings (e.g. [Suricata on pfSense](https://github.com/pfelk/pfelk/wiki/How-To:-Suricata-on-pfSense)). I would suspect other pfSense plugins may also have settings to set remote logging elsewhere too, if desired. 

This also allows for multiple instances of logging. It also accommodate both pfSense and OPNsense as with OPNsense you may select what you want to send and which IP:port. However, if you're looking to close those additional ports, simply modify 01-inputs.conf, as desired, making sure you restart logstash after making any changes. 

Hope that helps.

**Comment by saroyaj** [comment]
Oh fantastic. Thank you
