### ISSUE TITLE
Suricata fields not mapped / OPNsense 19.7.4 

### ISSUE THREAD

**Issue by BeNeDeLuX** [pfelk/pfelk#25]
The Suricata fields are not mapped. I´m on OPNsense 19.7.4.
The Firewall logs are correct mapped and working fine. Here are two screenshots.
Used the git checkout from today (13.09.2019)

![suricata_fields](https://user-images.githubusercontent.com/1895086/64888235-bdc20f80-d66a-11e9-8c59-f2720c73042b.PNG)

OPNsense options:
![suricata_opnsense](https://user-images.githubusercontent.com/1895086/64888237-bdc20f80-d66a-11e9-8ce3-1405761137c8.PNG)

Is the new EVE Format a problem ? 
Please give me a hint if you need more informations.

Thanks for your help & time!

**Comment by a3ilson** [comment]
@BeNeDeLuX the current configuration will not parse the EVE format.  I'll add this to the list of improvements.  I'll address in the near future.  

Thanks!

**Comment by legoguy1000** [comment]
I use this for PFsense and have already added the appropriate logstash config below.

`if [message] =~ "\A\{.+\}\z" {
          json { 
		    source => "message"
			target => "[suricata][eve]"
		  }
}`

This checks if it matches a JSON format and the uses the logstash parser.  The target should be "root" but I am trying to get it to be in the ECS format

**Comment by legoguy1000** [comment]
THis should be closed, the other issue for the ECS fields fixes this. https://github.com/legoguy1000/pfelk/blob/master/12-suricata.conf#L6
