### ISSUE TITLE
Installation Failed (script method)

### ISSUE THREAD

**Issue by ghost** [pfelk/pfelk#253]
Got as fas as Logstash (why does logstash have to be so problematical) 
Tar report cannot be opened.
#####################################################################################################

# Installing Logstash...

# Downloading Logstash...
/tmp/logstash_7.10.1_flo.deb                                    100%[====================================================================================================================================================>] 337.07M  2.50MB/s    in 2m 17s  
# Successfully downloaded Logstash version 7.10.1! 

# Installing Logstash...
# Failed to install Logstash...

Failed to start logstash.service: Unit logstash.service not found.

#########################################################################

# An error occurred. Aborting script...
# Please open an issue (pfelk.3ilson.dev) on github!

# Creating support file...
# Support file has been created here: /tmp/pfELK_support.tar.gz 

root@buster:/home/counciller# systemctl status logstash
Unit logstash.service could not be found.
root@buster:/home/counciller# tar xvzf /tmp/pfELK_support.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
root@buster:/home/counciller# ls /tmp
hsperfdata_root  pfELK	pfELK_support.tar.gz  systemd-private-9733f0baaa5d4256b936ec70210bc072-elasticsearch.service-ezaxds  systemd-private-9733f0baaa5d4256b936ec70210bc072-systemd-timesyncd.service-gjssF0
root@buster:/home/counciller# cp  /tmp/pfELK_support.tar.gz .
root@buster:/home/counciller# ls -l
total 208
-rwxr-xr-x 1 counciller counciller  88807 Jan 10 14:10 pfelk-installer.sh
-rw-r--r-- 1 root       root       122880 Jan 10 14:24 pfELK_support.tar.gz
root@buster:/home/counciller# tar xzvf pfELK_support.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
root@buster:/home/counciller# 
[pfELK_support.tar.gz](https://github.com/pfelk/pfelk/files/5792735/pfELK_support.tar.gz)

**Comment by a3ilson** [comment]
Thanks and apologize that the install was not successful.  I assume Elasticsearch installed successfully? I am also curious if you received any warning regarding available memory? Based on the provided log, it appears your system has ~2GB of ram which is not enough and likely the reason for the aborted install <- I'll confirm via testing when time permits (at a later time).

RAM Usage:
- OS
- Elasticsearch (1GB minimum; highly recommended 4GB+)
- Logstash (1-2GB; recommended 4-8GB)
- Kibana (>1GB)

**Comment by ghost** [comment]
Hi

No messages regarding memory insufficient, actually if i recall it said memory was sufficient.
As I am doing this on a VM, I can allocate more memory (within reason), so would 4Gb suffice?
Also had issues with the Docker (which I am not too keen on), maybe the same issue.
I though there was a version somewhere without logstash, which has been a PIA (and actually prompted the move away from ELK to TIKS+Grafana)

**Comment by a3ilson** [comment]
Yes, 4GB would be the minimum (I would recommend more and assuming nothing else is consuming resources). I'll do some more testing on the memory checks - thanks!

This project relies on the Elastic Stack and largely logstash.  There are some linked repos that leverage Grafana and Azure but both of those (that I am aware of) also leverage logstash for log enrichment.

**Comment by a3ilson** [comment]
Alternatively, you could leverage beats but again not natively supported with this repo. However, Elastic has a number of supportive plugins, if you choose to go that route.

**Comment by ghost** [comment]
Hi

OK, will try more memory, 4G min 6G max. 
I use a Buster VM on the NAS, so it imports in about 3 minutes.
Will try the github script method.

**Comment by a3ilson** [comment]
Great - let me know if it works and then I'll carve out some time to improve the script when resources are unmet.

**Comment by ghost** [comment]
Hi

Installed ok, memory usage climbed in a step fashion to approx 5.5Gb

**Comment by a3ilson** [comment]
Issue resolved but new script issue revealed and captured in issue #254
