### ISSUE TITLE
Documentation: add pfsense unbound configuration to log queries

### ISSUE THREAD

**Issue by rpelissi** [pfelk/pfelk#255]
**Describe the bug**
So it's not a bug, this ticket is just to add in the documentation https://github.com/pfelk/pfelk/blob/master/install/configuration.md#unbound what is needed to have pfsense unbound log queries so we can see them in elasticsearch.
I will post a screenshot to this ticket but basically:
- pfSense / Services / DNS Resolver
- General Settings / Custom options
- Add the line "log-queries: yes"
- Save
You should then be able to see the queries in elasticsearch and the dashboard working for unbound

**To Reproduce**
* Have pfsense configured, dns resolver working
* Use pfelk script setup on debian 10

**Screenshots**
See attachment

**Firewall System (please complete the following information):**
 - pfSense 
 - 2.4.5-p1
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 
 **Installation method (manual, ansible-playbook, docker, script):**
Script
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 
 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 - Kibana logs (`journalctl -u kibana.service`)

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; 
 
![image](https://user-images.githubusercontent.com/385483/104510992-0ae52700-55ba-11eb-9a39-a0970e1bb0aa.png)

**Comment by a3ilson** [comment]
I do not run pfSense natively but will fire up a virtual instance and purse this amongst others.

Thanks for highlighting this enhancement

**Comment by a3ilson** [comment]
@rpelissi - This was previously resolved via issue #213 but I believe the intrusions were never incorporated.  Please give the following a try and if it works let us know - we'll add it back to the instructions.

1.  Navigate to **Services>>DNS Resolver** 
2.  Add the following line to the custom options:
```
server:
    log-queries: yes
........
* any other custom config options *
```
3. Navigate to **Services>>DNS Resolver>>Advance Settings**
4. Set **Log Level** to **Level 0: No Logging**

**Comment by revere521** [comment]
Apologies that this was a lapse, but i have been using this logging option for some time with no issues with Unbound DNS passing logs for the DNS enrichment and dashboard.

**Comment by rpelissi** [comment]
No worries! 👍 Perfect if all the info is there to help others.
I really appreciate your work, I think having some useful dashboard to monitor key components in your infra is a must for a lot of reasons. I have to build this by myself and put a lot of tears but now I am happy again because your solution rock!
I still try to build some grafana dashboard based on some elasticdata because I think it worth the try.
Thanks again for your work!

**Comment by a3ilson** [comment]
Great!  I'll update the configuration page and close this issue out.  As for Grafana - @b4b857f6ee built some based on this project and posted to their GitHub [here](https://github.com/b4b857f6ee/opnsense_grafana_dashboard)

Reference: https://github.com/pfelk/pfelk/blob/master/install/configuration.md#extras---optional

**Comment by a3ilson** [comment]
Instructions for sending Unbound logs with pfSense added [here](https://github.com/pfelk/pfelk/blob/master/install/configuration.md#eight-Unbound---optional)
