### ISSUE TITLE
pf, _grokparsefailure

### ISSUE THREAD

**Issue by apedance** [pfelk/pfelk#26]
I always get this message. Did setup like posted on page here.

**Comment by a3ilson** [comment]
Please provide the following:
(1) pfSense or OPNsense version
(2) What items you are sending via syslog (OPNsense: System==>Settins==>Looing | pfSense: Statu==>System Logs==Settings);  Provide what events are checked
(3) The full text of the message field within logstash
(4) Screenshot of logstash depicting the received logs
