### ISSUE TITLE
Dashboards not fully populating or not working at all

### ISSUE THREAD

**Issue by Sub-SH** [pfelk/pfelk#263]
**Describe the bug**
The dashboards are either not working at all or only partially populating with data. 

I tried my first initial install manually. After having issues, I wiped and started with a fresh OS install and used the script install. Same issues though.

**Screenshots**
https://imgur.com/a/vwjCKqH

**Firewall System (please complete the following information):**
 - pfSense 
 - 2.4.5-RELEASE-p1 (amd64)
 
**Operating System (please complete the following information):**
Linux 5.4.0-65-generic x86_64 (Ubuntu Server running on ESXi v6.5)
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
 
 **Installation method (manual, ansible-playbook, docker, script):**
Initially, I installed manually. Then wiped the VM and started fresh with script.
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components:
 - elasticsearch  7.10.1       amd64
 - logstash       1:7.10.1-1   amd64
 - kibana         7.10.1       amd64
 
 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)

```
[2021-02-07T22:18:19,267][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [.kibana-event-log-7.10.1-000001] from [{"phase":"hot","action":"unfollow","name":"open-follower-index"}] to [{"phase":"hot","action":"unfollow","name":"wait-for-yellow-step"}] in policy [kibana-event-log-policy]
[2021-02-07T22:18:19,279][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [ilm-history-3-000001] from [{"phase":"hot","action":"unfollow","name":"wait-for-yellow-step"}] to [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] in policy [ilm-history-ilm-policy]
[2021-02-07T22:18:19,291][INFO ][o.e.x.i.IndexLifecycleTransition] [pfelk] moving index [.kibana-event-log-7.10.1-000001] from [{"phase":"hot","action":"unfollow","name":"wait-for-yellow-step"}] to [{"phase":"hot","action":"rollover","name":"check-rollover-ready"}] in policy [kibana-event-log-policy]
[2021-02-07T22:23:54,971][INFO ][o.e.c.m.MetadataMappingService] [pfelk] [pfelk-firewall-000001/NHCJX9NGSFK8dW7MHD4OoQ] update_mapping [_doc]
[2021-02-07T22:23:55,014][INFO ][o.e.c.m.MetadataMappingService] [pfelk] [pfelk-dhcp-000001/xJLDolXgQ7GAgscjrOoF0g] update_mapping [_doc]
[2021-02-07T22:25:45,491][INFO ][o.e.c.m.MetadataMappingService] [pfelk] [pfelk-firewall-000001/NHCJX9NGSFK8dW7MHD4OoQ] update_mapping [_doc]
[2021-02-07T22:26:46,155][INFO ][o.e.c.m.MetadataMappingService] [pfelk] [pfelk-firewall-000001/NHCJX9NGSFK8dW7MHD4OoQ] update_mapping [_doc]
[2021-02-07T22:41:59,086][INFO ][o.e.c.m.MetadataMappingService] [pfelk] [pfelk-firewall-000001/NHCJX9NGSFK8dW7MHD4OoQ] update_mapping [_doc]
[2021-02-07T22:46:45,861][INFO ][o.e.c.m.MetadataMappingService] [pfelk] [pfelk-suricata-000001/5uk9S3OwRySn0FfZ2nyhTQ] update_mapping [_doc]
[2021-02-07T22:56:35,437][INFO ][o.e.c.m.MetadataMappingService] [pfelk] [pfelk-suricata-000001/5uk9S3OwRySn0FfZ2nyhTQ] update_mapping [_doc]
```

 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
```
 [2021-02-07T22:10:13,185][INFO ][logstash.inputs.udp      ][main][pfelk-2] Starting UDP listener {:address=>"0.0.0.0:5141"}
[2021-02-07T22:10:13,224][INFO ][logstash.inputs.udp      ][main][pfelk-1] Starting UDP listener {:address=>"0.0.0.0:5140"}
[2021-02-07T22:10:13,386][INFO ][logstash.inputs.udp      ][main][pfelk-haproxy] Starting UDP listener {:address=>"0.0.0.0:5190"}
[2021-02-07T22:10:13,478][INFO ][logstash.inputs.udp      ][main][pfelk-haproxy] UDP listener started {:address=>"0.0.0.0:5190", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2021-02-07T22:10:13,490][INFO ][logstash.inputs.udp      ][main][pfelk-2] UDP listener started {:address=>"0.0.0.0:5141", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2021-02-07T22:10:13,498][INFO ][logstash.inputs.udp      ][main][pfelk-1] UDP listener started {:address=>"0.0.0.0:5140", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2021-02-07T22:10:13,460][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2021-02-07T22:10:13,886][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2021-02-07T22:45:11,421][WARN ][logstash.outputs.elasticsearch][main][4f76e1ebbe328d8cc2c6a005bb5e2e57e04e1a80ea322768a71271254a248850] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"pfelk-firewall", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x4e9331f2>], :response=>{"index"=>{"_index"=>"pfelk-firewall-000001", "_type"=>"_doc", "_id"=>"niyrfncBJj6JtnjrmrJx", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [pf.app] tried to parse field [app] as object, but found a concrete value"}}}}
[2021-02-07T22:45:16,524][WARN ][logstash.outputs.elasticsearch][main][4f76e1ebbe328d8cc2c6a005bb5e2e57e04e1a80ea322768a71271254a248850] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"pfelk-firewall", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x4739bb9>], :response=>{"index"=>{"_index"=>"pfelk-firewall-000001", "_type"=>"_doc", "_id"=>"qiyrfncBJj6JtnjrrrJq", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"object mapping for [pf.app] tried to parse field [app] as object, but found a concrete value"}}}}
```
 - Kibana logs (`journalctl -u kibana.service`)

```
-- Logs begin at Sun 2021-02-07 21:49:28 UTC, end at Sun 2021-02-07 23:35:05 UTC. --
Feb 07 22:10:10 pfelk systemd[1]: Started Kibana.
Feb 07 22:10:13 pfelk systemd[1]: Stopping Kibana...
Feb 07 22:10:15 pfelk kibana[7102]: {"type":"log","@timestamp":"2021-02-07T22:10:15Z","tags":["info","plugins-service"]>
Feb 07 22:10:15 pfelk kibana[7102]: {"type":"log","@timestamp":"2021-02-07T22:10:15Z","tags":["info","plugins-service"]>
Feb 07 22:10:16 pfelk kibana[7102]: {"type":"log","@timestamp":"2021-02-07T22:10:16Z","tags":["warning","config","depre>
Feb 07 22:10:16 pfelk systemd[1]: kibana.service: Succeeded.
Feb 07 22:10:16 pfelk systemd[1]: Stopped Kibana.
Feb 07 22:10:16 pfelk systemd[1]: Started Kibana.
Feb 07 22:10:20 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:20Z","tags":["info","plugins-service"]>
Feb 07 22:10:20 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:20Z","tags":["info","plugins-service"]>
Feb 07 22:10:20 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:20Z","tags":["warning","config","depre>
Feb 07 22:10:21 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:21Z","tags":["info","plugins-system"],>
Feb 07 22:10:21 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:21Z","tags":["warning","plugins","secu>
Feb 07 22:10:21 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:21Z","tags":["warning","plugins","secu>
Feb 07 22:10:21 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:21Z","tags":["warning","plugins","encr>
Feb 07 22:10:21 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:21Z","tags":["warning","plugins","inge>
Feb 07 22:10:21 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:21Z","tags":["warning","plugins","repo>
Feb 07 22:10:21 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:21Z","tags":["info","plugins","reporti>
Feb 07 22:10:21 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:21Z","tags":["warning","plugins","acti>
Feb 07 22:10:21 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:21Z","tags":["warning","plugins","aler>
Feb 07 22:10:22 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:22Z","tags":["info","plugins","monitor>
Feb 07 22:10:22 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:22Z","tags":["info","savedobjects-serv>
Feb 07 22:10:22 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:22Z","tags":["info","savedobjects-serv>
Feb 07 22:10:22 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:22Z","tags":["info","savedobjects-serv>
Feb 07 22:10:22 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:22Z","tags":["info","savedobjects-serv>
Feb 07 22:10:22 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:22Z","tags":["info","savedobjects-serv>
Feb 07 22:10:22 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:22Z","tags":["info","savedobjects-serv>
Feb 07 22:10:22 pfelk kibana[7176]: {"type":"log","@timestamp":"2021-02-07T22:10:22Z","tags":["info","savedobjects-serv>
```

**Additional context**
Some aspects of the Suricata configuration in pfSense got a little confusing. For example, the overview config page specifies to set the EVE Output Type as "SYSLOG". However, in the in-depth wiki article, it says to do "File" https://imgur.com/a/3ta8lT6

Also, on my initial installation, I installed Syslog-ng for the first time. When I then wiped the OS and reinstalled via the script, I still had Syslog-ng installed on pfSense. Because of that, am I supposed to follow step 5 in the wiki article?

And one last, off-topic thing. I have a suggestion. It would be a very nice feature if the install script allowed me specify the directory for the ingested logs/data. My OS is on a small SSD, but I have another HDD mounted for data storage that I would like to save everything to. 

Anyways, thanks for this amazing project! You guys are awesome!

**Comment by a3ilson** [comment]
@subterminal - Thanks for highlighting some areas which need improvement and/or require attention. 

Based on the provided reference image, it appears that only the blocked  events are being logged.  There is an option within pfSense/OPNsense to log all events (i.e. blocked / passed) which will greatly enhance the visualizations.  Although this will provide greater detail, it all depends on what is needed/desired. The visualization with "Infinite..." simple mean there is no data.  This can often be remedied by increasing the time span from the defaulted 15m to a more generous amount but sometimes the events don't exist...depending on the size and configuration this will vary. 

Regarding the saved data, Kibana and Logstash have minimal writes but Elasticsearch will be the primary culprit for writing/reading logged events. The prescribed installation methods are indeed basic and refining is not explicitly covered within this repo.  There are simply too many variations to troubleshoot and support.  However, there are a few tweaks captured on the wiki page [here](https://github.com/pfelk/pfelk/wiki/How-To:-Performance) but I'll certainly add/update to include defining the saved location of the data but until then...[this](https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html) reference will provided the needed information to amend data path (e.g. amend the elasticsearch.yml and set the path for data)

**Comment by Sub-SH** [comment]
@a3ilson - Thanks for the reply! 

I think that I may have found the log all option that you were talking about. I enabled a log option under each and every individual firewall rule that I had, as well as found an option in the System Log -> Settings area.  https://imgur.com/a/cHaeMR8

That did help a bit, however, there was no impact on populating the Suricata dashboard. Ultimately, this project is meant to be part of a SIEM that I'm trying to get going for self-learning purposes, so the Suricata tables are a big one for me. And there are quite a few Suricata logs being produced (bottom part of the above imgur link). Also, here's my Suricata log settings just in case anything looks off: https://imgur.com/a/p3eHSTb

Anyways, thank you so much for taking the time to respond, as well as keeping this project going. You guys rock! Cheers :)

**Comment by a3ilson** [comment]
That is the correct setting, for sending all events (i.e. passed/blocked).  

Regarding your suricata configuration, did you setup following the [WiKi](https://github.com/pfelk/pfelk/wiki/How-To:-Suricata-on-pfSense)? Next, if you navigate to Kibana>>Discover and select suricata...are you seeing any events? I run this on a home lab and often need to generate traffic and enable more rules to obtain matches/events.

**Comment by Sub-SH** [comment]
@a3ilson - Yup, I followed the Wiki article. On step 4c, I omitted the entire line with failover as I don't have a redundant server.

I am seeing Suricata logs flow in under the Kibana>>Discover section: https://imgur.com/a/eKFWkvM 

However, my Suricata dashboard is completely empty. On occasion, I saw an entry at the very bottom under the Suricata Discover widget, but even then it didn't seem like it was parsing correctly as the fields weren't filled in properly (as seen in the dashboard screenshot of the original post).

**Comment by a3ilson** [comment]
The reference image is DHCP - can you expand the time parameters and include one of Suricata?

**Comment by Sub-SH** [comment]
@a3ilson - If you keep scrolling down on that initial screenshot, the Suricata dashboard is at the very bottom. It has some examples of Suricata logs showing up in the Discover widget.

Here's a new screenshot, however it doesn't show anything in it:
https://imgur.com/a/cXd3UKl

**Comment by a3ilson** [comment]
Gotcha - I was looking to see if Suricata Events are being received? Are there any entries via Kibana>>Discover (Suricata).

**Comment by Sub-SH** [comment]
Yup - https://imgur.com/a/eKFWkvM

**Comment by a3ilson** [comment]
> Yup - https://imgur.com/a/eKFWkvM

That is only showing DHCP events...and unable to scroll up/down

**Comment by Sub-SH** [comment]
Whoops, sorry. Here: https://imgur.com/a/ndvl1eQ

**Comment by a3ilson** [comment]
Great! 

Now can you expand one of those events (carrot to the right of the date) and provide?

or 

provide the contents of the original event

**Comment by Sub-SH** [comment]
Bouncing around at work on devices, so here's a screenshot from my phone. If you need something better, I'll be back at a computer soon...

https://ibb.co/wM3x9mc

**Comment by a3ilson** [comment]
Thanks!  Based on the provided reference, the log being received appears to be the syslog alerts which provide very little in comparison to the actual suricata log. However, it should be enough to populate the dashboard.

## Two issues here:
### 1️⃣ - Sending both the syslog alert and suricata log will depict a visualization but will also double the actual quantity of suricata events/logs
  - Suricata syslog events are those enriched via the pfelk.grok pattern
    - These typically only contain the `priority`, `rule.category`, `rule.description`, `rule.id`, `rule.uuid` and `rule.version` fields 
  - Suricata logs are typically in a json format which are enriched via the 05-apps.conf file 
    - ⚡ This is the preferred option as it contains all the details

⚠️ However both contain sufficient context to populate the dashboard...I'm current working to expand this

### 2️⃣ - The Suricata configuration was not properly configured and on my list to update the WiKi page.
  - [Step 4c](https://github.com/pfelk/pfelk/wiki/How-To:-Suricata-on-pfSense#step-4c) contains the following:
  ```
  {
     tcp("logstash.local"
     port(5141)
     failover( servers("192.168.0.10", "10.0.0.10") )
     );
  };
  ```
    - You omitted the failover line, which is optional but what did you input into your tcp and port lines?
      - The above would send the Suricata log file to host `logstash.local` via port `5141` utilizing `TCP`
      - pfelk is currently set/configured via 01-inputs.conf to received Suricata via two methods:
        - tcp via port 5040
        or
        - udp via port 5140 or 5141

## Recommendation: 
1️⃣ Do not send Suricata syslog events as these are also contained within the Suricata log file ([step 5](https://github.com/pfelk/pfelk/wiki/How-To:-Suricata-on-pfSense#step-5-optional))
2️⃣ Amend your configuration from step 4c to the following:
  ```
  {
     tcp("logstash.local"
     port(5040)
     );
  };
  ```
change `"logstash.local"` to where pfelk is installed (e.g. `"10.0.0.10"` or `"pfelk.local"`)

## To Do 
- [ ] Update the the Suricata WiKi Page
- [ ] Build out Suricata Syslog with filter to see one or the other (i.e. syslog or suricata)

**Comment by Sub-SH** [comment]
I made the changes, opting for an IP instead of hostname. Now,I don't seem to be getting any ingested data under Kibana>>Discover. And there are Suricata logs flowing in pfSense.

Do I need to make supporting changes in Syslogng (https://imgur.com/a/qbXu9V4) or anywhere else?

**Comment by a3ilson** [comment]
I am running OPNsense and just going off my notes from a prior issue. The configuration within syslog-ng was ticking the "Select this option to enable syslog-ng" those other fields highlighted were not changed/amended.  What was the Default port set to? I do not believe that needs to be set since we are using syslog-ng to send the suricata file.

**Comment by Sub-SH** [comment]
I don't recall ever changing those values, so they might currently be default. However, I think you're right and that they don't matter.

I was under SysLog-NG>>Log Viewer and saw these logs: https://imgur.com/a/9m16MKC

So, as best as I can interpret, SysLog-NG has an established connection with the server and is trying to output stuff. Perhaps the server isn't happy with the protocol or port?

**Comment by Sub-SH** [comment]
It's working. Minor oversight on a setting on my end. Thank you so much for both the support and this project!

**Comment by a3ilson** [comment]
Excellent and glad it was resolved!
