### ISSUE TITLE
How to define index size?

### ISSUE THREAD

**Issue by themendas** [pfelk/pfelk#265]
I see that it is defined for two months of time so that it goes overwriting data.

How can I define a maximum index size?

**Comment by a3ilson** [comment]
@themendas 

The default ILM policy will not overwrite the data, it simply moves the index from a hot to warm and then cold stage.

- Hot Phase 0-179 days or 5GB which ever occurs first
- Warm Phase on rollover if it doesn't meet the threshold for cold phase (i.e. 5GB prior to 179 days)
- Cold Phase 180-364 
- Delete 365

Navigate to Stack Management>>Index Lifecycle Policies and select the desired ILM policy. The policy will be separated by the various phases. Adjust as desired making note that with every change/revision, the versioning will increase by 1. The only phase which may be adjusted for maximum size is the hot phase which is located under the advanced settings.

Elasticsearch Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html

**Comment by themendas** [comment]
Hi,

Sure, but each time a new index is created, how can I select all the new issues with the policy?
![2021-02-17 22_02_52-Index Management - Elastic y 4 páginas más - Trabajo_ Microsoft​ Edge](https://user-images.githubusercontent.com/76823001/108267934-22d93900-716c-11eb-9d72-aa697e6bce3d.png)

![2021-02-17 22_05_40-Index Lifecycle Policies - Elastic y 4 páginas más - Trabajo_ Microsoft​ Edge](https://user-images.githubusercontent.com/76823001/108268083-59af4f00-716c-11eb-849b-6a74ca955ba3.png)

**Comment by a3ilson** [comment]
The ILM policy applies to all indeed created by pfelk.  Amend the pfelk
ILM will be applied to all indexes.  If you have other indexes, you’ll need
to define an ILM policy for those.

**Comment by themendas** [comment]
You mean the ilm-history-ilm-policy?

As you can see in the images, the policy does not have any linked index, and if you see the size of the index it is not being applied ...

What I can be doing wrong?

**Comment by a3ilson** [comment]
@themendas - ILM is not being applied to your indices.

Check the 50-outputs.conf file. The scripted install provides an option to enable or disable ILM but this must be done manually if not utilizing the scripted installer.


You'll want to uncomment all `#ILM#` lines. Once you've amended the 50-outputs.conf file, you'll need to restart Logstash for the changes to take affect.


Reference: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-ecs_compatibility

**Comment by themendas** [comment]
ok, I saw it. Thanks a lot!
