### ISSUE TITLE
DOC: script-installation-method point to the wrong script

### ISSUE THREAD

**Issue by rpelissi** [pfelk/pfelk#268]
**Describe the bug**
If you go with the manual installation using the script and follow the guide here https://github.com/pfelk/pfelk#script-installation-method, the link to download the script is 
$ wget https://raw.githubusercontent.com/pfelk/pfelk/master/etc/pfelk/scripts/pfelk-dashboard-installer.sh
but it should be
$ wget https://raw.githubusercontent.com/pfelk/pfelk/master/etc/pfelk/scripts/pfelk-installer.sh

**To Reproduce**
1. Follow the documentation for manual install
2. Use the link provided
3. Get confused by the script behaviour
4. Cry because you fail

**Comment by a3ilson** [comment]
Thanks! The issue/oversight was corrected and updated.
