### ISSUE TITLE
OPNSense Suricata issues

### ISSUE THREAD

**Issue by B3DTech** [pfelk/pfelk#271]
After having issue after issue installing pfelk using your pfelk-install.sh script on a clean Ubuntu 20.04 install (Logstash ports not open first time, dashboards not installed in Kibana), I finally have firewall, DHCP and Unbound data flowing into ELK, but the Suricata data isn't flowing into ELK.  Looking at OPNSense, I'm seeing events being logged.  The index is empty, which I'm guessing is why the dashboard shows Infinite Extent for field Y1.

OPNsense 21.1.1

**Comment by B3DTech** [comment]
Not sure what changed but data is flowing.  On to Grafana dashboards.

**Comment by a3ilson** [comment]
Glad it started working.
