### ISSUE TITLE
OPNsense Snort - Infinite extent for field "y1": [Infinity, -Infinity]

### ISSUE THREAD

**Issue by squirrelboot** [pfelk/pfelk#274]
Running now OPNsense 21.1.2-amd64. Had some issues getting Suricata working, but it seems to be going. 
Now however, I can't seem to get any snort information.

Infinite extent for field "y1": [Infinity, -Infinity]

I did the tricks from here (https://github.com/pfelk/pfelk/issues/266). 
Used the v20.2-Snort.ndjson you posted from ~22 hours ago. 

I was hoping we might figure out what the issue is.
EVE output is setup, etc. I followed all the configuration instructions. 
This is from a scripted installation on a fresh clean Debian 10 (netist).
Linux pfelk 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

Firewall and Suricata are working at least :) 

Let me know what I can provide. 

Thanks 👍

**Comment by a3ilson** [comment]
@squirrelboot - Need additional claicifation.  You're running OPNsense which to my understanding does not have snort as an optional package/plugin. The only snort related package is the os-intrusion-detection-content-snort-vrt (i.e. snort ruleset).  

The script installer does install all the current dashboards but to populate, you'll need the associated data/logs.

**Comment by squirrelboot** [comment]
My mistake in understanding the intrusion protection system. I had some thought that the os-intrusion-detection-content-snort-vrt package was enabling snort, or would then populate the snort dashboard included by pfelk. I realize now that Suricata is the IDS in use and not Snort. Just using the snort rules.
