### ISSUE TITLE
Rotate ELK logs to keep 2 weeks worth of data

### ISSUE THREAD

**Issue by myrsecurity** [pfelk/pfelk#275]
Hi guys, thanks for keeping the project up 

I was wondering what is the ELK configuration needed to keep 2 weeks of data, only. We dont want to hot store more time, the Elastic backend gets filled up very quickly and beyond 2 weeks is useless, at least for our use case. 

I tried few Elastic retention configurations being unable to hit the right button. 

Thank you!

**Comment by a3ilson** [comment]
@myrsecurity - This would be accomplished within the Index Lifecycle Policies.

1.  Navigate to Stack Management>>Lifecycle Management 
2. Create a new policy (upper right) and or amend existing policy
3. Once you have configured your policy (i.e. defined your parameters), save as new policy
4. You should now see a list of index lifecycle policies, click on "actions" and add policy to the specified index template

**Comment by a3ilson** [comment]
Let me know if you need further assistance getting ILM configured/setup.
