### ISSUE TITLE
cant parse the data in firewall

### ISSUE THREAD

**Issue by keshif** [pfelk/pfelk#279]
pfsense 2.5
ubuntu 20.04
sudo tcpdump -vvv -A -i any port 5140 can see the data 
but dashboard firewall cant parse it

**Comment by gokhansezen** [comment]
pfsense 2.5
Ubuntu 20.4.2 LTS
![Screenshot_20210301-151800~3](https://user-images.githubusercontent.com/16643176/109496378-a0bd0e80-7aa1-11eb-8df8-77cc1775e65f.png)

**Comment by gokhansezen** [comment]
![Screenshot_20210301-155916~2](https://user-images.githubusercontent.com/16643176/109500413-4a52ce80-7aa7-11eb-8491-298fff09d58c.png)
![Screenshot_20210301-152500](https://user-images.githubusercontent.com/16643176/109497760-9734a600-7aa3-11eb-96f4-675ae8f20870.jpg)

**Comment by a3ilson** [comment]
@keshif & @gokhansezen - Please check your logstash log. I suspect the issue was the result of an added grok pattern and revision to pfelk.grok (i.e. openvpn grok patterns were removed and an openvpn.grok file was created).

Logstash is likely not running as it is unable to define the openvpn grok pattern as a result of the changes noted above. 

Solution:
download the openvpn.grok file and restart logstash
- `sudo wget https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/patterns/openvpn.grok -P /etc/pfelk/patterns/`
- `systemctl restart logstash.service`


Please check back to confirm the proposed solution reminded the issue. Updates were made in the manual install instructions and script.

**Comment by EverWin42O** [comment]
Hi a3ilson,

Facing same issue, above fix didn't worked for me.

(pfSense 2.5.0 & ubuntu 20.04), it was working before updating with script v20.3a.

**Comment by a3ilson** [comment]
Awe shucks... can you run the error script and provide the associated log?

**Comment by EverWin42O** [comment]
[error.pfelk.log](https://github.com/pfelk/pfelk/files/6063185/error.pfelk.log)

Thanks for your quick response.
PFA.

**Comment by a3ilson** [comment]
> [error.pfelk.log](https://github.com/pfelk/pfelk/files/6063185/error.pfelk.log)
> 
> Thanks for your quick response.
> PFA.

Thanks! Found the issue..will fix here in a few

**Comment by a3ilson** [comment]
Redownload the [openvpn.grok](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/patterns/openvpn.grok) and restart logstash.

🐛 The issue or error: 
> #<Grok::PatternError: pattern %{OPENVPN_MGT} not defined>, 

🔧 The fix:
Amended Line 42 of [openvpn.grok](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/patterns/openvpn.grok) from:
> OPENVPN_MGT(%{OPENVPN_MGT_CLIENT}|%{OPENVPN_MGT_CMD})

to:
> OPENVPN_MGT (%{OPENVPN_MGT_CLIENT}|%{OPENVPN_MGT_CMD})

added a space between OPENVPN_MGT and the applied GROK

**Comment by EverWin42O** [comment]
updated openvpn.grok and restart logstash. Still no logs displayed in Discovery > firewall, suricata, dhcp (none).
[error.pfelk.log](https://github.com/pfelk/pfelk/files/6063433/error.pfelk.log)

**Comment by a3ilson** [comment]
> updated openvpn.grok and restart logstash. Still no logs displayed in Discovery > firewall, suricata, dhcp (none).
> [error.pfelk.log](https://github.com/pfelk/pfelk/files/6063433/error.pfelk.log)

Thanks @EverWin42O !

Had another typo (e.g. OEPNVPN_OTHER vs OPENVPN_OTHER on line 52).

Reload [openvpn.grok](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/patterns/openvpn.grok) and restart Logstash.

**Comment by gokhansezen** [comment]
It's the same with me :(

**Comment by EverWin42O** [comment]
Updated, Didn't worked.
[error.pfelk.log](https://github.com/pfelk/pfelk/files/6063509/error.pfelk.log)

**Comment by a3ilson** [comment]
> Updated, Didn't worked.
> [error.pfelk.log](https://github.com/pfelk/pfelk/files/6063509/error.pfelk.log)

No errors were noted...I would recommend purging (deleting) your indices then check to see if they are recreated and the document counts increase (logs).

**Comment by EverWin42O** [comment]
Tried deleting; it got created after reboot with yellow mark. Still no data.

**Comment by gokhansezen** [comment]
DHCPD DHCP(%{DHCPD_DISCOVER}|%{DHCPD_DUPLICATE}|%{DHCPD_OFF>
![Screenshot_20210301-212715](https://user-images.githubusercontent.com/16643176/109541717-2ad29a80-7ad5-11eb-86dd-524d858b114b.png)

**Comment by a3ilson** [comment]
@EverWin42O - I rebuilt my instance (loaded a snapshot of Ubuntu and installed pfelk)... everything appears to be working. Can you check to see if Logstash is logging any of your logs (this would be denoted within the index [i.e. document count])

**Comment by a3ilson** [comment]
> DHCPD DHCP(%{DHCPD_DISCOVER}|%{DHCPD_DUPLICATE}|%{DHCPD_OFF>
> ![Screenshot_20210301-212715](https://user-images.githubusercontent.com/16643176/109541717-2ad29a80-7ad5-11eb-86dd-524d858b114b.png)

@gokhansezen - please elaborate and/or provide context

**Comment by a3ilson** [comment]
@EverWin42O - what are you running (pfSense or OPNsense) and what version?

**Comment by EverWin42O** [comment]
pfsense 2.5.0

**Comment by a3ilson** [comment]
@EverWin42O - Let's give this a try:

Within pfSense try changing the output of your syslog (i.e. from BSD to Syslog or vice versa). The format was recently troubleshoot (#246) and was testing/working. However, if nothing is being logged and no errors are present, this would be the most logical issue.

1. Change pfSense logging output
  - Does problem still exist?

**Comment by EverWin42O** [comment]
Yes, Tried that switching BSD to Syslog and vice versa.
Tried clean installation and auto script.
clean ubuntu install and doing manual installation.

**Comment by a3ilson** [comment]
> Yes, Tried that switching BSD to Syslog and vice versa.
> Tried clean installation and auto script.
> clean ubuntu install and doing manual installation.

Alright, let me know if it works out.  If you still have the same results, I'd be curious to your logging and could further troubleshoot/assist.  Just provide a sanitized (amend IPs as needed/desired) by providing a sample of logs via tcpdump (`sudo tcpdump -vvv -A -i any port 5140`)

**Comment by EverWin42O** [comment]
Thank you so much for your support. Finally it started working. auto script worked perfectly. pfsense BSD log works.

**Comment by a3ilson** [comment]
@gokhansezen & @keshif - After updating the openvpn.grok file, let me know if you still have the same issue.

@EverWin42O - thanks for troubleshooting and providing the necessary logs to identify and correct.

**Comment by keshif** [comment]
firewall and ubound started working ! 
Thanks

**Comment by gokhansezen** [comment]
Many many thanks @a3ilson
Now automated install script running is perfectly.
