### ISSUE TITLE
World Heat Map field - Could not locate that index-pattern-field (id: geoip.location)

### ISSUE THREAD

**Issue by wylde780** [pfelk/pfelk#28]
**Describe the bug**
After following all of the instructions in the README and installing the searches, visualizations, and dashboard.json files. When I view the World Heat Map I'm presented with this error. Along with being prompted to try and fix it. Top Country word graph worlds without issue and i can see geo location fields being populated on the docs themselves. 

using logstash 7.3 and kibana 7.2 

Thank for this project it is helping me understand logstash processing much better.

**Comment by a3ilson** [comment]
wylde780,

The provided JSON files are a few iterations old.  I’ll update with new
iterations later this week.

**Comment by wylde780** [comment]
a3ilson, 

Thank you very much

**Comment by a3ilson** [comment]
wylde780,

I created a new dashboard for v7.3 which is located here (https://github.com/a3ilson/pfelk/blob/master/JSON/pf%2BELK(v7.3).ndjson)

Simply download and import within Kibana (Management--> Reporting)

**Comment by wylde780** [comment]
Awesome turn around time on this issue, but the json file does not pass json validation. I've tried encasing it in [ ]'s but that did not help.

**Comment by a3ilson** [comment]
wylde780,

Save the file and upload to Kibana (goto Management --> Reporting and upload the referenced file). Once uploaded it should populate 1xDashboard, 1xSearch and multiple visualizations.

**Comment by wylde780** [comment]
A3ilson, 

Thanks for this info however with my ECE install of Kibana 7.3 I do not see an upload button on the Management -> Reporting page .. I must be doing something else wrong or lack a dedicated Reporting server? I'll continue to troubleshoot things. 

For a visual guide, view the YouTube video below:
https://youtu.be/iqhuQSdbXlU

Thanks again

**Comment by wylde780** [comment]
Yes, I've tried importing it into the saved objects but the import saved objects process states "Sorry, there was an error the file could not be processed ". I was successful importing your previous json saved objects, but this new file I've tried with 2 different kibana 7.2 instances and it refuses to import.

**Comment by a3ilson** [comment]
Any consideration regarding an upgrade to v7.3+?

**Comment by wylde780** [comment]
Just upgraded everything and sadly the result remains the same. 

![image](https://user-images.githubusercontent.com/2114461/65560072-76554200-defa-11e9-8cdd-7dae4a389970.png)

**Comment by a3ilson** [comment]
Remove the .txt extension from the file and try again.

**Comment by wylde780** [comment]
OH damn .. i'll hang my head in shame for a while now. Sorry for wasting so much of your time and thank you for the help.

**Comment by a3ilson** [comment]
No worries,  did it work out?

**Comment by wylde780** [comment]
Yeah its all working quite well. Thank you very much
