### ISSUE TITLE
PFSENSE SURICATA problems

### ISSUE THREAD

**Issue by mrahmatellah** [pfelk/pfelk#287]
Hello,

I have done the same steps as you descibed (https://github.com/pfelk/pfelk/blob/main/install/configuration.md),

FIREWALL DHCP UNBOUNd HAPROXY work but suricata don't 

EVE Syslog Output Facility: AUTH
EVE Syslog Output Priority: NOTICE

can't found this 2 line on suricata

![image](https://user-images.githubusercontent.com/33620058/112151947-11a7a000-8be2-11eb-8c5e-2f5ee85d937e.png)

(PFSENSE PELK)

**Comment by revere521** [comment]
have a look at #276

Also verify the suricata config here https://github.com/pfelk/pfelk/blob/main/install/configuration.md#four-suricata---optional and here https://github.com/pfelk/pfelk/wiki/How-To:-Suricata-on-pfSense

**Comment by mrahmatellah** [comment]
updates:

I change the port of Step 4c (from 5141) to  5040 ( as mentionned on /etc/pfelk/conf.d/01-inputs.conf)
id => "pfelk-suricata"
type ....
port => 5040 (!!!)


after this modification, event coming ... so if anyone meet the same problem be sure that you have tyhe same port on the 2 configuration
