### ISSUE TITLE
Configure Elasticsearch for access from outside

### ISSUE THREAD

**Issue by nick2000713** [pfelk/pfelk#289]
Hello
I am currently trying to configure pfelk to be able to display it in grafana. I thought I would just enter in the elasticsearch.yml file: network.host: 0.0.0.0 and http.port: 9200 and then it would be done.But now I get an error. Do I have to set anything else or why is this not working. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

![Error](https://user-images.githubusercontent.com/81333562/113033645-86a24900-9191-11eb-978f-e25de8a399b0.PNG)
![Config](https://user-images.githubusercontent.com/81333562/113033932-d719a680-9191-11eb-8d81-b1aef1fe7a9a.PNG)
)

**Comment by a3ilson** [comment]
@nick2000713 

If you run through the install method (script or manual) you can add Grafana.  Although it is not natively supported on this repo, it is referenced and obvious works well.

@b4b857f6ee has a repo that leverages pfelk for Grafana which is referenced in [step 8](https://github.com/pfelk/pfelk/blob/main/install/configuration.md#a-grafana-dashborads-externally-supported) of the configuration page or you can access directly here: https://github.com/b4b857f6ee/opnsense_grafana_dashboard

**Comment by a3ilson** [comment]
No response
