### ISSUE TITLE
GeoIP/MAXMind install in wrong directory

### ISSUE THREAD

**Issue by gauthig** [pfelk/pfelk#290]
When running the pfelk-installer.sh the following error is generated after entering MAXmind account/key
**error retrieving updates: error creating database writer for GeoLite2-Country: database directory is not available: stat /var/lib/GeoIP: no such file or directory**

GeoIP directory defaults have changed to **/usr/share/GeoIP**

20.04.2 LTS (Focal Fossa)
geoipupdate 4.6.0
Not sure if same directory change of the geoipupdate package is on other debian and ubuntu releases
Also, did clean 20.04 install ran apt install geoipupdate to verify and yes install it in /usr/share/GeoIP
Uninstalled it and let the pfelk-installer.sh install geoipupdate - same results

The latest version of geoipupdate (4.6.0) in github shows the following contents
 _dpkg --contents  geoipupdate_4.6.0_linux_386.deb
drwxr-xr-x 0/0               0 2020-12-14 18:05 ./usr/
drwxr-xr-x 0/0               0 2020-12-14 18:05 ./usr/share/
drwxr-xr-x 0/0               0 2020-12-14 18:05 ./usr/share/GeoIP/
drwxr-xr-x 0/0               0 2020-12-14 18:05 ./usr/bin/
-rwxr-xr-x 0/0         4345856 2020-12-14 18:05 ./usr/bin/geoipupdate
drwxr-xr-x 0/0               0 2020-12-14 18:05 ./usr/share/doc/
drwxr-xr-x 0/0               0 2020-12-14 18:05 ./usr/share/doc/geoipupdate/
-rw-r--r-- 0/0            4876 2020-12-14 18:05 ./usr/share/doc/geoipupdate/CHANGELOG.md
-rw-r--r-- 0/0            1818 2020-12-14 18:05 ./usr/share/doc/geoipupdate/GeoIP.conf
-rw-r--r-- 0/0            2318 2020-12-14 18:05 ./usr/share/doc/geoipupdate/GeoIP.conf.md
-rw-r--r-- 0/0           11358 2020-12-14 18:05 ./usr/share/doc/geoipupdate/LICENSE-APACHE
-rw-r--r-- 0/0            1023 2020-12-14 18:05 ./usr/share/doc/geoipupdate/LICENSE-MIT
-rw-r--r-- 0/0            4532 2020-12-14 18:05 ./usr/share/doc/geoipupdate/README.md
-rw-r--r-- 0/0            2167 2020-12-14 18:05 ./usr/share/doc/geoipupdate/geoipupdate.md
drwxr-xr-x 0/0               0 2020-12-14 18:05 ./etc/
-rw-r--r-- 0/0            1818 2020-12-14 18:05 ./etc/GeoIP.conf_

**Potential fix:**
pfelk-installer-sh lines to change from **/var/lib/GeoIP**   to **/usr/share/GeoIP**
657
666
1076
1081

**Comment by a3ilson** [comment]
Thanks for highlighting this issue. This works for Debian but breaks Ubuntu installs...I am contemplating installing within the pfelk path which should work for both Debian and Ubuntu instances.

Let me make that change, test on both Debian and Ubuntu and update. It may be a little bit as I am a bit consumed with work and course work but should get around to it within a week or so.

**Comment by gauthig** [comment]
Great ideal to put everything into your own configuration structure.

**Comment by gauthig** [comment]
You are probably aware of this but just wanted to add it - 30-geoip.conf also needs updated to you new directory structure.

**Comment by a3ilson** [comment]
MaxMind GeoIP install location and cron job updated from `/var/lib/...` to `/etc/pfelk/GeoIP/`
