### ISSUE TITLE
Stray logs showing up in pfelk-firewall-*

### ISSUE THREAD

**Issue by ightnapovial** [pfelk/pfelk#295]
Not sure if this is expected behavior or not; I didn't see any existing issues that seem to relate to the behavior I'm seeing.

I noticed that in Kibana > discover > pfelk-firewall-* I am getting ntpd and dhcp events in addition to expected firewall events. This is on a stock installation of pfelk using the install script with logs coming from pfsense 2.5 shipping "everything" to pfelk.

I realize this isn't a huge amount of information to go on, but I'm not sure which configs/ settings would be helpful here. Happy to provide any additional information needed.

**Comment by a3ilson** [comment]
@ightnapovial 

Thanks for the feedback. I am utilizing OPNsense with native syslog-ng for remote logging which allows me to select the processes to send via syslog-ng. I was surprised that pfSense 2.5 didn't migrate to a native syslog-ng for remote logging.  

Anyways we can go about it one of two ways:
1. If you do not need or desire these logs, they can be dropped via [45-cleanup.conf](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/45-cleanup.conf)
  - You'll need to uncommit lines 11-13
  - You'll need to update line 11 with the process id (process.pid) that you desire to drop
2. Possibly filter only firewall logs while indexing all others to a separate index 
  - Would you mind providing a handful of these logs entries?
    - I'll see if I can filter them into another index (all others) cleaning up and scoping the firewall logs as firewall only

**Comment by ightnapovial** [comment]
Yeah no problem. Do you want the logs as they appear in Kibana or like a pcap?

**Comment by a3ilson** [comment]
Either works but if extracting from Kibana, please include just the raw text of the 'event.original' fields pertaining to non-firewall events.

**Comment by ightnapovial** [comment]
DHCP example (hostname and address redacted):
`<190>Apr 11 10:58:32 dhcpd[50712]: DHCPREQUEST for XXX.XXX.XXX.XXX from 7e:b4:26:ac:61:5c (HOSTNAME) via em1`

NTPD example (address redacted):
`<102>Apr 11 09:34:11 ntpd[56010]: 78.46.53.8 local addr XXX.XXX.XXX.XXX -> <null>`

**Comment by a3ilson** [comment]
Thanks!

NTPD is defined by 05-apps.conf but there is no reference GROK pattern. 

DHCP is defined by 05-apps.conf and there is a corresponding GROK pattern which should parse those logs out and index within the DHCP index.  However, after reviewing...it is also index in the firewall index due to the multi tag containing `firewall, dhcp, dhcpdv4`

Let me fix this...

**Comment by a3ilson** [comment]
Download and update both the 05-apps.conf and 50-outputs.conf. Once downloaded, restart logstash and those stray logs will not be included within the firewall index going forward.

Once confirmed, please close this issue.

**Comment by ightnapovial** [comment]
Well, I'm not getting dhcp or ntp logs in the firewall index, but I'm not getting firewall logs either and dhcp logs arent showing up in that index either. 

I deleted the old conf files and downloaded the new ones, restarted logstash and rebooted the vm just to be sure.

**Comment by ightnapovial** [comment]
> Well, I'm not getting dhcp or ntp logs in the firewall index, but I'm not getting firewall logs either and dhcp logs arent showing up in that index either.
> 
> I deleted the old conf files and downloaded the new ones, restarted logstash and rebooted the vm just to be sure.

To add, reverting to the previous conf files reverts log behavior (where DHCP goes into the firewall index).

**Comment by a3ilson** [comment]
I just updated and tested with the updated 05-apps.conf and 50-outputs.conf. Everything is working - give it another attempt. If it doesn't work, check the logstash logs to make sure something else isn't causing issues.

**Comment by ightnapovial** [comment]
Tested on another vm and the new confs work as intended so issue must be on my my end.

@a3ilson thanks a ton for the quick turnaround on this! I would have been excited to have a solution this week, nevermind same-day.
