### ISSUE TITLE
Maxmind download fails due to missing directory.

### ISSUE THREAD

**Issue by ightnapovial** [pfelk/pfelk#296]
**Describe the bug**
On Ubuntu 20.04 base install, installer script fails to download MaxMind databases due to the destination directory (/etc/pfelk/GeoIP) not existing yet. Installer script later notes that the db's can't be found and reverts to elastic geoip.

**To Reproduce**
 - Run installer script selecting MaxMind geoip option with valid credentials.
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`): Ubuntu 20.04.2 LTS
 
 **Installation method (manual, ansible-playbook, docker, script):**
Install script 

**Additional context**

Running the geoipupdate command manually without the destination folder being created yet fails:
```
$ geoipupdate -d /etc/pfelk/GeoIP
error retrieving updates: error creating database writer for GeoLite2-Country: database directory is not available: stat /etc/pfelk/GeoIP: no such file or directory
```
After creating the directory manually, the command completes without issue.

#290

**Comment by ightnapovial** [comment]
On a fresh VM, confirmed creating the /etc/pfelk/GeoIP directory before running the installer allows the MaxMind option to complete as intended- script finds the downloaded dbs and does not revert to elastic.

**Comment by a3ilson** [comment]
Updated/fixed the script.
