### ISSUE TITLE
integrate WAZUH on PFELK ?

### ISSUE THREAD

**Issue by mrahmatellah** [pfelk/pfelk#300]
hello @a3ilson ,

i think that to consolidate the system (PFELK) you can add wazuh on it,
by that you will centralized pfsense log but also if it's a needy to add a lot of information from other servers (linux windows and other) by wazuh (server and agent), to have one big and powerfull system on a home lab or company ...

**Comment by a3ilson** [comment]
Not sure what you are asking here...Wazuh can do what pfelk does (e.g. centralized logging) but pfelk does not have the capabilities of Wazuh. The benefit pfelk has is the customization but Wazuh is a phenomenal alternative.

I believe what your asking is a solution to your other issues [here](https://github.com/wazuh/wazuh/issues/3454) and [here](https://github.com/wazuh/wazuh/issues/8235) where it appears you area already utilizing Wazuh but having difficulties parsing pfSense logs. I would offer the following suggestions:
- Leverage logstash to enrich the logs to meet Wazuh requirements 
- Change your logging application
  - pfSense 2.5.0 logging was a huge let down as they are natively supporting the legacy syslog
  - Consider installing and utilizing syslog-ng
    - you may still need to leverage Logstash to enrich the logs for Wazuh to recognize them

Local and centralized logging are recommended but logging solutions vary and dependent upon various parameters.
