### ISSUE TITLE
Add how to configure syslog-ng on PFsense to send to pfELK server (as apposed to using the default syslog)

### ISSUE THREAD

**Issue by linuxer0x42** [pfelk/pfelk#313]
**Is your feature request related to a problem? Please describe.**
My problem is that there is no guide in the wiki that shows how to setup syslog-ng in PFsense to send to a pfELK server. There is the Suricata guide but if there was one for this it would make it easier to setup.

**Describe the solution you'd like**
A page in the wiki on how to setup syslog-ng to send logs to a syslog server.

**Describe alternatives you've considered**
Using the Suricata syslog-ng guide.

**Additional context**
Specifically, how to setup source, log and destination objects in syslog-ng.
If @a3ilson does not have PFsense, I can provide screenshots that could go into the wiki if needed, since I am running PFsense currently.

**Comment by a3ilson** [comment]
@yusi1 - Thanks and you are welcome to provide screenshots and instructions on syslog-ng for pfSense.
