### ISSUE TITLE
[WIKI] How To: MaxMind via GeoIP with pfELK

### ISSUE THREAD

**Issue by ShagoY** [pfelk/pfelk#317]
Hello Andrew,

I just noticed some errors in the Maxmind wiki.

Deletion of :

- Modify line 18 as follows:
```DatabaseDirectory /var/lib/GeoIP/```

I think it would be better to leave the original folder ```/usr/share/GeoIP``` as other applications also use the original path.

I will add in the section "pfELK with MaxMind" :
```ln -s /usr/share/GeoIP /etc/pfelk/GeoIP```

This will allow to stay compatible with 30-geoip.conf without asking for any modification.

Also there is a typo in the command :
```--systemctl restart Logstash.service```
```++systemctl restart logstash.service```

**Comment by a3ilson** [comment]
Thanks!

- [x] Updated the typo
- [x] DatabaseDirectory
-- Will need to confirm this works with both Debian and Ubuntu
- [x] Symbolic Link
-- Will need to confirm this works with both Debian and Ubuntu

**Comment by a3ilson** [comment]
@ShagoY - I agree and feel free to test and submit a pull request otherwise it'll be a few weeks before I get around to it.

**Comment by a3ilson** [comment]
@ShagoY - I updated the Wiki to work with the current build.  As for the original path, Ubuntu and Debian install MaxMind in different locations.  I recall utilizing the default path before which resulted in numerous issues as a result of various Linux installations.

**Comment by a3ilson** [comment]
Updated to default install location of GeoIP (/usr/share/GeoIP)
