### ISSUE TITLE
TrueNas core jail integration

### ISSUE THREAD

**Issue by coldbootinitheart** [pfelk/pfelk#318]
Currently getting pfelk to run on TrueNas core jail is a major pain in the ass. I haven't yet managed to get it succesfully working just because it requires so much work getting it up on one machine let alone multiple, so I didn't bother.

I know this is asking too much but if there is enough interest can pfelk officially support Truenas jails?

Alternatively if you guys could help me get started on running pfelk on TrueNas, it would be awesome!

**Comment by a3ilson** [comment]
A Docker instance would be the best to get this working. Unfortunately, I do not use TrueNAS but hopefully someone out there has crossed this bridge as I'd be happy to help where possible.
