### ISSUE TITLE
rollover_alias and index templates that cover multiple patterns

### ISSUE THREAD

**Issue by kingtat** [pfelk/pfelk#322]
I recently upgraded pfelk & my elk stack and I'm struggling with ILM second time round. I've followed the directions re enabling ILM.
Despite uncommenting the ILM fields, I find I must still manually assign an ILM policy and rollover_alias to related index templates in Kibana Stack management.
I believe this is by design. Template push from logstash is now disabled. I haven't tried enabling it either. But does this not make the `ilm-policy` & `rollover_alias` logstash directives redundant?

Now, in kibana, I'm stumped when I go to assign an ILM policy. Where the `pfelk` new style index template covers multiple index patterns, the same ILM policy can be applied across the board. But each index pattern covered by this template requires a unique rollover_alias (as per 50-outputs.conf). However, it doesn't seem possible to do so via the kibana UI. It only provides for specifying a single rollover_alias, at the template level. 

How do I do that or, more likely, what am I misunderstanding?
Many thanks.

**Comment by kingtat** [comment]
My workaround, if in fact one is needed, is to move each of the the index patterns in the main pfelk index template to their own separate index templates. i.e. only one index pattern per template. Then rollover_alias can be successfully applied.

Whilst searching for ways to address this issue (rollover_alias vs multiple index patterns in templates), I did not find a solution other than the mention of data streams as a 'new way'. But I did not want to deviate too much from the current pfelk approach.

It seems ILM is not employed by many users of this project. So I'm wondering how others manage their indexes. ILM seems the only analogy to log rotate in elasticstack world.

**Comment by a3ilson** [comment]
@kingtat - thanks! I plan to migrate to data streams in the future (hopefully by the end of the year). As for ILM, it does need some tweaking.

Thanks!

**Comment by kingtat** [comment]
> I plan to migrate to data streams in the future (hopefully by the end of the year). As for ILM, it does need some tweaking.

I look forward to it. I find using the Elastic stack simultaneously enjoyable and frustrating. Changes and new features pop up all the time, making articles you may find online become outdated fast. Consequently, I now avoid consulting anything over 6 months old!
I understand you don't bother with ILM. So how do you manage your elastic indexes?

**Comment by a3ilson** [comment]
I have pfELK running with ILM but not the same configuration as the repo. I have not had much time to dedicate towards this project since the beginning of this year and currently in the process of relocating (moving). I hope (plan) to rollout some updates later this year.

**Comment by a3ilson** [comment]
Data Streams and ILM now configured by default

**Comment by kingtat** [comment]
Thanks for this. I look forward to trying it out.
