### ISSUE TITLE
Add dns.answers.type to Unbound

### ISSUE THREAD

**Issue by Dustie** [pfelk/pfelk#323]
Would it be possible to add Unbound dns.answers.type? I'm using pfsense to block ads (pfblockerng) so it would be nice if dns.answers.type wasn't empty.

**Comment by a3ilson** [comment]
@Dustie - Interesting that they are empty.

I am running OPNsense with unbound + blacklist (similar to pfblockerng) and my `dns.question.type` fields are not empty. Would you be able to provide a sampling of your unbound logs (raw format) for comparison?

**Comment by Dustie** [comment]
@a3ilson Oh, I see, I thought it wasn't implemented! I'm not sure what / how much log data you want. The raw logs from pfsense > Unbound? Is it possible to share it privately somewhere so I don't have to go though the log looking for privacy issues (I'm not the only user of the connection so I'd rather not go through it)?

**Comment by Dustie** [comment]
I thought some more on this. I'm using Log level 0 in pfsense and "server:log-queries: yes" but I can't remember where I got these settings. Everything else is logged fine in pfelk though, it is only dns.answers.type that is empty in the dash.

**Comment by a3ilson** [comment]
@Dustie - Send me a sampling of those logs (a dozen or so with the dns.answers.type) and I'll see if we can enrich the GROK pattern. 

andrew@pfelk.com

**Comment by Dustie** [comment]
@a3ilson I send a log. It was from pfsense though (/var/log/resolver.log) which might not be the same as what gets forwarded to pfelk with `server: log-queries: yes` but I don't know how to look at the raw data pfelk receives.

**Comment by a3ilson** [comment]
@Dustie 

Set Log Level = Level 3: Query level information

Based on your provided log, it appears that you are capturing the dns.answer.type and pfelk should be enriching those elements. I've tested your logs and confirm it will enrich/parse out dns.answer.type

**Comment by Dustie** [comment]
@a3ilson 

Setting the log level setting `Level 3: Query level information` will make pfsense log at level 3 to the local drive (from where I got the log for you). Remote logging for pfelk is set in unbound custom options with `server:log-queries: yes`. As stated I don't know if these two logs are actually logging the same since I don't know where to look in pfelk to see the raw data received. I of course should have looked at `man unbound` before doing anything else but better late than never! I found that there are two options: `log-queries` and `log-replies`. I'm guessing this might be the missing piece though I have no knowledge of Unbound. I will report back.

There is also this setting that might make filtering easier(?):

`log-tag-queryreply: <yes or no>`
              `Prints  the  word  'query'  and  'reply'  with  log-queries  and log-replies.`

**Comment by Dustie** [comment]
I just noticed that pfelk says OPNsense in all menus, not pfsense. Is this how it is supposed to be? I used the script to install everything.

**Comment by cheath94** [comment]
I used the script to install pfelk on a Ubuntu 20.04 container. I have pfSense 2.5.0 running with the same issue of the unbound dashboard answer type empty. I followed the configuration.md and set the log level to 0 and added the custom option (server: log-queries: yes)

**Comment by a3ilson** [comment]
@Dustie and/or @cheath94 - can you provide a screenshot from Kiban?

Here's one Unbound log from my system (OPNsense):
```
<30>Aug 12 15:25:38 firewall.box.com unbound[68035]: [68035:3] info: 172.16.71.131 video.h1.bytedance.map.fastly.net. A IN
```
After it is initally parsed, we are left with ```[68035:3] info: 172.16.71.131 video.h1.bytedance.map.fastly.net. A IN``` to be enriched by the unbound GROK pattern(s)

A provided Unbound log from pfSense is as follows:
```
Aug  8 02:32:27 pfSense unbound[79063]: [79063:2] info: 192.168.0.110 plex.tv. A IN
```

After it is initially parsed, we are left with ```[79063:2] info:  192.168.0.110 plex.tv. A IN``` which will be enriched by the unbound GROK pattern.

The unbound grok pattern https://github.com/pfelk/pfelk/blob/ac33512233f31399d42a5da314bd84e4a0ad3e50/etc/pfelk/patterns/pfelk.grok#L84


Parses the above as follows:
- OPNsense
 ```
 {
  "[dns][question][class]": "IN",
  "[client][ip]": "172.22.22.131",
  "[dns][question][name]": "video.h1.bytedance.map.fastly.net",
  "[dns][question][type]": "A",
  "[process][pgid]": "68035",
  "[process][thread][id]": "3",
  "[log][level]": "info"
}
 ```
- pfSense
```
{
  "[dns][question][class]": "IN",
  "[client][ip]": "192.168.0.110",
  "[dns][question][name]": "plex.tv",
  "[dns][question][type]": "A",
  "[process][pgid]": "79063",
  "[process][thread][id]": "2",
  "[log][level]": "info"
}
```

**Comment by cheath94** [comment]
![unbound log](https://user-images.githubusercontent.com/88810391/129261873-266562e5-5ec9-46ca-b7b2-2e9195b7191b.png)
Here is a screen shot of a log and the parse json of that log. Looks similar to what you have.

{
  "_index": "pfelk-unbound-000001",
  "_type": "_doc",
  "_id": "U67pO3sBRncCAIlNVOGS",
  "_version": 1,
  "_score": null,
  "fields": {
    "dns.question.class": [
      "IN"
    ],
    "event.original": [
      "<30>1 2021-08-12T14:49:14.103773-05:00 pfSense.internal unbound 82432 - - [82432:5] info: 172.16.10.15 outlook.office365.com. A IN"
    ],
    "process.name.text": [
      "unbound"
    ],
    "observer.name": [
      "pfSense"
    ],
    "dns.question.type": [
      "A"
    ],
    "client.ip": [
      "172.16.10.15"
    ],
    "process.pid": [
      82432
    ],
    "process.pgid": [
      82432
    ],
    "tags": [
      "unbound"
    ],
    "observer.serial_number": [
      "001"
    ],
    "process.name": [
      "unbound"
    ],
    "@timestamp": [
      "2021-08-12T19:49:12.364Z"
    ],
    "ecs.version": [
      "1.9.0"
    ],
    "observer.type": [
      "firewall"
    ],
    "event.created": [
      "2021-08-12T19:49:14.103Z"
    ],
    "@version": [
      "1"
    ],
    "dns.question.registered_domain": [
      "office365.com"
    ],
    "log.level": [
      "info"
    ],
    "observer.product": [
      "Baracuda"
    ],
    "process.thread.id": [
      5
    ],
    "dns.question.name": [
      "outlook.office365.com"
    ],
    "observer.ip": [
      "172.16.99.1"
    ],
    "event.dataset": [
      "pfelk.unbound"
    ],
    "log.syslog.version": [
      "1"
    ]
  },
  "sort": [
    1628797752364
  ]
}

**Comment by cheath94** [comment]
Ok so you will have to excuse me as my knowledge of ELK is pretty slim, but I got the chart to work the way I believe it is supposed to or at least looks like the screenshots on the main page. I changed the the field on the visualization to dns.question.type instead of dns.answer.type. There appears to be no dns.answer fields being parsed. 

![dns answer type](https://user-images.githubusercontent.com/88810391/129359422-23d34a3d-9cf5-4fde-a649-2ffb750f4c6f.png)

This began filling the chart with dns record types like this:

![answer type chart](https://user-images.githubusercontent.com/88810391/129359822-f137543f-9e19-4281-a944-83692035a0db.png)

This may not be the correct field, but record types are filling the chart.

**Comment by a3ilson** [comment]
I'm tracking now... I miss read and initial error regrading dns.question.type vs dns.answer.type

The dns.answer.type is not contained in the current log level.

**Comment by cheath94** [comment]
@a3ilson so your saying setting the log level to 3 in the pfsense gui should provide the necessary info for dns.answer.type? I have tried that and it does not seem to change anything. Does anything to be changed in the custom options along with the log level change?

**Comment by Dustie** [comment]
`log-replies` made no difference. Turning up the log level doesn't change anything ( it doesn't log more that is relevant than `log-queries` does). At least not that I can tell. I wish I had more to add but I simply know too little about ELK.

**Comment by revere521** [comment]
I think changing the log level in the pfsense UI sends a lot of garbage (unbound system messages), i had to set "log-queries: yes"  as one of my custom options instead.  I set the UI log level to 0. 

That does not allow you to change the verbosity though, at least not to my knowledge.   There does not appear to be data in those log messages that generates a dns.answers.type response.  as @cheath94 noted, there is a dns.questions.type that can be used:

![image](https://user-images.githubusercontent.com/23560313/129445466-416c835d-67af-451b-ae6d-621529116e0a.png)

that does appear to give you the record type...which i'm assuming is conceptually the same information?

**Comment by revere521** [comment]
You can also change the verbosity level of Unbound from the config file in this way (while keeping the GUI at 0): 
```
Include:
     verbosity: 1
     log-queries: yes
```

Doing this won't get you fields that fill the dns.answer.type (it gets you no answer fields)  - since the verbosity increase includes a lot more verbosity in the type of information received, it would require a bunch of new parsing (that would be most likely overly complex)   Conceptually, from pfsense, we see a lot of info about the dns queries outgoing, so changing the discover field and visualization field from answer to query seems to be a more elegant solution here. 

should this be closed?

**Comment by Dustie** [comment]
Feel free to close for my sake (my PFELK installation died).
