### ISSUE TITLE
No data in the pfelk-firewall-*

### ISSUE THREAD

**Issue by gemonpar** [pfelk/pfelk#324]
**Describe the bug**

First of all, sorry for my english, is not my mother language. 

I followed all the instructions in the manual guide and I don't know why but logstash was fetching the configuration in a wrong path, so I copied the .conf in pfelk/conf.d/ path and pasted into the logstash/conf.d path. That solved the problem, but when i was looking at the Index Management in Kibana, the only data coming was the pfelk-dhcp-2021.08 and pfelk-openvpn-2021.08 and i don't know why any data is coming into the pfelk-firewall.

**To Reproduce**

What I explain above.

**Screenshots**
![image](https://user-images.githubusercontent.com/49905811/127780428-d03aea68-fc65-4c00-a1b9-f1aeae5bf83e.png)
![image](https://user-images.githubusercontent.com/49905811/127781032-4ee520b0-9787-4501-b5ed-f67c192ece0e.png)

**Firewall System (please complete the following information):**
 - pfSense
 - 2.4.4
 
**Operating System (please complete the following information):**

Linux 5.4.0-80-generic x86_64
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
 
 **Installation method (manual, ansible-playbook, docker, script):**

 Manual method.

**Elasticsearch, Logstash, Kibana (please complete the following information):**

 - elasticsearch  7.13.4       amd64        Distributed RESTful search engine built for the cloud
 - logstash       1:7.13.4-1   amd64        An extensible logging pipeline
 - kibana         7.13.4       amd64        Explore and visualize your Elasticsearch data
 
 **Elasticsearch, Logstash, Kibana logs:**

 - Elasticsearch logs:
[2021-08-01T18:28:21,887][WARN ][o.e.m.j.JvmGcMonitorService] [elkserver] [gc][20] overhead, spent [623ms] collecting in the last [1s]
[2021-08-01T18:28:23,698][INFO ][o.e.t.LoggingTaskListener] [elkserver] 80 finished with response BulkByScrollResponse[took=1s,timed_out=false,sliceId=null,updated=10,created=0,deleted=0,batches=1,versionConflicts=0,noops=0,retries=0,throttledUntil=0s,bulk_failures=[],search_failures=[]]
[2021-08-01T18:28:23,889][INFO ][o.e.t.LoggingTaskListener] [elkserver] 76 finished with response BulkByScrollResponse[took=1.7s,timed_out=false,sliceId=null,updated=83,created=0,deleted=0,batches=1,versionConflicts=0,noops=0,retries=0,throttledUntil=0s,bulk_failures=[],search_failures=[]]
[2021-08-01T18:28:32,949][WARN ][o.e.m.j.JvmGcMonitorService] [elkserver] [gc][31] overhead, spent [542ms] collecting in the last [1s]
[2021-08-01T18:29:15,804][INFO ][o.e.c.m.MetadataCreateIndexService] [elkserver] [pfelk-openvpn-2021.08] creating index, cause [auto(bulk api)], templates [], shards [1]/[1]
[2021-08-01T18:29:16,903][INFO ][o.e.c.m.MetadataMappingService] [elkserver] [pfelk-openvpn-2021.08/_M_CQImDTrmq27G2h89Oaw] create_mapping [_doc]
[2021-08-01T18:37:43,589][INFO ][o.e.c.m.MetadataCreateIndexService] [elkserver] [pfelk-dhcp-2021.08] creating index, cause [auto(bulk api)], templates [pfelk-dhcp], shards [1]/[1]
[2021-08-01T18:37:44,632][INFO ][o.e.c.m.MetadataMappingService] [elkserver] [pfelk-dhcp-2021.08/VtfeK7yfQmCSgfk7F14l7g] update_mapping [_doc]
[2021-08-01T19:06:38,111][INFO ][o.e.c.m.MetadataCreateIndexService] [elkserver] [.async-search] creating index, cause [api], templates [], shards [1]/[0]
[2021-08-01T19:06:40,303][INFO ][o.e.c.m.MetadataMappingService] [elkserver] [.kibana_7.13.4_001/0J49rsaBTYGWlLcl-XGhvw] update_mapping [_doc]

 - Logstash logs
 [2021-08-01T18:28:34,897][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-08-01T18:28:34,897][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-08-01T18:28:34,897][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-08-01T18:28:34,897][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-08-01T18:28:35,268][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-08-01T18:28:35,298][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch version determined (7.13.4) {:es_version=>7}
[2021-08-01T18:28:35,299][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-08-01T18:28:35,312][INFO ][logstash.outputs.elasticsearch][pfelk] Elasticsearch version determined (7.13.4) {:es_version=>7}
[2021-08-01T18:28:35,321][WARN ][logstash.outputs.elasticsearch][pfelk] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2021-08-01T18:29:07,626][INFO ][logstash.outputs.elasticsearch][pfelk] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}

 - Kibana logs
Aug 01 10:43:14 elkserver systemd[1]: Started Kibana.
Aug 01 10:50:15 elkserver systemd[1]: Stopping Kibana...
Aug 01 10:50:45 elkserver systemd[1]: kibana.service: Succeeded.
Aug 01 10:50:45 elkserver systemd[1]: Stopped Kibana.
Aug 01 10:50:45 elkserver systemd[1]: Started Kibana.
Aug 01 10:55:47 elkserver systemd[1]: Stopping Kibana...
Aug 01 10:56:22 elkserver systemd[1]: kibana.service: Succeeded.
Aug 01 10:56:22 elkserver systemd[1]: Stopped Kibana.
Aug 01 11:01:22 elkserver systemd[1]: Started Kibana.
Aug 01 11:04:28 elkserver systemd[1]: Stopping Kibana...
Aug 01 11:04:58 elkserver systemd[1]: kibana.service: Succeeded.
Aug 01 11:04:58 elkserver systemd[1]: Stopped Kibana.
Aug 01 11:04:58 elkserver systemd[1]: Started Kibana.
Aug 01 11:21:01 elkserver systemd[1]: Stopping Kibana...
Aug 01 11:21:31 elkserver systemd[1]: kibana.service: Succeeded.
Aug 01 11:21:31 elkserver systemd[1]: Stopped Kibana.
Aug 01 11:21:31 elkserver systemd[1]: Started Kibana.
Aug 01 11:31:23 elkserver systemd[1]: Stopping Kibana...
Aug 01 11:31:58 elkserver systemd[1]: kibana.service: Succeeded.
Aug 01 11:31:58 elkserver systemd[1]: Stopped Kibana.
-- Reboot --
Aug 01 11:32:20 elkserver systemd[1]: Started Kibana.
Aug 01 11:42:26 elkserver systemd[1]: Stopping Kibana...
Aug 01 11:43:03 elkserver systemd[1]: kibana.service: Succeeded.
Aug 01 11:43:03 elkserver systemd[1]: Stopped Kibana.
-- Reboot --
Aug 01 11:43:23 elkserver systemd[1]: Started Kibana.
Aug 01 18:12:43 elkserver systemd[1]: Stopping Kibana...
Aug 01 18:13:25 elkserver systemd[1]: kibana.service: Succeeded.
Aug 01 18:13:25 elkserver systemd[1]: Stopped Kibana.
Aug 01 18:13:25 elkserver systemd[1]: Started Kibana.
Aug 01 18:16:10 elkserver systemd[1]: Stopping Kibana...
Aug 01 18:16:19 elkserver systemd[1]: kibana.service: Succeeded.
Aug 01 18:16:19 elkserver systemd[1]: Stopped Kibana.
-- Reboot --
Aug 01 18:16:59 elkserver systemd[1]: Started Kibana.

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
[error.pfelk.log](https://github.com/pfelk/pfelk/files/6913298/error.pfelk.log)

**Comment by a3ilson** [comment]
@gemonpar - I see that you are using pfSense v2.4.4 which has since been upgraded to v2.5.0. The latest version is supported with pfELK and I suspect that your issue may be the result of the older pfSense version being utilized.  

Recommend:
- Upgrade to pfSense v2.5.0+
or
- Provide output via tcpdump of the pfSense syslog output and we can provide/reference a legacy GROK filter (e.g. version 4.5 support pfSense v2.4.4 - https://github.com/pfelk/pfelk/releases/tag/v4.5)

**Comment by gemonpar** [comment]
I'll ask if I can update pfSense. Meanwhile, I attach the output of the tcpdump.

[pfSense_logs.log](https://github.com/pfelk/pfelk/files/6917489/pfSense_logs.log)

**Comment by a3ilson** [comment]
@gemonpar - thanks for the tcpdump output!

It would be best to upgrade to v2.5.0 and hopefully you have a spare in which the upgrade can be tested prior to implementation.  However, downloading and leveraging v4.5 (https://github.com/pfelk/pfelk/releases/tag/v4.5) may be the best solution if electing to run pfSense 2.4.4.

The initial GROK filter is significantly different between the two versions.

Current version: 
```
match => {"message" => "%{POSINT:[log][syslog][priority]}?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}\s*?(\[)?%{POSINT:[process][pid]}(\]:)?\s*(\-\s*\-)?\s*%{GREEDYDATA:filter_message}|%{POSINT:[log][syslog][priority]}?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}\:\s%{GREEDYDATA:filter_message}"}
```

v4.5: 
```
match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:pf_message}" }
```

Unable to test, you could try amending to:
```
match => { "message" => "<(?<[log][syslog][priority]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA:filter_message}" }
```

However, I suspect it will not work and require additional testing. Let me know if you're able to upgrade otherwise report back and I'll see if we can get something working.

**Comment by gemonpar** [comment]
Thank you so much for helping me. I've changed what you've said in 03-filter.conf, but it didn't work. On the other hand, I've changed 05-apps.conf, changing the filterlog parameter and now it is like this:

"if [process][name] =~ /^filterlog:$/ " 

So now i'm receiving data in pfelk-firewall-*, but it's not parsed so the firewall dashboard is empty.

![image](https://user-images.githubusercontent.com/49905811/127887722-1fad7e5f-3809-4c63-8303-6748b72cf6c0.png)

**Comment by a3ilson** [comment]
Can you expand one of those events and provide the text contents?

**Comment by gemonpar** [comment]
Of course.
![image](https://user-images.githubusercontent.com/49905811/127893563-7892bb78-4485-4be0-8989-d20315f74f70.png)

**Comment by a3ilson** [comment]
Unable to replicate. I took one of your logs: ```<134>Aug  2 17:39:45 filterlog: 5,,,1000000003,vmx0,match,block,in,6,0x00,0x00000,255,ICMPv6,58,24,fe80::1eb0:44ff:fed2:f7f1,ff02::1,``` and parsed it through the current setup without issue.

I would recommend reverting the 05-apps.conf to its original state as you shouldn't have to amend that file.  Additionally, is this a new/initial install of pfELK? If so, please try the following:
- stop logstash
- navigate to Kibana and delete all indices within 
- Restart logstash and see if the issue persists

**Comment by gemonpar** [comment]
Ok, I changed what you said and now i only have data in this indices:

![image](https://user-images.githubusercontent.com/49905811/127901695-b7f3543f-df2c-4ae6-962c-82e590fd08d1.png)

So you recommend me make a fresh install of pfelk?

**Comment by a3ilson** [comment]
No need to reinstall. I am certain it is the initial GROK filter within the 03-filter.conf

Try replacing line https://github.com/pfelk/pfelk/blob/c0fe955ce2456f80ef28ca9faa36a56ec4a9bb52/etc/pfelk/conf.d/03-filter.conf#L12 with the following: ```match => {"message" => "<(?<[log][syslog][priority]>.*)>%{SYSLOGTIMESTAMP:[event][created]}\s+(%{SYSLOGHOST:[host][name]}\s+)?%{GREEDYDATA:filter_message}"}```

**Comment by gemonpar** [comment]
Thank you so much, but I tried what you said and it didn't work. So I reinstall all and with the default GROK filter within the 03-filter.conf, parses de messages like in the image. Where the [process][name] is being taken as "filterlog:", so if I don't replace the filter in 05-apps.conf like "filterlog:", I don't get any data into kibana.

![image](https://user-images.githubusercontent.com/49905811/127975991-a2cb5a51-1c70-4dda-b72a-9dbec0bbafa2.png)

So probably my problem is in the "PF_LOG_ENTRY" pfelk.grok in etc/pfelk/patterns/ ?

**Comment by a3ilson** [comment]
Gotcha - the semicolon is causing the issue.

Give this a try within the Grok Debugger (I am currently unable to test until next week):

- Added a semicolon after `[process][name]`
- `%{PROG:[process][name]}:\s*?(\[)?`
```
match => {"message" => "%{POSINT:[log][syslog][priority]}?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}:\s*?(\[)?%{POSINT:[process][pid]}(\]:)?\s*(\-\s*\-)?\s*%{GREEDYDATA:filter_message}|%{POSINT:[log][syslog][priority]}?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}\:\s%{GREEDYDATA:filter_message}"}
```
or
- Added an optional semicolon after `[process][name]`
- `%{PROG:[process][name]}(:)?\s*?(\[)?`
```
match => {"message" => "%{POSINT:[log][syslog][priority]}?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}(:)?\s*?(\[)?%{POSINT:[process][pid]}(\]:)?\s*(\-\s*\-)?\s*%{GREEDYDATA:filter_message}|%{POSINT:[log][syslog][priority]}?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}\:\s%{GREEDYDATA:filter_message}"}
```

**Comment by gemonpar** [comment]
Thank you, ok, now the firewall data is being taken. I would like to see the dashboards, this is what I see. 

![image](https://user-images.githubusercontent.com/49905811/128190995-288b9cae-7c28-427d-8da7-dbf51fbdf64e.png)

There is a tag _grokparsefailure.

![image](https://user-images.githubusercontent.com/49905811/128190772-e2ef8537-5b0e-4ff1-a68b-5fa395d22c12.png)

**Comment by firestormo** [comment]
i have the same issue running opnsense 21.7.1 (latest) and I have tried all the grok patterns above and they all fail the grok debugger. 

here is an example of my data

<134>Aug  4 10:12:21 router.home.directgate.net filterlog[35625]: 93,,,a5a4a52cb247a9d532d9e49588136184,em1,match,pass,out,4,0x0,,63,12054,0,DF,17,udp,309,192.168.176.43,192.168.1.245,49780,5514,289

**Comment by henworth** [comment]
I had this same issue. What I discovered was that the `[rule][uuid]` field changed from an integer to an alphanumeric after the latest opnsense update. So, in this line (in `/etc/pfelk/patterns/pfelk.grok` in the filesystem) change `%{INT:[rule][uuid]}` to ~~`%{UUID:[rule][uuid]}`~~ `%{WORD:[rule][uuid]}`, then restart Logstash, and it should parse once again.

https://github.com/pfelk/pfelk/blob/c0fe955ce2456f80ef28ca9faa36a56ec4a9bb52/etc/pfelk/patterns/pfelk.grok#L40

**Comment by firestormo** [comment]
> I had this same issue. What I discovered was that the `[rule][uuid]` field changed from an integer to an alphanumeric after the latest opnsense update. So, in this line (in `/etc/pfelk/patterns/pfelk.grok` in the filesystem) change `%{INT:[rule][uuid]}` to `%{UUID:[rule][uuid]}`, then restart Logstash, and it should parse once again.
> 
> https://github.com/pfelk/pfelk/blob/c0fe955ce2456f80ef28ca9faa36a56ec4a9bb52/etc/pfelk/patterns/pfelk.grok#L40

did that and still getting a grok parse failure

**Comment by henworth** [comment]
Yup, my bad, use `DATA` instead of `UUID`. I just tested your log entry in the debugger and it came back clean.

Edit: You could use `WORD` as well since that would be less greedy. It also seems to be the preferred choice in the pattern library.

**Comment by firestormo** [comment]
> Yup, my bad, use `DATA` instead of `UUID`. I just tested your log entry in the debugger and it came back clean.
> 
> Edit: You could use `WORD` as well since that would be less greedy. It also seems to be the preferred choice in the pattern library.

same error.. what do i put in the debugger for grok pattern to test on the data ? <134>Aug  4 16:57:00 router.home.directgate.net filterlog[95059]: 93,,,a5a4a52cb247a9d532d9e49588136184,em0,match,pass,out,4,0x0,,64,9669,0,none,17,udp,78,186.64.243.169,13.107.160.4,26217,53,58

edit: i tried WORD and DATA

edit2: here is what i have in at line 40 and commented out the old line
PF_LOG_DATA %{INT:[rule][ruleset]},%{INT:[rule][id]}?,,%{WORD:[rule][uuid]},%{DATA:[interface][name]},(?<[event][reason]>\b[\w\-]+\b),%{WORD:[event][action]},%{WORD:[network][direction]},

**Comment by henworth** [comment]
This is what I did.

Under **Sample Data** put:
`93,,,a5a4a52cb247a9d532d9e49588136184,em0,match,pass,out,4,0x0,,64,9669,0,none,17,udp,78,186.64.243.169,13.107.160.4,26217,53,58`

Under **Grok Pattern** put:
`%{PF_LOG_ENTRY}`

Expand **Custom Patterns** and put these:
```
PF_LOG_ENTRY %{PF_LOG_DATA}%{PF_IP_SPECIFIC_DATA}%{PF_IP_DATA}%{PF_PROTOCOL_DATA}?
PF_LOG_DATA %{INT:[rule][ruleset]},%{INT:[rule][id]}?,,%{WORD:[rule][uuid]},%{WORD:[interface][name]},%{WORD:[event][reason]},%{WORD:[event][action]},%{WORD:[network][direction]},
PF_IP_SPECIFIC_DATA %{PF_IPv4_SPECIFIC_DATA}|%{PF_IPv6_SPECIFIC_DATA}
PF_IPv4_SPECIFIC_DATA %{INT:[network][type]},%{BASE16NUM:[pf][ipv4][tos]},%{WORD:[pf][ipv4][ecn]}?,%{INT:[pf][ipv4][ttl]},%{INT:[pf][ipv4][packet][id]},%{INT:[pf][ipv4][offset]},%{WORD:[pf][ipv4][flags]},%{INT:[network][iana_number]},%{WORD:[network][transport]},
PF_IP_DATA %{INT:[pf][packet][length]},%{IP:[source][ip]},%{IP:[destination][ip]},
PF_PROTOCOL_DATA %{PF_TCP_DATA}|%{PF_UDP_DATA}|%{PF_ICMP_DATA}|%{PF_IGMP_DATA}|%{PF_IPv6_VAR}|%{PF_IPv6_ICMP}
PF_IPv6_SPECIFIC_DATA %{INT:[network][type]},%{BASE16NUM:[pf][ipv6][class]},%{WORD:[pf][ipv6][flow_label]},%{WORD:[pf][ipv6][hop_limit]},%{DATA:[pf][protocol][type]},%{INT:[pf][protocol][id]},
PF_IPv6_VAR %{WORD:type},%{WORD:option},%{WORD:Flags},%{WORD:Flags}
PF_TCP_DATA %{INT:[source][port]},%{INT:[destination][port]},%{INT:[pf][transport][data_length]},(?<[pf][tcp][flags]>(\w*)?),(?<[pf][tcp][sequence_number]>(\d*)?):?\d*,(?<[pf][tcp][ack_number]>(\d*)?),(?<[pf][tcp][window]>(\d*)?),(?<[pf][tcp][urg]>(\w*)?),%{GREEDYDATA:[pf][tcp][options]}
PF_UDP_DATA %{INT:[source][port]},%{INT:[destination][port]},%{INT:[pf][transport][data_length]}$
PF_IGMP_DATA datalength=%{INT:[network][packets]}
PF_ICMP_DATA %{PF_ICMP_TYPE}%{PF_ICMP_RESPONSE}
PF_ICMP_TYPE (?<icmp_type>(request|reply|unreachproto|unreachport|unreach|timeexceed|paramprob|redirect|maskreply|needfrag|tstamp|tstampreply)),
PF_ICMP_RESPONSE %{PF_ICMP_ECHO_REQ_REPLY}|%{PF_ICMP_UNREACHPORT}|%{PF_ICMP_UNREACHPROTO}|%{PF_ICMP_UNREACHABLE}|%{PF_ICMP_NEED_FLAG}|%{PF_ICMP_TSTAMP}|%{PF_ICMP_TSTAMP_REPLY}
PF_ICMP_ECHO_REQ_REPLY %{INT:[pf][icmp][echo][id]},%{INT:[pf][icmp][echo][sequence]}
PF_ICMP_UNREACHPORT %{IP:[pf][icmp][unreachport][destination][ip]},%{WORD:[pf][icmp][unreachport][protocol]},%{INT:[pf][icmp][unreachport][port]}
PF_ICMP_UNREACHPROTO %{IP:[pf][icmp][unreach][destination][ip]},%{WORD:[pf][icmp][unreach][network][transport]}
PF_ICMP_UNREACHABLE %{GREEDYDATA:[pf][icmp][unreachable]}
PF_ICMP_NEED_FLAG %{IP:[pf][icmp][need_flag][ip]},%{INT:[pf][icmp][need_flag][mtu]}
PF_ICMP_TSTAMP %{INT:[pf][icmp][tstamp][id]},%{INT:[pf][icmp][tstamp][sequence]}
PF_ICMP_TSTAMP_REPLY %{INT:[pf][icmp][tstamp][reply][id]},%{INT:[pf][icmp][tstamp][reply][sequence]},%{INT:[pf][icmp][tstamp][reply][otime]},%{INT:[pf][icmp][tstamp][reply][rtime]},%{INT:[pf][icmp][tstamp][reply][ttime]}
PF_SPEC \+
PF_IPv6_ICMP (?:%{DATA})
```

That should allow it to parse the line.

Now that I think about it, it could _also_ be the  `PF_IPv6_ICMP (?:%{DATA})` as in the original pattern file that is empty and the Kibana debugger did not like that. I added a non-capturing group instead on that pattern because I'm not familiar with what that field would actually be (no IPv6 on my network) and I just wanted it to parse.

**Comment by firestormo** [comment]
![image](https://user-images.githubusercontent.com/42076498/128267429-7f72325b-fc4e-4ef3-9e29-5a4ce19bd67e.png)
So the grok debigger works with the line i have in pfelk.grok but im still getting a grok failure tag and no data in the dashboard

![image](https://user-images.githubusercontent.com/42076498/128267522-be6033cd-d46c-4bad-87b5-d2587a889624.png)
![image](https://user-images.githubusercontent.com/42076498/128267529-a9415dd7-1d63-4c93-837d-92207f9262d3.png)

**Comment by firestormo** [comment]
> PF_IPv6_ICMP (?:%{DATA})

I changed the PF_IPv6_ICMP line as it was blank and added PF_IPv6_ICMP (?:%{DATA}). Still getting grok parse failure.. yet when I run it in the grok debugger with everything as you state above, it passes and the data looks correct. Just nothing parsing when its running and I look in the discover section. 

edit: i rebuilt from scratch pfelk yesterday thinking maybe it was older config, but alas nope

**Comment by henworth** [comment]
Just to confirm, when changing the pattern file are you restarting Logstash after? Logstash won't pick up the changes otherwise.

**Comment by firestormo** [comment]
> Just to confirm, when changing the pattern file are you restarting Logstash after? Logstash won't pick up the changes otherwise.

logstash and elasticsearch

**Comment by firestormo** [comment]
> Just to confirm, when changing the pattern file are you restarting Logstash after? Logstash won't pick up the changes otherwise.

ok i got it working.. i purged everything.. installed from scratch, then updated the pfelk.grok file with your updated line, then also had to update the line of PF_IPv6_ICMP and so I made it PF_IPv6_ICMP \+ and restarted logstash, then it was finally parsing correctly.

**Comment by henworth** [comment]
Nice! Yea I’ve also had that pattern as \+ and it was fine. Probably will update my PR with that as well. Glad you got it working.

**Comment by gemonpar** [comment]
It didn't work for me. I updated as you say the pfelk.grok. In the grok debugger works, but not in logstash. Here it is my pfelk grok pattern.

[pfelk.txt](https://github.com/pfelk/pfelk/files/6939789/pfelk.txt)

**Comment by henworth** [comment]
Looks like you have commented out a lot of the patterns in that file. Without those enabled the grok filter would certainly fail.

**Comment by firestormo** [comment]
here is the file i got it working with
[pfelk.txt](https://github.com/pfelk/pfelk/files/6939885/pfelk.txt)

**Comment by gemonpar** [comment]
Thank you for the grok file, but it didn't work for me. Not parsing the data in discovery firewall. I don't understand why in the grok debugger works but when I run it in logstash don't parse anything.

![image](https://user-images.githubusercontent.com/49905811/128394629-06513645-731e-497b-b890-99f2fb245f7a.png)

**Comment by firestormo** [comment]
> Thank you for the grok file, but it didn't work for me. Not parsing the data in discovery firewall. I don't understand why in the grok debugger works but when I run it in logstash don't parse anything.
> 
> ![image](https://user-images.githubusercontent.com/49905811/128394629-06513645-731e-497b-b890-99f2fb245f7a.png)

i had the same issue, i purged the install and re-ran the script install, then copied over the grok file, restarted logstash and it was working, then apt updated my stuff to the latest of 7.14 and when it asked about the logstash.yml i kept the existing one not overwrote with the one from the package, still working.

**Comment by a3ilson** [comment]
@gemonpar - Feel free to open another issue. I believe your issue was specific to a legacy version of pfSense. Whereas this thread appears to have morphed into another issue.

**Comment by a3ilson** [comment]
@gemonpar - has this been resolved?

**Comment by a3ilson** [comment]
No response from author
