### ISSUE TITLE
Firewall log grokparsefailure

### ISSUE THREAD

**Issue by ironspiresecurity** [pfelk/pfelk#327]
**Describe the bug**
The log changes in 21.1.9 broke the firewall grok parsing, now getting [ "firewall", "_grokparsefailure" ] in my tags from Opnsense running 21.1.9.  Trying to update the Grok pattern thus far for firewall has defeated me so hoping for some help.

**To Reproduce**
1. Upgrade Opnsense to 21.1.9
2. Witness your firewall filter log parsing fail

**Firewall System (please complete the following information):**
 - OPNsense
 - 21.1.9 
 
**Operating System (please complete the following information):**
"Ubuntu 16.04.7 LTS
 
 **Installation method (manual, ansible-playbook, docker, script):**
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 -  logstash       1:7.14.0-1
 
 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 - Kibana logs (`journalctl -u kibana.service`)

**Additional context**
Posted it here and got some feedback on what changed:
https://www.reddit.com/r/OPNsenseFirewall/comments/ovjh5i/filterlog_format_change/

Sample raw log from 21.1.9:
<134>Aug 10 01:55:54 4856d45d-aa0a-4e18-ac21-42e395fc2ec9.localdomain filterlog[69571]: 10,,,02f4bab031b57d1e30553ce08e0ec131,igb1,match,block,in,6,0x00,0x82182,1,udp,17,664,fe80::32:d1cc:29a:5134,ff02::c,56319,3702,664

**Comment by a3ilson** [comment]
Thanks! 

This was a result of the UUID being added for the rules.  The latest pull addresses and fixed this issue. Please download/update the latest version of pfelk.grok

Thanks @henworth for the fix!
