### ISSUE TITLE
No Data in Unbound dashboard

### ISSUE THREAD

**Issue by MySickSi** [pfelk/pfelk#331]
**Describe the bug**
The unbound dashboards show "Cannot read properties of undefined (reading 'table'). Captive dashboard just presents errors. I

The error seen when viewing the unbound dashboard.

`No matching indices found: No indices match pattern "pfelk-unbound-*"`

**Screenshots**
Pfsense Unbound config
![image](https://user-images.githubusercontent.com/40272145/132969264-828beafe-e42f-44d9-9985-a6da6713a7ac.png)

**Firewall System**
 pfSense 2.4.5
 
Linux 5.4.0-84-generic x86_64
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

 
 **Installation method (manual, ansible-playbook, docker, script):**
Docker install for Pfelk
Script install for dashboards

**Comment by MySickSi** [comment]
Missed a step - did not set the logging level to 0.

**Comment by revere521** [comment]
Did setting the logging level to 0 resolve the issue?

**Comment by MySickSi** [comment]
Yes it did, thanks!
