### ISSUE TITLE
lostash error related to GeoIP database

### ISSUE THREAD

**Issue by tbaror** [pfelk/pfelk#338]
Hello ,
Seems that logstash is having issues with Geoip database see log below
Please advice
Thanks

**Firewall System:
 - pfSense 
 - Version 2.5.2
 
**Operating System (please complete the following information):**
 - Linux 4.19.0-17-amd64 x86_64
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

 
 **Installation method: script
 
**Elasticsearch, Logstash, Kibana :x3 >7.15
 
 
**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 
[elasticsearch.log](https://github.com/pfelk/pfelk/files/7316331/elasticsearch.log)
[logstash-plain.log](https://github.com/pfelk/pfelk/files/7316332/logstash-plain.log)

**Comment by a3ilson** [comment]
@tbaror - not a GeoIP related issue. The error occurred when loading the dictionary file at /etc/pfelk/databases/rule-names.csv

**Comment by a3ilson** [comment]
@tbaror - There were also six additional errors (non-breaking) that were fixed with the 35-rules-desc.conf and 36-ports-desc.conf files.

However, I suspect the contents within your /etc/pfelk/databases/rule-names.csv to be the culprit.

**Comment by tbaror** [comment]
Thanks for the answer, finished by reinstalled the server completely using the script ,now   works
Thanks

**Comment by tbaror** [comment]
Reinnstalled server
