### ISSUE TITLE
Most of the dashboard no longer gets data

### ISSUE THREAD

**Issue by wylde780** [pfelk/pfelk#34]
Looks like a number of the fields have changed causing issues with a large portion of the dashboard. Also the path to the GeoIP db files wasn't /usr/share/GeoIP for my install it was /var/lib/GeoIP/. 

Thanks 

![image](https://user-images.githubusercontent.com/2114461/65827127-41275780-e24c-11e9-81e4-68eac9f38d67.png)

**Comment by wylde780** [comment]
So I found the issue and started to do a search / replace on the json file for the fields but now the headers have disappeared from the basic-search visualization. I'm not sure how I go about fixing this without doing it in a slow and painful way of search and replacing each field name one at a time. So I'm hoping you'll be able to post a new .json before I muster up the energy to do it. 

![image](https://user-images.githubusercontent.com/2114461/65831133-73987b00-e273-11e9-9b41-2984910e5a97.png)

**Comment by a3ilson** [comment]
I'll re-create the search, visualization and dashboard.  I wanted to make sure all the fields were kosher first.

**Comment by xpliz** [comment]
Yesterday I've followed the guide to setup opnsense+pfelk it somewhat worked. Now I updated changed files and most of dashboards stopped working, Surricata one didn't work at all. No suricata count, maps or other panels. It's complaining it's missing index-pattern-filed ids_sig_id.keyword. Dashboard dashboard is also missing lots of data today.  Since updating grok file i'm also getting this error:

`tags:pf, _grokparsefailure @timestamp:Sep 29, 2019 @ 14:38:26.682 type:syslog host:192.168.0.1 message:%{msg} @version:1 _id:9usHfW0BMMBUkIkLgUkN _type:_doc _index:pf-2019.09.29 _score: -`

**Comment by a3ilson** [comment]
@XplizitBe 

I am in the process of updated the GeoIP data to conform with ECS.  Once corrected, I'll update the dashboards.

-Andrew

**Comment by a3ilson** [comment]
> Yesterday I've followed the guide to setup opnsense+pfelk it somewhat worked. Now I updated changed files and most of dashboards stopped working, Surricata one didn't work at all. No suricata count, maps or other panels. It's complaining it's missing index-pattern-filed ids_sig_id.keyword. Dashboard dashboard is also missing lots of data today. Since updating grok file i'm also getting this error:
> 
> `tags:pf, _grokparsefailure @timestamp:Sep 29, 2019 @ 14:38:26.682 type:syslog host:192.168.0.1 message:%{msg} @version:1 _id:9usHfW0BMMBUkIkLgUkN _type:_doc _index:pf-2019.09.29 _score: -`

Just to clarify, your dashboards are not working but if you go to "Discover" is it working?  Can you post a screenshot.

**Comment by xpliz** [comment]
> Just to clarify, your dashboards are not working but if you go to "Discover" is it working? Can you post a screenshot.

Sure. Check lines 5, 6 of discover - this happens with todays updated grok. Also did screenshots of dashboards. And error that is always present with suricata visuals.

[screenshots](https://imgur.com/a/mgJyZ5i)

Maybe I should say I'm runing latest ELK stack on Ubuntu 18.04 LTS built in VM on 28.09.2019

**Comment by a3ilson** [comment]
Updated the Dashboard....However, I'll need to install and tinker a bit with Suricata.

I'm also working to get the GeoIP to map correctly....but have not made any progress...shelving for another day.

**Comment by xpliz** [comment]
I was trying different commits every now and then, some with more some with less success. I'll have to wait and try to help with any debugging needed. Now latest -1 commit just has no surricata at al. But I think geoip is somewhat working.

**Comment by a3ilson** [comment]
I rarely get any suricate hits and didn’t spend much time debugging.  When I get
more time (November) I’ll configure some simple rules and finish tweaking
the suricate portion.

Feel free to send any progress and I’ll help when possible - thanks!

Andrew

**Comment by a3ilson** [comment]
opened under a new issue, issue #42

**Comment by jameski83** [comment]
i'm still getting this issue with the new dashboard templates. Most of the fields specified by the visualisations don't seem to exist from my opnsense logs that have been gathered. Any ideas? When I add pf* Index Pattern I only have 24 fields, but when I add the dashboard template it adds another pf-* Index pattern with 134 fields. Any help would be appreciated.

**Comment by a3ilson** [comment]
Check the 10-pf.conf file and make sure you have the right grim pattern set
(competed out).  But default it is set to pfsense.
