### ISSUE TITLE
No data in indices

### ISSUE THREAD

**Issue by kostya-lebedev** [pfelk/pfelk#345]
Hello there
**Describe the bug**
Fresh install via script, try to use docker and manual method, but have the same problem. Last script version https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/scripts/pfelk-installer.sh 
Simple input-output logstash.conf add docs to index "logstash" normally, without any problem.

**To Reproduce**
1. Go to 'Stack Management'
2. "Index Management"
3. "Docs Count" in all indices = 0

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/3096742/137086686-2d3111d3-c261-478d-aaa9-1e1f1f366dfa.png)

**Firewall System (please complete the following information):**
 - pfSense
 - 2.5.x, 2.6.x
 
**Operating System (please complete the following information):**
Ubuntu 18.04.6 LTS and try on 20.04.3 same problem

 **Installation method (manual, ansible-playbook, docker, script):
script, docker, manual
 

**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
elasticsearch 7.14.1
logstash  1:7.14.1-1
kibana 7.14.1

 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 ![Screenshot_2](https://user-images.githubusercontent.com/3096742/137093263-a59a6929-adf1-4b11-b567-850d1bfb8043.png)
 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 ![Screenshot_3](https://user-images.githubusercontent.com/3096742/137093554-e907b63b-b797-4584-8382-d07c50ffdaca.png)
 - Kibana logs (`journalctl -u kibana.service`)
 ![Screenshot_5](https://user-images.githubusercontent.com/3096742/137093700-bff52f34-fbef-4033-a573-46ffe334b502.png)

**Additional context**
Non-cluster configuration only one pfelk server
Tcp dump
![Screenshot_6](https://user-images.githubusercontent.com/3096742/137094841-2365bcb0-3dd5-4832-a250-cc1e45792203.png)

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file
[error.pfelk.log](https://github.com/pfelk/pfelk/files/7336241/error.pfelk.log)

Do you have a solution to the problem? Many thanks in advance!

**Comment by kostya-lebedev** [comment]
[error.pfelk.log](https://github.com/pfelk/pfelk/files/7337011/error.pfelk.log)
fresh pfelk error log

**Comment by a3ilson** [comment]
What version of pfSense are you running (2.5.x or 2.6.x)? How do you have pfSesne configured (remote logging) and could you provide the raw (text) output of a couple of your logs via tcpdump (e.g. tcpdump -Ai eth0 port 5140).

**Comment by kostya-lebedev** [comment]
Thanks for your response,

This is tcpdump from Pfsense 2.5.1-RELEASE  log message format syslog RFC 5424/RFC 3339
[tcpdump_2.5.1.zip](https://github.com/pfelk/pfelk/files/7346117/tcpdump_2.5.1.zip)

In ideal configuration I want to receive logs from firewalls with multiple versions of pfsense 2.5.x and 2.6.x
This is tcpdump from Pfsense 2.6.0-DEVELOPMENT  log message format syslog RFC 5424/RFC 3339
[tcpdump_2.6.0.zip](https://github.com/pfelk/pfelk/files/7346118/tcpdump_2.6.0.zip)

**Comment by a3ilson** [comment]
Thanks! Let me convert those files and take a look. The current 03-filter.conf file will parse out pfSense and OPNsense logs...I suspect the 2.6.0 variant made another change to the output resulting in the error.

Have you had any luck with the 2.5.1 version? How do you have your remote logging configured (which format was configured)

**Comment by kostya-lebedev** [comment]
Same problem with pfsense 2.5.1

And if  logstash transport configuration like 
input
input {  
  tcp {
    type => "syslog"
    port => 5140
  }
}
input {  
  udp {
    type => "syslog"
    port => 5140
  }
}
output
output {
        elasticsearch {
                hosts => ["http://localhost:9200"]
                index => "logstash-%{+YYYY.MM.dd}" }
}
Index is creating
![Screenshot_17](https://user-images.githubusercontent.com/3096742/137378353-fdc5f778-ee40-44b0-ac68-c80545ab1e33.png)
![Screenshot_18](https://user-images.githubusercontent.com/3096742/137378956-27a689fc-b451-4ab9-9693-366787291e0a.png)

Remote logging configuration is default like in a article.
![Screenshot_20](https://user-images.githubusercontent.com/3096742/137379538-ae00c6db-b4d4-4bcd-91f4-e35f369616d0.png)
![Screenshot_19](https://user-images.githubusercontent.com/3096742/137379593-37c9bbfd-cee9-475a-bded-818425c394fe.png)

**Comment by a3ilson** [comment]
Very odd and wondering if any other pfSense users are experiencing the same issues.

I wrote an alternative for you to try:

Amend 03-filter.conf https://github.com/pfelk/pfelk/blob/bc9a7aeec2a5e6486dbf39110cc19bac544fae42/etc/pfelk/conf.d/03-filter.conf#L12

to the following:
```
match => {"message" => "<%{POSINT:[log][syslog][priority]}>?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{DATA:[host][name]}\s+)?%{PROG:[process][name]}\s*?(\[)?%{POSINT:[process][pid]}(\]:)?\s*(\-\s*\-)?\s*%{GREEDYDATA:filter_message}|%{POSINT:[log][syslog][priority]}?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}\:\s%{GREEDYDATA:filter_message}"}
```

The above parses out the trailing digit from the POSINT filed and for some odd reason your hostname is not being enriched via SYSLOGHOST. I adjusted to DATA which appears to be working.

**Comment by kostya-lebedev** [comment]
First of all, thanks a lot for your help. New line in 03-life.conf revives the pfelk-firewall index! Now it look working fine.
I used to have this problem with all Pfsense in my network. Fresh or old version 2.5.x is comunity edition from official source.

**Comment by a3ilson** [comment]
@kostya-lebedev - Great and glad it worked!

I'll update the repo shortly along with some other pending changes (minor).

**Comment by a3ilson** [comment]
Fix incorporated - thank you
