### ISSUE TITLE
Rules description export error with rule.ruleset, bad match

### ISSUE THREAD

**Issue by ghost** [pfelk/pfelk#347]
Hello, 

I followed the Rule Description guide: [https://github.com/pfelk/pfelk/wiki/References:-Rule-Descriptions](url)

The problem is that I have multiple rule description for the same rule UUID.

I did two diff between the last rules description export and a recent one, the same ruleset number is associated with multiple description:

**Rules description export of last week:**

- "978","AD LEGACY to AD TPN PARIS - TCP"
- "979","AD LEGACY to AD TPN PARIS - TCP"
- "980","AD LEGACY to AD TPN PARIS - TCP"
- "981","AD LEGACY to AD TPN PARIS - TCP"
- "982","AD LEGACY to AD TPN PARIS - TCP"
- "983","AD LEGACY to AD TPN PARIS - TCP"
- "984","AD LEGACY to AD TPN PARIS - TCP"
- "985","AD LEGACY to AD TPN PARIS - TCP"
- "986","AD LEGACY to AD TPN PARIS - TCP"
- "987","AD LEGACY to AD TPN PARIS - TCP"
- "988","AD LEGACY to AD TPN PARIS - TCP"
- "989","AD LEGACY to AD TPN PARIS - TCP"
- "990","AD LEGACY to AD TPN PARIS - TCP"
- "991","AD LEGACY to AD TPN PARIS - TCP"
- "992","AD LEGACY to AD TPN PARIS - TCP"
- "993","AD LEGACY to AD TPN PARIS - TCP"
- "994","AD LEGACY to AD TPN PARIS - TCP"
- "995","AD LEGACY to AD TPN PARIS - TCP"
- "996","AD LEGACY to AD TPN PARIS - TCP"
- "997","AD LEGACY to AD TPN PARIS - UDP"
- "998","AD LEGACY to AD TPN PARIS - UDP"
- "999","AD LEGACY to AD TPN PARIS - UDP"

**Rules description export of today:**

- "978","Allow SYSADMIN to AD TPN - TCP"
- "979","Allow SYSADMIN to AD TPN - TCP"
- "980","Allow SYSADMIN to AD TPN - TCP"
- "981","Allow SYSADMIN to AD TPN - TCP"
- "982","Allow SYSADMIN to AD TPN - UDP"
- "983","Allow SYSADMIN to AD TPN - UDP"
- "984","Allow SYSADMIN to AD TPN - UDP"
- "985","Allow SYSADMIN to AD TPN - UDP"
- "986","Allow SYSADMIN to AD TPN - UDP"
- "987","Allow SYSADMIN to AD TPN - UDP"
- "988","Allow SYSADMIN to AD TPN - UDP"
- "989","Allow SYSADMIN to AD TPN - UDP"
- "990","Allow SYSADMIN to AD TPN - UDP"
- "991","Allow SYSADMIN to AD TPN - UDP"
- "992","Allow SYSADMIN to AD TPN - UDP"
- "993","Allow SYSADMIN to AD TPN - UDP"
- "994","Allow SYSADMIN to AD TPN - UDP"
- "995","Allow SYSADMIN to AD TPN - UDP"
- "996","Allow SYSADMIN to AD TPN - NTP"
- "997","Allow SYSADMIN to Public NTP"
- "998","Allow SYSADMIN to Broadcast NETBIOS"
- "999","Allow SYSADMIN to Broadcast NETBIOS"

So in ELK, I cannot filter anymore with the description and the rule description become useless. 

Is it possible to export rule.uuid instead of rule.ruleset ? I tried to modify the sed command to filter out the UUID but I'm no good at it..

With the rule.uuid, the description will never be associated with another rule.

Thanks.

**Comment by ghost** [comment]
Only the rule number as configured in the running ruleset was logged by pf previously, and that isn't a static number.
We need to extract the uuid instead.

**Comment by a3ilson** [comment]
@s0p4L1N - are you running pfSense or OPNsense? I suspect this is related to OPNsense and release 20.7 when they implemented the rule UUIDs

**Comment by ghost** [comment]
> @s0p4L1N - are you running pfSense or OPNsense? I suspect this is related to OPNsense and release 20.7 when they implemented the rule UUIDs
@a3ilson
I run pfSense 2.5.0, we intend to upgrade it to the last version. We use the syslog (RFC 5424, with RFC 3339)

**Comment by ghost** [comment]
I almost find the right sed command to extract the uuid:

From the command on the tutorial
`
pfctl -vv -sr | grep USER_RULE | sed 's/@\([^(]*\).*"USER_RULE: *\([^"]*\).*/"\1","\2"/' | sort -t ' ' -k 1,1 -u
`

to this one
`
pfctl -vv -sr | grep USER_RULE | sed 's/\@.*(\([^)]*\).*"USER_RULE: *\([^"]*\).*/"\1","\2"/' | sort -t ' ' -k 1,1 -u
`

But I got some weird result at then end:

- "1634635422","Allow LAN to VPN LEGACY - UDP 4655"
- "1634635812","Allow PDQ Deploy TCP to LEGACY VPN"
- "1634635886","Allow PDQ Deploy UDP to LEGACY VPN"
- "1634636418","Allow HHUMBERT to DG VPN LEGACY - SSH"
- "1634637111","Allow LAN to SP3-04 LEGACY - DSM Access"
- "1634637172","Allow LAN to SP3-04 LEGACY - HTTP"
- "1634637219","Allow LAN to SP3-04 LEGACY - SMB"
- "1634637327","Allow LAN to SP3-04 LEGACY - NETBIOS"
- "1634655183","Allow LAN to TICKET"
- "1634655878","Allow LAN to Alexandrie"
- "1634656998","Allow LAN to WebService LEGACY"
- "1634678207","Allow LAN to Licensing LEGACY - PROD-008"
- "1634678535","Rancher TPN to RNCH LEGACY"
- "1634678702","Allow LAN to RNCH LEGACY - SSH"
- "1634679236","Allow LAN to Alexandrie - SSH"
- "1634680320","Allow IT TEAM to LEGACY SWITCH"
- "1634682672","Allow IT TEAM to RDP AD LEGACY"
- "1634683102","Allow LAN to Active Directory LEGACY - PRINT SHARING"
- "1634683791","Allow LAN to Licensing LEGACY - VP1-LICENCE"
- "1634684818","Allow LAN to SA3-01 - FILE SERVER 01"
- "1634685080","Allow LAN to SA3-03 - FILE SERVER 03"
- "igb0 ","allow traffic CCTV"
- "ix1 192.168.11.254","Allow LEGACY to TPN - ICMP"
- "self:32","Allow access to firewall"
- 

As I choose to filter content between parentheses instead of content after the @, in some line there is two colums with parenthese and the second one is chosen. The raw result below describe show some line with

`pfctl -vv -sr | grep USER_RULE`

Some line have reply-to parameters which add (interface  IP@ ) 

- @1012(1632318017) pass in log quick on igb1.xxx inet proto udp from 10.30.30.0/24 to 10.30.30.255 port = netbios-dgm keep state label "USER_RULE: Allow DMZ to Broadcast NETBIOS"
- @1013(1632318017) pass in log quick on igb1.xxx inet proto udp from 10.30.30.0/24 to 10.30.30.255 port = netbios-ssn keep state label "USER_RULE: Allow DMZ to Broadcast NETBIOS"
- @1014(1632318908) pass in log quick on igb1.xxx inet proto udp from 10.30.30.0/24 to 10.30.30.255 port = 17500 keep state label "USER_RULE: Allow DMZ to Broadcast DROPBOX"
- @1015(1632318953) pass in log quick on igb1.xxx inet proto udp from 10.30.30.0/24 to 10.30.30.255 port = 57621 keep state label "USER_RULE: Allow DMZ to Broadcast SPOTIFY"
- @1016(1632320893) pass in log quick on igb1.xxx inet from 10.30.30.0/24 to ! <ALL_SUBNET:30> flags S/SA keep state label "USER_RULE: Allow DMZto INTERNET"
- @1017(1632321254) pass in log quick on igb1.xxx inet proto tcp from 20.20.20.0/20 to <ALL_SUBNET:30> port = 8080 flags S/SA keep state label "USER_RULE: Allow DMZ to ALL Web Remote Server"
- @1018(1632409603) pass in log quick on igb1.xxx inet all flags S/SA keep state label "USER_RULE: DMZ - ALLOW ANY to ANY - Flux restant"
- @1019(1632210541) pass in log quick on ix1 reply-to (ix1 0.0.0.0) inet proto icmp from <LEGACY_ALL:2> to 10.10.10.0/20 icmp-type echorep keep state label "USER_RULE: Allow LEGACY to TPN - ICMP"
- @1020(1631782916) pass in log quick on ix1 reply-to (ix1 0.0.0.0) inet proto tcp from <LEGACY_ALL:2> to <puppetsrv:1> port = 8140 flags S/SA keep state label "USER_RULE: Allow PUPPET LEGACY CLIENT to PUPPET TPN SERVER"
- @1021(1631782916) pass in log quick on ix1 reply-to (ix1 0.0.0.0) inet proto tcp from <LEGACY_ALL:2> to <puppetsrv:1> port = 8142 flags S/SA keep state label "USER_RULE: Allow PUPPET LEGACY CLIENT to PUPPET TPN SERVER"


For now to extract, I have extrated all UUID rules and paste it in a Google Sheet to see the Rules description associated

My goal is to configure the 35-rules-desc.conf and replace rule.ruleset with rule.uuid

```
filter {
  if [observer][type] == "firewall" {
    if [rule][ruleset] {
   #if [rule][uuid] {
      translate {
        field => "[rule][ruleset]"
       #field => "[rule][uuid]"
        destination => "[rule][alias]"
        dictionary_path => "/etc/pfelk/databases/rule-names.csv"
        refresh_interval => 60
        refresh_behaviour => replace
        fallback => "%{[rule][ruleset]}"
       #fallback => "%{[rule][uuid]}"
      }
      mutate {
        add_field => { "[rule][description]" => "%{[interface][alias]}: %{[rule][alias]}" }
      }
    }
  }
}
```

**Comment by a3ilson** [comment]
@s0p4L1N - thanks! 

Feel free to submit a PR as both pfSense 2.5 and OPNsense 20.7 adjusted their log outputs (UUID). You can also submit a PR for the script and I'll have to allocate some time for OPNsense in the future.

Thanks

**Comment by ghost** [comment]
A pull request is when I have a solution, but I don't have the solution, i'm still trying to figure how to use uuid instead of ruleset to add the description, because the ruleset is not static to the description. UUID is.

My main issue is the extract command. Also it does not extrat the non USER_RULE rules, (I have 126 rules which was not recognized in ELK) because it was template rule created by pfsense.

**Comment by a3ilson** [comment]
@s0p4L1N are you using OPNsense or pfSense?

I can help troubleshoot with OPNsense.

**Comment by s0p4LiN** [comment]
I am still using pfSense, I did write this post also: [https://github.com/pfelk/pfelk/discussions/400](url)
I just changed my username.

**Comment by a3ilson** [comment]
#511
