### ISSUE TITLE
Only getting NTP logs

### ISSUE THREAD

**Issue by rpelissi** [pfelk/pfelk#348]
Hi!
I really like this project but I got some major issues and looking for help...
So I have deciced to rebuild from scratch a vm for pfelk. I use debian 10.11 and downloaded the latest script.
I run it but seems that the script got some issues while running because template and kibana objects where not available at the end of the script.
I manage to install using the scripts the template and the dashboards
After that configure my to firewall (1 pfsense and 1 opnsense) according to the doc. I then check if logstash is running and the listening ports are there using netstat. Even a tcpdump show me that the 2 firewalls are sendings logs.
But... in kibana, I can only see 1 firewall ntp logs and that's it...
Not sure what I can check to make it works.
Any help will be greatly appreciated.
Thanks!

**Comment by a3ilson** [comment]
How are you sending logs from both pfSense and OPNsense?
What firewall logs are you seeing?

**Comment by rpelissi** [comment]
Oh... forget about my ticket :) I have not read the doc about pfsense and the rsyslog format anf for opnsense I have select the correct Applications setting in settings/logging targets.
Now all is fine :) 
Did I saiy that I love this solution?
Thanks again!
