### ISSUE TITLE
[TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block]

### ISSUE THREAD

**Issue by gokhansezen** [pfelk/pfelk#349]
Hi,

My elasticsearch version: 7.15.0
My Linux system:  Ubuntu 20.04.3 LTS

I can't login with my valid credentials

![image](https://user-images.githubusercontent.com/16643176/138550683-95b8f90d-d664-43af-8cf7-b24ab66fe9ab.png)

![image](https://user-images.githubusercontent.com/16643176/138550693-1108a7ef-b9bd-4d83-891f-4049a072ba5a.png)

`{"type":"log","@timestamp":"2021-10-23T09:31:02+00:00","tags":["info","plugins","security","routes"],"pid":54111,"message":"Logging in with provider \"basic\" (basic)"}
{"type":"log","@timestamp":"2021-10-23T09:31:02+00:00","tags":["error","plugins","security","session","index"],"pid":54111,"message":"Failed to create session value: cluster_block_exception: [cluster_block_exception] Reason: index [.kibana_security_session_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];"}
{"type":"log","@timestamp":"2021-10-23T09:31:02+00:00","tags":["error","http"],"pid":54111,"message":"ResponseError: cluster_block_exception: [cluster_block_exception] Reason: index [.kibana_security_session_1] blocked by: [TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];\n    at onBody (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:353:23)\n    at IncomingMessage.onEnd (/usr/share/kibana/node_modules/@elastic/elasticsearch/lib/Transport.js:277:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1317:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21) {\n  meta: {\n    body: { error: [Object], status: 429 },\n    statusCode: 429,\n    headers: {\n      'x-elastic-product': 'Elasticsearch',\n      'content-type': 'application/json; charset=UTF-8',\n      'content-length': '435'\n    },\n    meta: {\n      context: null,\n      request: [Object],\n      name: 'elasticsearch-js',\n      connection: [Object],\n      attempts: 0,\n      aborted: false\n    }\n  }\n}"}
{"type":"error","@timestamp":"2021-10-23T09:31:02+00:00","tags":[],"pid":54111,"level":"error","error":{"message":"Internal Server Error","name":"Error","stack":"Error: Internal Server Error\n    at HapiResponseAdapter.toInternalError (/usr/share/kibana/src/core/server/http/router/response_adapter.js:61:19)\n    at Router.handle (/usr/share/kibana/src/core/server/http/router/router.js:177:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at handler (/usr/share/kibana/src/core/server/http/router/router.js:124:50)\n    at exports.Manager.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/toolkit.js:60:28)\n    at Object.internals.handler (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:46:20)\n    at exports.execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/handler.js:31:20)\n    at Request._lifecycle (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:370:32)\n    at Request._execute (/usr/share/kibana/node_modules/@hapi/hapi/lib/request.js:279:9)"},"url":"http://192.168.7.11:5601/internal/security/login","message":"Internal Server Error"}
{"type":"response","@timestamp":"2021-10-23T09:31:02+00:00","tags":[],"pid":54111,"method":"post","statusCode":500,"req":{"url":"/internal/security/login","method":"post","headers":{"host":"192.168.7.11:5601","connection":"keep-alive","content-length":"153","kbn-version":"7.15.0","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.50","content-type":"application/json","accept":"*/*","origin":"http://192.168.7.11:5601","referer":"http://192.168.7.11:5601/login?next=%2F","accept-encoding":"gzip, deflate","accept-language":"tr,en;q=0.9,en-GB;q=0.8,en-US;q=0.7"},"remoteAddress":"10.0.7.90","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36 Edg/94.0.992.50","referer":"http://192.168.7.11:5601/login?next=%2F"},"res":{"statusCode":500,"responseTime":90,"contentLength":97},"message":"POST /internal/security/login 500 90ms - 97.0B"}
`

**Comment by gokhansezen** [comment]
curl -u elastic:changeme -XPUT -H "Content-Type: application/json" http://localhost:9200/_all/_settings -d '{"index.blocks.read_only_allow_delete": null}'

But not resolve my problem.

**Comment by a3ilson** [comment]
What else are you running? I see a lot of packetbeat data being collected.

**Comment by gokhansezen** [comment]
> What else are you running? I see a lot of packetbeat data being collected.

Yes. It's true. But I turned it off and I don't use it anymore.

**Comment by gokhansezen** [comment]
I finally solved the problem. The problem was caused by the packetbeat logs.
