### ISSUE TITLE
Logstash not booting up due to LogStash::PipelineAction::Create/pipeline_id:pfelk exception

### ISSUE THREAD

**Issue by deriknel** [pfelk/pfelk#350]
**Describe the bug**
docker-compose logstash not booting up due to error: 

[ERROR] 2021-10-31 19:44:41.452 [Converge PipelineAction::Create<pfelk>] agent - Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:pfelk, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"{\", \"}\" at line 32, column 24 (byte 1251) after filter {\r\n  ### captive portal ###\r\n  # Rename pfSense captive portal log from logportalauth to captiveportal\r\n  if [process][name] =~ /^logportalauth/ {\r\n    mutate {\r\n      replace => { \"[process][name]\" => \"captiveportal\" }\r\n    }\r\n  }\r\n  if [process][name] =~ /^captiveportal/ {\r\n    mutate {\r\n      add_tag => \"captive\" \r\n      add_field => { \"[ecs][version]\" => \"1.7.0\" }\r\n      add_field => { \"[event][dataset]\" => \"pfelk.captive\" }\r\n      rename => { \"filter_message\" => \"captiveportalmessage\" }\r\n    }\r\n    grok {\r\n      patterns_dir => [ \"/etc/pfelk/patterns\" ]\r\n      match => [ \"captiveportalmessage\", \"%{CAPTIVEPORTAL}\" ]\r\n    }\r\n  }\r\n  ### dhcpd ###\r\n  if [process][name] =~ /^dhcpd$/ {\r\n    mutate {\r\n      add_tag => \"dhcp\"", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:32:in `compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:187:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:72:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:391:in `block in converge_state'"]},

**To Reproduce**
Steps to reproduce the behaviour:
Clean install using the docker-compose method, followed by manual configuration found here: https://github.com/pfelk/pfelk/blob/main/install/configuration.md. Containers boot up, but logstash shutdown due to above error and then goes into a reboot loop.

**Screenshots**
![image](https://user-images.githubusercontent.com/2233156/139599221-b74cccd9-dd2f-4825-9f60-64ce877463a1.png)

**Firewall System (please complete the following information):**
 - pfSense
 - 2.5.2-RELEASE (amd64)
 
**Operating System (please complete the following information):**
Linux 5.4.0-89-generic x86_64
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

 
 **Installation method (manual, ansible-playbook, docker, script):**
docker (docker-compose)
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 - Logstash Version 7.15.1
 - Elasticsearch version 7.15.1
 - jRuby 9.2.19.0 (2.5.8)
 - Kibana Version 7.15.1
 
 **Elasticsearch, Logstash, Kibana logs:**
See attached log ([_logstash_logs.txt](https://github.com/pfelk/pfelk/files/7449683/_logstash_logs.txt))

**Additional context**
No other changes or configuration changes were made outside of the manual configuration guide

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file
[_es02_logs.txt](https://github.com/pfelk/pfelk/files/7449679/_es02_logs.txt)
[_es03_logs.txt](https://github.com/pfelk/pfelk/files/7449681/_es03_logs.txt)
[_kibana_logs.txt](https://github.com/pfelk/pfelk/files/7449682/_kibana_logs.txt)
[_logstash_logs.txt](https://github.com/pfelk/pfelk/files/7449683/_logstash_logs.txt)
[_es01_logs.txt](https://github.com/pfelk/pfelk/files/7449684/_es01_logs.txt)

**Comment by a3ilson** [comment]
@deriknel - Run the following command prior to starting the Docker:
```sudo sysctl -w vm.max_map_count=262144```
Also make sure you have enough memory... the referenced yml defines 8GB for each Elasticsearch (24GB total) plus 8GB for Logstash.

**Comment by sfue83** [comment]
> @deriknel - Run the following command prior to starting the Docker: `2019 Tesla Model 3 · Standard Range Plus Sed` Also make sure you have enough memory... the referenced yml defines 8GB for each Elasticsearch (24GB total) plus 8GB for Logstash.

Having the same issue, could you please clarify, what command should be run?

**Comment by a3ilson** [comment]
```sudo sysctl -w vm.max_map_count=262144```

**Comment by sfue83** [comment]
> `sudo sysctl -w vm.max_map_count=262144`

I have done this before starting. The error seems to come from https://github.com/pfelk/docker/blob/main/etc/pfelk/conf.d/05-apps.conf

Lines 32 an 43 are missing brackets
add_tag => "dhcp", "dhcpdv4"
and add_tag => "dhcp", "dhcpdv6"
in https://github.com/pfelk/pfelk/blob/main/etc/pfelk/conf.d/05-apps.conf it is fixed

**Comment by a3ilson** [comment]
update the file and try again (https://github.com/pfelk/docker/blob/main/etc/pfelk/conf.d/05-apps.conf)

**Comment by sfue83** [comment]
I have already copied the file and logstash ist running fine now. Thanks a lot for this nice and complete solution
