### ISSUE TITLE
Logstash looping

### ISSUE THREAD

**Issue by tunavissie** [pfelk/pfelk#354]
Have been trying to install pfelk a few times with no success. As soon as I add pfelk to my logstash pipelines, my logstash keeps going into some sort of restart service loop. 

I have a production elk environment already running for my wingbeats having its own pipeline ID. Any assistance will be appreciated.

I'm trying to install it via the manual method btw.

**Comment by a3ilson** [comment]
can you provide a copy of your Logstash log.

**Comment by tunavissie** [comment]
[logstash-plain.log](https://github.com/pfelk/pfelk/files/7519239/logstash-plain.log)

**Comment by tunavissie** [comment]
![image](https://user-images.githubusercontent.com/93710526/141271907-0f1bd45a-1627-4c3a-a540-ad8c0cf68323.png)

as you can see no indicies are displaying

**Comment by tunavissie** [comment]
Updated logstash 
[logstash-plain.log](https://github.com/pfelk/pfelk/files/7519930/logstash-plain.log)
-

**Comment by a3ilson** [comment]
Appears to be a user permission issue based on the provided logs.

**Comment by tunavissie** [comment]
Using the elastic built-in account seems like it sorted a few errors out - but even with the elastic build-in user. I'm still not seeing any indices.
[logstash-plain.log](https://github.com/pfelk/pfelk/files/7520262/logstash-plain.log)


Attached new log file.

**Comment by a3ilson** [comment]
@tunavissie - can you provide a sample of your output logs being sent (e.g. tcpdump). Earlier this year the grok pattern was revised to accommodate all output types within pfSesne 2.5.0 but this along with other issues seems to be resonating from a likely issue with the default pfSense output (BSD) not being parsed correctly.

Issue #356 note this and was able to get working by switching the output type however, if possible, I would like a sampling of the output logging to correct the possible grok issue (I am running OPNsense [syslogng] and still baffled as to why pfSense has yet to fully migrated to syslogng #pfsesne)

**Comment by tunavissie** [comment]
I'm not exactly sure what logs are you referring to? I assume this will be from the pfsense firewall itself? If so can you explain to me where to extract these logs?

Thank you.

**Comment by a3ilson** [comment]
On the machine with pfELK installed, run the following command:
```sudo tcpdump -vvvv -A -i any port 5140```
Next, provide the text output (e.g. Msg: Nov 15......)

This will provide the logs which the grok pattern likely needs to be adjusted for the BSD output. After you've provided the logs, feel free to change the log output within pfSense which should fix the issue
![image](https://user-images.githubusercontent.com/16884679/141804460-496c1c6e-6694-4a4e-bde3-320e1a7170f4.png)

**Comment by a3ilson** [comment]
@tunavissie - was this resolved?
