### ISSUE TITLE
Fresh install via script; "No matching indices found" for any of the Index Patterns

### ISSUE THREAD

**Issue by Krond2010** [pfelk/pfelk#356]
**Describe the bug**
This is a fresh install using the installer script, with Ubuntu 20.04 (in VMware workstation 16). Dashboards show errors, and Index Patterns are not working (No matching indices found)

**To Reproduce**
1. Go to Dashboard
2. Click on any of the Dashboards
3. See errors

**Screenshots**
![image](https://user-images.githubusercontent.com/5729101/141424670-dd51247a-5deb-43c5-bb2b-ce67f993b1f6.png)

**Firewall System (please complete the following information):**
 pfSense 2.5.2-RELEASE (amd64)
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 
![image](https://user-images.githubusercontent.com/5729101/141424896-40e78b27-46b7-4a8c-8179-1a415b970d1d.png)

 **Installation method (manual, ansible-playbook, docker, script):**
 script

**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 
![image](https://user-images.githubusercontent.com/5729101/141425059-f979a42b-9d36-4a4b-a0aa-76e52cfbcdad.png)

 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)

![image](https://user-images.githubusercontent.com/5729101/141425195-ffe94135-d7ac-4799-8245-c58d16d5bab2.png)

 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
![image](https://user-images.githubusercontent.com/5729101/141425253-e1dad1b4-bec6-416a-a4f5-f2134e36ecb2.png)

 - Kibana logs (`journalctl -u kibana.service`)
![image](https://user-images.githubusercontent.com/5729101/141425386-2043d6df-5e3f-4dd3-be3b-d8f5f3a16970.png)

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file
[error.pfelk.log](https://github.com/pfelk/pfelk/files/7525603/error.pfelk.log)

**Comment by Krond2010** [comment]
tcpdump shows data is being received from pfSense:
![image](https://user-images.githubusercontent.com/5729101/141429757-a1c9c582-f9ef-440c-a7ac-9af8e3abbc5f.png)

**Comment by a3ilson** [comment]
Since this is running within a VM, I would recommended allocating more RAM. The logs, from what you provided, look good but I noted that you likely do not have enough RAM to keep everything run everything.

OS (Ubuntu - Desktop Variant) has 4GB specified for RAM
Elasticsearch requires a minimum of 8GB
Logstash recommends no less than 4GB
Kibana should run fine <1GB

**Comment by Krond2010** [comment]
So that worked, the indices are now showing. However, the dashboards are still empty.

For testing purposes, I set a deny entry for a host in the firewall, and an alert event for ICMP in snort, and while they are properly logged on pfSense, the dashboards in Kibana remain empty.

![image](https://user-images.githubusercontent.com/5729101/141525301-3648fa7a-b693-40b0-9698-7caa8cec1204.png)

![image](https://user-images.githubusercontent.com/5729101/141525331-cbbf450a-c06b-4544-b04d-e0d7c4b0eaff.png)

**Comment by Krond2010** [comment]
I fixed the issue.

By default, pfSense sends logs to a remote server in the BSD format. I had to change the format to syslog.

![image](https://user-images.githubusercontent.com/5729101/141535072-062af4f7-46e0-432f-a10c-a0f6b5eae4be.png)

Consider updating the configuration guide to include this step in case anyone else has this issue

**Comment by a3ilson** [comment]
We had previously test both formats earlier this year with the release of 2.5.0 - at that time the filter parsed both formats.  The BSD format does not provide the host name which is not required in the grok pattern.  If you can provide some log outs in the BSD format, I'd be happy to test/revise.

**Comment by pabsroq** [comment]
I too have a similar issue where there is no data populated within ELS, increased the RAM amount but still nothing... 

Are there any log files I could provide? I am running out of ideas about what to look for.

Thanks,

**Comment by benisai** [comment]
Can confirm that bsd logs do not work well in the newest release.. switching to syslog works fine.
