### ISSUE TITLE
No matching indices found: No indices match pattern for any of the indices

### ISSUE THREAD

**Issue by NickBolas** [pfelk/pfelk#358]
**Describe the bug**
Fresh install on Ubuntu server 20.04, same exact issue as # 356, except that I'm running the server within proxmox with 18GB of RAM assigned. I used the script install and am using pfSense 2.5.2

**Comment by a3ilson** [comment]
Try changing the pfSense output to syslog
![141535072-062af4f7-46e0-432f-a10c-a0f6b5eae4be](https://user-images.githubusercontent.com/16884679/143073702-7339122d-7d26-426c-a85e-cfeaa93e484a.png)

I am running OPNsense and still awaiting some sample logs of pfSense in BSD to update/fix the initial grok filter.

**Comment by NickBolas** [comment]
Yep, I tried it and then rebooted and nothing. Still has those errors. I tried the docker installation and am getting a java jre error. At work now so I can't check the logs.

**Comment by a3ilson** [comment]
What errors? 
Can you provide the logs from the pfelk/etc/pfelk/scripts/error-data.sh script? 
Can you provide a tcp dump ```sudo tcpdump -vvvv -A -i any port 5140```

**Comment by NickBolas** [comment]
.......(........<134>1 2021-11-24T01:34:46.393461-05:00 pfSense.localdomain filterlog 51411 - - 4,,,1000000103,igb2,match,block,in,4,0x0,,64,41936,0,DF,17,udp,
[pfelkerrorlog.txt](https://github.com/pfelk/pfelk/files/7593281/pfelkerrorlog.txt)

06:34:47.397695 IP (tos 0x0, ttl 64, id 25369, offset 0, flags [none], proto UDP (17), length 232)
    _gateway.syslog > pfelk-analytics.5140: [udp sum ok] SYSLOG, length: 204
        Facility local0 (16), Severity info (6)
        Msg: 1 2021-11-24T01:34:47.393261-05:00 pfSense.localdomain filterlog 51411 - - 6,,,1000000105,igb3,match,block,in,6,0x00,0x00000,1,Options,0,76,fe80::e87a:8ea6:a745:b543,ff02::16,HBH,RTALERT,0x0000,PADN,
        0x0000:  3c31 3334 3e31 2032 3032 312d 3131 2d32
        0x0010:  3454 3031 3a33 343a 3437 2e33 3933 3236
        0x0020:  312d 3035 3a30 3020 7066 5365 6e73 652e
        0x0030:  6c6f 6361 6c64 6f6d 6169 6e20 6669 6c74
        0x0040:  6572 6c6f 6720 3531 3431 3120 2d20 2d20
        0x0050:  362c 2c2c 3130 3030 3030 3031 3035 2c69
        0x0060:  6762 332c 6d61 7463 682c 626c 6f63 6b2c
        0x0070:  696e 2c36 2c30 7830 302c 3078 3030 3030
        0x0080:  302c 312c 4f70 7469 6f6e 732c 302c 3736
        0x0090:  2c66 6538 303a 3a65 3837 613a 3865 6136
        0x00a0:  3a61 3734 353a 6235 3433 2c66 6630 323a
        0x00b0:  3a31 362c 4842 482c 5254 414c 4552 542c
        0x00c0:  3078 3030 3030 2c50 4144 4e2c
E...c...@..r.......(.......-<134>1 2021-11-24T01:34:47.393261-05:00 pfSense.localdomain filterlog 51411 - - 6,,,1000000105,igb3,match,block,in,6,0x00,0x00000,1,Options,0,76,fe80::e87a:8ea6:a745:b543,ff02::16,HBH,RTALERT,0x0000,PADN,
^C
14 packets captured
14 packets received by filter
0 packets dropped by kernel

**Comment by a3ilson** [comment]
@NickBolas - Appears to have errored out looking for the MaxMind databases. 

Please confirm the location of your MaxMind Installation (```/usr/share/GeoIP```). If you did not have or choose not to use MaxMind (Logstash has a built in GeoIP database), you can delete the 30-geoip.conf and download a new copy with the MaxMind commented out). Finally, thanks for the tcpdump output - feel free to change back to BSD and provide the output <-- I would like to update the grok pattern for the BSD output but need those raw logs.

**Comment by NickBolas** [comment]
![pfelk](https://user-images.githubusercontent.com/94881217/143238386-bee9ed94-9b7b-4fb5-a4c9-4a66a9cf5b3d.PNG)


No luck, I used the new 30-geoip file. I noticed the GeoIP .mmd files were in /etc/pfelk/GeoIP while file was looking in /usr/share, I tried pointing it to the right spot, restarted all three elk stack services and still get the error above. 


E.......@..&.......(......]P<134>Nov 24 07:29:44 filterlog[51411]: 4,,,1000000103,igb2,match,block,in,4,0x0,,64,52391,0,DF,17,udp,69,192.168.3.97,9.9.9.9,35888,53,49
12:29:46.537287 IP (tos 0x0, ttl 64, id 38783, offset 0, flags [none], proto UDP (17), length 165)
    _gateway.syslog > pfelk-analytics.5140: [udp sum ok] SYSLOG, length: 137
        Facility local0 (16), Severity info (6)
        Msg: Nov 24 07:29:46 filterlog[51411]: 4,,,1000000103,igb2,match,block,in,4,0x0,,64,52441,0,DF,17,udp,69,192.168.3.97,9.9.9.9,34973,53,49
        0x0000:  3c31 3334 3e4e 6f76 2032 3420 3037 3a32
        0x0010:  393a 3436 2066 696c 7465 726c 6f67 5b35
        0x0020:  3134 3131 5d3a 2034 2c2c 2c31 3030 3030
        0x0030:  3030 3130 332c 6967 6232 2c6d 6174 6368
        0x0040:  2c62 6c6f 636b 2c69 6e2c 342c 3078 302c
        0x0050:  2c36 342c 3532 3434 312c 302c 4446 2c31
        0x0060:  372c 7564 702c 3639 2c31 3932 2e31 3638
        0x0070:  2e33 2e39 372c 392e 392e 392e 392c 3334
        0x0080:  3937 332c 3533 2c34 39
E.......@._O.......(......`U<134>Nov 24 07:29:46 filterlog[51411]: 4,,,1000000103,igb2,match,block,in,4,0x0,,64,52441,0,DF,17,udp,69,192.168.3.97,9.9.9.9,34973,53,49
^C
19 packets captured
19 packets received by filter
0 packets dropped by kernel


That's with the BSD log settings.


Later on, I'm going to try with an actual laptop instead of through proxmox. I have a feeling it's something to do with the virtual environment.

**Comment by a3ilson** [comment]
Excellent! Everything is running now as before it was crashing.  Thanks for the BSD log output format which recently was changed by pfSense and isn't currently parsing. I would change the output to something other than BSD - I believe that'll get you working.

I doubt proxmox is the issue...mine is running within a VM on proxmox.

**Comment by a3ilson** [comment]
Okay...just ran your log against the current grok pattern and no issues/errors... Can you navigate to three horizontal lines>>Stack Management>>Index Management and provide a screenshot of the Indices

**Comment by NickBolas** [comment]
![Screenshot_20211124-121450_Brave](https://user-images.githubusercontent.com/94881217/143284816-c4a79c83-fae1-4ee9-9882-4238badabe4a.jpg)

**Comment by a3ilson** [comment]
Thanks!

Figured it out...The script installer had an old reference to /etc/pfelk/geoip. This makes sense as to your original issue (i.e. Logstash stopping due to errors or more specifically invalid reference to the geoip database.  This was compounded as the script waits for Logstash which was likely running but quit. As a result the subsequent templates failed to install and as a result the data being received has no index/component templates resulting in no logged data.

To fix:
(Method 1): Download and run the [pfelk-template-insaller.sh](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/scripts/pfelk-template-installer.sh) script
- You may need to restart Logstash 
- Confirm template installation by navigating to three horizontal lines>>Stack Management>>Index Templates (you should see pfelk, pfelk-dhcp, and pfelk-suricata)

(Method 2): Reinstall

**Comment by NickBolas** [comment]
![Screenshot_20211124-130809_Brave](https://user-images.githubusercontent.com/94881217/143292207-91c42390-60db-4fe5-9686-38e76862322f.jpg)

This is after running  template installation script. I used the one you linked.

**Comment by a3ilson** [comment]
Excellent! now go back to three horizontal lines>>Stack Management>>Index Management and see if you have any indices. If the indices are present, then everything should be working.

**Comment by NickBolas** [comment]
I might have to try to reinstall, later on, I'll revert to a clean snapshot and try it fresh.

**Comment by a3ilson** [comment]
If you do not have any indices, give it a simple restart.

**Comment by NickBolas** [comment]
No luck yet! 
![Screenshot_20211124-131235_Brave](https://user-images.githubusercontent.com/94881217/143292675-dfa7eb6e-dc71-4a82-9139-fa94e9c025c7.jpg)
Does that error message mean anything on bottom right?

**Comment by a3ilson** [comment]
Unless you're running in a production, I would simply mute the warning - will not impact this instance.

Have you restarted Logstash? Can you confirm that it is running (logs/errors).

**Comment by NickBolas** [comment]
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-90-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed 24 Nov 2021 06:32:18 PM UTC

  System load:  3.11               Processes:              163
  Usage of /:   41.7% of 14.70GB   Users logged in:        0
  Memory usage: 59%                IPv4 address for ens18: 192.168.1.40
  Swap usage:   0%


2 updates can be applied immediately.
To see these additional updates run: apt list --upgradable


Last login: Wed Nov 24 18:03:05 2021 from 192.168.5.2
pfelk@pfelk-analytics:~$ systemctl status logstash.service
● logstash.service - logstash
     Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor pres>     Active: active (running) since Wed 2021-11-24 18:32:25 UTC; 3s ago
   Main PID: 5656 (java)
      Tasks: 16 (limit: 28758)
     Memory: 321.7M
     CGroup: /system.slice/logstash.service
             └─5656 /usr/share/logstash/jdk/bin/java -Xms1g -Xmx1g -XX:+UseConc>
Nov 24 18:32:25 pfelk-analytics systemd[1]: Started logstash.
Nov 24 18:32:25 pfelk-analytics logstash[5656]: Using bundled JDK: /usr/share/l>Nov 24 18:32:25 pfelk-analytics logstash[5656]: OpenJDK 64-Bit Server VM warnin>lines 1-12/12 (END)...skipping...
● logstash.service - logstash
     Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor pres>     Active: active (running) since Wed 2021-11-24 18:32:25 UTC; 3s ago
   Main PID: 5656 (java)
      Tasks: 16 (limit: 28758)
     Memory: 321.7M
     CGroup: /system.slice/logstash.service
             └─5656 /usr/share/logstash/jdk/bin/java -Xms1g -Xmx1g -XX:+UseConc>
Nov 24 18:32:25 pfelk-analytics systemd[1]: Started logstash.
Nov 24 18:32:25 pfelk-analytics logstash[5656]: Using bundled JDK: /usr/share/l>Nov 24 18:32:25 pfelk-analytics logstash[5656]: OpenJDK 64-Bit Server VM warnin>~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~                                                                               ~
~
~
~
~
● logstash.service - logstash                                                        Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor pres>     Active: active (running) since Wed 2021-11-24 18:32:25 UTC; 3s ago
   Main PID: 5656 (java)                                                              Tasks: 16 (limit: 28758)                                                       Memory: 321.7M
     CGroup: /system.slice/logstash.service
             └─5656 /usr/share/logstash/jdk/bin/java -Xms1g -Xmx1g -XX:+UseConc>
Nov 24 18:32:25 pfelk-analytics systemd[1]: Started logstash.
Nov 24 18:32:25 pfelk-analytics logstash[5656]: Using bundled JDK: /usr/share/l>Nov 24 18:32:25 pfelk-analytics logstash[5656]: OpenJDK 64-Bit Server VM warnin>~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
lines 1-12/12 (END)


![Uploading Screenshot_20211124-133142_Brave.jpg…]()

**Comment by NickBolas** [comment]
Java issues maybe?

**Comment by a3ilson** [comment]
Java is bundled with Logstash. It can be installed but is not required.

**Comment by a3ilson** [comment]
It's running...

Can you provide the contents of the Logstash log (e.g. ```tail -30 /var/log/logstash/logstash-plain.log```)

**Comment by NickBolas** [comment]
● logstash.service - logstash
pfelk@pfelk-analytics:~$ tail -30 /var/log/logstash/logstash-plain.log          [2021-11-24T19:02:10,360][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2021-11-24T19:02:10,513][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2021-11-24T19:02:15,596][INFO ][logstash.runner          ] Logstash shut down.
[2021-11-24T19:02:15,615][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.19.0.jar:?]
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.19.0.jar:?]
        at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:94) ~[?:?]
[2021-11-24T19:02:32,596][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2021-11-24T19:02:32,605][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2021-11-24T19:02:34,041][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"/etc/logstash/conf.d/*.conf"}
[2021-11-24T19:02:34,052][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2021-11-24T19:02:34,193][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2021-11-24T19:02:39,259][INFO ][logstash.runner          ] Logstash shut down.
[2021-11-24T19:02:39,272][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.19.0.jar:?]
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.19.0.jar:?]
        at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:94) ~[?:?]
[2021-11-24T19:02:56,539][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2021-11-24T19:02:56,552][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2021-11-24T19:02:57,945][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"/etc/logstash/conf.d/*.conf"}
[2021-11-24T19:02:57,956][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2021-11-24T19:02:58,115][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2021-11-24T19:03:03,183][INFO ][logstash.runner          ] Logstash shut down.
[2021-11-24T19:03:03,211][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby-complete-9.2.19.0.jar:?]
        at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby-complete-9.2.19.0.jar:?]
        at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:94) ~[?:?]
pfelk@pfelk-analytics:~$ clear


Seeing errors in there!

**Comment by a3ilson** [comment]
alright... Logstash is looking for log files here ```/etc/logstash/conf.d/*.conf``` where they should be ```/etc/pfelk/conf.d/*.conf``` please download and place the [pipelines.yml](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/logstash/pipelines.yml) file in the ```/etc/logstash/``` directory

That's odd as your original error had the correct path otherwise it would not have errored on the GeoIP path.

**Comment by a3ilson** [comment]
Your original pfelkerrorlog also had the correct pipelines.yml content - have you made any other changes?

**Comment by NickBolas** [comment]
I think the only change since then was the reinstall of the templates.

Once I get home and I have a clean snapshot of Ubuntu server, should I use the script method with the updated installer?

**Comment by a3ilson** [comment]
I would give the pipelines.yml update a try. Once downloaded and placed in the correct path, restart Logstash.

**Comment by NickBolas** [comment]
![Screenshot_20211124-143505_JuiceSSH](https://user-images.githubusercontent.com/94881217/143302656-45aded90-76fe-414e-9836-394537a36224.jpg)

Not sure if commented out the right parts.

**Comment by a3ilson** [comment]
it should look like this

```
# pipelines.yml
################################################################################
# Version: 21.03                                                               #
# Required: Yes                                                                #
# Description: This is a required file for a pfelk installation                #
# This file is where you define your pipelines. You can define multiple.       #
# For more information on multiple pipelines, see the documentation:           #
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html   #
#                                                                              #
################################################################################
#
- pipeline.id: pfelk
  path.config: "/etc/pfelk/conf.d/*.conf"

# - pipeline.id: main
#  path.config: "/etc/logstash/conf.d/*.conf"
```

**Comment by NickBolas** [comment]
Ok, I'm home now. Did  a restore to a clean state and will try a clean install.

UPDATE: Ok my friend, first of all, thank you for all of your help! It's working! Here's exactly what I did.

1. Fresh install of Ubuntu server 20.04
2. Downloaded the updated pfelk install script in your repo.
3. Selected  yes for ILM
4. Selected NO for Maxmind and used the built in GeoIP
5. I did not  upgrade the system packages
6. After the script finished, I installed the dashboards with the script in the repo.
7. Dashboards are working and displaying the correct information!
8. Thank you!

Also, if you need any logs or data let me know and I'll provide them. Do you think something can be made for ntopng and DPI visualizaton?

**Comment by a3ilson** [comment]
Regarding 6, the script installs the dashboards but no harm in running it twice. As for ntopng and DPI, just send a sampling of the logs and I can take a look.
