### ISSUE TITLE
Importing Kibana Dashboard fails

### ISSUE THREAD

**Issue by Kunibert-007** [pfelk/pfelk#360]
Importing the Kibana Dashboards under "Saved Objects" fails after round about 10 minutes waiting for the result:
![image](https://user-images.githubusercontent.com/35669927/143945885-b8ba5745-33fa-48b2-b7a5-93afd066a4c3.png)

I did the way like it is described under:
https://github.com/pfelk/pfelk/blob/main/install/configuration.md

I use Elasticsearch and Kibana in Docker-Containers on a Synology NAS.

Elasticsearch: 7.9.3
Kibana: 7.9.3

**Comment by a3ilson** [comment]
@Kunibert-007 - Are you able to spin up newer versions of Elasticsearch/Kibana (e.g. 7.15.x)?  It is very possible that the version you are running may not be compatible.

**Comment by BuzztiF** [comment]
Hi @a3ilson , just as an info to this: I have the same problem. It still exists after upgrading to Elastic and Kibana 7.15.2. I've used the official docker container from elastic. By creating an new visualisation in Kibana and copying the vega-visualisation by hand, then it works. Hope it somehow can help.

**Comment by a3ilson** [comment]
@BuzztiF - I'll do a manual install and extract the dashboards. I suspect some changes with the various elastic updates.  

The dashboards were built nearly a year ago (7.10.x). I'll do some testing later, as time permits, with v8 (beta) and will likely fix with the v8 release.

**Comment by a3ilson** [comment]
Tested with latest revision with docker and manual install - both worked without issue/unable to duplicate.

**Comment by a3ilson** [comment]
Couuld you provide a copy of the file you are attempting to import that is causing the error?

**Comment by a3ilson** [comment]
No response and unable to duplicate.
