### ISSUE TITLE
Scripted Install Question

### ISSUE THREAD

**Issue by stevefxp1** [pfelk/pfelk#361]
I have tried the scripted install but do have a question...if I see something in the script that comes back in red should I assume this step has failed? For example it showed the memory on my system(24 gig) and swap(8 gig), both in red.

Thanks,
Steve

**Comment by a3ilson** [comment]
@stevefxp1 - Thanks!  I can change to minimize confusion.

If one's system is <8GB it'll warn in red. However if it meets the minimum requirements it will display your member and swap in red. 

Reference Script: https://github.com/pfelk/pfelk/blob/ee973faf0595e566cb699bd76e8272c15a776ed3/etc/pfelk/scripts/pfelk-installer.sh#L930-L948
