### ISSUE TITLE
Suricata grock for PFsense

### ISSUE THREAD

**Issue by legoguy1000** [pfelk/pfelk#37]
The suricata EVE logs have a PID right next to the word suricata.  The grok filter needs to be updated to account for that.  

`PFSENSE %{MONTH}.%{MONTHDAY}.*%{TIME}.%{WORD:application}(?<pid>(\[[0-9]*\])?):.%{GREEDYDATA:msg}`

The `(?<pid>(\[[0-9]*\])?)` allows for the PID or not

**Comment by a3ilson** [comment]
Which file is this in reference too?

**Comment by legoguy1000** [comment]
pf-09.2019.grok

**Comment by a3ilson** [comment]
@legoguy1000 - updated/thanks!
