### ISSUE TITLE
Multiple Instances of pfsense

### ISSUE THREAD

**Issue by kostya-lebedev** [pfelk/pfelk#370]
Hello,

I use several pfsenses in my environment, more than 6.
Using this tutorial https://github.com/pfelk/pfelk/wiki/References:-Multiple-Instances, I can only set up two. Can you help me, what additional filters are required? 
Thanks a lot!

**Comment by a3ilson** [comment]
@kostya-lebedev - there are a few ways that this can be accomplished:

(1) You can send all 6 (six) pfSense remote logs to pfELK
- All pfSense instance can be delineated by the `host.name` field value but only if the 6 (six) pfSense instance are uniquely named
- The log output must support the `host.name` field and I believe the pfSense BSD output does not include the `host.name` field. You may need to confirm (I'm running OPNsense and utilizing syslog-ng)
- The potential issue with this method may be the lack or inability to enrich the network interfaces if there is more than one interface (e.g. pfSense box 1 has em0 and pfSense box 2 has em0). However, this can easily be remedied by modification of the 20-interfaces.conf file (e.g. `if [host][name] == "pfSense-1" {`

(2) The second method is to expand upon the referenced tutorial, [References: Multiple Instances](https://github.com/pfelk/pfelk/wiki/References:-Multiple-Instances)
- This will require adding four additional (six total) configurations for the 6 (six) pfSense instances. Adding a new conf file or amending 01-inputs.conf, 02-types.conf and 20-interfaces.conf.
- Each pfSesne will need to send the logs to a different port (e.g. pfSesne 1 via 5140, pfSense 2 via 5141 etc...)
- Attached are three modified conf files. Replace the current conf files with the ones attached. You'll need to configure each pfSense to send logs remotely via ports 5140-5145. Next, you'll need to amend, as needed, the 20-interfaces.conf file to correctly reference your pfSense interfaces.

Let me know which method would work best with your configuration/setup.
[conf files.zip](https://github.com/pfelk/pfelk/files/7750420/conf.files.zip)

**Comment by kostya-lebedev** [comment]
First of all - thank you for your help! 
Second method is better to me and i'm trying to do it before open issue.
But in Firewall Dashboard it's look like my previous setup. Are there any additional steps I need to take? 
In Discover "observer.name" showing well
![Screenshot_75](https://user-images.githubusercontent.com/3096742/147066730-0bed36a3-297a-462b-87f3-c753deff6d13.png)
But in Firewall Dashboard i cannot select right firewall.
![Screenshot_76](https://user-images.githubusercontent.com/3096742/147066734-647c13f3-9071-44d2-ae01-99f8e9f01712.png)

**Comment by a3ilson** [comment]
@kostya-lebedev - You may need to expand the time frame as I suspect it is only showing the available options based on the time frame filter. In the upper right, by default, Kibana applies a 15-minute filter. Try changing this (i.e. expand it) and see if that helps.

**Comment by kostya-lebedev** [comment]
Yes, i'm expand the time frame but the see same old names of my previous setup. Edited Firewall - Firewall Selector visualisation and reselect observer.name, but it still look like on screenshot
![Screenshot_77](https://user-images.githubusercontent.com/3096742/147078529-93ace698-348f-4c8a-84f8-3a6823f39a6c.png)

**Comment by a3ilson** [comment]
That seems odd. You're able to filter and see all instances within discover... when filtering on those that do not appear in the drop down, are there recent logs/entries?

**Comment by kostya-lebedev** [comment]
Yes, this is a latest logs/entries. 
And scrolled over all conf files and not find any of this entries "OPNsense" etc.

**Comment by a3ilson** [comment]
Awe... so the drop-down list is good except for the "OPNsense" value? 

The OPNsense as you indicated was likely amended with the previous changes. However, the historic log entry still exists. To remove the OPNsense value, you'd need to purge the indices.

**Comment by revere521** [comment]
The triangle with the exclamation point in Kibana also may indicate that Kibana timed out while listing all the items for the dropdown.  If you hover your cursor on that little warning icon, it will give you a popup message, that may indicate increasing a timeout in the Kibana.yml

**Comment by a3ilson** [comment]
@kostya-lebedev - are you good-to-go?

**Comment by a3ilson** [comment]
@kostya-lebedev - the last config should have worked...however, I just updated the repo and you can now send multiple pfSense/OPNsense/haproxy logs to a single port (5140 by default).  If you have multiple instance of those running, you'll be able to filter based on the `host.name` value. However, be advised, if using pfSense, that you'll need to change the default log message output to something other than BSD as the default does not send the `host.name`.
