### ISSUE TITLE
Add support for Ubuntu 21.x 

### ISSUE THREAD

**Issue by benisai** [pfelk/pfelk#371]
**Is your feature request related to a problem? Please describe.**
Cannot run the install script as ubuntu is above 20.0.4

**Describe the solution you'd like**
possible to add 21.xx to the installer?

**Describe alternatives you've considered**
None so far.

**Comment by a3ilson** [comment]
Added Ubuntu Hirsute/Impish to the latest script...
* I prefer to stick with LTS releases but the revision should allow installation on 21.04/10
- [ ] please test/confirm
