### ISSUE TITLE
Pfelk to Elastic Cloud?

### ISSUE THREAD

**Issue by swiftbird07** [pfelk/pfelk#372]
Hello,

is it possible to send the logs from Logstash (on its own server with Pfsense already sending logs to it etc.) to Elastic Cloud? (The one that you can rent out per month).
I have this cloud.id, that is supposed to work natively with Logstash, but I am not sure how to connect this feature with the whole pipeline and stuff.

Any help would be appreciated. :)

**Comment by wylde780** [comment]
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-cloud_id
There is plenty of documentation available for the elasticsearch output plugin for logstash.
