### ISSUE TITLE
Index firewall missing after script installation

### ISSUE THREAD

**Issue by msim888** [pfelk/pfelk#377]
**Describe the bug**
The Index firewall is not created during the installation process.

**To Reproduce**
1. Install current Version with the script

**Screenshots**
![image](https://user-images.githubusercontent.com/73604538/147412798-80b6ff40-2013-46a6-a24d-2dfabc1c8eda.png)
![image](https://user-images.githubusercontent.com/73604538/147412817-823df2ce-1030-425e-a629-11a88d6d6be8.png)
![image](https://user-images.githubusercontent.com/73604538/147412833-08a4ea65-b29d-45cc-9036-ac3eeeb27186.png)

**Firewall System (please complete the following information):**
 - pfSense
 - Version 2.5.2
 
**Operating System (please complete the following information):**
 - OS:
Linux 5.4.0-91-generic x86_64
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

 **Installation method (manual, ansible-playbook, docker, script):**
- script
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components:
    elasticsearch 7.16.2
    logstash 7.16.2
    kibana 7.16.2

**Additional context**
 - Indices exists excluding firewall index but all of them are hidden
 - Templates exists

**Comment by a3ilson** [comment]
What do you have pfSense log output set to?

The updated version uses Data Streams vs Indices. Click on the Data Stream tab to view received Data Streams. Data Steams store via hidden indices.

**Comment by msim888** [comment]
Yeah, I saw that the updated version uses Data Streams but for some reason there is no the main data stream - logs-pfelk-firewall. It seems the pfsense process filterlog can't be recognized and the firewall logs go to logs-pfelk-unknown data stream (you can see that on the screenshots above).

Here is the pfsense log output settings:
![image](https://user-images.githubusercontent.com/73604538/147415707-8cc490f7-49dd-4443-a86b-60c0adbbb4be.png)

**Comment by a3ilson** [comment]
What is your output (log message format)
![143073702-7339122d-7d26-426c-a85e-cfeaa93e484a](https://user-images.githubusercontent.com/16884679/147415770-240de085-7780-4214-a3dd-764ce7e6c650.png)

**Comment by msim888** [comment]
The default one:
![image](https://user-images.githubusercontent.com/73604538/147415792-34728fa1-ffbc-4d5b-97e3-275984f6a697.png)

**Comment by a3ilson** [comment]
Change it to anything except that option.  

That is the default option of pfSense but does not contain the hostname. I've tested the GROK pattern but am in the process of updating a few things and will not include @pfSense's legacy/old/outdated support for their default logging (RFC3164). Rather I will be supporting syslog-ng (preferred but not native on pfSense) and those using pfSense, will support the RFC5424 output format

**Comment by msim888** [comment]
I've changed it to syslog format and now the missed data stream is here. Perfect! And thank you!
The only disadvantage now is that the web GUI pfsense logs look worse (especially the date):
![image](https://user-images.githubusercontent.com/73604538/147415958-9ceb1cc9-5b07-440f-a4ee-27bbf3e2961d.png)
Is there a way to avoid that?

**Comment by a3ilson** [comment]
Negative...the alternate logging (RFC5424/3339) utilizes more precise timing.

Syslog-ng (plugin of pfSesne) may fix it? not sure as I do not use pfSense.

**Comment by msim888** [comment]
I've already tried syslog-ng. Didn't help - it just add a new local (pfsense) syslog server

**Comment by a3ilson** [comment]
Give this a try:

* Set pfSense log message output to BSD

* Amend the 03-filter.conf file as follows:
```
# 03-filter.conf
################################################################################
# Version: 22.00(#377                                                          #
# Required: Yes                                                                #
# Descritpion: Inital GROK pattern filtering for delinating syslog messages    #
# Works for pfSense 2.5.0 (RFC 5424/RFC3164) and OPNsense 21.1+.               #
################################################################################
#
filter {
  if [observer][type] == "firewall" or [observer][type] == "haproxy" or [observer][type] == "suricata" {
    grok {
      match => {"message" => "<%{POSINT:[log][syslog][priority]}>?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?%{PROG:[process][name]}\s*?(\[)?%{POSINT:[process][pid]}(\]:)?\s*(\-\s*\-)?\s*%{GREEDYDATA:filter_message}"}
      }
    date {
      match => [ "[event][created]", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss", "ISO8601" ]
      target => "[event][created]"
    }
  }
}
```

* Restart logstash

**Comment by msim888** [comment]
Thanks! It seems that filter file works for pfsense firewall logs but it doesn't work for Unbouind.

**Comment by a3ilson** [comment]
@msim888 - do you mind sending me a few unbound logs? I can tweak the grok pattern but will need the raw unbound logs.

**Comment by msim888** [comment]
Oh, sorry, my bad - it works. I just had to restart the unbound service.
