### ISSUE TITLE
NEW Elastic Agent has official experimental support for pfSense

### ISSUE THREAD

**Issue by ObjectiveTruth** [pfelk/pfelk#380]
Hey All,
I love this project and use it in my homelab. It's been unbelievably useful.
I was playing around with Elasticsearch (upgrading) and I noticed the new pfSense integration being officially supported!

Not sure if this will deprecate this project or if there can be mutual learning from both but though I'd leave it here. Don't shoot the messager! BTW this includes, dashboards

_Currently the integration supports parsing the Firewall, Unbound, DHCP Daemon, OpenVPN, IPsec, and HAProxy logs. All other events will be dropped_

https://github.com/elastic/integrations/tree/master/packages/pfsense

**Comment by a3ilson** [comment]
@ObjectiveTruth - Thanks!

I just took a look and appears they reaped this repo (the dashboards are exactly the same, many of the fields are similar, but it's all good). Hopefully it grows out of the experimental stage and adds support to OPNsense.

This project is coming to an end but glad it will be natively supported by @elastic and thanks (sarcastic) for taking credit.
