### ISSUE TITLE
Logstash fails to parse date

### ISSUE THREAD

**Issue by nuggie** [pfelk/pfelk#381]
**Describe the bug**
Logstash fails to parse date since new year. 

`"caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [Jan  1 02:21:38] with format [strict_date_optional_time||epoch_millis||MMM d HH:mm:ss||MMM dd HH:mm:ss]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"Failed to parse with all enclosed parsers"}`

Original event:
`"event"=>{"original"=>"<134>Jan  1 02:21:38 xxxx.xxxx.xxx filterlog[97530]: `

**To Reproduce**

**Screenshots**

**Firewall System (please complete the following information):**
 - OPNsense
 
**Operating System (please complete the following information):**
 - Debian GNU/Linux 10 (buster)
 
 **Installation method (manual, ansible-playbook, docker, script):**
  - ansible-playbook
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - elasticsearch  7.16.2
 - logstash       1:7.16.2-1
 - kibana         7.16.2
 
 **Elasticsearch, Logstash, Kibana logs:**

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***

**Comment by a3ilson** [comment]
I have 2hrs before 1 January 2022...I'll see if I can reproduce the error/issue.

**Comment by a3ilson** [comment]
Confirmed - this broke my instance as well...I am doing some testing and troubleshooting but this appear to be an error with Logstash and opened and issue for Elastic [here](https://github.com/elastic/logstash/issues/13574)

**Comment by a3ilson** [comment]
Fixed...update with the latest [01-inputs.conf](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/01-inputs.conf) file

**Comment by nuggie** [comment]
cool, thanks! Have a great new year!
