### ISSUE TITLE
NGINX reversproxy logs

### ISSUE THREAD

**Issue by BeNeDeLuX** [pfelk/pfelk#383]
Since i switched from HAProxy to NGINX as reverseproxy on my OPNsene some time ago i miss the logs from NGINX in pfELK.
I integrated the logs from NGINX now in pfELK for me. I tried to use the ECS field reference for SIEM integration and enriched the IP with geo information. The Dashboard is still in development but growing.

If desired I can provide the config for it of course.

**Comment by BeNeDeLuX** [comment]
Here is my current status of the NGINX Logs inside pfELK:

**Data & Fields**

![Screen_Nginx_2](https://user-images.githubusercontent.com/1895086/148114751-9b35f8ec-69c4-4df4-ae68-24cf67f84f04.png)
![Screen_Nginx_1](https://user-images.githubusercontent.com/1895086/148114757-4de7f8f1-70ad-4502-b9b5-5b8a7fb20d0b.png)

**Dashboard (first shoot)**
![Dashboard_Nginx](https://user-images.githubusercontent.com/1895086/148114760-3074b4c4-b01e-479e-93b4-2c55096143e4.png)

Does it make sense to merge it into pfelk at this stage ?

**Comment by a3ilson** [comment]
@BeNeDeLuX 

Thanks! Although, there is a module for NGINX via FileBeat. Adding support and integration with pfELK is certainly welcomed to help advance this repo. There is also a [sample dashboard](
https://www.elastic.co/guide/en/beats/filebeat/current/images/kibana-nginx.png) for ideas but I'll lean on you for the dashboard and majority of NGINX.



References: 
[FileBeat Module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-nginx.html#_fields_46)
[NGNIX Fileds](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-nginx.html)

**Comment by BeNeDeLuX** [comment]
@a3ilson Pull request is out. 
I will setup a fresh VM if the merge is done to verify my changes with a new installation.
If everything is fine i will adjust the dashboard install script and push a first documentation on OPNsense.

**Comment by a3ilson** [comment]
@BeNeDeLuX - can you confirm the file mappings specifically the`ngnix.upstream.###` I'm guessing those should be `ngnix.ingress_###` according to the NGNIX Fields referenced within Elastic [here](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-nginx.html)

**Comment by BeNeDeLuX** [comment]
Yes, you are right! Well found - I will correct them.

**Comment by BeNeDeLuX** [comment]
Fields are corrected in the pull request.
Here is my current template. Not sure if it's correct but it works for me.

```

PUT _index_template/pfelk-nginx
{
  "version": 22,
  "priority": 291,
  "template": {
    "settings": {
      "index": {
        "lifecycle": {
          "name": "pfelk"
        }
      }
    },
    "mappings": {
      "_routing": {
        "required": false
      },
      "numeric_detection": false,
      "dynamic_date_formats": [
        "strict_date_optional_time",
        "yyyy/MM/dd HH:mm:ss Z||yyyy/MM/dd Z"
      ],
      "dynamic": true,
      "_source": {
        "excludes": [],
        "includes": [],
        "enabled": true
      },
      "dynamic_templates": [],
      "date_detection": true
    }
  },
  "index_patterns": [
    "*-pfelk-nginx*"
  ],
  "data_stream": {
    "hidden": false
  },
  "composed_of": [
    "pfelk-settings",
    "pfelk-mappings-ecs"
  ],
  "_meta": {
    "managed": true,
    "description": "default nginx indexes installed by pfelk"
  }
}
```

**Comment by a3ilson** [comment]
@BeNeDeLuX - PR Merged, other various updates applied.

Once possible please provide a quick overview/guide/how-to. We'll place this within the Wiki and add a reference and/or add to the [configuration](https://github.com/pfelk/pfelk/blob/main/install/configuration.md) page

**Comment by BeNeDeLuX** [comment]
@a3ilson Pull request for the configuration page is done.
I will setup a VM from scratch to verify the function of the new NGINX Logs

**Comment by a3ilson** [comment]
Awesome/thanks!

**Comment by BeNeDeLuX** [comment]
Everything is working as expected. Thanks for all your help and support.
I will spent some time to expand the NGINX Dashboard in the future because some time charts are missing.
I close this issue here now.
