### ISSUE TITLE
Field interface.alias does not exist

### ISSUE THREAD

**Issue by BeNeDeLuX** [pfelk/pfelk#391]
The Field `interface.alias` is missing inside the pflek-firewall index. Therefore the dashboard selection for the interfaces doesn´t work.
I have a fresh installation here of pfELK with OPNsense.  

@a3ilson  Or do we need to change the field inside the dashboard to `interface.name` which is present in my case. 
I did not changed the `20-interfaces.conf` at all. It's the default one.

**To Reproduce**
1. Install pfelk
2. Push data to pflek
3. Open Firewall Dashboard
4. Interface selection without function

**Screenshots**
![interface_alias](https://user-images.githubusercontent.com/1895086/149388622-3279bb3b-7632-46f3-bc75-692f3ded6485.png)

The field rule.description:
![Bildschirmfoto_2022-01-13_19-23-47](https://user-images.githubusercontent.com/1895086/149388762-d2d24a42-1039-406c-8018-65d148747ff7.png)

**Firewall System (please complete the following information):**
 - OPNsense

Thanks!

**Comment by revere521** [comment]
@BeNeDeLuX  - it looks like the the item in question is this line in the 20-interfaces.conf:
```if [host][name] == "first.network.local" {```

that may need to be set to your actual hostname to trigger naming of the interfaces.  I'm testing now changing mine to  `"pfsense.local"`  to see what happens

**Comment by a3ilson** [comment]
@BeNeDeLuX & @revere521 

That is correct, the pfSense or OPNsense name needs to be applied or inputted into line 11 of the 20-interfaces.conf. For example if my OPNsense name was firewall.opnsense.local I would amend to line 11 as:
```
  if [host][name] == "firewall.opnsense.local" {
```

I certainly overlooked added that to the guide but will do so later today. This also applies to pfSense but if the default logging method is utilized, it does not include the host name in the syslog message.

**Comment by BeNeDeLuX** [comment]
Ok, i understand! Thank you both for the fast explanation
