### ISSUE TITLE
Possible issue with parsing.

### ISSUE THREAD

**Issue by gyterpena** [pfelk/pfelk#393]
We have issue with parsing php-fpm messages. Non of the pf. fields are present.
I think this is because PF_APP assigns concrete value to [pf][app] and subsequent patterns in PF_APP_LOGIN|LOGOUT|ERROR|GEN
are trying to use [pf][app] as object, aka [pf][app][action]

`PF_APP (%{DATA:[pf][app]}):
PF_APP_DATA (%{PF_APP_LOGOUT}|%{PF_APP_LOGIN}|%{PF_APP_ERROR}|%{PF_APP_GEN})
PF_APP_LOGIN (%{DATA:[pf][app][action]}) for user \'(%{DATA:[pf][app][user]})\' from: (%{GREEDYDATA:[pf][remote][ip]})
PF_APP_LOGOUT User (%{DATA:[pf][app][action]}) for user \'(%{DATA:[pf][app][user]})\' from: (%{GREEDYDATA:[pf][remote][ip]})
PF_APP_ERROR webConfigurator (%{DATA:[pf][app][action]}) for \'(%{DATA:[pf][app][user]})\' from (%{GREEDYDATA:[pf][remote][ip]})
PF_APP_GEN (%{GREEDYDATA:[pf][app][action]})`

**Comment by a3ilson** [comment]
@gyterpena 

Would you be able to provide some raw PF_APP logs?

**Comment by gyterpena** [comment]
/index.php: User logged out for user 'FooBar' from: 1.1.1.1 (Local Database)
/index.php: Successful login for user 'FooBar' from: 1.1.1.1 (Local Database)

ends up like this.(but I could be doing something wrong)
`{"pf":{"app":"/index.php"},"host":"ATS-DEBUG","message":"/index.php: User logged out for user 'FooBar' from: 1.1.1.1 (Local Database)","path":"/tmp/foo","tags":["grok"],"@version":"1","@timestamp":"2022-01-14T12:25:04.425Z"}
`

**Comment by gyterpena** [comment]
I have it working with this grok.
    grok {
      patterns_dir => [ "/etc/logstash/patterns/pfelk" ]
      match => { "message" => [ "%{PF_APP}" ] }
     add_tag => [ "grok" ]
    }

changed this line in patterns
PF_APP (%{DATA:[pf][application]}): %{PF_APP_DATA} 

Returns
{"@version":"1","@timestamp":"2022-01-14T12:42:44.676Z","host":"ATS-DEBUG","tags":["grok"],"message":"/index.php: User logged out for user 'FooBar' from: 1.1.1.1 (Local Database)","path":"/tmp/foo","pf":{"application":"/index.php","remote":{"ip":"1.1.1.1 (Local Database)"},"app":{"action":"logged out","user":"FooBar"}}}

I'd also change these in patterns
(%{GREEDYDATA:[pf][remote][ip]}) to (%{IP:[pf][remote][ip]}) to get IP only.

**Comment by a3ilson** [comment]
@gyterpena - thanks!

Would it be possible to get a few logs (text) from the `event.original` field? 

Unfortunately, I built the grok pattern for this years ago but have since migrated to OPNsense. However, I can certainly help and it appears you've already got the solution. I'd just like to review the logs and grok pattern for ECS compliance.

**Comment by gyterpena** [comment]
Hello
We don't store event.original I have these unique lines from php-fpm message field

/rc.carpbackup: HA cluster member "(10.0.0.1@lagg0.1): (vlan01)" has resumed CARP state "BACKUP" for vhid 17
/rc.newipsecdns: Gateway, none 'available' for inet6, use the first one configured. ''
/rc.newipsecdns: WARNING: Setting i_dont_care_about_security_and_use_aggressive_mode_psk option because a phase 1 is configured using aggressive mode with pre-shared keys. This is not a secure configuration.
/rc.newipsecdns: IPSEC: One or more IPsec tunnel endpoints has changed its IP. Refreshing.
/rc.openvpn: Gateway, none 'available' for inet6, use the first one configured. ''
/rc.openvpn: OpenVPN: One or more OpenVPN tunnel endpoints may have changed its IP. Reloading endpoints that may use SOMEVTITUNNEL_VTIV4.
/index.php: Successful login for user 'FooBar' from: 10.0.0.2 (Local Database)
/index.php: FooBar@10.0.0.2 (Local Database) attempted to access /index.php but does not have access to that page. Redirecting to diag_backup.php.
/rc.update_alias_url_data: Download file failed with status code 404. URL: https://someurl.com/file.txt
/rc.update_alias_url_data: Failed to download alias https://someurl.com/file.txt

#following seems to be result of php-fpm crashing.
phpsession_begin(..) - /etc/inc/auth.inc:2037
simplestacktrace(..) - /etc/inc/phpsessionmanager.inc:55
[2] => #### phpsession_begin ####

**Comment by a3ilson** [comment]
@gyterpena - are you sending these logs to pfelk? If so could you navigate to Discover and select the *-pfelk-firewall_processes* index pattern. The php-app logs should be visible there along with the event.original values which are the raw message logs. Providing those will allow me to better assist as I am not running pfSense. The alternative would be capturing the pcap's but would suspect that would be more time intensive as you'll have limited php-app logs compare to all others.

Currently, I do not have these fields defined (mappings) but with your logs can correct this issue and build mappings making better use of the data.

**Comment by a3ilson** [comment]
@gyterpena - are you still having issues?

**Comment by gyterpena** [comment]
Hello

Sorry, no this is now fine. We don't use pfelk, just patterns for parsing. After changing patterns and match line in grok logs are parsed 

Regards
