### ISSUE TITLE
QNAP: systemd systemctl

### ISSUE THREAD

**Issue by Quasaur** [pfelk/pfelk#394]
This is not a bug complaint...you can relax!

I did the script install on Ubuntu 18.04 (bionic)
I seem to have an issue installing systemd, which is required to run the systemctl command to get Logstash going on Ubuntu.

This is a bit heartbreaking since most of the install seemed to go flawlessly...

...did i mention that I'm trying to do this on a QNAP TS-H686 NAS with 128GB RAM & 16TB disk space?
Tried first with Linux Station, then with Container Station (which was really cool because it gave me a bare-bones Ubuntu command line in which i could install EVERYTHING from scratch)!!!

Unfortunately, Linux Station grabbed ALL my RAM, which would be bad for the other NAS operations; fortunately Container Station allowed me to restrict both CPU & RAM resources used. 
However Container Station was weird in that no matter how i tried, i couldn't get systemd to load as PID 1, which is required by your script.

This is neither a rant, nor a complaint...think of it as a contribution to those daring enough to try the same thing.

If you have any comments or tips to share with me as I try the manual installation in Container Station, I would be IMMENSELY grateful.

Thank you for all the hard work you put into such a great project!

P.S.: It just hit me that on my last attempt i forgot to install java 14!!!

**Comment by a3ilson** [comment]
@Quasaur 

Have you tried @VMWare (ESXi) which is supported/certified for VMWare, Hyper-V and Veeam for the TS-h686? I've utilized ESXi on past builds with various Linux VMs and no issues installing pfelk (manual/script).  It is odd that the VM instance is giving you issues with systemd. Hopefully someone else has some insight regarding QNAP installations - I can not speak to either Linux Station or Contain Station other than reading about it online.  Based on my quick review, I would opine that the Container Station would be a better path. It supports both LXC/LXD and Docker both of which I've installed pfelk onto multiple times without issue (currently running pfelk via @Docker and do most of my testing on a LXC instance via @Proxmox

I am curious into how you derived to systemd running as PID 1 being required within the script - there is no requirement or link to the PID and it should run regardless of the PID.  

As for Java 14...you can install but it is not required. Logstash 7.10.+ has bundled Java and as such you can install but if it isn't installed, Logstash will run the bundled JDK. This is the same for GeoIP which is also bundled with Logstash.

**Comment by Quasaur** [comment]
Heart-felt thanks for your time and attention...it's been too long since I really got into containers, so I'm gonna go with Virtualization Station (VS) and a full Ubuntu bionic server install...that should take care of the systemd / systemctl issue (logstash could not be loaded because systemd wasn't PID 1). This is because the QTS OS on QNAP devices doesn't use systemd...no worries. VS will install a FULL Ubuntu server and allow a script install while allowing me to control how much RAM Ubuntu uses...putting the whole thing to rest.

**Comment by Quasaur** [comment]
The install went flawlessly...i just had to restart ElasticSearch.
The problem is that I'm a noob and an idiot when it comes to ELK; i know pfELK is receiving data (it has said as much), but I have NO IDEA how to reproduce your BEAUTIFUL charts & graphs.
Yes, I've watched your videos; but you fly through them so FAST that, even when I freeze the video(s) nothing makes any sense...
...LOL...any chance your have a step-by-step on what to do next?????

SORRY!!!!

P.S. Just joined the Elastic Stack Community on Slack as well as watching the Beginner's Crash Course to the Elastic Stack on Youtube.

**Comment by a3ilson** [comment]
I assume you installed via the script? If so the script should have installed all the saved objects (dashboards). 

Can you please confirm you are receiving data and check to see if the dashboards were installed?

Navigate to three horizontal lines
- Stack Management (scroll all the way to the bottom)
- Index Management 
- Click on Index Templates (provide screenshot)
- Click on Data Streams (provide screenshot)

Navigate to three horizontal lines
- Stack Management (scroll all the way to the bottom)
- Saved Objects (provide screenshot)

**Comment by Quasaur** [comment]
Once again, THANK YOU...I can only imagine how busy you are. I've just joined the Elastic Stack Community on Slack (calvin.mitchell@daimlertruck.com...this is not a work-related project; I'm just trying to understand the data from my home firewall: a Netgate SG-1100 running pfSense Plus 21.05.2) as well as watching the Beginner's Crash Course to the Elastic Stack on Youtube.

See attachments.
![Index_Management-Elastic](https://user-images.githubusercontent.com/1619078/149750346-4eb8669c-d424-4d30-92a0-a1602b838530.png)
![IM-DataStreams](https://user-images.githubusercontent.com/1619078/149750654-970dc021-eef8-49f3-b604-2688de8609b2.png)
![SavedObjects-Elastic](https://user-images.githubusercontent.com/1619078/149750954-05993de2-390d-4c2c-874d-c1fd1487a3b9.png)

**Comment by a3ilson** [comment]
@Quasaur - Appears that almost everything installed but I've see an issue or two with the dashboards failing to installed (unable to replicate but suspect starting time to be the culprit as Kibana can take up to 3minutes to fully start).

However, this is an easy fix:
### Script
(1) On the VM where you installed pfelk open the CLI
- type `wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/scripts/pfelk-dashboard-installer.sh`
- type `chmod +x pfelk-dashboard-installer.sh`
- ./pfelk-dashboard-installer
* these steps are also listed [here](https://github.com/pfelk/pfelk/blob/main/install/configuration.md#b-scripted-method-page_with_curl-1)

### Manual
(2) Navigate to the configuring page [here](https://github.com/pfelk/pfelk/blob/main/install/configuration.md#one-dashboards) and follow the steps within the manual method


That should install all the saved objects, allowing you to navigate to the various dashboards/visualizations. Let me know how that works out.

**Comment by Quasaur** [comment]
Exquisite! do i have to shutdown ELK before running the script or restart everything afterwards?

**Comment by a3ilson** [comment]
Nope, run while everything is running. After you’ve ran the script, all saved objects will be accessible.

**Comment by Quasaur** [comment]
OMG!!! IT'S WORKING!!!!!! (drunk with power)
