### ISSUE TITLE
_grokparsefailure for all HAProxy logs

### ISSUE THREAD

**Issue by TildeSlashC0re** [pfelk/pfelk#398]
**Describe the bug**
On a fresh bare-metal install of pfelk 22.01 (via script) I'm having trouble parsing all fields provided by the index pattern for `*-pfelk-haproxy-*`

**To Reproduce**
1. Install pfelk on a fresh debian11 machine
2. Import dashboards and objects via `pfelk-dashboard-installer.sh` (since the main install script failed to do so apparently)
3. Configure OpnSense remote logging to point to the debian11 machine port 5140
4. Configure haproxy logging as described in the documentation
5. Configure haproxy public service with `option tcplog` (it's a tcp mode frontend - the general issue remains in httpmode with httplog)
6. Receive `_grokparsefailure` tag on each received object

Example:
```json
{
  "_index": ".ds-logs-pfelk-haproxy-2022.01.24-000001",
  "_type": "_doc",
  "_id": "IpVkjH4BnKaR2r2lhMI_",
  "_version": 1,
  "_score": 1,
  "_source": {
    "service": {
      "type": "system"
    },
    "data_stream": {
      "namespace": "haproxy",
      "type": "logs",
      "dataset": "pfelk"
    },
    "process": {
      "pid": "60972",
      "name": "haproxy"
    },
    "@version": "1",
    "host": {
      "ip": "10.0.2.1"
    },
    "@timestamp": "2022-01-24T14:01:44.666Z",
    "event": {
      "original": "<131>Jan 24 15:01:44 haproxy[60972]: 172.70.85.211:61992 [24/Jan/2022:15:01:13.628] my-fronted~ my-pool/my-server-ssl 37/2/31010 794 cD 35/35/34/34/0 0/0\n",
      "dataset": "pfelk.haproxy",
      "created": "2022-01-24T14:01:44.000Z"
    },
    "tags": [
      "pfelk",
      "haproxy",
      "_grokparsefailure"
    ],
    "type": "firewall",
    "log": {
      "syslog": {
        "facility": {
          "code": 16,
          "name": "local0"
        },
        "severity": {
          "code": 3,
          "name": "Error"
        },
        "priority": 131
      }
    }
  },
  "fields": {
    "log.syslog.severity.code": [
      3
    ],
    "event.original": [
      "<131>Jan 24 15:01:44 haproxy[60972]: 172.70.85.211:61992 [24/Jan/2022:15:01:13.628] my-fronted~ my--pool/my-server-ssl 37/2/31010 794 cD 35/35/34/34/0 0/0\n"
    ],
    "process.name.text": [
      "haproxy"
    ],
    "data_stream.namespace": [
      "haproxy"
    ],
    "process.pid": [
      60972
    ],
    "type": [
      "firewall"
    ],
    "data_stream.type": [
      "logs"
    ],
    "tags": [
      "pfelk",
      "haproxy",
      "_grokparsefailure"
    ],
    "service.type": [
      "system"
    ],
    "host.ip": [
      "10.0.2.1"
    ],
    "process.name": [
      "haproxy"
    ],
    "log.syslog.facility.name": [
      "local0"
    ],
    "@timestamp": [
      "2022-01-24T14:01:44.666Z"
    ],
    "event.created": [
      "2022-01-24T14:01:44.000Z"
    ],
    "data_stream.dataset": [
      "pfelk"
    ],
    "@version": [
      "1"
    ],
    "log.syslog.severity.name": [
      "Error"
    ],
    "log.syslog.priority": [
      131
    ],
    "log.syslog.facility.code": [
      16
    ],
    "event.dataset": [
      "pfelk.haproxy"
    ]
  }
}
```

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Firewall System (please complete the following information):**
 - OPNsense 
 - 21.7.7-amd64
 
**Operating System (please complete the following information):**
```
Linux 5.10.0-11-amd64 x86_64
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
 
 **Installation method (manual, ansible-playbook, docker, script):**
`script` 
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - 7.16.2
 
~~ **Elasticsearch, Logstash, Kibana logs:**~~

~~**Additional context**~~

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file

**Comment by a3ilson** [comment]
@TildeSlashC0re - this was originally built in collaboration with @BeNeDeLuX (reference issue #151)

However, @BeNeDeLuX has since migrated to Nginx. I can certainly assist with updating but will need your help for testing/validation.

Based on previous endeavors a few years ago, the grok patterns still works but I noted that your referenced log contains some differences resulting in a grokfailure. Not sure if this is the result of HAProxy updates and/or configuration but let's start off with collecting additional logs.

Original log example:
- ```<134>Aug 22 20:27:09 haproxy[69803]: 89.238.73.76:33256 [22/Aug/2020:20:27:09.606] FrontServer_443~ Nextcloud_Backend/nextcloud 0/0/1/12/13 200 2180 - - ---- 2/2/0/0/0 0/0 \"GET //ocs-provider/ HTTP/1.1\"\n"```
Compared to:
- ```<131>Jan 24 15:01:44 haproxy[60972]: 172.70.85.211:61992 [24/Jan/2022:15:01:13.628] my-fronted~ my--pool/my-server-ssl 37/2/31010 794 cD 35/35/34/34/0 0/0\n"```

Your log parses fine up until we get to the numbers followed by forward slashes 
- ```37/2/31010 794 cD 35/35/34/34/0 0/0\n"``` <-- your log 
- ```0/0/1/12/13 200 2180 - - ---- 2/2/0/0/0 0/0 \"GET //ocs-provider/ HTTP/1.1\"\n``` <-- previous referenced HAProxy log

I could refine the logs but based on haproxy the log does not appear to be in the correct format ([reference](https://www.haproxy.com/wp-content/uploads/2017/07/aloha_load_balancer_memo_log.pdf))

Please provide more logs (e.g. event original values) and confirm HAProxy is configured properly.

**Comment by TildeSlashC0re** [comment]
Welp ... I went at it again and combed through the haproxy settings... 
I've switched my fronted/backend to http mode (ssl offloading) (n.b. NOT tcp) and lo and behold I'm receiving detailed httplogs... who would've thought. :man_facepalming: 

I guess you can consider this resolved.

though for good measure, this is what the log-entries I'm receiving now look like

```json
    "event.original": [
      "<134>Jan 25 02:51:12 haproxy[38003]: 172.70.162.165:54522 [25/Jan/2022:02:51:12.274] my-fronted~ my-pool/my-server-ssl 0/0/0/530/530 200 1148 - - ---- 72/72/34/34/0 0/0 \"GET /_matrix/federation/v1/event/%24uiAEdm6KpomFNs6EivXrZsJLLH6dBqiH1Ad2M0RXIqA HTTP/1.1\"\n"
    ],
```

**Comment by a3ilson** [comment]
Perfect! Those logs look more consistent with haproxy documentation.
