### ISSUE TITLE
_grokparsefailure on pfsense 2.4.3

### ISSUE THREAD

**Issue by anojht** [pfelk/pfelk#4]
I used your config files including the pfsense_2_4_2.grok with my pfsense 2.4.3 install.

But I get 100% _grokparsefailure when the logs come in. Because of this I don't have any of the fields you demonstrated in your video and guide to use with visualizers.
I pasted an example JSON message below:
`
{
  "_index": "logstash-2018.06.03",
  "_type": "doc",
  "_id": "YzYwx2MB7ZXvZXBcOCFc",
  "_version": 1,
  "_score": null,
  "_source": {
    "type": "syslog",
    "syslog_facility": "user-level",
    "@version": "1",
    "syslog_severity": "notice",
    "tags": [
      "syslog",
      "_grokparsefailure"
    ],
    "@timestamp": "2018-06-03T19:46:56.089Z",
    "syslog_severity_code": 5,
    "syslog_facility_code": 1,
    "host": "101.17.0.18",
    "message": "<134>Jun  3 12:46:56 filterlog: 9,,,1000000103,igb3,match,block,in,4,0x0,,51,16809,0,none,6,tcp,40,197.44.176.155,96.24.49.165,48368,23,0,S,1179624696,,4936,,"
  },
  "fields": {
    "@timestamp": [
      "2018-06-03T19:46:56.089Z"
    ]
  },
  "sort": [
    1528055216089
  ]
}
`

**Comment by anojht** [comment]
Thanks for your swift response and time in putting such a great guide together! I have uploaded my log below:
[logstash.log](https://github.com/a3ilson/pfelk/files/2066324/logstash.log)

**Comment by a3ilson** [comment]
I ran your output into a grok debugger and had no issues... can you confirm
you have a grok pattern (default location: /etc/logstash/conf.d/patterns/)
; Please go to Kibana>>Management>>Index Patterns>> and click on the
refresh button (next to the red trash can); Next provide a screenshot of
the Kibana>>Discover menu and a screenshot of what pfSense is pushing
(System Events/Firewall Events)

**Comment by anojht** [comment]
My grok pattern:
![image](https://user-images.githubusercontent.com/21053678/40891373-36402b9c-6739-11e8-8a82-1cfa3892c436.png)

Discover menu:
![image](https://user-images.githubusercontent.com/21053678/40891378-497c830e-6739-11e8-9851-51c0718db6b0.png)

pfSense Remote Log Settings:
![image](https://user-images.githubusercontent.com/21053678/40891387-66917fda-6739-11e8-8b60-a944704c0ac8.png)

**Comment by a3ilson** [comment]
Looks like your running ipv6?  I have not been able to complete the Grok
pattern for ipv6 as my service provider does not offer ipv6.   How
comfortable are you with editing the GROK pattern?  You could take the
output message and plugging it into https://grokdebug.herokuapp.com/ until
you've worked the ipv6 kinks out?  Or your welcome to post/reply with
several of your ipv6 outputs and i'll update the GROK pattern.

-Andrew

**Comment by anojht** [comment]
Actually I have IPv6 disabled on my firewall and to drop any IPv6 traffic. 
My network is entirely using IPv4. Even if your grok patterns do not support IPv6, why does IPv4 not seem to work either? I can't import and use your dashboards/searches/visualizers since I am missing all the necessary fields.

![image](https://user-images.githubusercontent.com/21053678/40891597-48be6604-673d-11e8-87cf-7faf404212cf.png)

**Comment by anojht** [comment]
I am completely new to grok so I can try working out the ipv6 pattern. As for helping with ipv6 I can help you with ipv6 entries in my log that are being dropped, it's the least I could do for you graciously making this guide open source:

Time | Message
-- | --
Jun 3 14:52:46 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,86,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,86
Jun 3 14:52:43 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,86,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,86
Jun 3 14:52:42 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,86,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,86
Jun 3 14:52:33 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,98,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,98
Jun 3 14:52:30 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x1839f,255,ICMPv6,58,16,fe80::146c:4c5b:1204:bb14,ff02::2,
Jun 3 14:52:25 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x1839f,255,ICMPv6,58,16,fe80::146c:4c5b:1204:bb14,ff02::2,
Jun 3 14:52:24 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,98,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,98
Jun 3 14:52:23 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,86,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,86
Jun 3 14:52:21 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,86,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,86
Jun 3 14:52:21 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,98,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,98
Jun 3 14:52:18 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,98,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,98
Jun 3 14:52:17 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x00000,1,Options,0,36,fe80::146c:4c5b:1204:bb14,ff02::16,HBH,PADN,RTALERT,0x0000,
Jun 3 14:52:15 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,98,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,98
Jun 3 14:52:15 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x00000,1,Options,0,36,fe80::146c:4c5b:1204:bb14,ff02::16,HBH,PADN,RTALERT,0x0000,
Jun 3 14:52:14 | filterlog: 5,,,1000000003,igb0,match,block,in,6,0x00,0x526c3,255,UDP,17,98,fe80::146c:4c5b:1204:bb14,ff02::fb,5353,5353,98

**Comment by a3ilson** [comment]
did you use the files from github or did you follow the guide on
pfelk.3ilson.com and utilize those files?

**Comment by anojht** [comment]
I used the files on Github as I followed your guide.

**Comment by a3ilson** [comment]
Remove the two lines (#x-pack....) from within the 30-outputs.conf file.
Then execute the following command: systemctl restart logstash.service

**Comment by anojht** [comment]
Done logstash restarted without issues but still the same results.

**Comment by a3ilson** [comment]
Dang....well give this a try

navigate to your configuration folder:
cd /etc/logstash/conf.d/
sudo rm *
cd patterns
sudo rm *
cd ..
wget https://github.com/a3ilson/pfelk/raw/master/All%20Files%20Zipped.zip
unzip All Files Zipped.zip
sudo nano 10-syslog.conf

////update the first host from:
if [host] =~ /10\.0\.0\.1/ {

to the following:
if [host] =~ /172\.168\.1\.1/ {


systemctl restart logstash.service

**Comment by anojht** [comment]
Wait your 11-pfsense.conf file has two typos, the location of the GeoIP database should be /etc/logstash/ instead of /usr/share and also should that if host line be the ip of my pfsense which is 192.168.1.1 or my elk host which is 172.168.1.2?

**Comment by a3ilson** [comment]
Depends on where GeoIP is installed....adjust to point to the correct
location.  As for the IP address, that should be the ip address of your
pfSense

**Comment by anojht** [comment]
ok ran those sequence of commands, made the appropriate changes and restarted the service. Still getting the same results. Is this because I am on 2.4.3 and these files are not compatible anymore?

**Comment by a3ilson** [comment]
Nope, I am running the same version and those files were copied directly
from my instance which is currently.  The only difference is our pf
settings....however, I adjusted mine to match...didn't have any issues.
Are you running any extra packages?

running.

**Comment by anojht** [comment]
Ok finally, we have something different lol 
Now I am getting these error messages in stdout of my docker container:

```
```
[2018-06-03T22:59:20,748][ERROR][logstash.pipeline ] Error registering plugin {:pipeline_id=>"main", :plugin=>"#<LogStash::FilterDelegator:0x3771f2f @metric_events_out=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 - name: out value:0, @metric_events_in=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 - name: in value:0, @metric_events_time=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 - name: duration_in_millis value:0, @id=\"133ce2137b4dbbc0e088c90322bfabf68bab54416afdd92002eef681741eaae1\", @klass=LogStash::Filters::Grok, @metric_events=#<LogStash::Instrument::NamespacedMetric:0x1f6fa712 `@metric`=#<LogStash::Instrument::Metric:0x3c3fd134 @collector=#<LogStash::Instrument::Collector:0x2ba83b99 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x109dd7a4 @store=#<Concurrent::Map:0x00000000000fc8 entries=3 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x5ac2fdf3>, @fast_lookup=#<Concurrent::Map:0x00000000000fcc entries=202 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :filters, :\"133ce2137b4dbbc0e088c90322bfabf68bab54416afdd92002eef681741eaae1\", :events]>, @filter=<LogStash::Filters::Grok patterns_dir=>[\"/etc/logstash/conf.d/patterns\"], match=>{\"message\"=>\"%{PFSENSE_SURICATA}\"}, id=>\"133ce2137b4dbbc0e088c90322bfabf68bab54416afdd92002eef681741eaae1\", enable_metric=>true, periodic_flush=>false, patterns_files_glob=>\"*\", break_on_match=>true, named_captures_only=>true, keep_empty_captures=>false, tag_on_failure=>[\"_grokparsefailure\"], timeout_millis=>30000, tag_on_timeout=>\"_groktimeout\">>", :error=>"pattern %{I P:ids_src_ip} not defined", :thread=>"#<Thread:0x13af94cc run>"}

[2018-06-03T22:59:21,145][ERROR][logstash.pipeline ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<Grok::PatternError: pattern %{I P:ids_src_ip} not defined>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/2.3.0/gems/jls-grok-0.11.4/lib/grok-pure.rb:123:in `block in compile'", "org/jruby/RubyKernel.java:1292:in `loop'", "/opt/logstash/vendor/bundle/jruby/2.3.0/gems/jls-grok-0.11.4/lib/grok-pure.rb:93:in `compile'", "/opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-4.0.3/lib/logstash/filters/grok.rb:281:in `block in register'", "org/jruby/RubyArray.java:1734:in `each'", "/opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-4.0.3/lib/logstash/filters/grok.rb:275:in `block in register'", "org/jruby/RubyHash.java:1343:in `each'", "/opt/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-4.0.3/lib/logstash/filters/grok.rb:270:in `register'", "/opt/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `register_plugin'", "/opt/logstash/logstash-core/lib/logstash/pipeline.rb:353:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/opt/logstash/logstash-core/lib/logstash/pipeline.rb:353:in `register_plugins'", "/opt/logstash/logstash-core/lib/logstash/pipeline.rb:731:in `maybe_setup_out_plugins'", "/opt/logstash/logstash-core/lib/logstash/pipeline.rb:363:in `start_workers'", "/opt/logstash/logstash-core/lib/logstash/pipeline.rb:290:in `run'", "/opt/logstash/logstash-core/lib/logstash/pipeline.rb:250:in `block in start'"], :thread=>"#<Thread:0x13af94cc run>"}

[2018-06-03T22:59:21,203][ERROR][logstash.agent ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main, action_result: false", :backtrace=>nil}
```
```

**Comment by a3ilson** [comment]
Dang... the file didn't copy correctly....

Go into your patterns directory and remove the file then download the
following:

wget https://github.com/a3ilson/pfelk/blob/master/pfsense2_4_3.grok

systemctl restart logstash.service

**Comment by anojht** [comment]
The new file has large spaces as well but its ok I removed them and restarted logstash.
Now I get 124 fields and this looks much better! 
However my discover window is completely empty, is that normal?

**Comment by a3ilson** [comment]
Excellent!  Let it run for a little bit (1-3min) then refresh your browser
and the discover should populate.

**Comment by anojht** [comment]
Discover menu is populating however still 100% _grokparsefailure :( 
What are we missing here? lol

**Comment by anojht** [comment]
I am running pfsense 2.4.3 with the latest Suricata running in inline mode on my WAN and LAN. I have openvpn, ntop, pfblockerng running as packages. I think all of this is pretty standard?

**Comment by a3ilson** [comment]
I have all the same packages running...So you got 124 fields but within discover everything is still failing?

**Comment by anojht** [comment]
Yeah every single entry has the _grokparsefailure tag. I filter by tags and it shows 100% failure...

**Comment by anojht** [comment]
Idk if this is useful but the docker container I am running is using the latest version of Elasticsearch, Logstash, Kibana which is 6.2.4.....

You said your configuration which you currently have running and working, which version of the ELK stack are you running?

**Comment by a3ilson** [comment]
I am running the same version. I have still have some _grokparsefailures but mostly within ipv6 (RTALERT).  I assuming something is slightly different or off which is causing the issue....can you provide a couple of your messages? Do you have any that are tagged with pfsense, firewall, dhcpd, etc...

**Comment by anojht** [comment]
Here is something weird, every single entry has only two tags: syslog and _grokparsefailure

```
{
  "_index": "logstash-2018.06.04",
  "_type": "doc",
  "_id": "9wIdyGMB0SL-14aK_cgP",
  "_version": 1,
  "_score": null,
  "_source": {
    "syslog_facility": "user-level",
    "@version": "1",
    "message": "<134>Jun  3 17:06:38 filterlog: 81,,,1770008623,igb3,match,block,in,4,0x0,,244,54321,0,none,6,tcp,40,107.170.231.4,70.79.164.248,40426,9000,0,S,716072279,,65535,,",
    "type": "syslog",
    "syslog_severity_code": 5,
    "syslog_facility_code": 1,
    "tags": [
      "syslog",
      "_grokparsefailure"
    ],
    "host": "172.168.1.1",
    "syslog_severity": "notice",
    "@timestamp": "2018-06-04T00:06:38.488Z"
  },
  "fields": {
    "@timestamp": [
      "2018-06-04T00:06:38.488Z"
    ]
  },
  "sort": [
    1528070798488
  ]
}
```
```
{
  "_index": "logstash-2018.06.04",
  "_type": "doc",
  "_id": "8wIdyGMB0SL-14aKyMhD",
  "_version": 1,
  "_score": null,
  "_source": {
    "syslog_facility": "user-level",
    "@version": "1",
    "message": "<141>Jun  3 17:06:24 suricata[11921]: [Drop] [1:2009582:3] ET SCAN NMAP -sS window 1024 [Classification: Attempted Information Leak] [Priority: 2] {TCP} 5.188.86.27:59762 -> 70.79.164.248:52975",
    "type": "syslog",
    "syslog_severity_code": 5,
    "syslog_facility_code": 1,
    "tags": [
      "syslog",
      "_grokparsefailure"
    ],
    "host": "172.168.1.1",
    "syslog_severity": "notice",
    "@timestamp": "2018-06-04T00:06:24.968Z"
  },
  "fields": {
    "@timestamp": [
      "2018-06-04T00:06:24.968Z"
    ]
  },
  "sort": [
    1528070784968
  ]
}
```
```
{
  "_index": "logstash-2018.06.04",
  "_type": "doc",
  "_id": "8AIdyGMB0SL-14aKZsi5",
  "_version": 1,
  "_score": null,
  "_source": {
    "syslog_facility": "user-level",
    "@version": "1",
    "message": "<190>Jun  3 17:05:59 dhcpd: DHCPACK on 172.168.1.7 to 52:54:00:68:0b:82 (freebsd) via igb2",
    "type": "syslog",
    "syslog_severity_code": 5,
    "syslog_facility_code": 1,
    "tags": [
      "syslog",
      "_grokparsefailure"
    ],
    "host": "172.168.1.1",
    "syslog_severity": "notice",
    "@timestamp": "2018-06-04T00:05:59.988Z"
  },
  "fields": {
    "@timestamp": [
      "2018-06-04T00:05:59.988Z"
    ]
  },
  "sort": [
    1528070759988
  ]
}
```

**Comment by a3ilson** [comment]
Check your Suricata log settings: Services>>Suricata>>Interfaces>>WAN Settings
![suricata](https://user-images.githubusercontent.com/16884679/40892843-1175ee60-676a-11e8-80aa-0b792263401c.png)

**Comment by anojht** [comment]
Yup we have the same settings for Suricata

**Comment by a3ilson** [comment]
Take a look at line 38 within the 10-syslog.conf file: locale => "en".  This may be the culprit.... change to the appropriate language code.

"en", "CA"
"CA"
"fr_CA"
"en_CA" 

I would adjust the locale to match what your utilizing....once changed you'll need to restart Logstash (systemctl restart logstash.service).

**Comment by anojht** [comment]
My file only has one block which points to my single pfsense instance. I have already removed the second block. 

Ah I see, my pfsense is set to English which is en_US I just changed the language code to en_US but still the same result. I have been at this two days, and just about tried the best I could....I still have no idea why it won't parse correctly....

**Comment by a3ilson** [comment]
The GROK pattern works...I've taken and tested your message output.  Both our setups are essential the same.  I would troubleshoot pfSense (their documentation is somewhat horrible);  

Suggest:  a clean/fresh install of pfSense (spare computer, VM, docker etc...) 
Configure just the log portion to send to your ELK stack
Configure 10-syslog.conf to listen to the new IP address of your vanilla pfSense instance

If that works...I would add one package at a time while testing afterwards and hopefully identifying/troubleshooting the specific issue. It does appear that the DHCP/Suricata messages look good minus the prefix in the message that is inhibiting proper filtering.  You may be able to adjust the filter to read and interpret the "syslog_facility": "user-level", which doesn't appear on mine.

{
  "_index": "logstash-2018.06.04",
  "_type": "doc",
  "_id": "_rxEyGMB0mW2pC3sUqhW",
  "_version": 1,
  "_score": null,
  "_source": {
    "proto": "tcp",
    "direction": "in",
    "ip_ver": "4",
    "src_port": "55291",
    "offset": "0",
    "tos": "0x0",
    "dest_port": "443",
    "length": "83",
    "evtid": "134",
    "prog": "filterlog",
    "id": "36350",
    "iface": "igb1",
    "tracker": "1000000103",
    "action": "block",
    "@version": "1",
    "src_ip": "10.0.0.30",
    "reason": "match",
    "data_length": "31",
    "flags": "DF",
    "proto_id": "6",
    "host": "10.0.0.1",
    "ttl": "64",
    "message": "9,,,1000000103,igb1,match,block,in,4,0x0,,64,36350,0,DF,6,tcp,83,10.0.0.30,34.202.184.200,55291,443,31,PA,219253599:219253630,4059336140,30407,,nop;nop;TS",
    "rule": "9",
    "tags": [
      "pfsense",
      "firewall",
      "firewall"
    ],
    "type": "syslog",
    "@timestamp": "2018-06-04T00:48:30.000Z",
    "dest_ip": "34.202.184.200"
  },
  "fields": {
    "@timestamp": [
      "2018-06-04T00:48:30.000Z"
    ]
  },
  "sort": [
    1528073310000
  ]
}

**Comment by a3ilson** [comment]
I believe I found it....

within your 10-syslog.conf file what tag is added to your host? 

filter {
  if [type] == "syslog" {
    if [host] =~ /10\.0\.0\.1/ {
      mutate {
        add_tag => ["pfsense", "Ready"]

Be sure that ["pfsense", "Ready"] is added.

This is vital for the 11-pfsense.conf to correctly extract the evtid and date

**Comment by anojht** [comment]
First of all thank you so much for your time and help. I do not have doubts in your files. I know the problem lies somewhere in my configuration.

This is how my 10-syslog.conf file starts out, I noticed you don't have slashes for your ip??
EDIT: nvm that's just Github escaping if not put inside codeblocks
```
filter {
  if [type] == "syslog" {
    if [host] =~ /192\.168\.1\.1/ {
      mutate {
        add_tag => ["pfsense", "Ready"]
      }
    }

    if "Ready" not in [tags] {
      mutate {
        add_tag => [ "syslog" ]
      }
    }
  }
}
filter {
  if [type] == "syslog" {
    mutate {
      remove_tag => "Ready"
    }
  }
}
```

**Comment by a3ilson** [comment]
I copied but the slashes did not....yours is correct.

**Comment by anojht** [comment]
Odd question, my host server which is running unRAID OS is running docker with the elk container on a bridge network. The ports are correctly setup between the container and the host. Could this network setup be the culprit?

I ask because I did not do the initial hostname stuff since I didn't think it was important as I am running inside a docker environment where hostnames don't stick. Are those initial two steps necessary?

**Comment by a3ilson** [comment]
Give this a try....
edit your 10-syslog.conf and add the following below the "add_tag => [ "firewall" ]" line

      match => [ "message", "<(?<evtid>.*)>(?<datetime>(?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)?|May|Jun(?:e)?|Jul(?:y)?|Aug(?:ust)?|Sep(?:tember)?|Oct(?:ober)?|Nov(?:ember)?|Dec(?:ember)?)\s+(?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9]) (?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:[0-5][0-9])) (?<prog>.*?): (?<msg>.*)" ]
            }
            mutate {
              gsub => ["datetime","  "," "]
            }
            date {
              match => [ "datetime", "MMM dd HH:mm:ss" ]
            }
            mutate {
              replace => [ "message", "%{msg}" ]
            }
            mutate {
              remove_field => [ "msg", "datetime" ]
            }

**Comment by a3ilson** [comment]
essentially changing the order in hopes it properly filters.  Your files, setup are good but for some odd reason the filtering is not taking/working.  I would focus on that area...making sure you conduct restarts of logstash after each change....looking for the message to be properly filtered.

**Comment by anojht** [comment]
Thank you I will try and troubleshoot the syslog.conf file since the problem exists here for sure. Adding the previous message's settings to this file results in a config error. I will keep trying!

**Comment by a3ilson** [comment]
Good luck.  I will conduct a fresh/new install this weekend and see if I
can devise a filter to get you up and running.  I upgraded from ELK
v6.0....

**Comment by Metric** [comment]
I just would like to note, that whenever someone includes an @Metric in their debug log and posts it on Github comments somewhere, I am pinged in as part of the message. If you could be so kind and rename @Metric in your debug log to something else, that would be great. Just don't use the @ in front and it would be fine.

I know very well, that it may be part of LogStash, but please see what you can do.

Thanks.

**Comment by anojht** [comment]
Sorry for that, logstash uses (at)Metric. I will try to be aware of this in the future.

@a3ilson I got it to work!! Had to change the IP of host to my server's subnet IP. This is because of my environment where I had elk running as a container virtually bridged to the server's network. Hence, pfsense was sending to my servers address which was then sending the traffic to the docker container. 

Thanks again for your time and effort into putting this awesome guide and conf files together!

Cheers,
Anojh
