### ISSUE TITLE
No Indices and no ILM for pfelk on fresh install (pfelk 22.01)

### ISSUE THREAD

**Issue by s0p4LiN** [pfelk/pfelk#401]
**Describe the bug**
I do not have any indices on my fresh install pfelk 22.01 but I have one one my old 21.10 pfelk

**To Reproduce**
1. Go to 'Stack Managemeent > Indices'
2. See error (no indice)

**Screenshots**

**No indice**

![22 01 pfelk](https://user-images.githubusercontent.com/68989865/151059942-7929c3c1-79b5-4559-8770-4e79399795e9.PNG)

**If i click on hidden indice, there are many indices, and one related to pfelk logs **

![pfelk hidden indice 22 01](https://user-images.githubusercontent.com/68989865/151060081-26295fc2-2e7c-4da5-91a3-5a7cd4cae2ef.PNG)

**.ds-logs-pfelk-firewall-2022.01.25-000001**

![error lifecycle](https://user-images.githubusercontent.com/68989865/151060218-f45dd5a3-3c67-448a-b3c1-8852c2b0cbfe.PNG)

**Heres an example of my old 21.10 pfelk indices:**

![21 10 pfelk](https://user-images.githubusercontent.com/68989865/151060410-bffc6554-5c73-417b-82b5-d5f550546c61.PNG)

As you can see there are all indices...

**Firewall System (please complete the following information):**
 - pfSense 
 - Version 2.5.0 RC
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 
```
Linux 5.4.78-2-pve x86_64
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

 **Installation method (manual, ansible-playbook, docker, script):**
Scripted installation
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)

 
 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 - Kibana logs (`journalctl -u kibana.service`)

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file

**Comment by s0p4LiN** [comment]
I have fixed the pfelk ILM policy missing by creating it, now it is linked but it seems still different than the 21.10 version, the Indice are all hidden..

![image](https://user-images.githubusercontent.com/68989865/151071053-d602d780-f424-43ca-a273-526a94aba74a.png)

**Comment by a3ilson** [comment]
The new version v22.X utilizes datastreams and you will not or should not see pfelk indices.

## Data Streams
![Screen Shot 2022-01-25 at 8 48 18 PM](https://user-images.githubusercontent.com/16884679/151089657-4b3feeb0-bce0-4975-8eeb-3319cf4b4ea5.png)

## ILM
![Screen Shot 2022-01-25 at 8 48 51 PM](https://user-images.githubusercontent.com/16884679/151089755-d8462267-0cf6-47ed-9889-786c95684f61.png)

- [ ] Please check to see if you have Data Streams 
- [ ] Please check to see if you have linked indices to the pfelk ILM

**Comment by s0p4LiN** [comment]
I have the datastream correctly, but I did not had the pfelk ILM.

I had in the first place pfelk-ilm but not pfelk. I created the pfelk policy in order to fix the issue.

![image](https://user-images.githubusercontent.com/68989865/151133988-17656678-c185-4697-bf46-755196f90e8b.png)

**Comment by a3ilson** [comment]
Excellent! I assume all is working now?

**Comment by s0p4LiN** [comment]
Yes, all is working, thank your for the reactivity !

**Comment by uhhmeeyell** [comment]
Hello. I have a similar problem with a brand new install of OPNsense 22.1 along with a fresh install of your full pfelk script and dashboards. Nothing shows up on my Index Management (stream) while I also tried to add pfelk in the Index Lifecycle Policies but shows zero Linked Indices. Could this be tied to the new option "rfc5424"?

**Comment by a3ilson** [comment]
@uhhmeeyell

RFC5424 is an option within OPNsense 22.01 but it will not cause any issues. However, the new added field when RFC 5424 is enabled does not currently parsed but has not issues with the current configuration.
![Screen Shot 2022-02-03 at 7 44 22 AM](https://user-images.githubusercontent.com/16884679/152346000-0deb4c06-bb56-4224-8953-94df5b3650a1.png)



As for your specific issue. The ILM will have no impact...but it sounds as though the templates may not have installed. Please check to confirm if the required index templates were installed:
![Screen Shot 2022-02-03 at 7 50 26 AM](https://user-images.githubusercontent.com/16884679/152346283-b75d04ab-cf47-4362-97ee-4141003fec33.png)


If you are missing the templates, you can install manually or via a script. Sometimes the script method depending on hardware) attempts to install the scripts prior to elastic services running.

https://github.com/pfelk/pfelk/blob/main/install/configuration.md#zero-templates

**Comment by uhhmeeyell** [comment]
Hi @a3ilson. Thank you for the comment. I have verified that I do have the Index Management templates installed. I took some screen shots below of what my configuration looks like. I have pfelk running on:

Linux 5.4.0-97-generic x86_64
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

Please let me know your thoughts.

![Screenshot from 2022-02-03 20:54:01](https://user-images.githubusercontent.com/60636349/152474604-09ba9082-b74b-401a-abe2-0c6b4103f04d.png)

![Screenshot from 2022-02-03 20:53:46](https://user-images.githubusercontent.com/60636349/152474632-54fbc54e-d27d-41be-8834-79c0ec43e1f8.png)

![Screenshot from 2022-02-03 20:53:33](https://user-images.githubusercontent.com/60636349/152474640-819c3218-592a-45e2-a1b8-7b8a3219c70f.png)

![Screenshot from 2022-02-03 20:53:13](https://user-images.githubusercontent.com/60636349/152474647-567abfb9-eb5f-48ae-9ab3-9194ff269610.png)

![Screenshot from 2022-02-03 20:52:29](https://user-images.githubusercontent.com/60636349/152474684-3f988176-c4be-46d6-8db4-8ab71e5e243e.png)

I used your scripted method for both pfelk install and dashboards. I have attempted to disable my firewall but produced no change in communication.

**Comment by a3ilson** [comment]
@uhhmeeyell 

Thanks for providing the above screenshots, they all look good. You mentioned that you created an ILM policy. The script would have installed one (pfelk) and I assume the one you installed is pfelk-ilm? It will have not impact but you can remove the pfelk-ilm (no linked indices). Next, could you provide a screen shot of the Data Stream tab as shown below:
![Screen Shot 2022-02-04 at 3 55 39 AM](https://user-images.githubusercontent.com/16884679/152500228-0ffe0692-2488-4e7b-b3a8-933e65bdaed2.png)

The latest versions on pfelk (v22.01) migrated from Indices to Data Streams. 

Next, confirm that the Kibana objects were imported by navigate to stack management>>saved objects:
![Screen Shot 2022-02-04 at 3 57 54 AM](https://user-images.githubusercontent.com/16884679/152500611-f0172795-96be-4fb5-b29f-572b4325d88e.png)

You should have a various saved objects as depicted above.


Finally, if all those appear to be in order, let's take a look at your Logstash logs:
navigate to the system with pfelk installed and run the following command `tail -20 /var/log/logstash/logstash-plain.log`. Additionally, you may run the error-data.sh script and provide the generated log file here (as an attachment) for further review/inspection which by default (script installation) should be located -> `/etc/pfelk/scripts/`

**Comment by uhhmeeyell** [comment]
Hi @a3ilson. Thank you so much for your assistance! I have provided what you requested:

![Screenshot from 2022-02-04 17:55:35](https://user-images.githubusercontent.com/60636349/152624924-4e3bbb28-56b5-4fdd-b742-2a9901e5fa39.png)

![Screenshot from 2022-02-04 17:54:53](https://user-images.githubusercontent.com/60636349/152624927-27ea4f75-0361-4350-9321-4c3cbf2bc51c.png)

[error.pfelk.log](https://github.com/pfelk/pfelk/files/8007172/error.pfelk.log)

[logstash-plain.log](https://github.com/pfelk/pfelk/files/8007173/logstash-plain.log)

**Comment by a3ilson** [comment]
Thanks!

I'm doing a clean install, in an attempt to duplicate the issue.

It appears everything is setup/configured but logs from OPNsense to pfelk appears to be the issue. Can you run the following command to check if logs are being sent and received by the system running pfelk:

`sudo tcpdump -vvvv -A -i any port 5140`

**Comment by uhhmeeyell** [comment]
I got some weird (partial) results after loading 50 web pages back to back:

![Screenshot from 2022-02-04 19:29:09](https://user-images.githubusercontent.com/60636349/152627285-55a3f171-70ce-4186-b318-c61fd5b7182b.png)

Nothing shows up on Data Streams tab :(

**Comment by a3ilson** [comment]
check the status of logstash and provide the output
`sudo systemctl status logstash.service`

**Comment by uhhmeeyell** [comment]
![Screenshot from 2022-02-04 19:41:02](https://user-images.githubusercontent.com/60636349/152627532-97b39e05-e22b-42b9-8986-1a1d1b61201c.png)

**Comment by a3ilson** [comment]
Odd...your original error.log depicted an error (i.e. Logstash shutdown). However, it shows running. I took another look at your logs and the geoip config appears to be the culprit.

According to your logs:
- GeoIP files are `/etc/pfelk/geoip`

The 30-geoip.conf:
- If MaxMind is utilized, references those files `/var/lib/GeoIP`


Check both paths:
- `ls /etc/pfelk/GeoIP/`
- `ls /var/lib/GeoIP/`

**Comment by uhhmeeyell** [comment]
Success!!! I made the change on 30-geoip.conf with the correct working directory. I'm getting streams and still crawling ... This is awesome!! Thank you sooooo much!

![Screenshot from 2022-02-04 19:59:40](https://user-images.githubusercontent.com/60636349/152628219-04a60ac5-0fde-4253-b9d6-d2ab3f09155c.png)

![Screenshot from 2022-02-04 20:12:11](https://user-images.githubusercontent.com/60636349/152628220-6216cbee-7a09-4e6a-bc15-3143db821c0c.png)

This is a bit weird how Maxmind GeoIP can prevent all functionality.

**Comment by a3ilson** [comment]
No worries! Thanks for reaching out! I updated the script to correct the MaxMind GeoIP path. Logstash has Java and GeoIP baked in and neither are required but may be utilized, if desired.

Tth 30-geoip.conf had the correct path (`/lib/bar/GeoIP/` but the script contained an older path. As long as the reference in 30-geoip.conf points to the file(s) it doesn't matter where they are.

**Comment by a3ilson** [comment]
Logstash is a bit sensitive...any reference that does not exist results in nothing working
