### ISSUE TITLE
OPNsense v22.1 RFC 5424

### ISSUE THREAD

**Issue by a3ilson** [pfelk/pfelk#403]
**Describe the bug**
OPNsesne v22.1 added RFC 5424 support 

**Screenshots**
![Screen Shot 2022-01-27 at 10 27 30 PM](https://user-images.githubusercontent.com/16884679/151482337-6a015cda-48b6-4892-b3f3-31040d1893b5.png)

**Firewall System (please complete the following information):**
 - OPNsense
 - Version 22.1
 
**Operating System (please complete the following information):**
 - Docker Installation
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - 7.16.3
 

- [ ] Add GROK support for OPNsense RFC 5424
- [x] Parses RFC 5424 logs ignoring the meta sequenceID integer 
  - Ignore or add to GROK

**Comment by a3ilson** [comment]
New GROK which adds the field `event.sequence` when RFC 5424 is ticked (OPNsense only)

```
<%{POSINT:[log][syslog][priority]}>?(%{INT:[log][syslog][version]}\s*)?(%{SYSLOGTIMESTAMP:[event][created]}|%{TIMESTAMP_ISO8601:[event][created]})\s(%{SYSLOGHOST:[host][name]}\s+)?(%{PROG:[process][name]}\:|%{PROG:[process][name]})(\s*)?(\[)?(%{POSINT:[process][pid]}(\]:)?)?\s*(\-\s*\-)?(-\s*)?\s*(\[meta sequenceId=\"%{INT:[event]sequence]}\"\]\s)?*%{GREEDYDATA:filter_message}
```

Works but breaks pfSense Logs

**Comment by tweak19** [comment]
Hi,
I am using the new version of opnsense, and i get stuck that there are no firewall-logs in kibana. Already tried to setup pfelk few times but it didn't work. Could you explain that?
I didn't check the RF 5424 box as descriped in the wiki. Months before ive got pfelk running with this setup, but now it didn't work.
And I didn't receive a Firewall-Dashboard at installation, is that korrekt?

Thanks!

**Comment by a3ilson** [comment]
What method did you install it with?

Can you provide and output from the error-data script (/etc/pfelk/scripts/error-data.sh)

**Comment by tweak19** [comment]
Hi, 
I try to use the script installer and the manual method, both with the same ending scenario.
Here the output from error-data script
[error.pfelk.log](https://github.com/pfelk/pfelk/files/8311738/error.pfelk.log)

**Comment by a3ilson** [comment]
Based on the log file, everything appears to be running. Let's try the following:

Cleanup the `/etc/pfelk/conf.d/` to only the following files:
- 01-inputs.pfelk
- 05-apps.pfelk
- 30-geoip.pfelk  
- 49-cleanup.pfelk
- 50-outputs.pfelk

Next, restart logstash (systemctl restart logstash.service). Give it a few and let me know if that works. If not we'll check on some additional items (logstash roles/permissions).

**Comment by tweak19** [comment]
Done, but still nothing from pfelk-firewall...
nginx, dhcp, work, but i can't get anything from the firewall...

**Comment by a3ilson** [comment]
awe...so nginx, dhcp, are receiving logs.  Typically, the logs would be captured with grok failures or Logstash errors but neither of those appear to be the cause here.

Check the following within opnsense:

![Screen Shot 2022-03-20 at 13 32 18](https://user-images.githubusercontent.com/16884679/159174921-64615404-f092-44aa-a48b-26a421d49429.png)

Which one's do you have ticked.

**Comment by tweak19** [comment]
I tried both, without anything selected as shown in the wiki and with the use-cases i need. Nothing would change anything to give me a "Firewall-Log"

**Comment by a3ilson** [comment]
The "filter (filterlog) " is the item required to obtain firewall messages.

**Comment by a3ilson** [comment]
I've had issues with past OPNsense versions where I had to stop and restart syslog-ng or enable/disable remote logging.

**Comment by a3ilson** [comment]
Next, login to Kibana and navigate to Stack Managment>>Index Management. What data streams are listed on your system.

**Comment by tweak19** [comment]
![grafik](https://user-images.githubusercontent.com/13833136/159175333-27f86938-2de7-4fa2-aa27-d17dbf4e3d1e.png)

Datastreams looks good, but if i go to discover nothing applys

**Comment by a3ilson** [comment]
Do you have the option within discover?

**Comment by tweak19** [comment]
nope, thats what i am missing

**Comment by a3ilson** [comment]
gotcha

**Comment by a3ilson** [comment]
Easy fix.... you'll need to manually import the missing saved objects:

https://github.com/pfelk/pfelk/blob/main/install/security.md#three-dashboards

**Comment by tweak19** [comment]
Didn't fix the issue, that i already tried.

**Comment by a3ilson** [comment]
Do these show up?

![Screen Shot 2022-03-20 at 13 51 29](https://user-images.githubusercontent.com/16884679/159175668-c9d3f30e-e008-474a-9fd3-f9ae82e35a70.png)

**Comment by tweak19** [comment]
No, thats empty, looks like there an issue?

**Comment by tweak19** [comment]
found it,
typo in the link for the firewall-dashboard
https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/dashboard/22.01-firewall.ndjson

**Comment by a3ilson** [comment]
Try the attached...if that works, I'll update the repo.

Be sure to remove the trailing .txt


[export.ndjson.txt](https://github.com/pfelk/pfelk/files/8311859/export.ndjson.txt)

**Comment by a3ilson** [comment]
Where are you pulling that link?  The listed here: https://github.com/pfelk/pfelk/blob/main/install/security.md is correct (step 3a)

**Comment by tweak19** [comment]
I corrected the script, looks the download path was wrong, but the install path looks correct.

**Comment by a3ilson** [comment]
https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/dashboard/22.04-firewall.ndjson

**Comment by tweak19** [comment]
https://github.com/pfelk/pfelk/blob/main/etc/pfelk/scripts/pfelk-kibana-saved-objects.sh
the script i used

**Comment by a3ilson** [comment]
Sorry about that and thanks/updated the script

**Comment by a3ilson** [comment]
Sorry about that and thanks/updated the script

**Comment by tweak19** [comment]
No way, thanks for your help!
Just a short question, there are any dashboards for vpn planned?

**Comment by a3ilson** [comment]
what type of logs? OpenVPN is on the list but those logs are a bit messy but any help is appreciated.

**Comment by tweak19** [comment]
Thanks for your answer depenting on openvpn.
Another question, is there still anything wrong with suricata and captive-dashboard?
I didn't get any usefull inormation there.

**Comment by a3ilson** [comment]
What is the specific issue with the suricata/captive dashboards?

**Comment by tweak19** [comment]
At the captive dashboard it looks that there is something wrong with the regex or the index

![grafik](https://user-images.githubusercontent.com/13833136/183267092-6b8d1134-34f5-40f5-a4b2-038f422e5a72.png)

And at suricata I didn't get anything:

![grafik](https://user-images.githubusercontent.com/13833136/183267115-58b407f2-d284-41a6-acbf-f43ab01a6d78.png)

**Comment by a3ilson** [comment]
Agreed.
Are you and you send a sampling of the raw logs?

**Comment by tweak19** [comment]
May this helps? 
Output from Suricata on ELK

`2022-08-07T17:34:53+02:00 fw01.xxx.xx suricata 72834 - [meta sequenceId="53726"] {"timestamp":"2022-08-07T17:34:53.994402+0200","flow_id":1305922850597986,"in_iface":"igb2","event_type":"alert","src_ip":"1.2.3.4","src_port":46705,"dest_ip":"4.3.2.1","dest_port":1433,"proto":"TCP","alert":{"action":"blocked","gid":1,"signature_id":2010935,"rev":3,"signature":"ET SCAN Suspicious inbound to MSSQL port 1433","category":"Potentially Bad Traffic","severity":2,"metadata":{"created_at":["2010_07_30"],"former_category":["HUNTING"],"updated_at":["2018_03_27"]}},"flow":{"pkts_toserver":1,"pkts_toclient":0,"bytes_toserver":60,"bytes_toclient":0,"start":"2022-08-07T17:34:53.994402+0200"}}`

**Comment by a3ilson** [comment]
Are you using pfSense or OPNsense?

**Comment by tweak19** [comment]
Hi,
i am Using OPNsense.
