### ISSUE TITLE
Alert page error: "legacy template [.lists-default] has index patterns [.lists-default-*] matching patterns from existing composable templates"

### ISSUE THREAD

**Issue by swiftbird07** [pfelk/pfelk#407]
**Describe the bug**
On the first try accessing the "Alerts" tab in Kibana I got the following error message:

```
{
  "name": "Error",
  "body": {
    "message": "illegal_argument_exception: legacy template [.lists-default] has index patterns [.lists-default-*] matching patterns from existing composable templates [pfelk,pfelk-dhcp,pfelk-suricata] with patterns (pfelk => [*-pfelk-captive*, *-pfelk-firewall*, *-pfelk-snort*, *-pfelk-squid*, *-pfelk-unbound*],pfelk-dhcp => [*-pfelk-dhcp*],pfelk-suricata => [*-pfelk-suricata*]), use composable templates (/_index_template) instead",
    "status_code": 400
  },
  "message": "Bad Request",
  "stack": "http_fetch_error_HttpFetchError@http://10.24.1.6:5601/49192/bundles/core/core.entry.js:8:50673\n@http://10.24.1.6:5601/49192/bundles/core/core.entry.js:8:54930\nasyncFunctionResume@[native code]\n@[native code]\npromiseReactionJobWithoutPromise@[native code]"
}
```

The alert tab does not load after this. It just says: "To use the detection engine, a user with the required cluster and index privileges must first access this page. You need permissions for the lists indices. For more help, contact your Elastic Stack administrator." (I am elastic superuser viewing this)

**To Reproduce**
1. Install everything according to the documentation (except the template priority, see #406)
2. Use fleet to add a host to Endpoint Security (I don't know if this step is necessary to reproduce this)
2. Go to "Alerts" tab in Elastic Security
3. See error

**Firewall System (please complete the following information):**
 - pfSense
 - 2.5.2
 
**Operating System (please complete the following information):**
Linux 5.4.162-1-pve x86_64
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
 
 **Installation method (manual, ansible-playbook, docker, script):**
 manual

**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 - logstash       1:**8.0.0**-1    amd64        An extensible logging pipeline
 - elasticsearch  8.0.0        amd64        Distributed RESTful search engine built for the cloud
 - kibana         8.0.0        amd64        Explore and visualize your Elasticsearch data
 (all on different servers)
 

**Additional context**
This is a completely fresh installation with everything up to date.

I hope someone can help me with that problem as I can't use ELK without the alert rules (the whole point for me).

**Comment by swiftbird07** [comment]
I fixed it myself by deleting everything and then setting the priority to something **below** 200 and not above 200. (See the mentioned issue.)

**Comment by a3ilson** [comment]
@maof97 - I was unaware v8.0.0 was released. I fixed this issue and will let it run for a day or two and see if any more tweaking is needed.

**Comment by a3ilson** [comment]
@maof97 - is GeoIP working for you with v8? Mine is missing a few fields. If not, are you using Maxmind or the built-in databases?

**Comment by swiftbird07** [comment]
> @maof97 - is GeoIP working for you with v8? Mine is missing a few fields. If not, are you using Maxmind or the built-in databases?

Didn't saw that response sorry. Yeah my GeoIP is working as far as I know but as mentioned in #409 the middle term like "geo" or "as" is doubled for some reason. Fixing that helps with the dashboards but doesn't help the fact that I am unable to use these fields in Elastic SIEM timelines or alerts.

**Comment by mraisane** [comment]
I hit this same "legacy template [.lists-default] has index patterns...." problem with alerts. Error message is obvious if you read it carefully and there is no need to change priorities.

Before importing index templates just change

  "index_patterns": [
    "*-pfelk-captive*",
    "*-pfelk-firewall*",
    "*-pfelk-snort*",
    "*-pfelk-squid*",
    "*-pfelk-unbound*"
  ],
  
  to
  
    "index_patterns": [
    ".ds-logs-pfelk-captive*",
    ".ds-logs-pfelk-firewall*",
    ".ds-logs-pfelk-snort*",
    ".ds-logs-pfelk-squid*",
    ".ds-logs-pfelk-unbound*"
  ],
  
  And of course same on dhcp, suricata... templates also. Without change index will patterns overlap because of wildcards.
  
  Of cource your mileage may vary. :)

**Comment by CharlieMK** [comment]
Hello, I used the scripted method and I'm hitting the same problem. @mraisane is there any other impact when doing the changes you propose on an existing installation?

**Comment by CharlieMK** [comment]
Update: just changing the template after they have been created (via app/management/data/index_management/templates) does not have any other impact as far as I can tell. As mraisane says this only changes the wildcard matching, so it should not have impact. 

@a3ilson perhaps an idea to change the templates so this issue does not occur after a clean install?
