### ISSUE TITLE
GeoIP (Geo Point) Not Generated with Elastic v8.0.0

### ISSUE THREAD

**Issue by a3ilson** [pfelk/pfelk#410]
GeoIP for v8.0.0 does not produce a `Geo Point` field.

According to [Elastic](https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html#plugins-filters-geoip-ecs_compatibility), GeoIP (Built-in) will support ECS if configured within pipelines.yml. 

## GeoIP ECS
- [x] Make pfELK compatible with new GeoIP ECS 
Revised 30-geoip.conf and pipelines.yml to support GeoIP with ECS.
- pipelines.yml must contain `pipeline.ecs_compatibility: v8`
  - Default is `disabled` and if not specified within pipeline.yml, it is set to `disabled`

## GeoIP - Geo Point
- [x] Update works as advertised but Geo Point (e.g. `geo.location` does not populate with lat & Lon
  - ` location* | [geo][location] | {"lat": 47.6062, "lon": -122.3321}"`

###
Reference: https://www.elastic.co/guide/en/logstash/current/plugins-filters-geoip.html#plugins-filters-geoip-default_database_type

**Comment by JSylvia007** [comment]
Jumping in here to help if I can!  As I said, I run this in my homelab and tore the whole thing apart to get upgraded to the latest version, so I'm willing to do some destructive stuff to help you test.

**Comment by a3ilson** [comment]
@JSylvia007 - thanks!

I believe the culprit to be the template and data stream support. The current templates reference the index patterns however, the data streams appear to be utilizing the logs templates vs pfelk resulting in incorrect field types.

![Screen Shot 2022-02-21 at 10 43 57 AM](https://user-images.githubusercontent.com/16884679/154987263-6a1b941d-968f-454e-82a7-11571baa9ad4.png)

**Comment by JSylvia007** [comment]
> I believe the culprit to be the template and data stream support. The current templates reference the index patterns however, the data streams appear to be utilizing the logs templates vs pfelk resulting in incorrect field types.

Y'know... I noticed this, as all of the incoming data is buried in hidden "log" indexes...  But the dashboards are working, etc.  This is also evident as I added a template to set all replicas to 0, and it's not being respected when these new ".log" indices are created.  I run this in a homelab, so replicas for me need to be 0 as I only have a single instance.

**Comment by a3ilson** [comment]
If GeoIP Point fields are needed. Use the alternate [50-outputs.conf](https://github.com/pfelk/pfelk/wiki/How-To:-Output-to-Indices-vs-Data-Streams) (indices vs data streams)


Homelab/testing: Same here...but leveraging three instances of Elasticsearch in a docker environment.

Looking at the built-in logs templates and components...they may suffice (ECS 1.12)

**Comment by JSylvia007** [comment]
> If GeoIP Point fields are needed. Use the alternate [50-outputs.conf](https://github.com/pfelk/pfelk/wiki/How-To:-Output-to-Indices-vs-Data-Streams) (indices vs data streams)

I assume this is something you're going to fix with data streams, so I will stick it out and help you test.  I don't mind not having the info until its sorted.  Seems like something you're pretty focused on fixing.

Does this also mean that the other related things are also broken, like ILM?

**Comment by a3ilson** [comment]
Found the fix...

I updated the priority on the index patterns which were conflicting with the built-in ones. I deleted all my datastreams and everything is working perfectly now...

However, I am curious if you can simply change the priority and restart logstash? if that will fix or if it requires purging the data (doubtful).

@JSylvia007 - Update the priorities as follows, restart logstash and check the data stream (should see pfelk vs logs):

- pfelk: 300
- pfelk-dhcp: 305
- pfelk-suricata: 310
- pfelk-nginx: 320
- pfelk-haproxy: 325

I am testing to see if the built-in templates will work...simplify this project.

**Comment by JSylvia007** [comment]
> Update the priorities as follows, restart logstash and check the data stream (should see pfelk vs logs)

Can you tell me where to update these?

**Comment by a3ilson** [comment]
Navigate to: Stack Management>>Index Management>>Index Templates
- type "pfelk"
- edit each one (pencil icon within the Actions column)
- adjust the priority
- save

![Screen Shot 2022-02-21 at 11 14 45 AM](https://user-images.githubusercontent.com/16884679/154992216-cc8be631-d7d2-43cf-a49d-9f2861446599.png)

**Comment by JSylvia007** [comment]
So simply updating the priorities didn't work... I've stopped logstash, deleted the indices, and am restarting logstash...

**Comment by JSylvia007** [comment]
Sooo... That didn't work for me.  I changed the priorities as you stated, stopped logstash, deleted the indices, started logstash, and the log-* prefixed pfelk streams re-appeared:

Did I miss a step?

![image](https://user-images.githubusercontent.com/32574636/154995623-03a3429d-f1f7-49d8-b71f-afb22e74a9ba.png)

**Comment by a3ilson** [comment]
Correct...logs will precede but clicking on the data streams should should pfelk as the ilm and index pattern vs logs

**Comment by JSylvia007** [comment]
> Correct...logs will precede but clicking on the data streams should should pfelk as the ilm and index pattern vs logs

You are correct.  And geo points exist...  I think you've closed this one too!

**Comment by a3ilson** [comment]
@JSylvia007 - thanks for your help! I notice you had some pfelk-unknown events...those are ones that are not enriched. 

You'll have to build a Kibana Data View to view the events but curious if those are of interest and if we can further enrich.

**Comment by sjey** [comment]
@a3ilson I still see this issue though the priority is set as per above. It's a fresh install and I am running the latest elastic/logstash/kibana v8 versions. I see it in snort and firewall. I see that the mapping as float for both lat and long. so not sure what's the issue or what am I doing wrong. The snort dashboard is looking for geo_point. When I try to create a firewall dashboard, I see an error that the indices does not geo data.

Data view "-pfelk-snort"" no longer contains the geo field "destination.geo.location"

**Comment by sjey** [comment]
@a3ilson dropped the datastreams and index templates, re-created them and it started working. my bad. Thanks

**Comment by a3ilson** [comment]
@sjey  glad you got it working! I’ve had issues when sending logs prior to getting everything serious and configured.
