### ISSUE TITLE
No indexes are being created and suricata data is not processed.

### ISSUE THREAD

**Issue by JSylvia007** [pfelk/pfelk#412]
**Describe the bug**
I was running one of your original builds of pfelk from over a year ago, and it was running well.  I recently rebuilt from the ground up (removing graylog from my environment so that I can update elastic), and followed the manual install for Ubuntu.  I'm not getting any errors, and I updated the Suricata and pfSense settings to the single port number (before it was different depending on the service), but it's still not working properly.

**To Reproduce**
Perform clean installation using manual steps. 

**Firewall System (please complete the following information):**
 - pfSense CE 2.6.0-release
 
**Operating System (please complete the following information):**
Linux 5.4.0-100-generic x86_64
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
 
 **Installation method (manual, ansible-playbook, docker, script):**
manual
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
All are v8.0.0
[error.pfelk.log](https://github.com/pfelk/pfelk/files/8107709/error.pfelk.log)

**Comment by a3ilson** [comment]
@JSylvia007 - Can you clarify if everything else is working? Is this specific to Suricata or all logs?

**Comment by JSylvia007** [comment]
So I think it's with everything... There are some data streams being created for the firewall pieces, but no indexes at all for anything.

I'm pretty sure the data is getting there, but it doesn't look like anything is happening with it. 

I don't see any errors in any logs at all...  

Note that my previous setup was with elastic v7 and it worked totally fine.  I'm also not an elastic expert by any means.  This is the only thing that I use it for. My next task is to stumble through getting regular syslog into the database. But first I want to get this taken care of. 

Could it be related to the Xpac Security settings?  That was a huge pain in the ass to get working. Note that your install scripts fail silently with a clean v8 install also, which is why I used the manual route.

**Comment by a3ilson** [comment]
The prior version of pfelk utilized indices however with version 22, we migrated to data streams. Let's check and see if data is being received:

### Data Stream
- click on one of your data streams and check the storage size


### Saved Objects
- Did you install the Saved Objects?
- Stack Management >> Saved Objects

**Comment by JSylvia007** [comment]
OK... So... See the screenshot.  Everything has been running over night, so its had plenty of time to get data.

![image](https://user-images.githubusercontent.com/32574636/154977787-767644f9-98e6-4c9a-ac17-7b620b981aef.png)

Note that the only thing I'm really concerned with is the firewall log and the suricata log.  I have rather extensive Grafana dashboards setup around them, so I need to make sure I can get the data flowing to Grafana as well.

I did install all the saved objects, and the firewall dashboard appears to be working.

**Comment by a3ilson** [comment]
@JSylvia007 - Excellent! Everything appears to be working. However, we'll need to dig into the Suricata events which based on the screenshot do not appear to be present.

**Comment by JSylvia007** [comment]
Correct.  Suricata appears to not be present.  Also, it appears that the firewall rule names aren't being enriched, even though the rules database exists.  I'm just seeing rule.rulest = NUMBER, not the name of the rule.

Also...  Any idea on how to reference streams in Grafana?  This is going to be really crappy if I can't get the data to Grafana for my daily dashboards.

**Comment by a3ilson** [comment]
The new version (v22) also consolidated listening ports. The updated conf files are able to delineate based on the observer process. You mentioned that you updated the ports...however, with pfSense, Suricata required a little more configuration via syslog-ng. Can you confirm you updated those settings to send Suricata events to the port in use?

Reference: https://github.com/pfelk/pfelk/wiki/How-To:-Suricata-on-pfSense#step-4c

**Comment by JSylvia007** [comment]
Yup.  I updated the ports... BUT... The syslog-ng package logs state:

`Feb 21 09:59:51 gw01 syslog-ng[36581]: Syslog connection failed; fd='22', server='AF_INET(SERVER_IP:5140)', error='Operation timed out (60)', time_reopen='60'`

I'm not sure why this is, as there's no firewall rule blocking it, and that's the correct port...  Its the same information used on the other config for pfsense firewall...

**Comment by a3ilson** [comment]
### Grafana
- I do not use these but hopefully someone else has insight.
- I would hope that you could reference them the same as how they were previously being referenced
  - `pfelk-firewall-*`(prior scheme) to `*-pfelk-firewall*`(v22 data stream scheme)

### Suricata @revere521 
- I suspect that error as a result of the connection being tcp vs udp
  - This should be an easy fix or adjustment 
  - Try updating to UDP (same area where the port was updated)...although, I recalled tcp was utilized to overcome the truncated messages within pfSesne
  - This may be another area worth exploring (@revere521) with pfSense support alternative log formats

### Rule.ruleset
- Can you share some logs? I suspect pfSense may have changed up their log outputs and/or various how the alternate log formats present this.

**Comment by JSylvia007** [comment]
### Suricata
You're exactly correct about the connection... I found it!  I only had a firewall rule allowing 5140 on UDP, not TCP.  I added a firewall rule and syslog-ng connected right away.

### Rule.ruleset
I can certainly provide some logs. How would you like me to gather them?

**Comment by JSylvia007** [comment]
> ### Grafana
> * I do not use these but hopefully someone else has insight.
> * I would hope that you could reference them the same as how they were previously being referenced
>   
>   * `pfelk-firewall-*`(prior scheme) to `*-pfelk-firewall*`(v22 data stream scheme)

This was also correct BTW.

**Comment by JSylvia007** [comment]
> ### Rule.ruleset
> I can certainly provide some logs. How would you like me to gather them?

So... LOL.  The rule names are correctly showing up in Grafana... LOL... It must be my misunderstandings with how Kibana dashboards work.  I'd guess that everything is working as expected.

**Comment by a3ilson** [comment]
### Rule.ruleset
- I would prefer the event.original
- I suspect it is a result of the field type (text vs number or something)

### Grafana
- [x] I'll post an alternate 50-outputs.conf that will use indices vs data streams but appears you got it working
  - https://github.com/pfelk/pfelk/wiki/How-To:-Output-to-Indices-vs-Data-Streams#data-streams
- Do you have this saved? In the past others have requested...I don't mind linking with these (https://github.com/pfelk/pfelk/blob/main/install/configuration.md#eight-extras---optional)

### Suricata
- [x] I'll update the wiki (port number tcp/udp... but with the logs being sent via UDP, you are receiving the entire event vs a truncated message)?
  - Already updated...just outdate screenshot

**Comment by JSylvia007** [comment]
I think everything is functioning.  Minor tweaking required to the Grafana dashboard, but all information is showing up!

This really is amazing work!

The only issue I'm having is with the Geo-location points for Grafana to show the map coordinates of IPs...  The existing Geo Hash point doesn't exist for some reason...

**Comment by a3ilson** [comment]
The Geo-Point was opened via #410 
- I'm tinkering with that one now...appears to be the incorrect template being applied to pfelk data streams (logs vs pfelk)

**Comment by JSylvia007** [comment]
Ok, awesome.  I can consider this one closed, I'll hop on #410.

Question - What happens when it's time to update (when you fix the template...). Is there a way to just apply the fix instead of a complete re-install?

**Comment by a3ilson** [comment]
A complete reinstall will not be needed... likely a small update and restart of logstash. However, doubtful this will apply to data processed prior to the fix.
