### ISSUE TITLE
ElasticSearch portion of installer script fails with authentication error after "service running" check

### ISSUE THREAD

**Issue by ghost** [pfelk/pfelk#416]
good luck

**Comment by a3ilson** [comment]
@nwdean - I ran this a half dozen times yesterday replicating the authentic error and work around in #415. I do not believe this to be an issue with the script and would be curious as to your hardware specifications in which pfelk is being installed. I suspected the "sleep" time (e.g. time the script waits after installing applications) may need to be increased, allowing sufficient time for the installation to finalize.

**Comment by a3ilson** [comment]
@nwdean - outside these two issues, have you been able to get an instance up and running?

**Comment by nwdean** [comment]
@a3ilson this is what I see when I try to manually start it, and when I reboot the machine it will hang forever waiting for logstash.service to stop and when it comes up again elastisearch.service Fails to start


![image](https://user-images.githubusercontent.com/659867/155860063-c98e01c3-f498-40dc-8501-57fe2866a98d.png)

**Comment by a3ilson** [comment]
Try starting via `sudo system start elastic.service` as the authentication is not the Elastic permission but rather the permission within your environment (linux).

That is odd and the script should have set it to run but if it errored out...give this a try:

`sudo /bin/systemctl daemon-reload`
`sudo /bin/systemctl enable elasticsearch.service`

Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/starting-elasticsearch.html

**Comment by a3ilson** [comment]
> @a3ilson just added another issue (wasn't sure if you wanted me to add on or separate them, let me know what you prefer)
> 
> RE: this issue
> 
> If there is a timeout I am thinking it might come to play because this is a little zotac box with a quad core celeron and 8gb of RAM. I did get elasticsearch.service to start BUT if I rum the systemctl command manually it asks me to authenticate. So if you reboot the box elasticsearch.service fails to start because the autostart config doesn't have creds for the pfelk system user as a paramter or something. Not sure how to proceed on this one unless there is a way to pass that auth in the systemctl command?

Well...it will run but 8GB of ram will likely result in various issues. Elasticsearch requires a minimum 8GB RAM. Kibana requires <1GB. Logstash requires 1GB. Additionally, the OS is also competing for RAM.

**Comment by nwdean** [comment]
@a3ilson and noted, this was my error not understanding the difference

**Comment by a3ilson** [comment]
No worries...hopefully we can get you up and running.

**Comment by bharathkarumudi** [comment]
I am also facing the same issue. Yesterday I installed the ELK with the script and was able to get up to Kibana GUI but was not able to see any logs. 

So today (few mins ago) I restored the VM to the clean OS install and started the fresh install with the script. Now I keep on getting the same issue from the installer as reported originally in this #416 with the message: `Failed to start elasticsearch.service: Unit elasticsearch.service not found.`

**Comment by a3ilson** [comment]
@bharathkarumudi 
Can you provide your elasticsearch logs? They are located at /var/log/elasticsearch/

I believe this may be a compounded issue but suspect the failure of elasticsearch to be related to hardware.

To get a system up and running, I recommend rolling back to elastic stack v7.17.0 or until this issue is resolved.

**Comment by bharathkarumudi** [comment]
@a3ilson 
I left the ELK VM as is overnight, and this morning after reading your comment, I did not see any files under `/var/log/elasticsearch/`  directory and thought to give it a try again with `systemctl`, and it started running. 

I then proceeded to run the pfelk Installer script again, and the script asked me whether to remove the existing elasticsearch; I selected `N` and completed the rest of the installation. 

In the end, I manually ran the below four steps and completed them. Now I am in the Elastic UI (on port 5601) with the elastic user. 

But I am not seeing anything coming to the ELK server. _Is there anything else that needs to be done manually?_ 


```
    sudo /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana --url "https://172.16.1.4:9200"
    sudo /usr/share/kibana/bin/kibana-verification-code
    sudo /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic
    Added the remote syslog in the pfsense GUI as 172.16.1.4:5140 
```

I observed that the port `5140` is listening on IPv6. 

```
# netstat -an | grep LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:5601            0.0.0.0:*               LISTEN     
tcp6       0      0 172.16.1.4:9200         :::*                    LISTEN     
tcp6       0      0 127.0.0.1:9200          :::*                    LISTEN     
tcp6       0      0 ::1:9200                :::*                    LISTEN     
tcp6       0      0 :::5140                 :::*                    LISTEN     
tcp6       0      0 127.0.0.1:9300          :::*                    LISTEN     
tcp6       0      0 ::1:9300                :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 127.0.0.1:9600          :::*                    LISTEN 
```

**Comment by a3ilson** [comment]
@bharathkarumudi 

You will also need to configure Logstash. With Elastic security by default, logstash does not have the permissions to send (will need to provide the cert and credentials). I noted this in issue #415 but haven't have time to update the repo and apologize for that delay.

**Comment by bharathkarumudi** [comment]
Thanks for your reply. 
So, do I have to copy the script that is in the below link and run it on the server? Anything else is needed to do manually? 

https://github.com/pfelk/pfelk/issues/415#issuecomment-1051664096

Thanks!

**Comment by a3ilson** [comment]
You'll need to do a few things:
(1) Install the saved objects (Kibana)
(2) Install the templates (Logstash/Elastic)
(3) Configure security (a) Elastic (b) Kibana which is required with v8.0.0 by default and (c) configure [security](https://www.elastic.co/guide/en/logstash/current/ls-security.html) for logstash

If Elastic and Kibana are running you should be able to login and confirm however, you'll need to configure logstash (security) to allow logstash to send data to Elastic.

**Comment by bharathkarumudi** [comment]
(c) configure [security](https://www.elastic.co/guide/en/logstash/current/ls-security.html) for logstash - somehow I am unable to follow this. Because the steps they mentioned is not clear on which files to edit.

**Comment by a3ilson** [comment]
@bharathkarumudi - I'll be able to provide a better walk through this weekend (currently away with minimal access to my setup).  However, you'll need to configure the 50-outputs.conf for the certificate, user, password. Additionally, you'll need to configure a user/password.

**Comment by nwdean** [comment]
@a3ilson looking forward to the updates, I took a look at this and was honestly shocked how unintuitive their documentation is.

**Comment by bharathkarumudi** [comment]
> @a3ilson looking forward to the updates, I took a look at this and was honestly shocked how unintuitive their (ElasticSearch) documentation is.

Exactly. The ELK's documentation is not friendly, at least for first-time users. I almost gave up on them, but counting on @a3ilson updates to proceed further to use the ELK stack.

**Comment by revere521** [comment]
I have my setup running in a home lab environment, so i just disabled security (with the intention of going back later and trying to figure it out) after the 8.0 update.  

I have nothing exposed externally, so i don't have a problem...so if you just want to get past it for now Set `xpack.security.enabled: false` in `/etc/elasticsearch/elasticsearch.yml` (and possibly also `/etc/kibana/kibana.yml`)

That will bypass the security requirement and make it so you can continue setting up pfELK

**Comment by revere521** [comment]
Correction just set `xpack.security.enabled: false` in `/etc/elasticsearch/elasticsearch.yml `

**Comment by a3ilson** [comment]
Thanks @revere521 - I should have focused on that until I had time to finalize the xpack (default security)

To confirm, your elasticsearch.yml looks like the following: 
```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /var/lib/elasticsearch
#
# Path to log files:
#
path.logs: /var/log/elasticsearch
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# By default Elasticsearch is only accessible on localhost. Set a different
# address here to expose this node on the network:
#
#network.host: 192.168.0.1
#
# By default Elasticsearch listens for HTTP traffic on the first free port it
# finds starting at 9200. Set a specific HTTP port here:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.seed_hosts: ["host1", "host2"]
#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
#cluster.initial_master_nodes: ["node-1", "node-2"]
#
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Allow wildcard deletion of indices:
#
#action.destructive_requires_name: false

#----------------------- BEGIN SECURITY AUTO CONFIGURATION -----------------------
#
# The following settings, TLS certificates, and keys have been automatically      
# generated to configure Elasticsearch security features on 26-02-2022 04:12:49
#
# --------------------------------------------------------------------------------

# Enable security features
xpack.security.enabled: false

xpack.security.enrollment.enabled: true

# Enable encryption for HTTP API client connections, such as Kibana, Logstash, and Agents
xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/http.p12

# Enable encryption and mutual authentication between cluster nodes
xpack.security.transport.ssl:
  enabled: true
  verification_mode: certificate
  keystore.path: certs/transport.p12
  truststore.path: certs/transport.p12
# Create a new cluster with the current node only
# Additional nodes can still join the cluster later
cluster.initial_master_nodes: ["logs"]

# Allow HTTP API connections from localhost and local networks
# Connections are encrypted and require user authentication
http.host: [_local_, _site_]

# Allow other nodes to join the cluster from localhost and local networks
# Connections are encrypted and mutually authenticated
#transport.host: [_local_, _site_]
```
 
no change to `xpack.security.enrollment.enabled: true` or other subsequent fields?

**Comment by revere521** [comment]
The only things i have un-commented in my default elasticsearch.yml (right now) is: 
```
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
xpack.security.enabled: false
```

Here is the whole thing, it has no options for security set at all

```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: my-application
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /var/lib/elasticsearch
#
# Path to log files:
#
path.logs: /var/log/elasticsearch
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# By default Elasticsearch is only accessible on localhost. Set a different
# address here to expose this node on the network:
#
#network.host: 192.168.0.1
#
# By default Elasticsearch listens for HTTP traffic on the first free port it
# finds starting at 9200. Set a specific HTTP port here:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.seed_hosts: ["host1", "host2"]
#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
#cluster.initial_master_nodes: ["node-1", "node-2"]
#
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Allow wildcard deletion of indices:
#
#action.destructive_requires_name: false
xpack.security.enabled: false
```

**Comment by bharathkarumudi** [comment]
Thank you, let me run the clean install with the installer from the latest [commit](https://github.com/pfelk/pfelk/commit/8629609bd5f386f1290e078b3c1cb7d5268cd687) that @a3ilson  made. 

@revere521 Any other manual changes made other than the ones you mentioned above to set up the whole thing? 

Thanks!

**Comment by revere521** [comment]
Nothing else manual that i remember at the moment, no.... we'll find out fir sure though :)

**Comment by a3ilson** [comment]
@bharathkarumudi - The script takes into account the elasticsearch.yml and should work...I'm in the process of testing now via a fresh VM.

**Comment by a3ilson** [comment]
@nwdean / @bharathkarumudi - Updated the script to disable the newly implemented default security. This will allow for the installation with no issues (tested) until we incorporate an easier solution to for the defaulted security.

Kudos to @revere521 for the suggestion!

**Comment by bharathkarumudi** [comment]
Thank you @a3ilson, I am starting the installation now. Will keep you posted.

**Comment by nwdean** [comment]
@a3ilson trying it out now!

@revere521 dude, thank you for that! No idea why I didn't think of just turning it off lol, NOYCE

**Comment by nwdean** [comment]
@a3ilson failed on ElasticSearch install step of installation script. Issue created with detailed steps to reproduce and error log package attached
