### ISSUE TITLE
Getting missing index error - No matching indices found: No indices match pattern "*-pfelk-suricata*

### ISSUE THREAD

**Issue by ghost** [pfelk/pfelk#417]
**Describe the bug**
It seems that something did not get created in the install script. Looks like either the listener for syslog or the indexes themselves are missing. I have added all templates and saved objects manually per other steps.

**To Reproduce**
1. Steps to get here were just following the install script and the added commands form the previous issues I submitted

**Screenshots**
![image](https://user-images.githubusercontent.com/659867/155859757-7e3a1a9c-6ab1-448c-bfba-cfc7e5761039.png)

**Firewall System (please complete the following information):**
 - pfSense or OPNsense
 - Version 
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 
 **Installation method (manual, ansible-playbook, docker, script):**
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 
 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 - Kibana logs (`journalctl -u kibana.service`)

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file

**Comment by a3ilson** [comment]
@nwdean - please provide logs via ` ./etc/pfelk/scripts/pfelk-error.sh` and attach.

**Comment by ghost** [comment]
It appears logstash can't reach elastic

[error.pfelk.log](https://github.com/pfelk/pfelk/files/8147746/error.pfelk.log)

**Comment by ghost** [comment]
@a3ilson also this is a fresh install of ubuntu server 18.04, only thing I have done is try and set this up

**Comment by a3ilson** [comment]
@nwdean - Let's do another clean install with the latest script. I still believe that it may be possible that there was a change but let's start with a good working base. 

@revere521 - are you running pfSesne with Suricata?

**Comment by revere521** [comment]
I am running pfSense 2.6 with Suricata, and I am running the config from the wiki (syslogng)

**Comment by a3ilson** [comment]
unable to duplicate...user error.

Rohan Mitra
tsohg54321
https://www.linkedin.com/in/rohan-gerard-mitra
https://www.facebook.com/rohan.ghost/about_details

**Comment by ghost** [comment]
> unable to duplicate...user error.

Seriously? This has been well documented across multiple issues. YOU didn't take into account the new security settings in your installer script.

**Comment by a3ilson** [comment]
The security settings had no impact on Suricata. They have and are documented as issues resulting in the configuration of the security settings.

**Comment by a3ilson** [comment]
Fuck you!

this is a community project and because you stuck at life doesn’t give you a pass to blame everyone else. It never was a suricata issue, it was a sending data to elastic.  Thanks for blaming and being incompetent hiding being deleted profile.
