### ISSUE TITLE
Force ElasticSearch to listen on ipv4

### ISSUE THREAD

**Issue by ghost** [pfelk/pfelk#420]
**Is your feature request related to a problem? Please describe.**
Not sure why but my install was refusing connections on localhost:9200 until I made this change

**Describe the solution you'd like**

1.) add the following to the file /etc/default/elasticsearch
ES_JVM_OPTIONS=/etc/elasticsearch/jvm.options.d

2.) add the file "custom.options" to the directory /etc/elasticsearch/jvm.options.d

3.) add the following to the file /etc/elasticsearch/jvm.options.d/custom.options
-Djava.net.preferIPv4Stack=true

**Comment by a3ilson** [comment]
@nwdean thanks but will defer this to those needing to customize their setup/configuration as this request will not meet everyone's needs (e.g. ipv6 deployments).
