### ISSUE TITLE
Have option in install script to limit memory footprint of Elastic Search

### ISSUE THREAD

**Issue by ghost** [pfelk/pfelk#421]
**Is your feature request related to a problem? Please describe.**
didn't end up needing to do it but I did test it out and it works. Might be useful for others though and would greatly expand the scope of people that could use this

**Describe the solution you'd like**

1.) add some sort of startup flag/option, or within the script itself when it is running, to ask if someone wants to limit the memory usage of Elastic Search

2.) if yes, ask how many gb they want to limit it to

3.) add the following to the file /etc/default/elasticsearch
ES_JVM_OPTIONS=/etc/elasticsearch/jvm.options.d

4.) add the file "custom.options" to the directory /etc/elasticsearch/jvm.options.d

5.) add the following to the file /etc/elasticsearch/jvm.options.d/custom.options

-Xms3g
-Xmx3g

(replace the 3 in this example with whatever they choose)

**Describe alternatives you've considered**

**Additional context**

**Comment by a3ilson** [comment]
@nwdean thanks for the input but this is covered in the [Wiki](https://github.com/pfelk/pfelk/wiki/How-To:-Performance) and will forgo implementing as the script is intended for a basic installation and those wishing to customize and/or optimize should do so at their own choosing. Adding this option will likely result in some not understanding the impacts (e.g. RAM set aside to elastic but still need some for logstash, Kibana, os and other resources)
