### ISSUE TITLE
Elasticsearch Failing to start

### ISSUE THREAD

**Issue by olsenwc** [pfelk/pfelk#423]
**Describe the bug**
I am attempting to install pfelk via the script.  I have run this script previously and had a similar error occur.  I attempted to run the script again and the error still occurred.  The Elasticsearch service is not starting and exiting with a code. 

**To Reproduce**
1. Execute command "sudo ./pfelk-installer.sh
2. Select n as the script was run previously 
3. Script exits with provided error messages. 

**Screenshots**
Error message displayed upon exit of script:
![image](https://user-images.githubusercontent.com/32272608/156908501-cff61b58-90d7-48c2-a1b9-293701fa9793.png)

**Firewall System (please complete the following information):**
 - OPNsense
 - Version: 22.1.2_1`
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):

NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
 
 **Installation method (manual, ansible-playbook, docker, script): Script
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 
dpkg -l elasticsearch
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=====================================================
ii  elasticsearch  8.0.0        amd64        Distributed RESTful search engine built for the cloud

Logstash and Kibana not installed

 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 - Kibana logs (`journalctl -u kibana.service`)

systemctl status elasticsearch.service

 elasticsearch.service - Elasticsearch
     Loaded: loaded (/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-03-06 03:51:36 UTC; 6min ago
       Docs: https://www.elastic.co
    Process: 77420 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (c>
   Main PID: 77420 (code=exited, status=1/FAILURE)

Mar 06 03:51:35 624thaoc systemd-entrypoint[77420]:         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasti>
Mar 06 03:51:35 624thaoc systemd-entrypoint[77420]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(En>
Mar 06 03:51:35 624thaoc systemd-entrypoint[77420]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(C>
Mar 06 03:51:35 624thaoc systemd-entrypoint[77420]:         at org.elasticsearch.cli.Command.main(Command.java:77)
Mar 06 03:51:35 624thaoc systemd-entrypoint[77420]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticse>
Mar 06 03:51:35 624thaoc systemd-entrypoint[77420]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticse>
Mar 06 03:51:35 624thaoc systemd-entrypoint[77420]: For complete error details, refer to the log at /var/log/elasticsea>
Mar 06 03:51:36 624thaoc systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Mar 06 03:51:36 624thaoc systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
Mar 06 03:51:36 624thaoc systemd[1]: Failed to start Elasticsearch.

journalctl -xe
Mar 06 03:59:13 624thaoc multipathd[729]: sda: failed to get sgio uid: No such file or directory
Mar 06 03:59:18 624thaoc multipathd[729]: sda: add missing path
Mar 06 03:59:18 624thaoc multipathd[729]: sda: failed to get udev uid: Invalid argument
Mar 06 03:59:18 624thaoc multipathd[729]: sda: failed to get sysfs uid: Invalid argument
Mar 06 03:59:18 624thaoc multipathd[729]: sda: failed to get sgio uid: No such file or directory
Mar 06 03:59:23 624thaoc multipathd[729]: sda: add missing path
Mar 06 03:59:23 624thaoc multipathd[729]: sda: failed to get udev uid: Invalid argument
Mar 06 03:59:23 624thaoc multipathd[729]: sda: failed to get sysfs uid: Invalid argument
Mar 06 03:59:23 624thaoc multipathd[729]: sda: failed to get sgio uid: No such file or directory
Mar 06 03:59:28 624thaoc multipathd[729]: sda: add missing path
Mar 06 03:59:28 624thaoc multipathd[729]: sda: failed to get udev uid: Invalid argument
Mar 06 03:59:28 624thaoc multipathd[729]: sda: failed to get sysfs uid: Invalid argument
Mar 06 03:59:28 624thaoc multipathd[729]: sda: failed to get sgio uid: No such file or directory
Mar 06 03:59:33 624thaoc multipathd[729]: sda: add missing path
Mar 06 03:59:33 624thaoc multipathd[729]: sda: failed to get udev uid: Invalid argument
Mar 06 03:59:33 624thaoc multipathd[729]: sda: failed to get sysfs uid: Invalid argument
Mar 06 03:59:33 624thaoc multipathd[729]: sda: failed to get sgio uid: No such file or directory
Mar 06 03:59:38 624thaoc multipathd[729]: sda: add missing path
Mar 06 03:59:38 624thaoc multipathd[729]: sda: failed to get udev uid: Invalid argument
Mar 06 03:59:38 624thaoc multipathd[729]: sda: failed to get sysfs uid: Invalid argument
Mar 06 03:59:38 624thaoc multipathd[729]: sda: failed to get sgio uid: No such file or directory
Mar 06 03:59:43 624thaoc multipathd[729]: sda: add missing path
Mar 06 03:59:43 624thaoc multipathd[729]: sda: failed to get udev uid: Invalid argument
Mar 06 03:59:43 624thaoc multipathd[729]: sda: failed to get sysfs uid: Invalid argument
Mar 06 03:59:43 624thaoc multipathd[729]: sda: failed to get sgio uid: No such file or directory
Mar 06 03:59:48 624thaoc multipathd[729]: sda: add missing path
Mar 06 03:59:48 624thaoc multipathd[729]: sda: failed to get udev uid: Invalid argument
Mar 06 03:59:48 624thaoc multipathd[729]: sda: failed to get sysfs uid: Invalid argument
Mar 06 03:59:48 624thaoc multipathd[729]: sda: failed to get sgio uid: No such file or directory
lines 1175-1203/1203 (END)

**Additional context**
![image](https://user-images.githubusercontent.com/32272608/156908852-7f6cf2c1-5b02-4c77-acb9-41d9eaa44565.png)
**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file
[pfELK_support.tar.gz](https://github.com/pfelk/pfelk/files/8191929/pfELK_support.tar.gz)

**Comment by a3ilson** [comment]
Thanks! Duplicate issue (#419) 

commands:
to list: /usr/share/elasticsearch/bin/elasticsearch-keystore list
to show values before deleting: /usr/share/elasticsearch/bin/elasticsearch-keystore show name-of-the-setting
to remove specific setting: /usr/share/elasticsearch/bin/elasticsearch-keystore remove name-of-the-setting

Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/elasticsearch-keystore.html

**Comment by ghost** [comment]
@opoplawski start here and go through the rest of the thread: https://github.com/pfelk/pfelk/issues/419#issuecomment-1059552412

**Comment by a3ilson** [comment]
Fixed and script/repo now support elastic's default security.

However, there are issues with the script when installing onto of prior installations.
