### ISSUE TITLE
Install Script Failure

### ISSUE THREAD

**Issue by stump-ed** [pfelk/pfelk#425]
**Describe the bug**

During new install from script:

: Updated Elasticsearch.yml...
Job for elasticsearch.service failed because the control process exited with error code.
See "systemctl status elasticsearch.service" and "journalctl -xe" for details.
 An error occurred. Aborting script...
 Please open an issue (pfelk.3ilson.dev) on github!
 Creating support file...
 Support file has been created here: /tmp/pfELK_support.tar.gz

[2022-03-09T18:49:14,659][ERROR][o.e.b.Bootstrap          ] [newhost.sds.lan] Exception
org.elasticsearch.ElasticsearchSecurityException: invalid configuration for xpack.security.transport.ssl - [xpack.security.transport.ssl.enabled] is not set, but the following settings have been configured in elasticsearch.yml : [xpack.security.transport.ssl.keystore.secure_password,xpack.security.transport.ssl.truststore.secure_password]

**To Reproduce**
Did not attempt to reproduce

**Screenshots**

**Firewall System (please complete the following information):**
 - pfSense CE 2.4
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 - Linux 5.4.0-104-generic x86_64
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
 
 **Installation method (manual, ansible-playbook, docker, script):**
script
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 dpkg -l [elasticsearch]|[logstash]|[kibana]
dpkg-query: no packages found matching [elasticsearch]
[kibana]: command not found
[logstash]: command not found

 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 - Kibana logs (`journalctl -u kibana.service`)

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file
[pfELK_support.tar.gz](https://github.com/pfelk/pfelk/files/8217517/pfELK_support.tar.gz)

**Comment by ghost** [comment]
@stump-ed 
This is the same issue I encountered. The problem is those settings are in a different file/config location. See the settings it listed out? You need to use the following commands to find them and then delete them. 

commands:
to list: /usr/share/elasticsearch/bin/elasticsearch-keystore list
to show values before deleting: /usr/share/elasticsearch/bin/elasticsearch-keystore show **_name-of-the-setting_**
to remove specific setting: /usr/share/elasticsearch/bin/elasticsearch-keystore remove **_name-of-the-setting_**

**Comment by ghost** [comment]
@stump-ed here is the link to the thread in the issue I submitted, start here and read through: 
https://github.com/pfelk/pfelk/issues/419#issuecomment-1059552412

**Comment by stump-ed** [comment]
Thank you for your help - but I couldn't find what "name-of-the-setting" needed to be removed....

I wound up abandoning the script install,  booted a clean Ubuntu 20.04 and went with docker install.    
Docker fails with an "unhealthy" container - did this three times, clean and updated boots between.
booted a clean Ubuntu 20.04 and went with a manual install.
I think I found a new issue here, with ElasticSearch being a more recent version than the script install - and I think some security features may have changed.  I bumbled around through the install, needed an install token on Elastic,  had to generate an access code on Kibana, resetting an elastic user name / password combo.  
I managed to manually import the templates into Elastic (import via script fails), but can't import the dashboards into Kibana manually throws  "The file could not be processed due to error: "Bad Request: Unexpected token < in JSON at position 0"  error....  the script for dashboard installs fails.
Sigh..... 
SO,
docker doesn't seem to work;
install scripts fail on Elastic;
manually entering the commands installed a more recent version of both Elastic and Kibana which then don't seem to work with the rest of the stuff....
I'm not complaining or criticizing  - I understand how this stuff changes and updates can kill a script / presets etc. 
I'm just relating my experience in attempting to install.

**Comment by ghost** [comment]
@stump-ed you have them listed in your error code above:

 **invalid configuration for xpack.security.transport.ssl - [xpack.security.transport.ssl.enabled] is not set, but the following settings have been configured in elasticsearch.yml : [xpack.security.transport.ssl.keystore.secure_password,xpack.security.transport.ssl.truststore.secure_password]**

xpack.security.transport.ssl.keystore.secure_password
xpack.security.transport.ssl.truststore.secure_password

So you need to use the two following commands:

/usr/share/elasticsearch/bin/elasticsearch-keystore remove xpack.security.transport.ssl.keystore.secure_password

/usr/share/elasticsearch/bin/elasticsearch-keystore remove xpack.security.transport.ssl.truststore.secure_password

The problem is the error code is wrong. Those settings aren't in elasticsearch.yml. They are in a keystore file and to edit that file you need to use the commands I listed above in this comment and the other comment a few above this. The two commands listed right above this paragraph should fix that error though

**Comment by ghost** [comment]
@stump-ed also heads up the security issue is all of the original stuff you posted where it is missing the matching SSL settings. The stuff you referenced regarding tokens is addressed in the install script and is a standard part of ELK config

**Comment by cr0cdev** [comment]
1.) You shouldn't remove those key's from keystore. Keep them in there, but disable the xpack security that reads those key values in elasticsearch.yml:
**_xpack.security.http.ssl:
  enabled: false
xpack.security.transport.ssl:
  enabled: false_**

But I do recommend that you keep everything enabled and setup Elasticsearch with a proper security as it is intended. Basically removing or disabling those key's will make your Elasticsearch vulnerable to data hijacking.

2.) But if you do want to remove them then please do not remove those key's from keystore without storing their value somewhere safe:
**_/usr/share/elasticsearch/bin/elasticsearch-keystore show <key>_**

**Comment by stump-ed** [comment]
Thank you all for the help - I'm going to attempt this again as soon as I can.  Not clear how to restart the script once it fails however.  Maybe I can put a pause into the script when the .yml gets updated that will allow me to disable the xpack.security before it tries to continue?

**Comment by ghost** [comment]
@cr0cdev 

I'm guessing you did not test this? Because that error happens even if that is set to disabled. 

The "data hijacking" isn't an issue if this is all on one local machine.

@stump-ed no need to edit the script for that. You should read the script, it handles cleanup at the begining for each run

**Comment by stump-ed** [comment]
I saw the cleanup - in a quick review I assumed it would overwrite changes to the keystore and put the values back in.  I'll check it out - Thanks!

**Comment by ghost** [comment]
@stump-ed ah gotcha, misunderstood what you were saying.
Just re-run the installer script, choose to keep the stuff you already installed when asked, then after run the commands above, then stop ElasticSearch, LogStash, Kibana and restart in that order <-----

I did this and it all worked except the templates didn't install, so after it was all up and running and I just ran the individual template installer script and it has been working for the last week or so

**Comment by cr0cdev** [comment]
> 

You are correct as I forgot to add that you need to also disable the whole xpack security which is not recommended either:
_**xpack.security.enabled: false
xpack.security.http.ssl:
enabled: false
xpack.security.transport.ssl:
enabled: false**_

True on the data hijacking part on localhost and it is recommended that you setup at least http SSL even if it is running on local lan. You do not need to setup ssl transport if you do not want to.
But overall it is highly recommended by Elasticsearch that you setup xpack security even on instances that are running on localhost. I also encountered another issue when removing the key's from Elasticsearch keystore which caused Kibana not being able to authenticate with Elasticsearch. I haven't fully tested Elasticsearch 8.0 or 8.1, but I know that with ES 7.X removing the key's did not cause the problem where Kibana was unable to authenticate with Elasticsearch. This might be something new in ES 8.X.

I do recommend that the install script would include Elasticsearch security autoconfiguration part (_elastic user etc_) plus _elasticsearch-setup-passwords_ and then just a self-signed certificate for HTTPS and transport.

**Comment by stump-ed** [comment]
Well....I've tried every way from Sunday  (or at least Wednesday!) to make this work.  I've tried the docker install (clean) multiple times (always "unhealthy" - won't run)  found a reference to passwords not being set in the .env file - tried a clean docker-compose with my own set of passwords in the .env file - that gets further down the road, but the docker cluster never seems to work properly.
I've done multiple scripted installs (18.04 and 20.04) with the above suggestions - haven't been able to make it work.  
I suspect changes in Elasticsearch versions are the culprit.
I've gotten further with manual install, but then the templates and dashboards are a problem.

I'm not a noob at ubuntu; but I've spent waayyy too much time on this experimental trial.  I will keep poking at it, but need to find a different solution for logging and analysis of my pfsense firewalls.   

Thank you all for your suggestions and help - community forums are a great resource and I appreciate the assistance!

**Comment by a3ilson** [comment]
@stump-ed - I'm currently working to make the scripted install become more reliable (working).  My native install choice is docker and getting it up and running isn't bad but you'll have to manually install the templates/saved objects.

**Comment by a3ilson** [comment]
@stump-ed below is likely the easiest solution. However, if you would like to take advantage of the security features I would recommend the docker file from [here](https://github.com/pfelk/docker) but as you experienced earlier, you'll need to amend the `.env` file with user credentials.

The method below works and does not employ the defaulted security:
### Docker Installation
1) `sudo apt-get install docker; sudo apt-get install docker-compose`
2) `sudo sysctl -w vm.max_map_count=262144`
3) Install/download the following files (9):
  -  `wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/01-inputs.conf -P /etc/pfelk/conf.d/`
  - `wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/05-apps.conf -P /etc/pfelk/conf.d/`
  - `wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/30-geoip.conf -P /etc/pfelk/conf.d/`
  - `wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/45-cleanup.conf -P /etc/pfelk/conf.d/`
  - `wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/50-outputs.conf -P /etc/pfelk/conf.d/`
  - `wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/patterns/pfelk.grok -P /etc/pfelk/patterns/`
  - `wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/patterns/openvpn.grok -P /etc/pfelk/patterns/`
  - `wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/logstash/pipelines.yml -P /etc/pfelk/logstash/config/`
  - `wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/logstash/logstash.yml -P /etc/pfelk/logstash/config/`
4) Download this [docker-compose.yml](https://raw.githubusercontent.com/pfelk/pfelk/main/docker-compose.yml) file and place in `etc/docker`
5) sudo docker-compose up -d

### Notes
- You'll need to manually install the templates and saved objects.
- The referenced docker-compose.yml file allocates 32GB of RAM..ensure your system has 32GB plus ram for the OS and/or other processes or amend the file and reduce as desired. 
### Proxmox Running Ubuntu Server and Docker-Compose
- 2 CPUs
- 48GB Ram
- 256GB SSD
![Screen Shot 2022-03-12 at 12 16 46](https://user-images.githubusercontent.com/16884679/158027931-ebf740a1-2365-41e1-a35b-cd0629ad5f9e.png)

**Comment by ghost** [comment]
@cr0cdev it's not that. It'll still do it when that's disabled, please see the other thread for details

**Comment by a3ilson** [comment]
@nwdean sorry...one item was overlooked above. You'll need to amend the 50-outputs.conf file as follows:

Change This: `hosts => ["http://localhost:9200"]` to this: `hosts => ["http://es01:9200"]`

**Comment by stump-ed** [comment]
Thanks for the encouragement - I did update the 50-outputs file as shown above
I've spun up the docker files as listed.   ES webpage show Kibana server is not ready.  Docker Logs Kibana shows:

 [2022-03-12T18:11:06.933+00:00][INFO ][plugins.taskManager] TaskManager is identified by the Kibana UUID: b8feeb78-2580-4ba6-b582-85ec07d05839
[2022-03-12T18:11:07.539+00:00][WARN ][plugins.security.config] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-03-12T18:11:07.540+00:00][WARN ][plugins.security.config] Session cookies will be transmitted over insecure connections. This is not recommended.
[2022-03-12T18:11:07.613+00:00][WARN ][plugins.security.config] Generating a random key for xpack.security.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.security.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-03-12T18:11:07.615+00:00][WARN ][plugins.security.config] Session cookies will be transmitted over insecure connections. This is not recommended.
[2022-03-12T18:11:07.682+00:00][WARN ][plugins.reporting.config] Generating a random key for xpack.reporting.encryptionKey. To prevent sessions from being invalidated on restart, please set xpack.reporting.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-03-12T18:11:07.687+00:00][WARN ][plugins.reporting.config] Found 'server.host: "0.0.0.0"' in Kibana configuration. Reporting is not able to use this as the Kibana server hostname. To enable PNG/PDF Reporting to work, 'xpack.reporting.kibanaServer.hostname: localhost' is automatically set in the configuration. You can prevent this message by adding 'xpack.reporting.kibanaServer.hostname: localhost' in kibana.yml.
[2022-03-12T18:11:07.716+00:00][WARN ][plugins.encryptedSavedObjects] Saved objects encryption key is not set. This will severely limit Kibana functionality. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-03-12T18:11:07.758+00:00][WARN ][plugins.actions] APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-03-12T18:11:07.829+00:00][WARN ][plugins.alerting] APIs are disabled because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command.
[2022-03-12T18:11:07.897+00:00][INFO ][plugins.ruleRegistry] Installing common resources shared between all indices
[2022-03-12T18:11:10.432+00:00][INFO ][plugins.screenshotting.config] Chromium sandbox provides an additional layer of protection, and is supported for Linux Ubuntu 20.04 OS. Automatically enabling Chromium sandbox.
[2022-03-12T18:11:18.280+00:00][ERROR][elasticsearch-service] Unable to retrieve version information from Elasticsearch nodes. connect ECONNREFUSED 172.19.0.4:9200
[2022-03-12T18:11:22.239+00:00][INFO ][plugins.screenshotting.chromium] Browser executable: /usr/share/kibana/x-pack/plugins/screenshotting/chromium/headless_shell-linux_x64/headless_shell

**Comment by stump-ed** [comment]
Can't tell where:  Unable to retrieve version information from Elasticsearch nodes. connect ECONNREFUSED 172.19.0.4:9200
this address is coming from....

Wait.....maybe I'm just not patient enough.....I think I have an elastic webpage up!
I'm going to try to install the templates and dashboards....

**Comment by a3ilson** [comment]
@stump-ed - My prior message was after installing a fresh instance (reloaded a clean VM), installed docker and configured pfelk.  

It appears you got it up and running as I was just going to say sometimes it takes a few to get everything running and for the docker cluster to turn "green"

After you install the templates, you may need to restart logstash.

**Comment by a3ilson** [comment]
Fixed and script/repo now support elastic's default security.

However, there are issues with the script when installing onto of prior installations.
