### ISSUE TITLE
Formatting of destination.port & source.port

### ISSUE THREAD

**Issue by meulie** [pfelk/pfelk#428]
Hi,

I'm quite new to Elastic, so if what I'm reporting is actually an Elastic/Kibana issue, I hereby apologize 😇

In 'Firewall - Discover' I see source.port & destination.port formatted as, for example, '56,092' & '8,080', instead of 56092 & 8080. 

Is this a bug/feature in pfelk, or am I barking up the wrong tree?

**Comment by a3ilson** [comment]
@meulie Elastic Common Schema (ECS) is utilized. Both fields in reference are defined and conform to ECS, both values are numeric and more specifically "long integer" the radix character (the comma separating the groups) is present and agree looks odd when comparing other sources of port values.

There are benefits of ECS but if the radix character is a concern, you could change the value type. This would likely result in other required changes.
