### ISSUE TITLE
pfsense_2_4_2.grok || HTTP request sent, awaiting response... 404 Not Found

### ISSUE THREAD

**Issue by Pandya6423** [pfelk/pfelk#43]
https://raw.githubusercontent.com/a3ilson/pfelk/master/pfsense_2_4_2.grok
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-10-12 08:40:45 ERROR 404: Not Found.

**Comment by democles9308** [comment]
try  curl https://github.com/a3ilson/pfelk/releases/download/v3.0/pf-10.2019.grok

**Comment by a3ilson** [comment]
@Pandya6423 
You have an old link... @democles9308 provided the latest link which will eliminate your 404 error - thanks @democles9308
