### ISSUE TITLE
This script is not made for your OS.

### ISSUE THREAD

**Issue by Jmmx1237** [pfelk/pfelk#432]
Hi, I have some trouble installing PFelk on Ubuntu Server 22.01. I copy&paste the steps in the quick start installation with script guide.
Edit: The ubuntu server runs as a proxmox guest.

**Describe the bug**
Output from installer script: This script is not made for your OS.

**To Reproduce**

Download installer script from [pfelk](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/scripts/pfelk-installer.sh) repository
$ wget https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/scripts/pfelk-installer.sh
Make script executable
$ chmod +x pfelk-installer.sh
Run installer script
$ sudo ./pfelk-installer.sh

#####################################################################################################

# This script is not made for your OS.
# Feel free to contact pfELK (pfelk.3ilson.dev) on github, if you need help with installing pfELK or alternate installation options.

OS_CODENAME = jammy

Kind regards

**Comment by a3ilson** [comment]
@Jmmx1237 - thanks! I have not had time to update the script for Ubuntu 22.04 but it will be updated in the future. However, until then, the manual and/or docker methods work with 22.04.

**Comment by Jmmx1237** [comment]
Thanks for your replay, I have downgraded my ubuntu to 20, my pfelk is running and work fine. Thanks for your great work!

**Comment by a3ilson** [comment]
Script updated
