### ISSUE TITLE
Traffic data request by User or IP in Captive Portal

### ISSUE THREAD

**Issue by darvinrivera** [pfelk/pfelk#435]
@a3ilson I would like to have the data traffic sorted by size (sent and received) by users or by IP that are connected to the captive portal.
pfSense shows the traffic by users.

![CaptivePortal-TrafficDetails](https://user-images.githubusercontent.com/17580342/175567398-dc69ab71-128a-4d6c-a2a1-74eff3a772f0.png)

**Comment by a3ilson** [comment]
I'll take a look at this in July along with Captive

**Comment by a3ilson** [comment]
@darvinrivera - can you provide remote logs related to this?

**Comment by darvinrivera** [comment]
@a3ilson  - I can't find where the remote logs are.

**Comment by a3ilson** [comment]
Take a loo at the original logged message via Kibana>>Discover. If the bytes are sent via logging, this will be easy to implement.

**Comment by darvinrivera** [comment]
@a3ilson - It's not in the captive portal log (Discovery).

**Comment by a3ilson** [comment]
@darvinrivera - I believe that may be the issue...I don't recall seeing the bytes within the remote logs.

You are receiving logs (discovery) just not anything pertaining to bytes, correct?

**Comment by darvinrivera** [comment]
@a3ilson 

> You are receiving logs (discovery) just not anything pertaining to bytes, correct?

Yes, that information (bytes) its not there maybe in firewall. I dont know how pfsense do to get that information in Captive Portal Users Logged In.

**Comment by a3ilson** [comment]
data is not sent via Syslog (pfSense / OPNsense) and unable to provide bytes corresponding to users
