### ISSUE TITLE
Indexes missing?

### ISSUE THREAD

**Issue by darvinrivera** [pfelk/pfelk#436]
I was checking the indexes and i see that they are not generated as "normally" they were seen. (It was a clean installation of pfelk with version 8 of elasticsearch)
From console:
![From Console](https://user-images.githubusercontent.com/17580342/176746213-4d6338fe-928a-422b-8541-3b6f5d583abc.jpg)

From Kibana
![Kibana-index](https://user-images.githubusercontent.com/17580342/176747006-35c70563-616c-46f4-8837-42de78e0e17b.jpg)

From Kibana - Show Hidden Indexes
![Kibana-Hidden-index](https://user-images.githubusercontent.com/17580342/176746385-7fec83ec-0f80-4e63-bb93-ad1be5ce5e89.jpg)

How I hope the indexes look (This is how they look on my other server with old pfelk with elk 7)
![Old Index](https://user-images.githubusercontent.com/17580342/176746698-cd27d9a4-b256-4639-8914-d882ebb7ec0d.jpg)

What am i missing?

**Comment by a3ilson** [comment]
@darvinrivera the updated version migrated from indices to data streams. Please check the data streams tab from within the new installation.

**Comment by darvinrivera** [comment]
Yes, I see them, thanks.
![Data Stream](https://user-images.githubusercontent.com/17580342/176905027-7924eecc-44df-4b20-aa1c-82e7339f6771.jpg)
