### ISSUE TITLE
HAProxy TCP frontends not logged

### ISSUE THREAD

**Issue by mmartinello** [pfelk/pfelk#437]
**Describe the bug**
I installed pfelk on my ELK system and configured my pfSense and my HAProxy boxes to send logs to ELK.
I see logs from every HTTPS HAProxy frontends but I don't see any log from TCP/Basic frontends.
Is it expected or am I making something wrong?

**Firewall System (please complete the following information):**
 - pfSense
 - Version 2.5.2-RELEASE (amd64)
 -  HAProxy version 2.2.14-a07ac36
 
 **Installation method (manual, ansible-playbook, docker, script):** manual
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (Elasticsearch, Logstash, Kibana): 8.3.3

**Comment by BeNeDeLuX** [comment]
Hi mmartinello,

yes that part is missing. When i brought HAProxy into pfelk two years ago or so i only had HTTPS frontends and no TCP Frontends. Therefore the support for it is missing at this point. I myself have since switched to Nginx. However, I use nginx also only https connections.

**Comment by a3ilson** [comment]
@mmartinello - if you provide some logs, we can build out the grok patter to enrich. However, I would consider taking a look at the built-in haproxy module.

**Comment by a3ilson** [comment]
closed...no response from submitter
