### ISSUE TITLE
grokparsefailure - Squid logs from pfsense 

### ISSUE THREAD

**Issue by joseluisgd** [pfelk/pfelk#438]
Hi!

I'm having trouble with squid logs. Every log that comes from squid, gets a tag "_grokparsefailure". 

Here is the original log:
<166>Aug  6 17:54:02 (squid-1)[52528]: 10.168.1.3 - - [06/Aug/2022:17:54:02 -0500] "CONNECT 184.105.176.47:443 HTTP/1.1" 200 0 NONE:HIER_NONE

05-apps.pfelk
  ### squid ###
  if [process][name] == "(squid-1)" {
    mutate {
      replace => [ "[process][name]", "squid" ]
      add_field => { "[event][dataset]" => "pfelk.squid" }
    }
    if [filter_message] =~ /^{.*}$/ {
      json {
        source => "filter_message"
        add_tag => "squid_json"
      }
    }
    if "squid_json" not in [tags] {
      grok {
        patterns_dir => [ "/etc/pfelk/patterns" ]
        match => [ "filter_message", "%{SQUID}" ]
      }
    }

Grok pattern used: 
SQUID %{IPORHOST:[client][ip]} %{NOTSPACE:[labels][request_status]}/%{NUMBER:[http][response][body][status_code]} %{NUMBER:[http][response][bytes]} %{NOTSPACE:[http][request][method]} (%{URIPROTO:[url][scheme]}://)?(?<[url][domain]>\S+?)(:%{INT:[url][port]})?(/%{NOTSPACE:[url][path]})?\s+%{NOTSPACE:[http][request][referrer]}\s+%{NOTSPACE:[lables][hierarchy_status]}/%{NOTSPACE:[destination][address]}\s+%{NOTSPACE:[http][response][mime_type]}

Firewall System (please complete the following information):

pfSense
2.6.0-RELEASE (amd64)
squid version 0.4.45_8

**Comment by a3ilson** [comment]
@joseluisgd - can you provide some squid logs for further testing.

**Comment by a3ilson** [comment]
Consolidated within issue #462
