### ISSUE TITLE
Suricata JSON parsing seems not to work

### ISSUE THREAD

**Issue by democles9308** [pfelk/pfelk#44]
Hi,  deploying your PELK  in Docker environment and have some trouble to get the suricata feedback correct. (using ELK 7.4.0, pfsense 2.4.4-RELEASE-p3
**in pfsense** 
- [Status/system Logs/settings] : remote syslog activated for system-, firewall- and vpnevents.
- [Services/Suricata/Edit Interface settings] :  

1. send alerts to syslog using LOCAL1 and level to NOTICE
2. EVE JSON log enabled with  SYSLOG output, SYSLOG facility and NOTICE priority
3. all EVE traffic logged

**in ELK /Kibana**
incoming msg but not completely parsed 
`
Oct 12, 2019 @ 10:45:23.708 | tags:pf, Suricata, _grokparsefailure, Suricata syslog_program:suricata event.module:suricata, suricata 
event.original:<45>Oct 12 10:45:23 suricata[99171]: {"timestamp": "2019-10-12T10:45:23.645713+0200", "flow_id": 1719720250391083, "in_iface": "igb0", "event_type": "dns", "src_ip": "216.239.34.10", "src_port": 53, "dest_ip": "12.34.56.78", "dest_port": 61815, "proto": "UDP", "dns": {"version": 2, "type": "answer", "id": 8058, "flags": "8400", "qr": true, "aa": true, "rrname": "google.com", "rrtype": "A", "rcode": "NOERROR", "answers": [{"rrname": "google.com", "rrtype": "A", "ttl": 300, "rdata": "172.217.20.110"}], "grouped": {"A": ["172.217.20.110"]}}} 
event.dataset:suricata, ON4CRM host:172.17.0.1 type:syslog @timestamp:Oct 12, 2019 @ 10:45:23.708 syslog_timestamp:Oct 12 10:45:23 received_at:Oct 12, 2019 @ 10:45:23.708 @version:1
`
looking at the pipeline/12-suricata.conf  we're in the first part this part of the code...
`if [message] =~ /^{.*}$/ {
      json {
        source => "syslog_message"
        target => "[suricata][eve]"
      }
    } else {
      grok {
        patterns_dir => ["/etc/logstash/patterns"]
        match => [ "syslog_message", "%{SURICATA}"]
      }
    }
`
.. .so the JSON plugin should be used. For my understanding the code after the above test does modify some fields based on the info in the JSON EVE msg stored in [suricata][eve] by the JSON plugin. Based on the msg seen, i modified the if clause as there is nou [source_ip] field in the output of pfsense.

`if [suricata][eve][src_ip] {
                mutate {
                  add_field => { "[source][ip]" => "%{[suricata][eve][src_ip]}"}
                }
          }
    if [suricata][eve][dest_ip] {
                mutate {
                  add_field => { "[destination][ip]" => "%{[suricata][eve][dest_ip]}"}
                }
          }
    if [suricata][eve][src_port] {
                mutate {
                  add_field => { "[source][port]" => "%{[suricata][eve][src_port]}"}
                }
          }
    if [suricata][eve][dest_port] {
                mutate {
                  add_field => { "[destination][port]" => "%{[suricata][eve][dest_port]}"}
                }
          }....`

At the end of the code some last fields are updated, which seems to work
`   mutate {
        add_field => { "[event][module]" => "suricata"}
        add_field => { "[event][dataset]" => "ON4CRM"}
    }
`

In the patterns/pf- file I got:

`SURICATA \[%{NUMBER:ids_gen_id}:%{NUMBER:ids_sig_id}:%{NUMBER:ids_sig_rev}\]%{SPACE}%{GREEDYDATA:ids_desc}%{SPACE}\[Classification:%{SPACE}%{GREEDYDATA:ids_class}\]%{SPACE}\[Priority:%{SPACE}%{NUMBER:ids_pri}\]%{SPACE}{%{WORD:[ids_network[transport]}}%{SPACE}%{IP:[ids_source][ip]}:%{NUMBER:[ids_source][port]}%{SPACE}->%{SPACE}%{IP:[ids_destination][ip]}:%{NUMBER:[ids_destination][port]}`

I removed the leading space as there is no space in the msg.. but this should not be used as we're not in the case of a grok parsing... 

Any ideas why we get a _grokparsefailure ?

**Comment by a3ilson** [comment]
@democles9308 
This was a previously identified issue (#42).  Omit (comment out) the suricata GROK patter.  I plan to address in November/December.  However, any help or contributions are appreciated. 

Alternative:
Elastic Stack has a suricata module (x-pack) for parsing suricata json formatted messaged:
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-suricata.html

https://suricata.readthedocs.io/en/latest/output/eve/eve-json-format.html

**Comment by democles9308** [comment]
@a3ilson 
Thanks for update and guidance... will look into  x-pack !  Some thoughts... removing the grok pattern will solve the _grokfailure but not the  -maybe - incorrect working of the JSON plugin or do I see this wrong ? 
I'll try to help...

**Comment by a3ilson** [comment]
I’m not 100% the removal of the grok pattern well removed the error but I
would give it a try.

**Comment by democles9308** [comment]
**Update**

Removing the 'else' clause does solve the grokfailure
`if [message] =~ /^{.*}$/ { json { source => "syslog_message" target => "[suricata][eve]" } } else { grok { patterns_dir => ["/etc/logstash/patterns"] match => [ "syslog_message", "%{SURICATA}"] } }`

But more important is to change the if clause to
`if [syslog_message] =~ /^{.*}$/  { ... code... }`

Now the JSON is being parsed and fields are added !!  I'll try to post  a pull request
