### ISSUE TITLE
New Suricata field containing the full URL

### ISSUE THREAD

**Issue by swiftbird07** [pfelk/pfelk#446]
**Is your feature request related to a problem?**
For ELKs Threat Intel feature you can compare a threat intel report's field to fields in your dataset (eg. source.ip to threatintel.indicator.ip), but the problem is, that the suricate logs do not provide a field which contains both the URL-domain and the path. There is one field for the hostname (_suricata.eve.http.hostname_) and one for the url path (_suricate.eve.http.url_) but I need them both concatenated in one field as a full URL.

**Further explanaition why I need this**
Threat-intel rule only allows field to field comparisons and not any kind of AND statement
E.g: I can do _source.ip == threatintel.indicator.ip OR destination.ip == threatintel.indicator.ip_ but I can't do (_suricata.eve.http.hostname == threatintel.indicator.domain AND suricata.eve.http.url == threatintel.indicator.path_) OR (_..._)
If I just compare the URL path to the URL path from threat intel I get tons of false positives for paths like "/" or "/index.html". I also get false positives if I just use the hostname like "cdn.discordapp.com".

**Describe the solution you'd like**
I have no idea how I would achieve this, please help :/

**Comment by a3ilson** [comment]
I did a check on suricata and elastic but saw no mention of the field in reference.

However, you can easily concatenated the values of two fields into a new field:


mutate {
  add_field => {
    "[threatintel][indicator][ip]" => "%{[source][ip]} %{[suricate][eve][http][url]}"
 }
}



Reference:
https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-suricata.html
https://suricata.readthedocs.io/en/suricata-6.0.0/output/eve/eve-json-output.html

**Comment by swiftbird07** [comment]
Ok thanks for the reply. Where would I put this mutate in pfelk? I get the logs from pfSense SyslogNG as described in the guide.

**Comment by a3ilson** [comment]
fixed...added additional mutate for full URL
