### ISSUE TITLE
Multiple instances

### ISSUE THREAD

**Issue by xonacs** [pfelk/pfelk#447]
Hi are multiple instances still supported? Cannot find any documentation about it and not sure how to go about it.

**Comment by a3ilson** [comment]
Yes.

Prior version required multiple input statements. However, both pfSense and OPNsense support logging that contains the host name (RFC 5424). 

The initial grok filters the host name (host.name). As long as multiple instance are uniquely named, you’ll be able to delineated/compare between multiple instances.

**Comment by xonacs** [comment]
> Yes.
> 
> Prior version required multiple input statements. However, both pfSense and OPNsense support logging that contains the host name (RFC 5424).
> 
> The initial grok filters the host name (host.name). As long as multiple instance are uniquely named, you’ll be able to delineated/compare between multiple instances.

Hi

Thanks - my pfSenses have different host names but my pfELK instance is not picking them up. Is there manual config to be made still or should the filters be picking it up already?

**Comment by a3ilson** [comment]
@xonacs - what log type is configured for pfSense?

the default is BSD (RFC 3164) which does not include the hostname in the remote log. However, syslog (RFC5424) will send the hostname.

![pfsense-gravwell-1](https://user-images.githubusercontent.com/16884679/189208107-4b655581-9dcd-4b1c-94ae-fb1aeb32fa50.png)

**Comment by xonacs** [comment]
> @xonacs - what log type is configured for pfSense?
> 
> the default is BSD (RFC 3164) which does not include the hostname in the remote log. However, syslog (RFC5424) will send the hostname.
> 
> ![pfsense-gravwell-1](https://user-images.githubusercontent.com/16884679/189208107-4b655581-9dcd-4b1c-94ae-fb1aeb32fa50.png)

Did not know that! Changed it now and let's see. Thanks!

**Comment by eliofaria** [comment]
Hi!
I have multiple instances with Opnsense. I just don't have hostname identification in the squid logs.
Squid log is exported in json format.

Is it possible to keep the hostname in the squid log?

**Comment by a3ilson** [comment]
@eliofaria - can you provide a sample of squid logs in their original format

**Comment by a3ilson** [comment]
@eliofaria - checking back before closing...the logs from the firewall will contain the firewall's host name.

**Comment by a3ilson** [comment]
Multiple instances was/is supported but depends on the pfSense  logging output (i.e. requires syslog in RFC 5424 format to obtain the host name). This (host name) is utilized and appended the `host.name` field which may be filtered via the dashboard(s).
