### ISSUE TITLE
I cant find the pfelk-settings file

### ISSUE THREAD

**Issue by AnhDungDoan** [pfelk/pfelk#453]
Dear sir, I watch your video (https://www.youtube.com/watch?v=KV27ouVUGuc) but can't find the `pfelk-settings` file. Is it neccessary?

**Comment by AnhDungDoan** [comment]
I enable `remote logging options`, but in ELK, there is no indices in **index management**. What should I do? Pls help me(IP remote is IP of ELK:5140)
![image](https://user-images.githubusercontent.com/66262696/204964065-0518c815-93bf-4c6a-a0d9-61b592198cdb.png)
![image](https://user-images.githubusercontent.com/66262696/204964317-433682ee-d3c6-4cab-bafa-d230414f2e45.png)

**Comment by Snickasaurus** [comment]
> Dear sir, I watch your video (https://www.youtube.com/watch?v=KV27ouVUGuc) but can't find the `pfelk-settings` file. Is it neccessary?

I believe what you're looking for might have been renamed to just "pfelk". Check the "Templates" section and let me know if that's what you are looking for. 

https://github.com/pfelk/pfelk/blob/main/install/security.md#two-templates

**Comment by Snickasaurus** [comment]
> I enable `remote logging options`, but in ELK, there is no indices in **index management**. 

Which method did you use to install pfelk? Did you use the installer script or do everything manually?

**Comment by AnhDungDoan** [comment]
i follow your instruction sir. Manually everything

**Comment by AnhDungDoan** [comment]
Here: http://pfelk.3ilson.com/
And everything in this git. :((

**Comment by a3ilson** [comment]
@AnhDungDoan - the pfelk-settings is no longer required (the video is slightly dated).  Additionally, the indices skills be empty as we’ve migrated away from indices to streams. Please check the days streams under index management.
