### ISSUE TITLE
Index Template Warning.  Can this be ignored?

### ISSUE THREAD

**Issue by charlesw23** [pfelk/pfelk#456]
**Describe the bug**

When installing templates instead of just the 

{
  "acknowledged": true
}

The output is this.

#! index template [pfelk-dhcp] has index patterns [*-pfelk-dhcp*] matching patterns from existing older templates [.monitoring-logstash,.monitoring-es,.monitoring-beats,.monitoring-kibana] with patterns (.monitoring-logstash => [.monitoring-logstash-7-*],.monitoring-es => [.monitoring-es-7-*],.monitoring-beats => [.monitoring-beats-7-*],.monitoring-kibana => [.monitoring-kibana-7-*]); this template [pfelk-dhcp] will take precedence during new index creation

**To Reproduce**
1. Go to the installation instructions to import the templates
2. Import the Template
3. Click the play

**Screenshots**
![image](https://user-images.githubusercontent.com/36480937/205521529-2c3c458d-b470-4dee-94a0-556916d28864.png)

**Firewall System (please complete the following information):**
 - pfSense - should not matter here
 - Version 
 
**Operating System (please complete the following information):**
 Linux 5.15.0-56-generic x86_64
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

 **Installation method (script):**

**Comment by a3ilson** [comment]
@charlesw23 it’ll work.  I’ll leave this issue open until I can update and eliminate the warning

**Comment by a3ilson** [comment]
not an issues...
