### ISSUE TITLE
Java 12 no longer available

### ISSUE THREAD

**Issue by vsboost** [pfelk/pfelk#46]
**Describe the bug**
Following your instructions to install java 12..

Reading package lists... Done
Building dependency tree
Reading state information... Done
Package oracle-java12-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'oracle-java12-installer' has no installation candidate

sudo apt-get install oracle-java12-installer

 - OS: Ubuntu
 - Version 18.04

Had to install Java 13 but logstash is not getting any logs from pf
-------------------------------
 elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-11-04 13:17:56 UTC; 16min ago
     Docs: http://www.elastic.co
 Main PID: 3098 (java)
    Tasks: 58 (limit: 2181)
   CGroup: /system.slice/elasticsearch.service
           ├─3098 /usr/share/elasticsearch/jdk/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiating
           └─3189 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller

Nov 04 13:17:08 ubuntu systemd[1]: Starting Elasticsearch...
Nov 04 13:17:10 ubuntu elasticsearch[3098]: OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be
Nov 04 13:17:56 ubuntu systemd[1]: Started Elasticsearch.

-------------------------------
kibana.service - Kibana
   Loaded: loaded (/etc/systemd/system/kibana.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-11-04 13:03:32 UTC; 33min ago
 Main PID: 1010 (node)
    Tasks: 21 (limit: 2181)
   CGroup: /system.slice/kibana.service
           └─1010 /usr/share/kibana/bin/../node/bin/node /usr/share/kibana/bin/../src/cli -c /etc/kibana/kibana.yml

Nov 04 13:23:44 ubuntu kibana[1010]: {"type":"response","@timestamp":"2019-11-04T13:23:44Z","tags":[],"pid":1010,"method":"get","statusCode":304,"req":{"
Nov 04 13:23:45 ubuntu kibana[1010]: {"type":"response","@timestamp":"2019-11-04T13:23:44Z","tags":[],"pid":1010,"method":"get","statusCode":304,"req":{"
Nov 04 13:23:53 ubuntu kibana[1010]: {"type":"response","@timestamp":"2019-11-04T13:23:53Z","tags":[],"pid":1010,"method":"post","statusCode":200,"req":{
Nov 04 13:23:54 ubuntu kibana[1010]: {"type":"response","@timestamp":"2019-11-04T13:23:54Z","tags":[],"pid":1010,"method":"post","statusCode":200,"req":{
Nov 04 13:23:54 ubuntu kibana[1010]: {"type":"response","@timestamp":"2019-11-04T13:23:54Z","tags":[],"pid":1010,"method":"post","statusCode":200,"req":{
Nov 04 13:23:54 ubuntu kibana[1010]: {"type":"response","@timestamp":"2019-11-04T13:23:54Z","tags":[],"pid":1010,"method":"post","statusCode":200,"req":{
Nov 04 13:23:55 ubuntu kibana[1010]: {"type":"response","@timestamp":"2019-11-04T13:23:55Z","tags":[],"pid":1010,"method":"post","statusCode":200,"req":{
Nov 04 13:23:55 ubuntu kibana[1010]: {"type":"response","@timestamp":"2019-11-04T13:23:55Z","tags":[],"pid":1010,"method":"post","statusCode":200,"req":{
Nov 04 13:23:56 ubuntu kibana[1010]: {"type":"response","@timestamp":"2019-11-04T13:23:56Z","tags":[],"pid":1010,"method":"post","statusCode":200,"req":{
Nov 04 13:24:03 ubuntu kibana[1010]: {"type":"response","@timestamp":"2019-11-04T13:24:02Z","tags":[],"pid":1010,"method":"post","statusCode":200,"req":{
lines 1-18/18 (END)

-------------------------------
logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-11-04 13:36:52 UTC; 15s ago
 Main PID: 5201 (java)
    Tasks: 14 (limit: 2181)
   CGroup: /system.slice/logstash.service
           └─5201 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt

Nov 04 13:36:52 ubuntu systemd[1]: logstash.service: Service hold-off time over, scheduling restart.
Nov 04 13:36:52 ubuntu systemd[1]: logstash.service: Scheduled restart job, restart counter is at 29.
Nov 04 13:36:52 ubuntu systemd[1]: Stopped logstash.
Nov 04 13:36:52 ubuntu systemd[1]: Started logstash.
Nov 04 13:36:52 ubuntu logstash[5201]: Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely
Nov 04 13:36:55 ubuntu logstash[5201]: WARNING: An illegal reflective access operation has occurred
Nov 04 13:36:55 ubuntu logstash[5201]: WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/usr/share/logstash/logstash-cor
Nov 04 13:36:55 ubuntu logstash[5201]: WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
Nov 04 13:36:55 ubuntu logstash[5201]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Nov 04 13:36:55 ubuntu logstash[5201]: WARNING: All illegal access operations will be denied in a future release

-------------------------------

from my /var/log/logstash/logstash-plain.log

[2019-11-04T13:37:29,078][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :excep$
[2019-11-04T13:37:29,094][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>$
[2019-11-04T13:37:29,162][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Error: Don't know how to handle `Java::Ja$
[2019-11-04T13:37:29,313][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExi$
[2019-11-04T13:37:59,567][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.4.2"}
[2019-11-04T13:38:04,577][INFO ][org.reflections.Reflections] Reflections took 66 ms to scan 1 urls, producing 20 keys and 40 values
[2019-11-04T13:38:05,739][ERROR][logstash.filters.geoip   ] Invalid setting for geoip filter plugin:

  filter {
    geoip {
      # This setting must be a path
      # File does not exist or cannot be opened /etc/logstash/GeoLite2-City.mmdb
      database => "/etc/logstash/GeoLite2-City.mmdb"
      ...
    }
  }
[2019-11-04T13:38:05,744][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :excep$
[2019-11-04T13:38:05,766][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>$
[2019-11-04T13:38:05,830][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Error: Don't know how to handle `Java::Ja$
[2019-11-04T13:38:05,964][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExi$

**Comment by a3ilson** [comment]
I'll take a look and troubleshoot later this week.  It appears you also have an issue with the reference of your GeoLite2-City.mmdb.  I would check your /var/lib/GeoIP for this file and if present adjust (i.e. update the conf files to point to the correct location)

**Comment by vsboost** [comment]
Thanks for looking into this, i am trying a reinstall will a copy of jdk-12.0.1_linux-x64_bin.deb that i found, ill also take a look that the GeoLite2-City.mmdb file and see where it is.

**Comment by vsboost** [comment]
Got this working now with ver 12 java - just have an issue with the fields which i commented on in issue 47

**Comment by vsboost** [comment]
Just did another install, this time using Java 13 and everything works as its supposed to, you can probably close this issue and perhaps include in the instructions

sudo apt-get install oracle-java13-installer

Also another thing that might go well in the instructions is to let people know to change the options in the 10-pf.conf file to match if they are using pfsense or OPNsense - this one caught me out.

Cheers

**Comment by a3ilson** [comment]
Updated/Thanks!
