### ISSUE TITLE
Captive - Dashboard displays an error

### ISSUE THREAD

**Issue by jpcapone** [pfelk/pfelk#466]
**Describe the bug**
Captive - Dashboard displays an error for Captive - Events Metric
The field "event.action" associated with this object no longer exists in the data view. Please use another field.

**To Reproduce**
Go to Kibana > Management > Stack Management > Kibana > Saved Objects > Select Captive - Dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/47680328/214172594-1b1a40eb-96d1-4998-b562-22c6aa9a8640.png)

**Firewall System (please complete the following information):**
 - pfSense 2.6.0
 
**Operating System (please complete the following information):**
Browser
 
 **Installation method (manual, ansible-playbook, docker, script):**
Docker

**Comment by a3ilson** [comment]
@jpcapone - Do you have any captive logs (i.e., kibanan>>discovery and copy/paste a sampling of event.original logs from the captive logs)?
