### ISSUE TITLE
pfelk-installer.sh is broken

### ISSUE THREAD

**Issue by Sebidev** [pfelk/pfelk#471]
My installation method is script under a virtual machine I've tried it on Debian 11(Vanilla) and on Ubuntu 22.04 Server(Vanilla) but when run it always comes up. No log files are written either.

pfelk-installer.sh is latest commit [872cc0f](https://github.com/pfelk/pfelk/commit/872cc0f199c0216e1ed0e8bf0748999a37f7a4cd) 5 days ago

![Screenshot 2023-03-24 135631](https://user-images.githubusercontent.com/1012474/227531293-93618709-6909-446d-b706-d0725dd0d412.png)
![Screenshot 2023-03-24 141326](https://user-images.githubusercontent.com/1012474/227531302-a9a4ce72-357e-483b-a913-4dbfeb3a4fdc.png)
[pfELK_support_debian11.tar.gz](https://github.com/pfelk/pfelk/files/11062425/pfELK_support_debian11.tar.gz)
[pfELK_support_ubuntu22-04.tar.gz](https://github.com/pfelk/pfelk/files/11062426/pfELK_support_ubuntu22-04.tar.gz)

Thank you for an answer.

**Comment by a3ilson** [comment]
What happens when you run the script again after the failure? I could not reproduce and thinking a larger time delay or check will be required between the download, install and starting of the service.

**Comment by Sebidev** [comment]
I downloaded the latest Debian 11.6 and Ubuntu 22.04 Server both images from the official website and installed it normally on a virtual machine (VMware Workstation 16) without a GUI.
And logged in as root, downloaded your current script with wget and run your pfelk installation script as root.  And I keep coming back to the point where I made the screenshots for you. 
I can't get any log files out :/

**Comment by Sebidev** [comment]
May cause swap issues if a swap partition is installed on my system?

**Comment by a3ilson** [comment]
Copy/thanks!  Let me take another look.

**Comment by a3ilson** [comment]
I added checks for the Elasticstack with the latest iteration of the script. Elasticsearch and Kibana should be active but Logstash will not be active until you update the 50-outputs.conf with the credentials from the [security](https://github.com/pfelk/pfelk/blob/main/install/security.md) settings. 

When you are prompted to try again or skip the check for Logstash, simply press "s" to skip. Once the security portion is completed, all should work fine.

**Comment by Sebidev** [comment]
Thank you very much for your quick help it works now :)
