### ISSUE TITLE
Rule List/Sync with multiple firewalls

### ISSUE THREAD

**Issue by s7thamon** [pfelk/pfelk#476]
Using some opnsense boxes and wanted to get the rule sync setup. I'm not 100% sure how it works yet but I noticed in the csv file for the rules there's no column for the hostname or the like. If there are multiple firewalls that happen to have the same Rule ID, I imagine this would not work well?

Likewise if I see a rule ID come in the data like "54" is there a way to track this down in the opnsense GUI? I'm not really finding where that ID would be.

**Comment by a3ilson** [comment]
@s7thamon - That would be a nice feature within OPNsense (i.e., the ability to see the associated/corresponding rule id - @opnsense)

1) There is no issue with multiple OPNsense instances running as each log would be amended with the rule lookup via their ID.
- For example, 
`<134>Apr 21 10:12:21 opnsenseA.net filterlog[35625]: 93,,,a5a4a52cb247a9d532d9e49588136184,em1,match,pass,out,4,0x0,,63,12054,0,DF,17,udp,309,192.168.176.43,192.168.1.245,49780,5514,289` 
`<134>Apr 21 10:12:21 opnsenseB.net filterlog[35625]: 93,,,a5a4a52cb247a9d532d9e49588136186,em1,match,pass,out,4,0x0,,63,12054,0,DF,17,udp,309,192.168.176.43,192.168.1.245,49780,5514,289`

- The `opnsenseA.net` log would contain a hostname of "opnsenseA.net" whereas the second log would contain a hostname of "opnsenseB.net"
- I'd have to dig into and do some test (just won't have time for a few months) to better understand how the "Rule ID" is generated. However, they are comprised of an alpha numeric but not sure if two exact rules would generate the same "Rule ID" but my guess would say that they wouldn't be the same.

2) Unaware of any "GUI" method to obtain view the Rule ID but that would be a great feature @OPNsense
- However, this can be accomplished via CLI. Take a look at the script @ShagoY built [here](https://github.com/pfelk/pfelk/wiki/References:-Rule-Description-Script-Generator)

**Comment by s7thamon** [comment]
Thank you for the information.

1. Yup I get that 100% agree there, my concern was having multiple firewalls that happened to have the same rule id but are actually different rules/descriptions on each of them respectively.

The generated ID in the rule csv is simply something like "65" which seems high to have an chance of overlapping. We currently have about 10 firewalls going.

It looks like rule.uuid is present, maybe this would be a better lookup instead of the ruleset/id? One of mine for example looks like "1ea63e770df93d06aec6c5a8d92b254e"

![image](https://user-images.githubusercontent.com/66268528/233720216-5b920d70-8924-487b-abc7-8336217957d5.png)

**Comment by a3ilson** [comment]
Yes, the uuid would likely be the better option for the time being. Ultimately, being and to define our specify these values would be ideal or at a minimum better documentation from the opnsense team.

**Comment by s7thamon** [comment]
This seems to work fine using UUID, but haven't dived into the scripts yet.

```
root@pfelk:/etc/pfelk/databases# cat rule-names.csv
"Rule","Label"
"1ea63e770df93d06aec6c5a8d92b254e","Emerging Threats Blocklist"
```

```
# 35-rules-desc.pfelk
################################################################################
# Version: 22.04                                                               #
# Required: No - Optional                                                      #
# Description: Checks for the presense of the rule_number field, if present    #
# runs translates the rule_number into a referenced description.               #
################################################################################
#
filter {
  if "firewall" in [tags] {
    if [rule][uuid] {
      translate {
        source => "[rule][uuid]"
        target => "[rule][alias]"
        dictionary_path => "/etc/pfelk/databases/rule-names.csv"
        refresh_interval => 60
        refresh_behaviour => replace
        fallback => "%{[rule][uuid]}"
      }
      mutate {
        add_field => { "[rule][description]" => "%{[interface][alias]}: %{[rule][alias]}" }
      }
    }
  }
}
```

**Comment by a3ilson** [comment]
@revere521  do pfsense logs contain a uuid or int when referencing the rules?

**Comment by revere521** [comment]
I believe they do?  I haven't looked at them in a while because the regex in the sid command in the script was fairly complex.  I can try to look again later this weekend to verify

**Comment by revere521** [comment]
@a3ilson here is an export of `pfctl -vv -sr | grep USER_RULE` on my firewall - there appears to be an `ridentifier` that may be a unique UUID/number for each rule?  i don't necessarily see anything that would identify a specific firewall rule from another other than that though. 

```
@51(0) pass quick on re0 inet proto icmp from any to 10.10.10.1 icmp-type echoreq keep state label "USER_RULE: pfB_DNSBL_Ping auto rule" ridentifier 1770001239
@52(0) pass quick on re0 inet proto tcp from any to 10.10.10.1 port = 8081 flags S/SA keep state label "USER_RULE: pfB_DNSBL_Permit auto rule" ridentifier 1770001466
@53(0) pass quick on re0 inet proto tcp from any to 10.10.10.1 port = 8443 flags S/SA keep state label "USER_RULE: pfB_DNSBL_Permit auto rule" ridentifier 1770001466
@54(0) pass quick on re0 inet proto udp from any to 10.10.10.1 port = 8081 keep state label "USER_RULE: pfB_DNSBL_Permit auto rule" ridentifier 1770001466
@55(0) pass quick on re0 inet proto udp from any to 10.10.10.1 port = 8443 keep state label "USER_RULE: pfB_DNSBL_Permit auto rule" ridentifier 1770001466
@56(0) block drop log quick on em0 inet from <pfB_Top_v4:33002> to any label "USER_RULE: pfB_Top_v4 auto rule" ridentifier 1770009222
@57(0) block drop log quick on em0 inet from <pfB_PRI1_v4:10162> to any label "USER_RULE: pfB_PRI1_v4 auto rule" ridentifier 1770009472
@58(0) block drop log quick on em0 inet from <pfB_PRI2_v4:178> to any label "USER_RULE: pfB_PRI2_v4 auto rule" ridentifier 1770009496
@59(0) block return log quick on re0 inet from any to <pfB_PRI1_v4:10162> label "USER_RULE: pfB_PRI1_v4 auto rule" ridentifier 1770004425
@60(0) block return log quick on ovpnc1 inet from any to <pfB_PRI1_v4:10162> label "USER_RULE: pfB_PRI1_v4 auto rule" ridentifier 1770004425
@61(0) block return log quick on re0 inet from any to <pfB_PRI2_v4:178> label "USER_RULE: pfB_PRI2_v4 auto rule" ridentifier 1770004449
@62(0) block return log quick on ovpnc1 inet from any to <pfB_PRI2_v4:178> label "USER_RULE: pfB_PRI2_v4 auto rule" ridentifier 1770004449
@63(0) pass in log quick on re0 inet proto tcp from any to 127.0.0.1 port = domain flags S/SA keep state label "USER_RULE: NAT Redirect DNS" ridentifier 1502419344
@64(0) pass in log quick on re0 inet proto udp from any to 127.0.0.1 port = domain keep state label "USER_RULE: NAT Redirect DNS" ridentifier 1502419344
@65(0) pass in log quick on re0 inet proto tcp from any to 127.0.0.1 port = domain-s flags S/SA keep state label "USER_RULE: NAT Redirect DNS TLS" ridentifier 1571437899
@66(0) pass in log quick on re0 inet proto udp from any to 127.0.0.1 port = domain-s keep state label "USER_RULE: NAT Redirect DNS TLS" ridentifier 1571437899
@68(0) pass in log quick on re0 route-to (em0 50.32.82.110) inet from <BypassVPN:19> to any flags S/SA keep state label "USER_RULE: BypassVPN" dnqueue(1, 2) ridentifier 1464380017
@69(0) pass in log quick on re0 route-to (em0 50.32.82.110) inet from any to <Website_VPN_Bypass:9> flags S/SA keep state label "USER_RULE: Website VPN Bypass" dnqueue(1, 2) ridentifier 1480694975
@70(0) pass in log quick on re0 inet all flags S/SA keep state label "USER_RULE: Flexible Limiter" dnqueue(1, 2) ridentifier 1464486662
```

**Comment by s7thamon** [comment]
According to [pfsense docs](https://docs.netgate.com/pfsense/en/latest/monitoring/logs/firewall.html) this looks correct using ridentifier:

![image](https://user-images.githubusercontent.com/66268528/234396679-09d77aa0-1c6a-4720-a961-667f279e8fee.png)

**Comment by a3ilson** [comment]
@s7thamon I believe it would work either way but...the rule ids are not specific to the instance that logged the event either meaning it would be possible to have multiple firewalls with the same identifier but completely different rules. The issue would then be a single rule lookup where you'd need multiple lookups or a lookup that matches on the firewall.

Here's my thoughts, let's revise the 35-rules-desc.pfelk to enrich these rules utilizing multiple rule lookups based on the firewall.

```
# 35-rules-desc.pfelk
################################################################################
# Version: 22.04                                                               #
# Required: No - Optional                                                      #
# Description: Checks for the presense of the rule_number field, if present    #
# runs translates the rule_number into a referenced description.               #
################################################################################
#
filter {
  if "firewall" in [tags] {
    if [rule][uuid] {
      translate {
        source => "[rule][uuid]"
        target => "[rule][alias]"
        if "[log][syslog][hostname] =~ /^firewall1.local/ {       
        dictionary_path => "/etc/pfelk/databases/rule-names-firewall1.csv" }
        if "[log][syslog][hostname] =~ /^firewall2.local/ {       
        dictionary_path => "/etc/pfelk/databases/rule-names-firewall2.csv" }
        refresh_interval => 60
        refresh_behaviour => replace
        fallback => "%{[rule][uuid]}"
      }
      mutate {
        add_field => { "[rule][description]" => "%{[interface][alias]}: %{[rule][alias]}" }
      }
    }
  }
}
```

Not sure if the above will work...needs testing.

**Comment by a3ilson** [comment]
@s7thamon 
Closing this issue but happy to help/test.
