### ISSUE TITLE
Winlogbeat to pfelk

### ISSUE THREAD

**Issue by hirenchavda25** [pfelk/pfelk#478]
Sending winlogbeat logs to pfelk is it possible i am not getting that logs

**Comment by a3ilson** [comment]
@hirenchavda25 it’s certainly possible but not natively supported with pfelk.

Adding another pipeline within the pipelines.yal might be the easiest way to implement.

**Comment by hirenchavda25** [comment]
> @hirenchavda25 it’s certainly possible but not natively supported with pfelk.
> 
> Adding another pipeline within the pipelines.yak might be the easiest way to implement.

Thanks for your reply like adding pipeline in pfelk can get me logs correct?

If it is possible can u please guide me please

**Comment by a3ilson** [comment]
Check out the following for adding multiple pipelines:
https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html
