### ISSUE TITLE
Failed to download Elasticsearch

### ISSUE THREAD

**Issue by TwinkmrMask** [pfelk/pfelk#479]
I ran into some kind of problem while installing pfelk

Elasticsearch download failed. I'm not an expert, but this may be due to the fact that these repositories are not signed and there is no way to safely update from them

It doesn't matter which GeoIP you choose, it doesn't matter if you have login details, it doesn't matter if you agree to updates. The error will be in any case when installing Elasticsearch

[pfELK_support.tar.gz](https://github.com/pfelk/pfelk/files/11451742/pfELK_support.tar.gz)

**Comment by a3ilson** [comment]
> I ran into some kind of problem while installing pfelk

Which method of installations have you tried? 

> Elasticsearch download failed. I'm not an expert, but this may be due to the fact that these repositories are not signed and there is no way to safely update from them

Is the issue installing or updating?

>It doesn't matter which GeoIP you choose, it doesn't matter if you have login details, it doesn't matter if you agree to updates. The error will be in any case when installing Elasticsearch

- As for the repositories, Elastic is downloaded from directly from Elastic and MaxMind download from MaxMind
- What error are you encountering?

**Comment by TwinkmrMask** [comment]
I'm use https://github.com/pfelk/pfelk/blob/main/README.md#script-installation-method, 
After running the script, at the stage of downloading Elasticsearch, I see the inscription 

> Failed to download Elasticsearch

With a proposal to open an Issue on this topic

**Comment by a3ilson** [comment]
Unable to replicate....referenced script below: https://github.com/pfelk/pfelk/blob/6c550a031a6da0ef0dbc3f1efa967e8b799bb53a/etc/pfelk/scripts/pfelk-installer.sh#L917-L942

Are you able to download elastic manually? (e.g., wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.1-amd64.deb

**Comment by a3ilson** [comment]
Is this still an issue?
