### ISSUE TITLE
Failed to Finish PFELK - After Installing Elasticsearch

### ISSUE THREAD

**Issue by stevefxp1** [pfelk/pfelk#480]
I am trying to build PFELK on a VMware virtual machine. I am using ESXi 8.0U1. My vm is configured as follows:

1) 2 vCPUs
2) 16 Gig vRAM
3) 30 gig primary partition using Paravirtual controller
4) 50 gig secondary partition using NVMe controller (/var/lib/elasticsearch)

It fails just after the successful install of Elasticsearch. Attached is a screenshot of the install process, as well as the log that was generated.
[pfELK_support.tar.gz](https://github.com/pfelk/pfelk/files/11522821/pfELK_support.tar.gz)
![Screenshot 2023-05-20 125805](https://github.com/pfelk/pfelk/assets/70986226/4dafdb2c-6e37-42f6-abe2-282db9a61dbc)

**Comment by stevefxp1** [comment]
I have done a bit more testing. I tried to install with two partitions, but using the NVMe controller on both partitions. It still failed. Again I tried to install with two partitions, only using the default Paravirtual controller on both partitions. It again failed. Lastly I did an install on one partition, and it worked, so I am going to assume your installer does not like multiple partitions?

**Comment by a3ilson** [comment]
@stevefxp1 - the script installer is simply built to easily install and different partitions may result in errors depending on how those partitions are configured. 

I recommend the manual method or docker for more advanced configurations where you can customize the installation to meet your needs.

**Comment by a3ilson** [comment]
Please reopen if this is still an issue.

unable to replicate/duplicate.
