### ISSUE TITLE
Suricata Dashboard shows only Timestamp

### ISSUE THREAD

**Issue by KHOne23** [pfelk/pfelk#482]
**Describe the bug**

**To Reproduce**
1. Go to 'Suricata Dashboard'
2. Click on 'nothing'
3. Scroll down to 'Suricata Discover'

**Screenshots**
![image](https://github.com/pfelk/pfelk/assets/45553117/b7c25000-3e37-407b-88bc-15a3869fa412)

**Firewall System (please complete the following information):**
 - OPNsense
 - OPNsense 23.1.8 
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 Linux 5.10.0-23-amd64 x86_64
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

 **Installation method (manual, ansible-playbook, docker, script):**
 Script
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 
 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 - Kibana logs (`journalctl -u kibana.service`)

**Additional context**
Installation finished sucessfull. Only on Suricata Dashboard i get no Informations.
**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file

**Comment by a3ilson** [comment]
Did you apply these settings to OPNsense:

https://github.com/pfelk/pfelk/blob/main/install/configuration.md#one-suricata---optional

**Comment by KHOne23** [comment]
Yes.
![image](https://github.com/pfelk/pfelk/assets/45553117/8f2e6d07-5749-47f5-8ab8-c36f9e9cc40f)

otherwise i would not get the timestamps?

**Comment by a3ilson** [comment]
Do you have any logged events?

**Comment by a3ilson** [comment]
@KHOne23 would you be able to navigate to Kibana>>Discover (select suricate) and provide a few 'event.original' entries?

**Comment by KHOne23** [comment]
Sure looks like that
![image](https://github.com/pfelk/pfelk/assets/45553117/13c0d402-3d9f-4d25-bf55-6bb677c3d31f)

**Comment by a3ilson** [comment]
@KHOne23 you should be able to expand each of those logged events. Expand and provide the text value of the 'event.original' field.

![Screenshot 2023-06-15 at 8 55 51 AM](https://github.com/pfelk/pfelk/assets/16884679/00135e9f-bab9-4774-bcef-397d84c14ab8)

**Comment by KHOne23** [comment]
![image](https://github.com/pfelk/pfelk/assets/45553117/8404d630-e4ab-4fe5-af92-316640c2f96b)

**Comment by a3ilson** [comment]
@KHOne23 - thanks! that isn't a suricate triggered event but a system (suricate) log which will not populate the dashboard. I  suspect, you don't have any triggered (matching signatures) yet... Try adding a custom rule (i.e., ping) and testing or let it run and expand your timeframe within the dashboard for something greater than the 15m default (e.g., 4-days).

**Comment by DrAndri** [comment]
I'm having the same exact problem running OPNsense 23.1.11 and docker-pfelk. Did a fresh install now with STACK_VERSION=8.8.1 but still no dice. 

There are events being submitted but there aren't any suricata.eve fields in the documents or the original event. However, all of the missing info is there in the original event
<img width="940" alt="image" src="https://github.com/pfelk/pfelk/assets/6573949/4a9c3b99-09c7-4a66-a590-d98d95a8f7c0">
I do have "Enable eve syslog output" enabled in OPNsense

**Comment by DrAndri** [comment]
I noticed that there were 400 errors in logstash log when submitting suricata events to elastic

```javascript
"error"=>{
  "type"=>"mapper_parsing_exception", 
  "reason"=>"failed to parse field [threatintel.indicator.ip] of type [ip] in document with id 'myid'. Preview of field's value: '10.10.10.10 /a/random/url.txt'", 
  "caused_by"=>{
    "type"=>"illegal_argument_exception", 
    "reason"=>"'10.10.10.10 /a/random/url.txt' is not an IP string literal."
  }
}
```

If I remove the url from the corresponding field in 05-apps.pfelk
```
    if [suricata][eve][dest_port] and ![destination][port] {
      mutate {
        add_field => { "[destination][port]" => "%{[suricata][eve][dest_port]}" }
#        add_field => { "[threatintel][indicator][ip]" => "%{[source][ip]} %{[suricata][eve][http][url]}" }
        add_field => { "[threatintel][indicator][ip]" => "%{[source][ip]}" }
      }
    }
```
and restart pfelk the suricata dashboards work and I don't notice anything broken

Is the url needed for something I'm missing?
