### ISSUE TITLE
Logs dont arrive to my elasticsearch instance 

### ISSUE THREAD

**Issue by ZenxB** [pfelk/pfelk#484]
**Describe the bug**
Hello, I have followed the steps to set up pfelk on my syslog server but the logs are not going up from my pfsense to my syslog server. I have no index created after setting up the remote log server on my pfsense. I've also created the template indexes and imported the dashboards.
Thank you for any help you will able to provide !

**Screenshots**

Setup of pfsense remote log server :
![image](https://github.com/pfelk/pfelk/assets/85116879/77f975ac-a2f1-417f-b681-2c28e5fbe0af)

**Firewall System (please complete the following information):**
 - pfSense 
 - Version : 2.4.5-p1 CE
 
**Operating System (please complete the following information):**
 - OS of the syslog server : Ubuntu 22.04.2 LTS
 
Installation method : manual
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 
elasticsearch  8.8.0        amd64
kibana         8.8.0        amd64      
logstash       1:8.8.0-1    amd64        

 
 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 - Kibana logs (`journalctl -u kibana.service`)
 
[journalKibana.txt](https://github.com/pfelk/pfelk/files/11651045/journalKibana.txt)
[logElasticsearch.txt](https://github.com/pfelk/pfelk/files/11651046/logElasticsearch.txt)
[logLogstash.txt](https://github.com/pfelk/pfelk/files/11651047/logLogstash.txt)

**Additional context**

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file

**Comment by ZenxB** [comment]
I have log traffic on the port 5140 on my syslog server :
![image](https://github.com/pfelk/pfelk/assets/85116879/396864eb-73f6-49b2-8205-da091cf0f528)

But the index is not created.

**Comment by a3ilson** [comment]
@ZenxB - support for pfSense versions prior to 2.5.0 may be deprecated due to the updated output. Check to see if this setting is viewable and if so set to RFC 5424:
![image](https://github.com/pfelk/pfelk/assets/16884679/7c4e3cfe-9f40-4885-9b2e-dbfb4afbfc85)


Alternatively, you could upgrade to pfSense 2.5.0+ or you could utilize an older version of PFELK (https://github.com/pfelk/pfelk/releases/tag/20.10)

**Comment by ZenxB** [comment]
Hello @a3ilson and thank you for your answer. 
I upgraded my pfsense to 2.6.0 version and changed the pfsense syslog messages settings : 
![image](https://github.com/pfelk/pfelk/assets/85116879/ed615dba-653b-4bb0-a58e-8c39d3802b41)

But it didn't fix the problem.
Thank you for any help you will be able to provide me.
Regards.

**Comment by ZenxB** [comment]
Otherwise, how can i process with the pfelk integration for elastic cloud ? Is it the same process ? Because i haven't an access to the machine prompt on the cloud deployment, only to the dev tool.
Thank you !

**Comment by ZenxB** [comment]
Hello @a3ilson. I fixed the problem for the logs that not arrived. I have the pfsense logs in the logs index but the 2 indices pfelk-unbound and pfelk-firewall  are not generated. As a result, the imported dashboards display no data.

Have you an idea of the problem ? Could this be due to the fact that I don't have Warm and Cold instances on my Elastic deployment but only Hot, which may conflict with the index lifecycle policy? 

Thank you for any help !

**Comment by a3ilson** [comment]
@ZenxB the Lifecycle Policy within Elastic should not affect the receipt of logs. Hopefully the upgrade wasn't too painful - sorry I was hoping that would have resolved the issue.

1) I use OPNsense and most of the filtering and patterns are based off those. @revere521 has provided lots of inputs regarding pfSense. I am curious as to the "Where to show rule descriptions" option in your screenshot above and wondering if those are being amended to the logs being exported. I'd be curious as to what other options are available under the dropdown and what those look like if added to the log message format.

2) I've had issues in the past where Elastic created the index (data stream) but the initial logs being sent were incorrectly being enriched (e.g., updating the filtering). Even thought everything was correct, that initial Elastic index that was created prevented the correct logs from being received.
   - I would access Kibana and navigate to the the data streams. Then delete the unbound and firewall entries....wait a minute or two and they should reappear.
   - Next, navigate to the Discover View and select either the firewall or unbound and see if the logs are being parsed correctly.

3) Prior to taking the steps in the above (2); navigate to the discover view and see if the logs are being indexed. If so, please provided the raw text of the 'event.original' value which should be the raw log entry.

**Comment by shahidakhter786** [comment]
> Hello @a3ilson. I fixed the problem for the logs that not arrived. I have the pfsense logs in the logs index but the 2 indices pfelk-unbound and pfelk-firewall are not generated. As a result, the imported dashboards display no data.
> 
> Have you an idea of the problem ? Could this be due to the fact that I don't have Warm and Cold instances on my Elastic deployment but only Hot, which may conflict with the index lifecycle policy?
> 
> Thank you for any help !

Can you tell me what this mean? and how did you resolve this issue? Thanks

**Comment by shahidakhter786** [comment]
> @ZenxB the Lifecycle Policy within Elastic should not affect the receipt of logs. Hopefully the upgrade wasn't too painful - sorry I was hoping that would have resolved the issue.
> 
> 1. I use OPNsense and most of the filtering and patterns are based off those. @revere521 has provided lots of inputs regarding pfSense. I am curious as to the "Where to show rule descriptions" option in your screenshot above and wondering if those are being amended to the logs being exported. I'd be curious as to what other options are available under the dropdown and what those look like if added to the log message format.
> 2. I've had issues in the past where Elastic created the index (data stream) but the initial logs being sent were incorrectly being enriched (e.g., updating the filtering). Even thought everything was correct, that initial Elastic index that was created prevented the correct logs from being received.
>    
>    * I would access Kibana and navigate to the the data streams. Then delete the unbound and firewall entries....wait a minute or two and they should reappear.
>    * Next, navigate to the Discover View and select either the firewall or unbound and see if the logs are being parsed correctly.
> 3. Prior to taking the steps in the above (2); navigate to the discover view and see if the logs are being indexed. If so, please provided the raw text of the 'event.original' value which should be the raw log entry.

I have followed the instructions , deleted those datastreams, Now i can see data coming in discover / logs but no data in dashboards still. Any solution for that?

**Comment by shahidakhter786** [comment]
> @ZenxB the Lifecycle Policy within Elastic should not affect the receipt of logs. Hopefully the upgrade wasn't too painful - sorry I was hoping that would have resolved the issue.
> 
> 1. I use OPNsense and most of the filtering and patterns are based off those. @revere521 has provided lots of inputs regarding pfSense. I am curious as to the "Where to show rule descriptions" option in your screenshot above and wondering if those are being amended to the logs being exported. I'd be curious as to what other options are available under the dropdown and what those look like if added to the log message format.
> 2. I've had issues in the past where Elastic created the index (data stream) but the initial logs being sent were incorrectly being enriched (e.g., updating the filtering). Even thought everything was correct, that initial Elastic index that was created prevented the correct logs from being received.
>    
>    * I would access Kibana and navigate to the the data streams. Then delete the unbound and firewall entries....wait a minute or two and they should reappear.
>    * Next, navigate to the Discover View and select either the firewall or unbound and see if the logs are being parsed correctly.
> 3. Prior to taking the steps in the above (2); navigate to the discover view and see if the logs are being indexed. If so, please provided the raw text of the 'event.original' value which should be the raw log entry.

  "event.original": [
    "<13>Jun 16 18:13:30 ids suricata: {\"timestamp\":\"2023-06-16T18:13:30.286298+0500\",\"flow_id\":1090747192533776,\"in_iface\":\"ena0\",\"event_type\":\"netflow\",\"src_ip\":\"1.2.3.4\",\"src_port\":443,\"dest_ip\":\"1.2.3.4\",\"dest_port\":63573,\"proto\":\"TCP\",\"app_proto\":\"tls\",\"netflow\":{\"pkts\":4,\"bytes\":513,\"start\":\"2023-06-16T18:09:07.877328+0500\",\"end\":\"2023-06-16T18:09:07.882221+0500\",\"age\":0,\"min_ttl\":64,\"max_ttl\":64},\"tcp\":{\"tcp_flags\":\"1a\",\"syn\":true,\"psh\":true,\"ack\":true}}\n"

**Comment by shahidakhter786** [comment]
: [2023-06-16T18:07:22,522][WARN ][logstash.outputs.elasticsearch][pfelk][a7963741b9cd105e5d8b3de38d303a4b4243e544786704a8117f80ae7621b9d0] Could not index event to Elasticsearch. {:status=>4>
Error: Unable to create actions client because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command. at onError (

**Comment by revere521** [comment]
these are my logging options (also pfsense 2.6.0) 
![image](https://github.com/pfelk/pfelk/assets/23560313/284b9945-6785-4c48-a9a0-34667f0f6f2e)

Do you have SyslogNG setup?  for suricata logs you will need that

**Comment by shahidakhter786** [comment]
> these are my logging options (also pfsense 2.6.0) ![image](https://user-images.githubusercontent.com/23560313/246427831-284b9945-6785-4c48-a9a0-34667f0f6f2e.png)
> 
> Do you have SyslogNG setup? for suricata logs you will need that

I followed all the steps as you guys mentioned above, now getting this error:
Error: Unable to create actions client because the Encrypted Saved Objects plugin is missing encryption key. Please set xpack.encryptedSavedObjects.encryptionKey in the kibana.yml or use the bin/kibana-encryption-keys command. at onError (
: [2023-06-16T18:07:22,522][WARN ][logstash.outputs.elasticsearch][pfelk][a7963741b9cd105e5d8b3de38d303a4b4243e544786704a8117f80ae7621b9d0] Could not index event to Elasticsearch. {:status=>4>
seems like this is the issue.

**Comment by revere521** [comment]
I don't have the xpack security enabled, my instance is on my internal homelab LAN so i haven't messed with it.   If you don't need it, you can disable the security - or I believe there is a guide to generate the keys and set it up in the Wiki or readme for the setup steps.

**Comment by shahidakhter786** [comment]
Just created key. let's see if it works.

**Comment by shahidakhter786** [comment]
Everything is working correctly. There's no error in logstash,elastic or kibana , logs coming in discover in logs* category.. But dashboards arent showing anything at all.
![image](https://github.com/pfelk/pfelk/assets/35581040/072485ba-243a-45e0-8399-deb39ec447ff)

**Comment by shahidakhter786** [comment]
Solved. 


It was old dashboard issue. reinstalled again with new ones sand it worked.

**Comment by ZenxB** [comment]
> Solved.
> 
> It was old dashboard issue. reinstalled again with new ones sand it worked.

@shahidakhter786 Have you the two indices pfelk-unbound and pfelk-firewall which appeared or have you the data in logs-* data view ? 
@a3ilson I have not these 2 indices created but i have the data in the logs-* data view and the dashboards display data when i change the data view to logs-*.
I don't know if this is the way it should be.

**Comment by a3ilson** [comment]
@ZenxB 

- [ ] Please confirm you have the latest configuration.
- [ ] Try stopping Logstash, then within Kibana delete all the current data streams, and restart Logstash

**Comment by shahidakhter786** [comment]
> > Solved.
> > It was old dashboard issue. reinstalled again with new ones sand it worked.
> 
> @shahidakhter786 Have you the two indices pfelk-unbound and pfelk-firewall which appeared or have you the data in logs-* data view ? @a3ilson I have not these 2 indices created but i have the data in the logs-* data view and the dashboards display data when i change the data view to logs-*. I don't know if this is the way it should be.

No, in suricata dashboard , i can actually see data. but there's still no data in firewall and unbound dashboard.
@a3ilson  Any suggestions?

**Comment by shahidakhter786** [comment]
so, mine are working fine now as i have followed steps of @a3ilson . Thanks

**Comment by kevinf135** [comment]
> Bonjour@a3ilson. J'ai résolu le problème pour les journaux qui n'étaient pas arrivés. J'ai les logs pfsense dans l'index des logs mais les 2 index pfelk-unbound et pfelk-firewall ne sont pas générés. Par conséquent, les tableaux de bord importés n'affichent aucune donnée.
> 
> Avez-vous une idée du problème ? Cela pourrait-il être dû au fait que je n'ai pas d'instances Warm et Cold sur mon déploiement Elastic mais uniquement Hot, ce qui peut entrer en conflit avec la politique de cycle de vie de l'index ?
> 
> Merci pour toute aide !

**Comment by kz135** [comment]
> Bonjour@a3ilson. J'ai résolu le problème pour les journaux qui n'étaient pas arrivés. J'ai les logs pfsense dans l'index des logs mais les 2 index pfelk-unbound et pfelk-firewall ne sont pas générés. Par conséquent, les tableaux de bord importés n'affichent aucune donnée.
> 
> Avez-vous une idée du problème ? Cela pourrait-il être dû au fait que je n'ai pas d'instances Warm et Cold sur mon déploiement Elastic mais uniquement Hot, ce qui peut entrer en conflit avec la politique de cycle de vie de l'index ?
> 
> Merci pour toute aide !

@ZenxB  please how did you solve this problem ?
