### ISSUE TITLE
Suricata Dashboard Not showing alerts they arrive - Showing late and then showing it in same bar

### ISSUE THREAD

**Issue by shahidakhter786** [pfelk/pfelk#488]
![image](https://github.com/pfelk/pfelk/assets/35581040/0537bb4c-2a7e-4331-8cf7-a50a9c0e4f29)
my suricata in pfsense is working 24/7 , all other PFELK dashboards working fine but this one , as you can see in picture, not giving me timely results, showing all data in one bar. Dont know what happened but this's happening from yesterday and have also effected previous logs data.

**Comment by a3ilson** [comment]
Are you running pfsense or opnsense

**Comment by shahidakhter786** [comment]
> Are you running pfsense or opnsense

PFSENSE

**Comment by a3ilson** [comment]
Did you follow the steps referenced here: https://github.com/pfelk/pfelk/wiki/How-To:-Suricata-on-pfSense
