### ISSUE TITLE
Unbound Grok Failures

### ISSUE THREAD

**Issue by a3ilson** [pfelk/pfelk#500]
A handful of logs via Unbound are tagged with _grokfailure

- [ ] Expand GROK filter for Unbound logs
- [ ] Test GROK filter
- [ ] Update pfelk.grok

Example message:
```
<30>1 2023-08-13T21:20:09+00:00 firewall.test.com unbound 94939 - [meta sequenceId="93225"] [94939:0] info: 2610:8080:2829:a21a:2cd7:1234:5678:7133 2610?8080?2829?abcd?1234?abcd?1234?5432. A IN
```
* Not sure why the second ipv6 address is separated with `?` rather than ':' which is likely an OPNsense or Unbound issue...need to determine.
```
<30>1 2023-08-13T21:19:29+00:00 firewall.test.com unbound 94939 - [meta sequenceId="92948"] [94939:3] info: 2610:8080:2829:a21a:2cd7:1234:5678:7133 local. SOA IN
```
* Simple fix...collecting more logs to build GROK

**Comment by SasquatchSecurity** [comment]
I'm also having Grok issues with Unbound. It might be worth noting that I have DNS over TLS enabled. I'm unsure if that changes logging formatting; I haven't checked that yet. OPNSense 23.7 system.

Sample data (hostname obfuscated) from the event.original field:

`<30>Nov 19 19:38:13 test.host.name unbound[22837]: [22837:7] query: 192.168.1.142 edge.microsoft.com. HTTPS IN`

**Comment by a3ilson** [comment]
Testing...the latest 02-firewall.pfelk, GROK patterns and templates from #527 appear to have fixed but will continue to collect logs for a few more days to confirm.
