### ISSUE TITLE
OPNSENSE firewall logs were not correctly capturing TCP/UDP information

### ISSUE THREAD

**Issue by eckley** [pfelk/pfelk#501]
**Describe the bug**
OPNSENSE firewall logs were not correctly capturing TCP/UDP information.

In etc/pfelk/conf.d/02-firewall.pfelk
1) IPv4 protocol and iana_number are around the wrong way for opnsense logs. I can't confirm for pfsense.  
2) UDP section is using TCP number 

Tested against OPNSENSE: 23.7.1_3

Example syslog message:
<134>Aug 21 09:59:58 XXXX.local filterlog[13407]: 89,,,UID,igc0,match,pass,in,4,0x0,,58,3018,0,DF,6,tcp,IP,IP,48442,443,0,S,413112877,,64240,,mss;sackOK;TS;nop;wscale

**Firewall System (please complete the following information):**
 - OPNsense
 -  OPNSENSE: 23.7.1_3

**Comment by eckley** [comment]
Proposed fix in: https://github.com/pfelk/pfelk/compare/main...eckley:pfelk:main

**Comment by a3ilson** [comment]
@eckley 

Thank you! I am also using OPNsense and this was an oversight on my part. The output for pfSense is the same (https://docs.netgate.com/pfsense/en/latest/monitoring/logs/raw-filter-format.html).
