### ISSUE TITLE
Instruction for Pfsense + Suricata

### ISSUE THREAD

**Issue by rootbdfy** [pfelk/pfelk#505]
```
EVE Output type: FILE
EVE Syslog Output Facility: AUTH
EVE Syslog Output Priority: NOTICE
```
There is no facility for output type `FILE`.

**Comment by a3ilson** [comment]
What version of pfsense are you running?

**Comment by rootbdfy** [comment]
> What version of pfsense are you running?

Hello. I use Pfsense v2.7.0.
Output type FILE:
![изображение](https://github.com/pfelk/pfelk/assets/18612349/ee56beac-9358-47da-a45c-381c9488aeb4)
Output type SYSLOG:
![изображение](https://github.com/pfelk/pfelk/assets/18612349/79749e3e-850e-4b7e-aeb0-654c68e667e8)

**Comment by a3ilson** [comment]
@rootbdfy did you follow these instructions: https://github.com/pfelk/pfelk/wiki/How-To:-Suricata-on-pfSense
