### ISSUE TITLE
How to upgrade from 23.03 to 23.08?

### ISSUE THREAD

**Issue by shahidakhter786** [pfelk/pfelk#506]
How to upgrade already installed and perfectly running pfelk 23.03 to 23.08?
Elastic+Kibana version 8.8.1
ubuntu 22.04 , used script to install PFELK

**Comment by a3ilson** [comment]
Merging with #491 


To upgrade only the pfelk files from 20.03 to 20.08 (current). Do the following:

1) Stop logstash
- `systemctl stop logstash.service`

2) Download updated pfelk files
 ``` 
  wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/02-firewall.pfelk -P /etc/pfelk/conf.d/
  wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/05-apps.pfelk -P /etc/pfelk/conf.d/
  wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/30-geoip.pfelk -P /etc/pfelk/conf.d/
  wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/conf.d/49-cleanup.pfelk -P /etc/pfelk/conf.d/

  wget -q https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/patterns/pfelk.grok -P /etc/pfelk/patterns/
```
3) Start logstash
- `systemctl start logstash.service` 

🐙

**Comment by shahidakhter786** [comment]
@613377 Thanks for sharing these details. what about elastic and kibana which asks for latest versions to import these dashboards?
Moreover, it's not letting me upgrade elastic and kibana to newer version because whenever i try, it says, it's already a newer version.

**Comment by shahidakhter786** [comment]
![image](https://github.com/pfelk/pfelk/assets/35581040/c1b8de3f-d870-487e-a699-d4ec83b3d2e9)

**Comment by shahidakhter786** [comment]
No worries. i have upgraded those packages now.

**Comment by a3ilson** [comment]
@shahidakhter786 - you were able to update Elastic/Kibana/Logstash?  

Are importing the dashboards still an issue?

**Comment by shahidakhter786** [comment]
@613377 Everything is working perfectly fine now.
