### ISSUE TITLE
Request for Citation Details

### ISSUE THREAD

**Issue by swiftbird07** [pfelk/pfelk#510]
Hello,

First of all, sorry for putting this as a feature request. I don't know in which other category to put this kind of request.

Currently I am in the process of drafting my bachelor thesis where I used pfELK to collect network data of android smartphones in my lab and I find it important to properly acknowledge the hard work and effort put into this project. Therefore, I am reaching out to inquire how you would prefer this project to be cited in academic works.

Would you prefer a standard citation to the GitHub repository, or is there a related research paper or publication that you would prefer I cite? Also, please let me know the preferred citation format (APA, MLA, Chicago, etc.) and any specific details that you would like included in the citation.

Thank you once again for your invaluable contribution to the community through this project. I look forward to hearing from you soon to ensure proper attribution in my research.

Greetings 
Martin

**Comment by a3ilson** [comment]
:mortar_board: Congradiulations!

I current work in digital forensic and would be very interested in your research paper/project (feel free to reach out and/or share via (613377 @ proton.me)...Leveraging Arkime to capture and analyze network traffic may also be of interest.


Thanks for asking and merely citing this repository would be sufficient:
`Wilson, A. (2023). pfelk: pfSense/OPNsense + Elastic Stack. GitHub. https://github.com/pfelk/pfelk`

**Comment by swiftbird07** [comment]
Great, I will notify you when it's finished :)

**Comment by swiftbird07** [comment]
@613377 It's finished and graded. Here is the final thesis. Thanks again for the work, helping me in this research.
[GrapheneOS_Thesis.pdf](https://github.com/pfelk/pfelk/files/13301228/GrapheneOS_Thesis.pdf)
