### ISSUE TITLE
Firewall/Unbound dashboard issue - "Adjust autocomplete settings in kibana.yml"

### ISSUE THREAD

**Issue by kozistan** [pfelk/pfelk#514]
"Adjust autocomplete settings in kibana.yml" is shown up at the dashboard with "Interface and firewall selector" on pfelk Firewall Dashboard and UnbounD Dashboard with "Unbound - Observer". Please see attached screenshot:

<img width="247" alt="Screenshot 2023-09-20 at 20 31 17" src="https://github.com/pfelk/pfelk/assets/5096897/239df711-d5a2-4c28-919e-265f26998976">

After some research, with no luck, I've modified with several tweaks like:

`unifiedSearch.autocomplete.valueSuggestions.timeout: 1000`
`kibana.autocompleteTimeout: 1000`
`kibana.autocompleteTerminateAfter: 1000000`

Any advise here?

I'm running latest opnsense 23.7.4 on FreeBSD 13.2-RELEASE-p3 amd64 as VM on Proxmox 8.0.4 and latest elasticsearch/lkibana and logstash versions 8.10

Thanks in advance for any help/suggestions.

**Comment by a3ilson** [comment]
@kozistan can you provide the referenced screenshots?

**Comment by kozistan** [comment]
It's attached also in the original message but i've make it bigger now ;)

This in from "Unbound - Dashboard"

<img width="563" alt="Screenshot 2023-09-23 at 7 36 53" src="https://github.com/pfelk/pfelk/assets/5096897/e3c636f3-3b51-4c1d-93b3-9114a1d529f5">

and those from "Firewall - Dashboard":

<img width="487" alt="Screenshot 2023-09-23 at 7 39 16" src="https://github.com/pfelk/pfelk/assets/5096897/cd59cd2d-6642-404c-9487-63ad73c86576">
<img width="566" alt="Screenshot 2023-09-23 at 7 39 29" src="https://github.com/pfelk/pfelk/assets/5096897/63f17f04-d973-4c02-8478-96f18863a75c">
<img width="569" alt="Screenshot 2023-09-23 at 7 39 42" src="https://github.com/pfelk/pfelk/assets/5096897/fbd34086-16c0-4f07-a16b-4ee185dc69df">

And please find kibana.yml attached here:

[kibana.yml.zip](https://github.com/pfelk/pfelk/files/12705713/kibana.yml.zip)

**Comment by a3ilson** [comment]
I believe that may be the result of a latency due to the number of records being indexed. I haven't been able to duplicate but suspect your system may have a bit more logs. 

- How many logs are being indexed over the span of 10hrs?
  - I'll attempt to replicated or mimic but curious as to your setup (ram, cpu, drive + number of records)

**Comment by kozistan** [comment]
Hi, i think that the issue has to do with my raid 1 HDD ZFS pool on Proxmox, i'm going to replace in two weeks for SSD's. Please wait for it, it's very possible this will fix it. Anyway thanx a lot for having look into it. 

Will update after the change.

**Comment by a3ilson** [comment]
no problem - I'm guessing the issue is related to latency and not necessarily the proxmox pool. I'll standby to see how your looming upgrade goes.

**Comment by kozistan** [comment]
> * How many logs are being indexed over the span

Here is my actual config of the VM. Could you please advice how to get those stats?

<img width="646" alt="Screenshot 2023-09-24 at 21 56 20" src="https://github.com/pfelk/pfelk/assets/5096897/f9113b82-b3a5-4ab9-97d8-fb40b3e4c2e3">

**Comment by a3ilson** [comment]
aggregate the block/pass amounts from the firewall log - I’ll use that as a reference point.

**Comment by kozistan** [comment]
pass/block logs 1062785 for last Thursday form 8AM to 6PM

**Comment by a3ilson** [comment]
@kozistan have you tried adjusting the observability within Kibana?
Stack management>>Advanced Settings>>Observability <<<adjusting the default from 100 to 1000>>>

<img width="1508" alt="Screenshot 2024-03-02 at 14 23 17" src="https://github.com/pfelk/pfelk/assets/16884679/7527d0d8-5ee8-4b2a-98cb-eefc916e78f9">
