### ISSUE TITLE
Unable to create DHCP Dashboard, DHCP Saved Objects as there is a data view conflict

### ISSUE THREAD

**Issue by ajtatum** [pfelk/pfelk#519]
**Describe the bug**
All other dashboards are working fine; however, I can't get the DHCP Dashboard running and can't save the DHCP Saved Object (23.03-dhcp.ndjson) as when I do, I get the error, " Data Views Conflicts, The following saved objects use data views that do not exist. Please select the data views you'd like re-associated with them. You can create a new data view if necessary."

**To Reproduce**
Go to saved objects and try to import 23.03-dhcp.ndjson

**Firewall System (please complete the following information):**
 - OPNsense
 - Version: 23.7.7_3-amd64
 
**Operating System (please complete the following information):**
 - Debian 12 (bookworm)
 
 **Installation method (manual, ansible-playbook, docker, script):**
- Tried both manual and scripted
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - elasticsearch 8.10.4
 - kibana 8.10.4
 - logstash 1:8.10.4-1
 
 **Elasticsearch, Logstash, Kibana logs:**
 When I run pflek-kibana-saved-objects for just the DHCP object, the console logs:
```
{"successCount":4,"success":false,"warnings":[],"successResults":[{"type":"visualization","id":"282e0550-c59f-11ed-954f-97ef352c731c","meta":{"title":"DHCPv6 - IP/DUID Flow","icon":"visualizeApp"},"managed":false},{"type":"dashboard","id":"3340cc70-c59f-11ed-954f-97ef352c731c","meta":{"title":"DHCPv6 - Dashboard","icon":"dashboardApp"},"managed":false},{"type":"visualization","id":"bf8b2040-3a9b-11eb-96b2-e765737b7534","meta":{"title":"DHCP - IP/MAC Flow","icon":"visualizeApp"},"managed":false},{"type":"dashboard","id":"c8b42350-3a9c-11eb-96b2-e765737b7534","meta":{"title":"DHCP - Dashboard","icon":"dashboardApp"},"managed":false}],"errors":[{"id":"ae3e6050-641f-11ec-8e46-7751ae25367b","type":"search","meta":{"title":"DHCP - Discover","icon":"discoverApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"},{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"816485d0-3a9c-11eb-96b2-e765737b7534","type":"visualization","meta":{"title":"DHCP - Interface Selector","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"8c777400-3a9c-11eb-96b2-e765737b7534","type":"visualization","meta":{"title":"DHCP - Observer Selector","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"6f94bd20-3a9c-11eb-96b2-e765737b7534","type":"visualization","meta":{"title":"DHCP - Interface","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"629cf980-c59f-11ed-954f-97ef352c731c","type":"visualization","meta":{"title":"DHCPv6 - Operation/Time","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"7cc3c4b0-c59f-11ed-954f-97ef352c731c","type":"visualization","meta":{"title":"DHCPv6 - Operation","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"a8000940-c59f-11ed-954f-97ef352c731c","type":"visualization","meta":{"title":"DHCPv6 - Client IP/Time","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"965b2120-c59f-11ed-954f-97ef352c731c","type":"visualization","meta":{"title":"DHCPv6 - Client IP","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"1e94c960-c5a0-11ed-954f-97ef352c731c","type":"search","meta":{"title":"DHCPv6 - Discover","icon":"discoverApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"},{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"457371f0-3afe-11eb-96b2-e765737b7534","type":"visualization","meta":{"title":"DHCP - Operation/Time","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"dffb6ab0-3a9b-11eb-96b2-e765737b7534","type":"visualization","meta":{"title":"DHCP - Operation","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"9990cd00-3afe-11eb-96b2-e765737b7534","type":"visualization","meta":{"title":"DHCP - Client IP","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}},{"id":"072449e0-3a9c-11eb-96b2-e765737b7534","type":"visualization","meta":{"title":"DHCP - Client IP/Time","icon":"visualizeApp"},"error":{"type":"missing_references","references":[{"type":"index-pattern","id":"id-dhcp"}]}}]}
```

**Comment by ajtatum** [comment]
Here's the error log. I have no idea what's going on. 

[error.pfelk.log](https://github.com/pfelk/pfelk/files/13270693/error.pfelk.log)

**Comment by ajtatum** [comment]
I also tried the Docker install, and as soon as I get to the point where I upload the DHCP dashboard... I get the same error when I try to upload it. After telling it to proceed without a data view, it brought in DHCP - IP/MAC Flow and DHCPv6 IP/DUID Flow.

**Comment by a3ilson** [comment]
@ajtatum - no need to reinstall. I am in the process of rebuilding the dashboards as they were built several versions ago (~2years ago). 

Thanks for reporting/opening.

**Comment by ajtatum** [comment]
Good to know @613377! I appreciate your time on this project, but I'm just curious what sort of timeline you're thinking? Would there be an upgrade path from this version to the next? I'm just trying to determine if I should roll with what currently exists, without the DHCP dashboard, or if it would be best to wait until the next release.

**Comment by a3ilson** [comment]
@ajtatum I don't have much time to dedicate but this (dashboard) updates will be updated after and once the 02-firewall.pfelk file is revised (kv vs csv).

**Comment by thetravellor** [comment]
Watching, as I have precisely the same issue

**Comment by a3ilson** [comment]
Please download, and import the 24.02-dhcp.ndjson file. It appears that it was missing the Data View (no reference for visualizations) - updated and tested but please confirm that it is working.

https://github.com/pfelk/pfelk/blob/main/etc/pfelk/dashboard/24.02-dhcp.ndjson
