### ISSUE TITLE
Grok filter is not able to parse TCP logs properly

### ISSUE THREAD

**Issue by nmortezaei** [pfelk/pfelk#52]
**Describe the bug**
TCP logs from pfsense are not being parsed properly and for example none of following fields such as tcp_flags, sequence_number are being extracted from the message.
 
**To Reproduce**
Using the exactly same configuration files provided (except the geoip items for simplicity) following data is being extracted from the original event:
{
               "geoip" => {
              "timezone" => "Europe/Helsinki",
                    "ip" => "x.x.x.x",
              "latitude" => 60.1708,
         "country_code2" => "FI",
          "country_name" => "Finland",
         "country_code3" => "FI",
        "continent_code" => "EU",
              "location" => {
            "lon" => 24.9375,
            "lat" => 60.1708
        },
             "longitude" => 24.9375
    },
              "offset" => "0",
         "destination" => {
        "port" => "47433",
          "ip" => "x.x.x.x"
    },
               "flags" => "none",
              "length" => "40",
              "source" => {
        "port" => "58995",
          "ip" => "x.x.x.x"
    },
      "syslog_program" => "filterlog",
      "syslog_message" => "5,,,1000000103,vmx0,match,block,in,4,0x0,,249,36398,0,none,6,tcp,x.x.x.x,x.x.x.x,58995,47433,0,S,3763004844,,1024,,",
           "interface" => "vmx0",
                "type" => "syslog",
                 "ttl" => "249",
             "network" => {
        "transport_id" => "6",
           "transport" => "tcp",
                "type" => "4",
             "packets" => "0",
           "direction" => "in"
    },
                "tags" => [
        [0] "pf",
        [1] "firewall"
    ],
       "received_from" => "x.x.x.x",
          "@timestamp" => 2019-11-30T19:56:09.078Z,
    "syslog_timestamp" => "Nov 30 21:56:09",
         "received_at" => "2019-11-30T19:56:09.078Z",
            "@version" => "1",
                "host" => "x.x.x.x",
             "tracker" => "1000000103",
                 "tos" => "0x0",
               "event" => {
            "code" => "5",
        "original" => "<134>Nov 30 21:56:09 filterlog: 5,,,1000000103,vmx0,match,block,in,4,0x0,,249,36398,0,none,6,tcp,x.x.x.x,x.x.x.x,58995,47433,0,S,3763004844,,1024,,",
          "action" => "block",
              "id" => "36398",
         "outcome" => "match"
    }
}

 

**Screenshots**

**Operating System (please complete the following information):**
 - OS: CentOS
 - Version 7.4
 
**Elastic, Logstash, Kibana (please complete the following information):**
 - Version 7.4

**Additional context**

**Comment by a3ilson** [comment]
Is this specific to ipv4 or ipv6?

**Comment by nmortezaei** [comment]
Unfortunately i cannot say anything about IPv6 as the environment is running entirely on IPv4. 
Problem is that when it comes to PF_PROTOCOL_DATA it only applies PF_UDP_DATA to both TCP and also UDP packets and never applies the PF_TCP_DATA to packets (i double checked it by renaming PF_UDP_DATA fields to something different than PF_TCP_DATA fields to make them different).

**Comment by nmortezaei** [comment]
ok a quick update. Grok patterns works fine only if the logs have all elements required by grok filters. problem is that logs sometimes miss some parameters such as ack_number or sequence number is in format of xxx:yyy instead of only xxx.
changing filters to pick elements if they exists can solve the problem like this:
PF_TCP_DATA %{INT:[transport][source_port]},%{INT:[transport][destination_port]},%{INT:[transport][data_lenght]},(?<tcp_flags>(\w*)?),(?<sequence_number>(\d*)?),(?<ack_number>(\d*)?),(?<window_size>(\d*)?),(?<tcp_urg_data>(\w*)?),%{GREEDYDATA:tcp_options}

**Comment by nmortezaei** [comment]
and also PF_ICMP_DATA %{PF_ICMP_TYPE},%{PF_ICMP_RESPONSE} need to be changed to PF_ICMP_DATA %{PF_ICMP_TYPE}%{PF_ICMP_RESPONSE} to parse ICMP logs properly

**Comment by a3ilson** [comment]
nmortezawl - greatly appreciated!  I’ll update this weekend with your
improvements.

**Comment by a3ilson** [comment]
Updated and added your improvements - thanks!
