### ISSUE TITLE
Can't select firewall entry in Dashboard after uprade with Unable to fetch terms, error

### ISSUE THREAD

**Issue by rpelissi** [pfelk/pfelk#524]
**Describe the bug**
I have upgrade my pfelk setup to use the latest configurations/dashboard/etc from the gitlab repo, I use to have pfsense 2.7.1 and opnsense 23.x logs but now, even if I receive data, I cannot select the firewall name in the Firewall selector field for the Firewall Dashboard

```
Firewall Selector
Unable to fetch terms, error:
EsError: Required one of fields [field ,script], but no one were specidfied
```

**To Reproduce**
1. Upgrade to the latest pfelk components (logstash, kibana, elasticsearch)
2. Upgrade/replace all config files from the git repo

**Screenshots**
![image](https://github.com/pfelk/pfelk/assets/385483/aa8b5bf1-f062-40a6-babd-bc7a2ad9d8e5)

**Firewall System (please complete the following information):**
 - pfSense 2.7.2
 - OpnSense 24.1.1
 
**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 - Linux 5.10.0-27-amd64 x86_64
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
 
 **Installation method (manual, ansible-playbook, docker, script):**
Manual
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components (`dpkg -l [elasticsearch]|[logstash]|[kibana]`)
 root@pdrpfelk01:/etc# dpkg -l elasticsearch
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=====================================================
ii  elasticsearch  8.12.0       amd64        Distributed RESTful search engine built for the cloud
root@pdrpfelk01:/etc# dpkg -l kibana
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=============================================
ii  kibana         8.12.0       amd64        Explore and visualize your Elasticsearch data
root@pdrpfelk01:/etc# dpkg -l logstash
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  logstash       1:8.12.0-1   amd64        An extensible logging pipelin
 
 **Elasticsearch, Logstash, Kibana logs:**
 - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
 - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
 - Kibana logs (`journalctl -u kibana.service`)

```
root@pdrpfelk01:/etc# tail -f /var/log/logstash/logstash-plain.log
[2024-02-09T17:58:13,249][ERROR][logstash.licensechecker.licensereader] Unable to retrieve Elasticsearch cluster info. {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError}
[2024-02-09T17:58:13,249][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"No Available connections"}
[2024-02-09T17:58:43,248][ERROR][logstash.licensechecker.licensereader] Unable to retrieve Elasticsearch cluster info. {:message=>"No Available connections", :exception=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError}
[2024-02-09T17:58:43,249][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"No Available connections"}
```

ro```
ot@pdrpfelk01:/etc# tail -f /var/log/kibana/kibana.log
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.6.1"},"@timestamp":"2024-02-09T16:44:19.376-05:00","message":"Fleet Usage: {\"agents_enabled\":true,\"agents\":{\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"inactive\":0,\"unenrolled\":0,\"total_all_statuses\":0,\"updating\":0},\"fleet_server\":{\"total_all_statuses\":0,\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"updating\":0,\"num_host_urls\":0}}","log":{"level":"INFO","logger":"plugins.fleet"},"process":{"pid":494,"uptime":839255.949995405},"trace":{"id":"32e975dda611d5470a6bca4050226e81"},"transaction":{"id":"2dccfd7422377fb1"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.6.1"},"@timestamp":"2024-02-09T16:57:11.987-05:00","message":"Authentication attempt failed: SESSION_EXPIRED","log":{"level":"INFO","logger":"plugins.security.authentication"},"process":{"pid":494,"uptime":840028.562508814},"trace":{"id":"10c46b6529524f4bcaab1935d7f7d035"},"transaction":{"id":"b4a3144ebeb03af2"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.6.1"},"@timestamp":"2024-02-09T16:59:19.464-05:00","message":"Fleet Usage: {\"agents_enabled\":true,\"agents\":{\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"inactive\":0,\"unenrolled\":0,\"total_all_statuses\":0,\"updating\":0},\"fleet_server\":{\"total_all_statuses\":0,\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"updating\":0,\"num_host_urls\":0}}","log":{"level":"INFO","logger":"plugins.fleet"},"process":{"pid":494,"uptime":840156.037797654},"trace":{"id":"32e975dda611d5470a6bca4050226e81"},"transaction":{"id":"d5dedd21ae69a62c"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.6.1"},"@timestamp":"2024-02-09T17:14:22.458-05:00","message":"Fleet Usage: {\"agents_enabled\":true,\"agents\":{\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"inactive\":0,\"unenrolled\":0,\"total_all_statuses\":0,\"updating\":0},\"fleet_server\":{\"total_all_statuses\":0,\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"updating\":0,\"num_host_urls\":0}}","log":{"level":"INFO","logger":"plugins.fleet"},"process":{"pid":494,"uptime":841059.033206744},"trace":{"id":"32e975dda611d5470a6bca4050226e81"},"transaction":{"id":"b00a458f87d79cb8"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.6.1"},"@timestamp":"2024-02-09T17:17:31.489-05:00","message":"Running Fleet Usage telemetry send task","log":{"level":"INFO","logger":"plugins.fleet"},"process":{"pid":494,"uptime":841248.06483753},"trace":{"id":"4c5f7b43fcb25409cf09276110e43cbd"},"transaction":{"id":"457081296af084e7"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.6.1"},"@timestamp":"2024-02-09T17:29:22.521-05:00","message":"Fleet Usage: {\"agents_enabled\":true,\"agents\":{\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"inactive\":0,\"unenrolled\":0,\"total_all_statuses\":0,\"updating\":0},\"fleet_server\":{\"total_all_statuses\":0,\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"updating\":0,\"num_host_urls\":0}}","log":{"level":"INFO","logger":"plugins.fleet"},"process":{"pid":494,"uptime":841959.097138416},"trace":{"id":"32e975dda611d5470a6bca4050226e81"},"transaction":{"id":"367f2b48bb2f9acb"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.6.1"},"@timestamp":"2024-02-09T17:34:21.618-05:00","message":"Logging in with provider \"basic\" (basic)","log":{"level":"INFO","logger":"plugins.security.routes"},"process":{"pid":494,"uptime":842258.192436123},"trace":{"id":"7ce4ed122c2e76f8cc710585eca281e7"},"transaction":{"id":"8b3502edb4434d96"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.6.1"},"@timestamp":"2024-02-09T17:44:22.607-05:00","message":"Fleet Usage: {\"agents_enabled\":true,\"agents\":{\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"inactive\":0,\"unenrolled\":0,\"total_all_statuses\":0,\"updating\":0},\"fleet_server\":{\"total_all_statuses\":0,\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"updating\":0,\"num_host_urls\":0}}","log":{"level":"INFO","logger":"plugins.fleet"},"process":{"pid":494,"uptime":842859.18083514},"trace":{"id":"32e975dda611d5470a6bca4050226e81"},"transaction":{"id":"59065be4ddc9b394"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.6.1"},"@timestamp":"2024-02-09T17:52:42.195-05:00","message":"Fetch risk engine metrics","log":{"level":"INFO","logger":"plugins.securitySolution"},"process":{"pid":494,"uptime":843358.769814061},"trace":{"id":"2953a821ec1a112d12a9ee4637c8bd98"},"transaction":{"id":"056fed76f43ca9fe"}}
{"service":{"node":{"roles":["background_tasks","ui"]}},"ecs":{"version":"8.6.1"},"@timestamp":"2024-02-09T17:59:22.679-05:00","message":"Fleet Usage: {\"agents_enabled\":true,\"agents\":{\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"inactive\":0,\"unenrolled\":0,\"total_all_statuses\":0,\"updating\":0},\"fleet_server\":{\"total_all_statuses\":0,\"total_enrolled\":0,\"healthy\":0,\"unhealthy\":0,\"offline\":0,\"updating\":0,\"num_host_urls\":0}}","log":{"level":"INFO","logger":"plugins.fleet"},"process":{"pid":494,"uptime":843759.253458801},"trace":{"id":"32e975dda611d5470a6bca4050226e81"},"transaction":{"id":"23d49845edfdce0a"}
```

```
root@pdrpfelk01:/etc# tail -f /var/log/elasticsearch/elasticsearch.log
[2024-02-09T18:00:47,367][WARN ][o.e.h.n.Netty4HttpServerTransport] [pdrpfelk01] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:35494}
[2024-02-09T18:01:17,377][WARN ][o.e.h.n.Netty4HttpServerTransport] [pdrpfelk01] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:46374}
[2024-02-09T18:01:47,389][WARN ][o.e.h.n.Netty4HttpServerTransport] [pdrpfelk01] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:59324}
[2024-02-09T18:02:17,400][WARN ][o.e.h.n.Netty4HttpServerTransport] [pdrpfelk01] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:42706}
[2024-02-09T18:02:47,409][WARN ][o.e.h.n.Netty4HttpServerTransport] [pdrpfelk01] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:34274}
[2024-02-09T18:03:17,429][WARN ][o.e.h.n.Netty4HttpServerTransport] [pdrpfelk01] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:56004}
[2024-02-09T18:03:47,440][WARN ][o.e.h.n.Netty4HttpServerTransport] [pdrpfelk01] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:57792}
[2024-02-09T18:04:17,453][WARN ][o.e.h.n.Netty4HttpServerTransport] [pdrpfelk01] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:56046}
[2024-02-09T18:04:47,464][WARN ][o.e.h.n.Netty4HttpServerTransport] [pdrpfelk01] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:37930}
[2024-02-09T18:05:17,475][WARN ][o.e.h.n.Netty4HttpServerTransport] [pdrpfelk01] received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/127.0.0.1:9200, remoteAddress=/127.0.0.1:32940}
```







**Additional context**
Add any other context about the problem here.

**Attach the pfELK Error Log (error.pfelk), for Better Assistance***
 - Do not copy/paste log; attach as a file

**Comment by a3ilson** [comment]
@rpelissi 

Remove the current firewall dashboard (saved object) which appears to be the 22.01 version. There was a minor change (i.e., field was amended to log.syslog.hostname) and an updated firewall dashboard was applied.

- [x] Checked manual installation instructions 
- [x] Corrected pfelk-kibana-saved-objects.sh script

23.09 Firewall Dashboard https://github.com/pfelk/pfelk/blob/main/etc/pfelk/dashboard/23.09-firewall.ndjson

![Screen Shot 2024-02-10 at 11 20 32 AM](https://github.com/pfelk/pfelk/assets/16884679/36cadb5c-c7b8-478a-b370-8053029986c4)

**Comment by rpelissi** [comment]
Hi!
Perfect it works!
After cleaning and readding using the script the objects for the Firewall, I can now select the entry I want in the Firewall Selector.
I may have not done my cleanup correctly..
Thank you really much for your help!
I have one minor issue with the Snort Observer but I will open a new bug report for this.
Again, what a great tool!
:)
