### ISSUE TITLE
Dashboard templates not receiving data

### ISSUE THREAD

**Issue by IcarusFallin** [pfelk/pfelk#526]
**Issue**
Templates are not receiving log data from the correct location

![image](https://github.com/pfelk/pfelk/assets/96397406/0d19af66-8187-4534-abd6-3e3c485d3857)

*Cause**
My templates are likely out of date as I benched my pfELK project for some time following issues getting logstash.yml to work with Xpack security.

I believe my dashboard templates are looking for logs using a "pfsense" datastream data set instead of a "pfelk" datastream:

![image](https://github.com/pfelk/pfelk/assets/96397406/faf4cef6-44d2-4f3e-8b7a-e2d1f9e90e55)

![image](https://github.com/pfelk/pfelk/assets/96397406/7e2a47d0-50fe-4ae2-8313-dcb950574bce)

![image](https://github.com/pfelk/pfelk/assets/96397406/602a172a-e9cd-424e-9383-f51e2265bda0)

ALL dashboards show no data available when I am receiving data from logs with filter applied. We can see that the data I would like access to on these dashboards is available, all i need to do is remove the filters from the search:

![image](https://github.com/pfelk/pfelk/assets/96397406/e7a45f24-0059-4d31-807f-7b0212351685)

I'm sure this issue has been addressed but I am very new to ELK and was hoping I could get some help with getting my templates updated. Should I delete files and re-start from scratch, if so where is pfelk templates dir and what is the best process for this, etc/pfelk/templates folder is empty. Can I make an easy manual change? 

My pipelines.yml is default with only the etc/pfelk/conf.d config referenced.

**Firewall System (please complete the following information):**
 - ELK Version v 8.10.2
 - OS Ubuntu 22.04.3
 

 **Templates Installation method (manual, ansible-playbook, docker, script): manual, then script

**Comment by a3ilson** [comment]
Gotcha...so you've updated from a prior iteration of pfelk and specially the dashboards?

1. Recommend deleting the saved objects (reference [YouTube](https://www.youtube.com/watch?v=KV27ouVUGuc&t=280s))

2. Next, install the new/updated saved objects referencing: https://github.com/pfelk/pfelk/blob/main/install/templates.md#two-dashboards

**Comment by IcarusFallin** [comment]
Thank you so much, this worked like a charm. First time with successful dashboard/firewall logs ever, how marvelous!

Is case anyone else sees this post having a similar issue in the future: 

I used the date-stamps to locate all the "Saved Objects" associated specifically with PfELK since I had other integrations installed. 

Make sure you delete ALL the pfelk "Saved Objects" and only items found here. Reinstall BOTH Templates and Dashboards fresh (make sure to fully delete and redownload pfelk-kibana-saved-objects.sh since the FILE DOES CHANGE if doing scripted method).

Data is flowing beautifully now.

**Comment by IcarusFallin** [comment]
There's an issue receiving data from the *-pfelk-dhcp* datastream now as it looks like it no longer exists, perhaps it never did:

![image](https://github.com/pfelk/pfelk/assets/96397406/6b3dd7de-4753-45df-90b2-a72fdf3ca9a8)

The new templates I updated though are looking for that data-stream and cannot find it:
![image](https://github.com/pfelk/pfelk/assets/96397406/be2d8ed4-3e1f-439e-96da-3231381f2ea3)

It shows up under "data views" just not data streams:
![image](https://github.com/pfelk/pfelk/assets/96397406/394db13c-572f-47c8-8c03-8d8ee1103904)

**Comment by a3ilson** [comment]
Depending on your network, you might have to wait until a DHCP event is logged. I typically disconnect and reconnect a device to force a new DHCP lease, when testing.

1. The 50-outputs.conf [line 13](https://github.com/pfelk/pfelk/blob/292ed23a9cbac15548e854f2d317aa0c0a2bfdf9/etc/pfelk/conf.d/50-outputs.pfelk#L13) will send all logged events where the app name equals "DHCP"
2. The DHCP template is located [here](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/templates/pfelk-dhcp)
4. The DHCP dashboard is located [here](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/dashboard/24.02-dhcp.ndjson)

Hopefully it just needed time to generate DHCP events.

**Comment by IcarusFallin** [comment]
I believe I found the issue, or at least had. It was due to the Network Capture integration being installed. I realized this because I saw huge log files for the network capture DHCP integrations data stream so I figured I would delete it. I removed that integration completely, deleting all saved objects associated with it. I also verified my DHCP template matches. I'm still not seeing a data stream being created for "logs-pfelk-dhcp" which is why I believe I'm also not seeing any fields in my *-pfelk-dhcp* data view.

![image](https://github.com/pfelk/pfelk/assets/96397406/c778325e-6ed0-4ec6-86f4-10ac74ec3a8c)

![image](https://github.com/pfelk/pfelk/assets/96397406/cb572dfd-038d-486b-a141-90d63c85f18d)

![image](https://github.com/pfelk/pfelk/assets/96397406/ad9890a2-696a-465b-97e6-470bd5b78e3d)

After deleting objects, rebooting the ELK server, reinstalling DHCP template/dashboard, and rebooting again I'm still getting the same issue. The data stream isn't being generated from the template?
Could this other logs template be an issue? 

![image](https://github.com/pfelk/pfelk/assets/96397406/b4a6aa31-1564-47a3-aabe-4b4825cbb760)

**Comment by a3ilson** [comment]
The other data streams and corresponding dashboards are working?

Are you using a different DHCP service other than the default?


Hasty DHCP Overview:
1) pfSense/opnsense sends remote logs
a. Check to make sure the DHCP logs are being sent
2) 02-firewall.pfelk separates events (logs) by comma
3) 05-apps.pfelk tags events which contain "DHCP" 
4) 50-outputs.pfelk separates most "appname" fields and for those with the "dhcp" value in "log.syslog.appname" are sent as the "dhcp" datastream.

- [ ] Confirm to see if in fact the dhcp events are being sent (should be "log.syslog.priority" 190/191)
- [ ] The "logs-pfelk-unknown" is a catch all and any events without the corresponding tag within the 50-outputs.pfelk file are or should be visible within this data stream.
- [ ] The 49-cleanup.pfelk will drop unwanted logs based on their "log.syslog.priority" but by default this is disabled


To view the "logs-pfelk-unknown" events you'll need to do the following:
1. Navigate to ≡ (upper left), scroll down and click on "Stack Management"
2. Click on "Data Views" (nested under Kibana)
3. Click + and add a new "Data View"
4. <img width="1525" alt="Screenshot 2024-02-25 at 10 46 36" src="https://github.com/pfelk/pfelk/assets/16884679/274881e6-1f87-43a5-89c2-e963e7b449b6">
5. Save new data view (will need to provide it a name)
6. Navigate to "Discover" and selected the new data view from step 5
a. Filter the log.syslog.priority for 190 and/or 191 (dhcp events) to check if those logs are not being parsed.
b. If located and not being parsed, please provide the original log (event.original)

**Comment by a3ilson** [comment]
@IcarusFallin is this still an issue?

**Comment by IcarusFallin** [comment]
I was not able to resolve the problem, it's been a moment since I've had time to spend on it. I noticed that the templates have been updated. I'm tempted to completely reinstall the stack from scratch and get the firewall logs working completely before installing Fleet Agent since I think that messed up my datastreams.

I went through deleting saved objects again and I'm trying to reinstall the templates and dashboards but getting errors when sending console requests: 


#! index template [pfelk-firewall] has index patterns [*-pfelk-firewall*] matching patterns from existing older templates [.monitoring-logstash,.monitoring-es,.monitoring-beats,.monitoring-kibana] with patterns (.monitoring-logstash => [.monitoring-logstash-7-*],.monitoring-es => [.monitoring-es-7-*],.monitoring-beats => [.monitoring-beats-7-*],.monitoring-kibana => [.monitoring-kibana-7-*]); this template [pfelk-firewall] will take precedence during new index creation
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "composable template [pfelk-firewall] template after composition with component templates [data-streams-mappings, pfelk-settings, pfelk-mappings] is invalid"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "composable template [pfelk-firewall] template after composition with component templates [data-streams-mappings, pfelk-settings, pfelk-mappings] is invalid",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "invalid composite mappings for [pfelk-firewall]",
      "caused_by": {
        "type": "illegal_argument_exception",
        "reason": "data stream timestamp field [@timestamp] has disallowed [ignore_malformed] attribute specified"
      }
    }
  },
  "status": 400
}

![image](https://github.com/pfelk/pfelk/assets/96397406/a22fb52c-bdce-4dee-944b-105332f39fcd)

**Comment by a3ilson** [comment]
@IcarusFallin 

1. Recommend getting working prior to utilizing any other plugins and/or integrations. 
2. Ensure you are using the lasted templates.
  a. <img width="1534" alt="Screenshot 2024-03-13 at 06 28 39" src="https://github.com/pfelk/pfelk/assets/16884679/27946c56-a760-451f-be47-8bd447bccd74">
3. Ensure you are using the latest dashboard (dhcp depicted below)
  a. <img width="1195" alt="Screenshot 2024-03-13 at 06 28 54" src="https://github.com/pfelk/pfelk/assets/16884679/b89bf899-0585-497c-a621-9692cc4aa093">

**Comment by IcarusFallin** [comment]
I went ahead and created a new stack from scratch and am experiencing the exact same issue. At this point I went ahead and created a new data view called "Unknown logs" using the index pattern you provided from earlier and here is what I am seeing:

![image](https://github.com/pfelk/pfelk/assets/96397406/530cceab-3e0b-45fe-9101-35198297f4c4)

**Comment by a3ilson** [comment]
Issue merged with #531 pfSense transitioned to kea-dhcp rendering the dhcpd saved objects/dashboards inoperable. See #531 as this issue is being worked.
