### ISSUE TITLE
Data not appearing in dashboards

### ISSUE THREAD

**Issue by gazelle-hub** [pfelk/pfelk#530]
I've installed pfelk today which is amazing but I'm only get a couple of dashboards working.

I've installed pfelk on Ubuntu 20.04 using the scripts method and am using PFSense 2.7.2 to send logs to pfelk.

The dashboards for Unbound and Firewall work fine but the ones for HAProxy and DHCP don't show any data.

I looked at Analytics - Discover and there is data views for haproxy and dhcp but the dhcp one has no data in it but haproxy does.

**Comment by a3ilson** [comment]
@gazelle-hub 

Would you mind sharing some logs for both `dhcp` and `haproxy`

The majority of this repo was developed with OPNsesne logs with various contributors who have been critical in expanding to pfSense and various plugins (e.g., haproxy). I presume the dhcp logs are good but there might be slight variations between pf/opnsesne. The haproxy logging sounds promising (presume it is simply a mapping issue).

## dhcp
Here are some dhcp logs from my system...which are working:
```
<190>1 2024-03-24T18:06:49+00:00 firewall.local dhcpd 48080 - [meta sequenceId="551848"] DHCPREQUEST for 172.22.3.5 from 33:22:11:5a:25:00 via ix0
```
```
<190>1 2024-03-24T18:06:49+00:00 firewall.local dhcpd 48080 - [meta sequenceId="551849"] DHCPACK on 172.22.3.5 to 33:22:11:5a:25:00 via ix0
```

## haproxy
As for haproxy logs...[v23.08](https://github.com/pfelk/pfelk/releases/tag/v23.08) was working and I suspect that the latest changes #527 is the likely culprit. The original haproxy is attributed to @BeNeDeLuX via issue #151 and it appears that the mappings utilized were all "keywords". Unfortunately, BeNeDeLuX no longer uses haproxy to my knowledge. I say all that to say, since data is being received and viewable within Discover, I suspect that the dashboards are not working due to mappings related to the haproxy logs. We can try 1 or 2 things:
1) Create (use prior mapping) mappings for haproxy fields and associate to current haproxy template
2) Build new mappings based on the field type and associate to current haproxy template



## DHCP

Make sure you are using the latest DHCP dashboard:
<img width="548" alt="Screenshot 2024-03-24 at 14 34 05" src="https://github.com/pfelk/pfelk/assets/16884679/8e46b9b1-5dad-4e17-ae1a-d88482b05144">

**Comment by a3ilson** [comment]
@gazelle-hub 

For the haproxy...try installing the following mappings via dev tools:
```
PUT _index_template/pfelk-haproxy
{
  "version": 2024,
  "priority": 400,
  "template": {
    "settings": {
      "index": {
        "lifecycle": {
          "name": "pfelk"
        }
      }
    },
    "mappings": {
      "_routing": {
        "required": false
      },
      "numeric_detection": false,
      "_source": {
        "excludes": [],
        "includes": [],
        "enabled": true
      },
      "dynamic": true,
      "dynamic_templates": [],
      "date_detection": false,
      "properties": {
        "haproxy": {
          "type": "object",
          "properties": {
            "server_name": {
              "eager_global_ordinals": false,
              "norms": false,
              "index": true,
              "store": false,
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              },
              "index_options": "docs",
              "split_queries_on_whitespace": false,
              "doc_values": true
            },
            "termination_state": {
              "eager_global_ordinals": false,
              "norms": false,
              "index": true,
              "store": false,
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              },
              "index_options": "docs",
              "split_queries_on_whitespace": false,
              "doc_values": true
            },
            "time_queue": {
              "type": "long"
            },
            "bytes_read": {
              "type": "long"
            },
            "mode": {
              "type": "keyword"
            },
            "backend_queue": {
              "type": "long"
            },
            "backend_name": {
              "eager_global_ordinals": false,
              "norms": false,
              "index": true,
              "store": false,
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              },
              "index_options": "docs",
              "split_queries_on_whitespace": false,
              "doc_values": true
            },
            "frontend_name": {
              "eager_global_ordinals": false,
              "norms": false,
              "index": true,
              "store": false,
              "type": "keyword",
              "fields": {
                "text": {
                  "type": "text"
                }
              },
              "index_options": "docs",
              "split_queries_on_whitespace": false,
              "doc_values": true
            },
            "http": {
              "type": "object",
              "properties": {
                "request": {
                  "type": "object",
                  "properties": {
                    "captured_cookie": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword"
                        }
                      }
                    }
                  }
                },
                "response": {
                  "type": "object",
                  "properties": {
                    "captured_cookie": {
                      "type": "text",
                      "fields": {
                        "keyword": {
                          "type": "keyword"
                        }
                      }
                    }
                  }
                }
              }
            },
            "server_queue": {
              "type": "long"
            },
            "time_backend_connect": {
              "type": "long"
            },
            "connections": {
              "type": "object",
              "properties": {
                "retries": {
                  "type": "long"
                },
                "server": {
                  "type": "long"
                },
                "active": {
                  "type": "long"
                },
                "backend": {
                  "type": "long"
                },
                "frontend": {
                  "type": "long"
                }
              }
            },
            "timestamp": {
              "format": "strict_date_optional_time||epoch_millis||dd/MMM/yyyy:HH:mm:ss.SSS",
              "index": true,
              "ignore_malformed": false,
              "store": false,
              "type": "date",
              "doc_values": true
            }
          }
        }
      }
    }
  },
  "index_patterns": [
    "*-pfelk-haproxy*"
  ],
  "data_stream": {
    "hidden": false,
    "allow_custom_routing": false
  },
  "_meta": {
    "description": "default haproxy indexes installed by pfelk",
    "managed": true
  }
}
```

**Comment by gazelle-hub** [comment]
Thanks so much for the detailed response.

Firstly, how do I get the DHCP logs? Just not sure where I find those for you? Here is a screenshot from PFsense for DHCP if that helps at all?
![image](https://github.com/pfelk/pfelk/assets/53669961/2e3bccbb-a243-40a3-8665-6359e20746cc)


I am using the latest dashboard file for DHCP

I tried the haproxy template but unfortunately it still didn't work.

When I go to the haproxy dashboard I see this:
![image](https://github.com/pfelk/pfelk/assets/53669961/f5994cb9-deb4-49c6-862b-1faaa3208cc6)

This is what I see for the data view for haproxy:
![image](https://github.com/pfelk/pfelk/assets/53669961/8f17afb4-4375-4373-9dea-67e3cf1f4587)


For DHCP I get this when I go to the data view:

![image](https://github.com/pfelk/pfelk/assets/53669961/491206dd-c085-4557-a20b-c8d703d92c66)

**Comment by a3ilson** [comment]
## DHCP
- You might need to expand the time frame (default is last 15m). When testing, I typically disconnect/reconnect a device to generate logs.
- Check the "Data Streams" to see if DHCP events are being or have been logged/observed.
  - <img width="1527" alt="Screenshot 2024-03-24 at 20 01 50" src="https://github.com/pfelk/pfelk/assets/16884679/58e0a6da-cf62-4403-b786-e0c9f50be880">


## HAPROXY
- Logs are being generated, based on what you've provided.
- Within Discover, expand a log and provide the text output from within the "event.original" field and also a screenshot of the parsed log(s)
  - <img width="561" alt="Screenshot 2024-03-24 at 20 02 58" src="https://github.com/pfelk/pfelk/assets/16884679/f73cbc84-231d-4c24-940f-8908135eb318">
  - <img width="1528" alt="Screenshot 2024-03-24 at 20 04 14" src="https://github.com/pfelk/pfelk/assets/16884679/ba90a675-3f95-4478-896e-32c2a407ba36">

**Comment by gazelle-hub** [comment]
So there doesn't seem to be anything in data streams for DHCP:
![image](https://github.com/pfelk/pfelk/assets/53669961/234560d2-d7d0-4c43-bfa3-38a7f5f8c968)


Here's the detail of haproxy:
<134>Mar 25 13:33:28 HAProxy haproxy[69282]: Connect from 192.168.1.159:59314 to 192.168.1.1:443 (internal_haproxy_fe/HTTP)

Here's a screenshot of my config for pfsense:
![image](https://github.com/pfelk/pfelk/assets/53669961/d0fb9935-2d36-4365-9b57-aafecfc56c2a)

Let me know if I haven't sent you the right things.

**Comment by a3ilson** [comment]
## HAProxy
- Can you provide another screenshot that shows available options within pfSense regarding haproxy? This was originally built via OPNsense.
  - The default/testing settings for pfelk logging were:
    - <img width="846" alt="Screenshot 2024-03-25 at 17 12 40" src="https://github.com/pfelk/pfelk/assets/16884679/9c7a2fd4-fcdb-442a-a1b1-855652f73857">
- Please update your settings (i.e., remove value within "Log hostname" and set "Syslog level" to "Info" and if available within pfSense, set the "pass-through" option to "httpplog"

## dhcp
Interesting that it is being logged but not logs (no data stream) is present.
- Try changing the Logging Option from "Firewall" to "Everything" and see if that works otherwise, we'll check the "unknown" logs and see why they aren't being parsed.

**Comment by gazelle-hub** [comment]
Here's a pdf with all of the options available for haproxy in Pfsense. I tried adding "option httplog" to the the section Global Advanced pass thru - Custom Options but it errored out. I did manage to put that option in the frontends and it seemed to accept it so I'll keep an eye on it.

[pfsenseold.gazelle-family.com - Services_ HAProxy_ Settings.pdf](https://github.com/pfelk/pfelk/files/14754250/pfsenseold.gazelle-family.com.-.Services_.HAProxy_.Settings.pdf)

Everything had been selected for logs so that shouldn't be it, where do I look to find the unknown data?

**Comment by a3ilson** [comment]
Navigate to "Stack Management">>"Data Views" and create a new view:
<img width="1658" alt="Screenshot 2024-03-27 at 05 30 24" src="https://github.com/pfelk/pfelk/assets/16884679/9e85a35f-9c84-431b-8e11-1d7c55a733a9">


Once created, navigate to Discover and select the new "Data View"
<img width="554" alt="Screenshot 2024-03-27 at 05 32 00" src="https://github.com/pfelk/pfelk/assets/16884679/8feac24b-c45a-4ebc-a557-ee4e8c7a7edf">

Look through the logs, looking for DHCP entries which could also be in other "data views". Once located, provide a few log entries (copy paste the "event.original") which should aid in further troubleshooting.

**Comment by a3ilson** [comment]
The "option httplog" set on the frontend was how this was originally set (#151). Are the haproxy logs still being collected within the "pfelk-haproxy" data view and if so could you provide a few logs?

**Comment by revere521** [comment]
@a3ilson i just had to rebuild my home lab pfelk server, and i also notice that the DHCP does not ingest data.  It looks like pfsense switched to Kea DHCP. 

 I can provide you with some log output if you like - but there are now two processes on pfsense for DHCP `kea-dhcp4` and `dhclient `

**Comment by a3ilson** [comment]
@revere521  if you don’t mind sharing some logs (dhcp), I’ll build a filter but will need your help building the updated dashboard.

**Comment by a3ilson** [comment]
Didn’t realize ISC DHCP reached its end of life and we as removed from pfsense. I’m guessing OPNSense will be next. I’ll transition to KEA (opnsense) and hopefully the log output is the same.

**Comment by a3ilson** [comment]
#531 
Open to address kea dhcp support.

**Comment by carlosmgc** [comment]
@revere521 for HAProxy in pfSense, go to your Frontend configuration and enable detailed logging. This did the trick for me.
![image](https://github.com/pfelk/pfelk/assets/30412401/9bc8c485-d316-4716-b41f-48fb850cca03)

**Comment by a3ilson** [comment]
> @revere521 for HAProxy in pfSense, go to your Frontend configuration and enable detailed logging. This did the trick for me. ![image](https://private-user-images.githubusercontent.com/30412401/326287658-9bc8c485-d316-4716-b41f-48fb850cca03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMzIwMTgsIm5iZiI6MTcxNDMzMTcxOCwicGF0aCI6Ii8zMDQxMjQwMS8zMjYyODc2NTgtOWJjOGM0ODUtZDMxNi00NzE2LWI0MWYtNDhmYjg1MGNjYTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE5MTUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNjVjMTc3YWE4NGFiYWY1NWI3YjU4YzViM2JhMDk4YTQ5ZTQzYzdjOTZjMGI4NDYxMWRmNzAwZjA1ZDhiNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SMsJyDfJHyg7DcK0quXxX2TJqzGzZ5gVr41XBbl3r7k)

Thanks @carlosmgc for confirming!
