### ISSUE TITLE
kea dhcp support

### ISSUE THREAD

**Issue by a3ilson** [pfelk/pfelk#531]
ISC DHCP reached EOL on 5 October 2022.
- pfSense has migrated to kea DHCP
- OPNsense has not migrated to kea DHCP although kea DHCPv4 is available and kea DHCPv6 looming

- [x] Build filter to parse kea DHCPv4 logs
- [ ] Build filter to parse kea DHCPv6 logs
- [ ] Build kea-dhcp dashboard (unified and/or v4 & v6)

* Issue origination steamed from #530

**Comment by a3ilson** [comment]
## kea-dhcp
1. Logged within `*-pfelk-unknown*`
2. Filed `log.syslog.appname` contains a value of `kea-dhcp4` (do not have dhcpv6...running OPNsense)
3. Log messages:
  - ```<134>1 2024-04-05T21:44:27+00:00 fw.something.com kea-dhcp4 91064 - [meta sequenceId="17350"] INFO  [kea-dhcp4.leases.0x834f58200] DHCP4_INIT_REBOOT [hwtype=1 ab:cd:ef:12:34:56], cid=[12:34:45:ab:cd:ef:00], tid=0x387fef6: client is in INIT-REBOOT state and requests address 172.2.1.100```
  - ```<134>1 2024-04-05T21:44:27+00:00  fw.something.com kea-dhcp4 91064 - [meta sequenceId="17351"] INFO  [kea-dhcp4.leases.0x834f58200] DHCP4_LEASE_ALLOC [hwtype=1 ab:cd:ef:12:34:56], cid=[12:34:45:ab:cd:ef:00], tid=0x387fef6: lease 172.2.1.100 has been allocated for 4000 seconds```

- [x] Gathering more logs...then build out `kea-dhcpv4` grok pattern within pfelk.grok
- [ ] Pending `kea-dhcpv6` logs for grok pattern, testing and implementation

**Comment by revere521** [comment]
@a3ilson thanks!  let me know if you want some log output

**Comment by a3ilson** [comment]
> @a3ilson thanks! let me know if you want some log output

If you have kea-dhcpv6 logs, I could use those as opnsense currently does not have support for kea-dhcpv6.

**Comment by a3ilson** [comment]
~12hours running with kea and only have four unique events logged out of a ~3K events.
```
<134>1 2024-04-06T12:12:38+00:00 fw.example.com kea-dhcp4 91064 - [meta sequenceId="324510"] INFO  [kea-dhcp4.leases.0x834f57400] DHCP4_LEASE_ALLOC [hwtype=1 aa:12:34:56:78:90], cid=[no info], tid=0x7729dab0: lease 192.168.1.13 has been allocated for 4000 seconds
<134>1 2024-04-06T12:12:34+00:00 fw.example.com kea-dhcp4 91064 - [meta sequenceId="324508"] INFO  [kea-dhcp4.leases.0x834f57400] DHCP4_LEASE_ADVERT [hwtype=1 bb:12:34:56:78:90], cid=[01:02:03:04:05:06:07], tid=0xda7d0a88: lease 192.168.1.106 will be advertised
<134>1 2024-04-06T12:12:33+00:00 fw.example.com kea-dhcp4 91064 - [meta sequenceId="324505"] INFO  [kea-dhcp4.leases.0x834f57400] DHCP4_LEASE_ALLOC [hwtype=1 cc:12:34:56:78:90], cid=[0a:02:03:04:05:06:07], tid=0x7677c730: lease 192.168.1.148 has been allocated for 4000 seconds
<134>1 2024-04-06T11:44:59+00:00 fw.example.com kea-dhcp4 91064 - [meta sequenceId="315706"] INFO  [kea-dhcp4.leases.0x834f58900] DHCP4_LEASE_ALLOC [hwtype=1 dd:12:34:56:78:90], cid=[ff:33:66:cc:bb:00:11:00:00:44:66:33:66:cc:ff], tid=0x469fb066: lease 192.168.1.192 has been allocated for 4000 seconds
```

If you have other logs types (different syntax) please provide.

**Comment by a3ilson** [comment]
![kea_lease-allocation](https://github.com/pfelk/pfelk/assets/16884679/15669479-39ce-47f7-bd5c-babe754dd60a)


hwtype = Hardware MAC address
cid = Client ID
tid = Time (appears to be unix timestamp recorded in hex); 
- appears to be the lease expiration time but need to confirm/validate (same value that is set within kea regarding lease time)
- subtracting 4000 from the decimal value of the tid does not equal the syslog timestamp
- converting the original tid to time is beyond the syslog timestamp
  - tid=0x7677c730 = 1712408653 which converts to Sat 6 April 2024 13:04:13 UTC
  - tid=0x7677c730 = 1712408653; 1712408653-4000 = 1712404653 which converts to Sat 6 April 2024 11:57:33 UTC
  - The original syslog time stamp for the event with tid=0x7677c730 was 2024-04-06T12:12:33+00:00
    - 4000 is 1-hours, 6-minutes and 40 seconds
    - original tid - 4000 is 15min prior to the syslog timestamp
    - original tid is 51min and 40seconds after the systole timestamp



Findings:
- 4000 is the lease time set/defined within kea
- 4000 is the default and a good duration for large/public/corporate networks
- 86400 (24-hours) is recommended for home networks
- tid is lease time associated to the cid (i.e., the initial kea-dhcp request tid is very close to the syslog timestamp)

Notes:
OPNsense does not allow any verbosity regarding remote kea-dhcp logging
Hostnames are recorded, if available, within the kea-dhcp lease record but not sent via syslog (OPNsense)

**Comment by a3ilson** [comment]
![](http://images.henrydu.com/post/2020-10-16-kea-dhcp-webinar/kea_lease-allocation.jpg)

KEA-DHCP logging is somewhat nonexistent
- hwtype? Possibly MAC address of device
- cid? Possibly the Client ID (unique to KEA)
- tid? Initially thought it was time in hex but upon further review that is unlikely...maybe lease id but more analysis is needed

**Comment by a3ilson** [comment]
Latest update is parsing kea-dhcp logs (OPNsense). Will run for a few days and check back for other log types.

**Comment by a3ilson** [comment]
<img width="2010" alt="Screenshot 2024-04-07 at 10 43 11" src="https://github.com/pfelk/pfelk/assets/16884679/aa7942a5-a0aa-4a9e-a4ab-eb0e898d3465">

The only GROK Failures, after running since latests updates, were what appears to be a cleanup cron job which run every hour. Added GROK filter to parse the cleanup kea-dhcp csv files (i.e., cron job).

Pending testing confirmation from pfSense instances running kea-dhcp.

**Comment by a3ilson** [comment]
Clean install, testing and will build out dashboard 12-24hrs after sufficient logs generated.

**Comment by carlosmgc** [comment]
I did some modifications to the existing dhcp data views to get the kea-dhcp logs into the view, and then I modified visualizations and was able to get the existing dashboard to display the kea-dhcp data. The only information i dont see available is interface,  everything else is looking good.

pfSense 2.7.2

![kea-dhcp-dashboard](https://github.com/pfelk/pfelk/assets/30412401/1cb0053c-3edb-4b26-9367-f23f450fc886)

**Comment by a3ilson** [comment]
@carlosmgc thanks!

so to confirm, you merely adjusted the visualization to interpret the kea-dhcp events? Fell free to submit a PR or I’ll update and post in the next few days.

while reviewing the logs, it doesn’t appear that kea provides the referenced interface.

**Comment by a3ilson** [comment]
kea (dhcpv4) completed...awaiting OPNsense to update with v6.

**Comment by carlosmgc** [comment]
> @carlosmgc thanks!
> 
> so to confirm, you merely adjusted the visualization to interpret the kea-dhcp events? Fell free to submit a PR or I’ll update and post in the next few days.
> 
> while reviewing the logs, it doesn’t appear that kea provides the referenced interface.

I apologize, I am not familiar with GitHub pull requests.  I am happy to contrubute here in whichever way I can.  Thank you for maintaining this project.

**Comment by a3ilson** [comment]
@carlosmgc 

thanks again and no worries, I already updated and posted the kea dhcp updated template and dashboard. I am running OPNsense which seems to be lagging a bit behind pfsense regarding the implantation of kea. I am only able to test and confirm dhcp v4 and curious as to what the v6 (ipv6) logs look like / any chance your configuration is running/supporting ipv6?

**Comment by carlosmgc** [comment]
At the moment I am not assigning any ipv6 on my internal network (on purpose).  I'll see if I can set it up in a lab sometime in the future to see how it looks.

**Comment by a3ilson** [comment]
awaiting IPv6 implementation for OPNsense for further testing. However, anyone with pfSense and KEADHCPv6 willing to test/contribute, it would be greatly appreciated.
