### ISSUE TITLE
Error loading Suricate template

### ISSUE THREAD

**Issue by ledge39** [pfelk/pfelk#534]
Doing a manual install and I receive the following error when index_template/pfelk-suricata.

<img width="1440" alt="Screenshot 2024-05-01 at 18 39 01" src="https://github.com/pfelk/pfelk/assets/37451439/167c16ce-e825-4838-ad98-eba9c836cb5d">

Can you help?

**Comment by a3ilson** [comment]
@ledge39 

thanks for ordinating and reporting this issue. I’ll update/fix in a few hours if you don’t mind giving it another try.

**Comment by a3ilson** [comment]
@ledge39 - updated....please try again and let me know if it works.

**Comment by ledge39** [comment]
All work fine now. Thanks for the quick response

**Comment by a3ilson** [comment]
#527 - fixed
