### ISSUE TITLE
Kibana will not start after changing VM (Ubuntu) IP Address

### ISSUE THREAD

**Issue by Buckeyes1995** [pfelk/pfelk#535]
**Describe the bug**
When I changed the IP address of my Proxmox VM (Ubuntu), Kibana will not start.  

**To Reproduce**
1. Change IP address in /etc/netplan/50-init-cloud.yaml

**Screenshots**

**Firewall System (please complete the following information):**
 - OPNsense
 - Latest version 
 
**Operating System (please complete the following information):**
 - Ubuntu 22.04.4 LTS:
 
 **Installation method (manual, ansible-playbook, docker, script):**
 - Script
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
Latest

 **Elasticsearch, Logstash, Kibana logs:**
The cabana log file indicates that the Hostname/IP does not match the certificates IP.  

**Additional context**
I was able to fix the first issue by updating /etc/kibana/kibana.yaml and change the IP address.  I'm unsure how to update the cert (or where it is) to change it in there.

**Comment by a3ilson** [comment]
Changing the IP address of the host system will break the trust relationship.
1) Revert to the prior IP address
2) Install with the system configured with the new IP address 
3) Reaccomplish the security steps (https://github.com/pfelk/pfelk/blob/main/install/security.md)
