### ISSUE TITLE
Cannot get data to display Suricata dashbord and Firewall dashbord

### ISSUE THREAD

**Issue by a3ilson** [pfelk/pfelk#539]
### Discussed in https://github.com/orgs/pfelk/discussions/538

<div type='discussions-op-text'>

<sup>Originally posted by **TieuBinh123** May 29, 2024</sup>
I have installed Suricata on pfSense and ELK. I tried sending data from the pfSense machine and checked the logs on the pfSense machine, and there were no issues. However, the log in Logstash shows an error indicating that it could not send data to Elasticsearch.
Im install in vmware
PFSENSE
24.2 beta2 - pfsense 2.7.2
Screenshot
 
I have tried with both RFC5424 and RFC3164, but neither worked.
![image](https://github.com/pfelk/pfelk/assets/107189807/437cee88-b225-4648-8df7-453fae38d3de)
![image](https://github.com/pfelk/pfelk/assets/107189807/35c31f62-58f5-45a8-b02f-7fa2e7ee610e)

![image](https://github.com/pfelk/pfelk/assets/107189807/01c9c2c2-5d82-40f8-b092-2dc1df3ac567)

Log suricata
![image](https://github.com/pfelk/pfelk/assets/107189807/3ccd3d90-f917-4f34-a730-a7ffd9a78bc9)

I have fully installed the pfELK packages on ELK.

Log Logstash 

![image](https://github.com/pfelk/pfelk/assets/107189807/e6c33f3f-96ce-4ee2-8d15-4b7029d90f16)
[2024-05-29T12:02:25,047][WARN ][logstash.outputs.elasticsearch][pfelk][6bb69d12df47f484da6edfc05eb82144a3ecc1409df56a5f949148c81f635d6b] Could not index event to Elasticsearch. {:status=>404, :action=>["create", {:_id=>nil, :_index=>"logs-pfelk-suricata", :routing=>nil}, {"@timestamp"=>2024-05-29T05:02:24.816720298Z, ...}], :response=>{"create"=>{"status"=>404, "error"=>{"type"=>"index_not_found_exception", "reason"=>"no such index [logs-pfelk-suricata] and composable template [*-pfelk-suricata*] forbids index auto creation", "index_uuid"=>"_na_", "index"=>"logs-pfelk-suricata"}}}

![image](https://github.com/pfelk/pfelk/assets/107189807/cde724f6-1e97-4d60-bb76-edc84f5b8598)

![image](https://github.com/pfelk/pfelk/assets/107189807/35cb3449-d59d-4804-9e8f-ea8838303a4d)

</div>

**Comment by a3ilson** [comment]
@TieuBinh123

Have you reviewed/followed [these steps](https://github.com/pfelk/pfelk/wiki/How-To:-Suricata-on-pfSense) located within the wiki page?

**Comment by a3ilson** [comment]
no response...

**Comment by TieuBinh123** [comment]
> page

I apologize for the delayed response. It's because I haven't been checking my Gmail regularly.
yes, I have reviewed/followed your step in wiki page
![image](https://github.com/pfelk/pfelk/assets/107189807/52cd7b06-fa39-44e4-90e0-f6694be811a1)
As requested earlier, I have tried uninstalling and reinstalling to troubleshoot. My Logstash has successfully received logs from pfSense and Suricata, but it still cannot forward logs to Elasticsearch.
![image](https://github.com/pfelk/pfelk/assets/107189807/cb5deb3e-7011-4980-9070-d8360a7df29a)

**Comment by TieuBinh123** [comment]
I tried to set up according to the instructions at this address. [https://github.com/pfelk/pfelk/blob/main/install/preparation.md](url)

**Comment by TieuBinh123** [comment]
In elastichsearch, I dont see connect in pfsense to elk ![image](https://github.com/pfelk/pfelk/assets/107189807/8bc74b3f-8b4a-4d93-9fe7-232d2bff036b)

**Comment by TieuBinh123** [comment]
Is it correct to add templates in this way?
![image](https://github.com/pfelk/pfelk/assets/107189807/040ced7b-c71c-41e1-823d-28491b29f937)

**Comment by a3ilson** [comment]
@TieuBinh123 based on your prior log, it appears Suricata data is being received and enriched by Logstash. However, the *-pfelk-suricata* index template did not allow for auto creation. 

I'm updated the template. Please delete the pfelk-suricata index templated and reapply.

1. Remove pfelk-suricata index template 
<img width="1325" alt="Screenshot 2024-07-06 at 06 29 05" src="https://github.com/pfelk/pfelk/assets/16884679/152b658c-6b8f-403a-a975-db5a6fc3ec25">


2. Reinstall the pfelk-suricata index template
  a. Access [here](https://raw.githubusercontent.com/pfelk/pfelk/492012bdf7a42b19150247811301fc594518a5a3/etc/pfelk/templates/index_template_pfelk-suricata)
  b. <img width="1411" alt="Screenshot 2024-07-06 at 06 33 03" src="https://github.com/pfelk/pfelk/assets/16884679/f7cff9ad-daa2-4ce2-8139-97166bfaf2c9">

**Comment by TieuBinh123** [comment]
Thank you very much, it worked.

![image](https://github.com/user-attachments/assets/ecea98c0-06ba-42ac-82d8-e9cabf2446bd)
![image](https://github.com/user-attachments/assets/a2ebff08-c2f2-4666-8791-5e76f1b689c6)
![image](https://github.com/user-attachments/assets/db8cf324-6e73-4250-a691-c91abfa3f477)
