### ISSUE TITLE
Logstash does not appear in the Index

### ISSUE THREAD

**Issue by pwgrau** [pfelk/pfelk#54]
I followed all the steps, but the index called logstash does not appear in the kibana, I attach these logs. please help ..

[log-elastic.txt](https://github.com/a3ilson/pfelk/files/3935671/log-elastic.txt)
[Log-logstash.txt](https://github.com/a3ilson/pfelk/files/3935672/Log-logstash.txt)

occupying pfsense

![image](https://user-images.githubusercontent.com/49996718/70382030-d5d8c080-1933-11ea-8017-2b8331dd0f12.png)

**Comment by a3ilson** [comment]
It appears you are using an old version of elastic stack (6.x) and you do not have Geoip installed or referenced to the correct location.  If you followed the latest guide the pattern should be of-*

Please follow the latest tutorial on GitHub.

**Comment by pwgrau** [comment]
> Parece que está utilizando una versión anterior de la pila elástica (6.x) y no tiene Geoip instalado o referenciado a la ubicación correcta. Si siguió la última guía, el patrón debería ser de- *
> 
> Siga el último tutorial en GitHub.

All the reason guide me from a previous post, all good, thanks.
