### ISSUE TITLE
HAProxy dashboard / HAProxy HTTP Status Codes: field invalid

### ISSUE THREAD

**Issue by mmartinello** [pfelk/pfelk#541]
**Describe the bug**

The HAProxy dashboard seems to be broken in the **HAProxy HTTP Status Codes** widget due to the following error:

Saved field "http.response.status_code" of data view "-pfelk-haproxy" is invalid for use with the "Range" aggregation. Please select a new field.

<img width="776" alt="Screenshot 2024-06-12 at 23 43 33" src="https://github.com/pfelk/pfelk/assets/3822398/d3bac5ef-dd58-498c-a1c1-f6f89f4aa3ba">

**Firewall System (please complete the following information):**
 - pfSense 2.7.0-RELEASE (amd64)
 
 **Installation method:** Docker
 
**Elasticsearch, Logstash, Kibana version:** 8.13.1

**Comment by a3ilson** [comment]
@mmartinello the haproxy was contributed/built by @BeNeDeLuX however, I believe they are now using nginx. I am unable to test this specific log type but believe I may have found the fix/solution.

The pfelk.grok file defines the http.response.status_code as an integer however, the index template did not contain a mapping to this field type. I've added a mapping and updated the [haproxy template](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/templates/pfelk-haproxy). Try reapplying the haproxy index template via the [Templates Installation](https://github.com/pfelk/pfelk/blob/main/install/templates.md#one-templates).

In the past when updating index template when data is already logged, I've experience issues and had to purge the index and data view when/if updating the index template fails to resolve the issue try the following:
1) stop sending haproxy logs or disconnect so that logs are not received
2) navigate to Stack Management>>Kibana and delete the *-pfelk-haproxy* data view
3) navigate to Stack Management>>Index Management>>Data Streams and delete "logs-pfelk-haproxy"

4) Add the data view back via installing the [HAProxy] Dashboard(https://github.com/pfelk/pfelk/blob/main/install/templates.md#two-dashboards)
5) enable logs to be sent (undo step 1)
6) check to see if the error persist

**Comment by mmartinello** [comment]
@a3ilson I made what you told be but unfortunately this did not solved the problem:

<img width="633" alt="Screenshot 2024-06-20 at 16 45 41" src="https://github.com/pfelk/pfelk/assets/3822398/8045b595-2c8b-4eeb-a714-0f4d6e4ef5d6">

I checked the new template and verified that `status_code` is now mapped as integer in the template:

<img width="617" alt="Screenshot 2024-06-20 at 16 45 32" src="https://github.com/pfelk/pfelk/assets/3822398/4421c94a-a93a-452f-990b-8cc2dca19452">

but unfortunately it's still saved as keyword:

<img width="621" alt="Screenshot 2024-06-20 at 16 47 27" src="https://github.com/pfelk/pfelk/assets/3822398/e55f202d-291b-4783-8472-49e0e38631e0">

I have multiple instances of pfSense, I can make some tests and debugs.
Please tell me if they are needed, I can collaborate on this.

Thank you!

**Comment by a3ilson** [comment]
That's odd... try setting up a new instance of pfelk and see if the values are still stored as "keywords" vs "int"

Alternatively, recreating the visualization would remedy the issue too.

**Comment by mmartinello** [comment]
I completely deleted the instance and recreate it from scratch (I also removed Docker volumes).
I reinstalled all files using the new version but I got the same results.

I know it's odd but there should be a reason.

If you want I am still available for do some debugging.

**Comment by mmartinello** [comment]
I'm debugging this.

For example, the following log entry:

```
Jun 26 16:30:07 fw1.dev.my.domain.com haproxy[88460]: 192.168.123.101:43540 [26/Jun/2024:16:30:07.403] Frontends.DEV-merged~ APM.DEV_ipvANY/elk.dev.my.domain.com 0/0/0/1/1 202 117 - - ---- 24/20/0/0/0 0/0 "POST /intake/v2/events HTTP/1.1"
```

seems to correctly match the grok pattern `HAPROXY`:

```
HAPROXY %{IP:[client][ip]}:%{INT:[client][port]} \[%{HAPROXYDATE:[haproxy][timestamp]}\] %{NOTSPACE:[haproxy][frontend_name]} %{NOTSPACE:[haproxy][backend_name]}/%{NOTSPACE:[haproxy][server_name]} %{INT:[haproxy][time_request]}/%{INT:[haproxy][time_queue]}/%{INT:[haproxy][time_backend_connect]}/%{INT:[haproxy][time_backend_response]}/%{NOTSPACE:[host][uptime]} %{INT:[http][response][status_code]} %{NOTSPACE:[haproxy][bytes_read]} %{DATA:[haproxy][http][request][captured_cookie]} %{DATA:[haproxy][http][response][captured_cookie]} %{NOTSPACE:[haproxy][termination_state]} %{INT:[haproxy][connections][active]}/%{INT:[haproxy][connections][frontend]}/%{INT:[haproxy][connections][backend]}/%{INT:[haproxy][connections][server]}/%{NOTSPACE:[haproxy][connections][retries]} %{INT:[haproxy][server_queue]}/%{INT:[haproxy][backend_queue]} (\{%{HAPROXYCAPTUREDREQUESTHEADERS}\})?( )?(\{%{HAPROXYCAPTUREDRESPONSEHEADERS}\})?( )?"(<BADREQ>|(%{WORD:[http][request][method]} (%{URIPROTO:[haproxy][mode]}://)?(?:%{USER:[user][name]}(?::[^@]*)?@)?(?:%{URIHOST:[http][request][referrer]})?(?:%{URIPATHPARAM:[http][mode]})?( HTTP/%{NUMBER:[http][version]})?))?"?
```

Many fields are indexed as `keyword` instead as `int`:

- `%{INT:[client][port]}`
- `%{INT:[haproxy][time_request]}`
- `%{INT:[haproxy][time_backend_response]}`
- `%{INT:[http][response][status_code]}`
- `%{INT:[haproxy][client][port]}`
- `%{INT:[haproxy][time_request]}`
- `%{INT:[haproxy][time_backend_response]}`

<img width="623" alt="Screenshot 2024-06-26 at 18 52 22" src="https://github.com/pfelk/pfelk/assets/3822398/fd79768d-8fcf-4c40-bde1-9dad6b3ee372">

<img width="633" alt="Screenshot 2024-06-26 at 18 52 29" src="https://github.com/pfelk/pfelk/assets/3822398/3fbbff5f-b17c-4799-9dfd-d41012461971">

<img width="628" alt="Screenshot 2024-06-26 at 18 52 36" src="https://github.com/pfelk/pfelk/assets/3822398/4713f4f8-3330-4fa8-93ed-5b93325e95f1">

<img width="625" alt="Screenshot 2024-06-26 at 18 52 44" src="https://github.com/pfelk/pfelk/assets/3822398/cf0f4a45-6983-451e-a17a-48c0e07e8d71">

<img width="627" alt="Screenshot 2024-06-26 at 18 52 52" src="https://github.com/pfelk/pfelk/assets/3822398/364369ad-45d0-4d75-a764-915e815ff1d4">

<img width="628" alt="Screenshot 2024-06-26 at 18 52 58" src="https://github.com/pfelk/pfelk/assets/3822398/e01eb721-9580-4432-aa3a-15747982ed2b">

<img width="628" alt="Screenshot 2024-06-26 at 18 56 25" src="https://github.com/pfelk/pfelk/assets/3822398/9fb444a4-fce9-4f1c-b61f-02a4c0a274e7">

Other fields are correctly indexed as `int`:

- `%{INT:[haproxy][time_queue]}`
- `%{INT:[haproxy][time_backend_connect]}`
- `%{INT:[haproxy][connections][active]}`
- `%{INT:[haproxy][connections][frontend]}`
- `%{INT:[haproxy][connections][backend]}`
- `%{INT:[haproxy][connections][server]}`
- `%{INT:[haproxy][server_queue]}`
- `%{INT:[haproxy][backend_queue]}`
- `%{INT:[haproxy][time_queue]}`
- `%{INT:[haproxy][time_backend_connect]}`

<img width="628" alt="Screenshot 2024-06-26 at 18 56 25" src="https://github.com/pfelk/pfelk/assets/3822398/0cb3e2ef-c4b3-4e79-a539-06d6e8e588c4">
<img width="625" alt="Screenshot 2024-06-26 at 18 56 16" src="https://github.com/pfelk/pfelk/assets/3822398/86b54d77-0566-4fad-b77a-af02978f0b6a">
<img width="622" alt="Screenshot 2024-06-26 at 18 56 10" src="https://github.com/pfelk/pfelk/assets/3822398/50397dfb-6400-444a-9e46-3cc33843ce26">
<img width="624" alt="Screenshot 2024-06-26 at 18 56 05" src="https://github.com/pfelk/pfelk/assets/3822398/6eea4880-2635-45db-a4df-ca841634fc0b">
<img width="630" alt="Screenshot 2024-06-26 at 18 55 59" src="https://github.com/pfelk/pfelk/assets/3822398/c008d6d5-927f-4962-ac4e-f9466e637c19">
<img width="626" alt="Screenshot 2024-06-26 at 18 55 53" src="https://github.com/pfelk/pfelk/assets/3822398/15876f27-ebe6-47d5-b104-307ea1167190">
<img width="632" alt="Screenshot 2024-06-26 at 18 55 46" src="https://github.com/pfelk/pfelk/assets/3822398/5ce4274d-7bf1-4b3b-8b0b-8fb981699f04">
<img width="623" alt="Screenshot 2024-06-26 at 18 55 15" src="https://github.com/pfelk/pfelk/assets/3822398/36314a70-a936-4e97-89c4-73872da1d94c">
<img width="627" alt="Screenshot 2024-06-26 at 18 55 07" src="https://github.com/pfelk/pfelk/assets/3822398/3b046694-b711-4d46-9adf-8755c68da437">
<img width="630" alt="Screenshot 2024-06-26 at 18 55 01" src="https://github.com/pfelk/pfelk/assets/3822398/8c927822-840e-4554-b807-963ab6682fe1">
<img width="634" alt="Screenshot 2024-06-26 at 18 54 56" src="https://github.com/pfelk/pfelk/assets/3822398/afdcdb22-ad2f-4945-afd2-ca4b8958c792">

I'm trying to find out what's happening, if you have any idea please let me know.

**Comment by mmartinello** [comment]
I tried to change the field name in the grok pattern renaming `%{INT:[http][response][status_code]}` to `%{INT:[http][response][status_code_new]}` as follow:

```
HAPROXY %{IP:[client][ip]}:%{INT:[client][port]} \[%{HAPROXYDATE:[haproxy][timestamp]}\] %{NOTSPACE:[haproxy][frontend_name]} %{NOTSPACE:[haproxy][backend_name]}/%{NOTSPACE:[haproxy][server_name]} %{INT:[haproxy][time_request]}/%{INT:[haproxy][time_queue]}/%{INT:[haproxy][time_backend_connect]}/%{INT:[haproxy][time_backend_response]}/%{NOTSPACE:[host][uptime]} %{INT:[http][response][status_code_new]} %{NOTSPACE:[haproxy][bytes_read]} %{DATA:[haproxy][http][request][captured_cookie]} %{DATA:[haproxy][http][response][captured_cookie]} %{NOTSPACE:[haproxy][termination_state]} %{INT:[haproxy][connections][active]}/%{INT:[haproxy][connections][frontend]}/%{INT:[haproxy][connections][backend]}/%{INT:[haproxy][connections][server]}/%{NOTSPACE:[haproxy][connections][retries]} %{INT:[haproxy][server_queue]}/%{INT:[haproxy][backend_queue]} (\{%{HAPROXYCAPTUREDREQUESTHEADERS}\})?( )?(\{%{HAPROXYCAPTUREDRESPONSEHEADERS}\})?( )?"(<BADREQ>|(%{WORD:[http][request][method]} (%{URIPROTO:[haproxy][mode]}://)?(?:%{USER:[user][name]}(?::[^@]*)?@)?(?:%{URIHOST:[http][request][referrer]})?(?:%{URIPATHPARAM:[http][mode]})?( HTTP/%{NUMBER:[http][version]})?))?"?
```

Anyway I see that the field still have the same name in Elasticsearch:

<img width="629" alt="Screenshot 2024-06-26 at 20 09 32" src="https://github.com/pfelk/pfelk/assets/3822398/5aac9e5d-4690-42da-89f9-83716fafb543">

For this reason, I think that that logs are not matching the `HAPROXY` grok pattern.

**Comment by mmartinello** [comment]
Ok, now the new field name is matched:

<img width="628" alt="Screenshot 2024-06-26 at 20 34 07" src="https://github.com/pfelk/pfelk/assets/3822398/0e11addd-ef37-46bc-a53f-e808f2581ded">

So, I'm sure that the grok pattern matches.

Let me continue debugging.

**Comment by mmartinello** [comment]
I tried to delete the data stream and index template, then I edited the grok pattern adding the `:int` modifier to the field:

```
%{INT:[http][response][status_code]:int}
```

I re-added the index template, anyway the field is still saved as keyword:

<img width="631" alt="Screenshot 2024-06-26 at 20 45 56" src="https://github.com/pfelk/pfelk/assets/3822398/d35967dc-32bd-4e8d-a5ec-e78feb0d5500">

I really cannot understand what's not working here!

**Comment by a3ilson** [comment]
@mmartinello the [index_tempalte_pfelk-haproxy](https://raw.githubusercontent.com/pfelk/pfelk/main/etc/pfelk/templates/index_template_pfelk-haproxy) was updated to define several fields that did not have corresponding mappings (i.e., undefined).

This should resolve the issue but there might be additional steps on your end for it to take effect.

1. When updating template patterns where data is already stored, Elastic will likely persist with the original data type.
  - You may need to purge the logs-pfelk-haproxy data stream
2. This may break the `Stack Management>>Data Views>> *-pfelk-haproxy*` view
  - You may need to delete and recreate this view....if that's the case, please submit a PR to update the haproxy dashboard

**Comment by mmartinello** [comment]
Yes, I removed the data stream after modifying the pattern.

Tomorrow I will do another try.

I saw you updated the index template and I used the latest version.
Just to be sure: did you test it? Do you have that field indexed as integer instead keyword?

**Comment by mmartinello** [comment]
Ok, I made it:

![Screenshot 2024-06-27 at 11 07 27](https://github.com/pfelk/pfelk/assets/3822398/cded9db5-a16b-44d0-9349-71c5ac396259)

We need to tell the grok pattern to  convert the field to int as follow: `%{INT:[http][response][status_code]:int}`.

Now the question is: should it be made on all other `INT`fields?

For example, `port` also is recognised as string:

![Screenshot 2024-06-27 at 11 09 52](https://github.com/pfelk/pfelk/assets/3822398/fe517b5a-d4cd-4f24-83cd-d407dfdaba0d)

And `log.syslog.procid` also:

![Screenshot 2024-06-27 at 11 10 44](https://github.com/pfelk/pfelk/assets/3822398/c791b752-6f1c-47cf-a434-b32fe64aa308)

If you confirm me that these fields should also be integer, I will send you a PR.

I'm also trying to fix the following visualization issue:

![Screenshot 2024-06-27 at 11 12 08](https://github.com/pfelk/pfelk/assets/3822398/a4f26d50-93ca-40e6-897a-a2312b0acd52)

Thank you!

**Comment by mmartinello** [comment]
Ok I think I fixed the issues and made a PR, please let me know if it's ok for you :-)

**Comment by a3ilson** [comment]
@mmartinello thank you for contributing...greatly appreciated!
