### ISSUE TITLE
Unmapped fields in template

### ISSUE THREAD

**Issue by jakes670** [pfelk/pfelk#544]
Elastic Search index does not contain following fields in template 

pf.app.user 
pf.remote.ip
pf.app.action
pf.app.page 

1. Login to PFsense as admin user
2. PFsense send record to PFELK that someone logged in
3. PFELK does not index the 4 values 
4. Can not use the values in Kibana

**Screenshots**

![image](https://github.com/pfelk/pfelk/assets/31097840/3d051b82-ef61-4f1e-9453-0507f1586d3f)

Firewall System 
 - pfSense 2.7.2

PFELK
 - OS  Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-113-generic x86_64)

Installation method: script
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components 
 - elasticsearch  8.14.1
 -  kibana         8.14.1  
 - logstash       1:8.14.1-1 
 

In previous Kibana 
I used to refresh the index patterns by doing the following.
Go inside Kibana (Management > Index patterns), select the index pattern, and press the "Refresh" button at the top right of the window in order to pick up the mapping changes.
However, now that option is missing  in the latest Kibana.

See this URL 
https://stackoverflow.com/questions/69026356/kibana-index-pattern-refresh-option-is-no-longer-there

**Comment by a3ilson** [comment]
Thanks @jakes670! The pfelk-mappings component template was updated. Please update the pfelk-mappings component template and confirm if that resolved the mapping issue.
- pf.remote.ip (IP)
- pf.app.user (Keyword)
- - pf.app.action (Keyword)
- pf.app.page (Text)

- <img width="608" alt="Screenshot 2024-07-09 at 18 52 04" src="https://github.com/pfelk/pfelk/assets/16884679/9529f6e9-7b98-44f4-b16e-bc68b2a2d27c">
