### ISSUE TITLE
Is Ubuntu 24.x not supported for a conflict, or just outdated installer script not recognizing NOBLE?

### ISSUE THREAD

**Issue by gleep52** [pfelk/pfelk#553]
**Is your feature request related to a problem? Please describe.**
When trying to run the installer script it immediately quits and says NOBLE is not supported.  I have a fresh Ubuntu 24.04 server set up and realize it's not on the supported list - but wasn't sure if the manual install would still work, or if there is specifically a reason 24.x is left off the compatibility list?

**Describe the solution you'd like**
It would be great to have the installer script support Ubuntu 24.x.

**Describe alternatives you've considered**
Ready to install 22.04 if required.

**Additional context**
Thank you for your awesome work on this magic product!

**Comment by a3ilson** [comment]
Thanks @gleep52!

Scripted updated with added support for Ubuntu 24.04 (Noble Numbat) and updated Elastic from 8.15.0 to 8.15.2.
- [x] I still need to test and validate but the script is located [here](https://raw.githubusercontent.com/a3ilson/pfelk/refs/heads/main/etc/pfelk/scripts/pfelk-installer.sh) 

I'll test with the next week or two...but if you or someone else tests/validates prior to, I'll submit the pull request.

**Comment by SaintPeeWee** [comment]
> Thanks @gleep52!
> 
> Scripted updated with added support for Ubuntu 24.04 (Noble Numbat) and updated Elastic from 8.15.0 to 8.15.2.
> 
> * [ ]  I still need to test and validate but the script is located [here](https://raw.githubusercontent.com/a3ilson/pfelk/refs/heads/main/etc/pfelk/scripts/pfelk-installer.sh)
> 
> I'll test with the next week or two...but if you or someone else tests/validates prior to, I'll submit the pull request.

I was having the same issue with 24.04 server and the updated script executed without an issue. Thanks!

**Comment by a3ilson** [comment]
scripted updated / Ubuntu 24.X supported
