### ISSUE TITLE
Private IP Enhancement >> private-hostnames not showing at the firewall dashboard

### ISSUE THREAD

**Issue by kozistan** [pfelk/pfelk#557]
**Describe the bug**
I have an issue with private-hostnames.csv. In the 45-enhanced_private.conf file, the filter is set as "if "dhcp" in [tags] or "unbound" in [tags] or "squid" in [tags]". I’m using KEA for DHCP, a Samba AD server for DNS, and I’m not using Squid, so any incoming data doesn’t have any of these tags. Is there a way to ensure that hostnames still appear on the dashboard despite this?

**Firewall System (please complete the following information):**
 - OPNsense
 - 24.7.7
 
**Operating System (please complete the following information):**
Linux 6.8.12-3-pve x86_64
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
 
 **Installation method manual
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK components:
elasticsearch 8.15.3 amd64 
kibana 8.15.3 amd64 
logstash 1:8.15.3-1 amd64

**Comment by a3ilson** [comment]
@kozistan - added `kea` support. Please update the 45-enhanced_private.pfelk file and confirm.

**Comment by kozistan** [comment]
Thanks a3lison, i've updated the file but still no hostnames there. 

here is and example from my private-hostnames.csv file:
`> # cat /etc/pfelk/databases/private-hostnames.csv
"IP","Hostname"
"10.10.150.5","p-mng-capsman"
"10.10.150.211","ap11"
"10.10.150.212","ap12"
"10.10.150.213","ap13"
"10.10.150.214","ap14"`

and here screeshot from elk discover:

<img width="1676" alt="Screenshot 2024-11-07 at 13 05 38" src="https://github.com/user-attachments/assets/35dd43a6-0a93-47e7-9622-ced5f94c4ef4">

Am I missing something?

**Comment by a3ilson** [comment]
After updating the 45-enhanced_private.pfelk file you’ll need to restart logstash ( e.g., systemctl restart logstash.service ).

Please confirm

**Comment by kozistan** [comment]
This has been done

**Comment by a3ilson** [comment]
Thanks!
Apologizes as the `45-enhanced_private.pfelk` hasn't been properly maintained. 

What would be more useful:
1) Update to parse the `host.ip` field <-- this is typically the IP address of the firewall/router and OPNsense stores this within the `log.syslog.hostname` field
2) Update to parse the `source.ip` or `destination.ip` when they contain a private IP addresses and adding...
- To comply with ECS, I'm thinking of `destination/source.subdomain`

**Comment by a3ilson** [comment]
@kozistan - `45-enhanced_private.pfelk` file was updated and tested. Please update and give it another try.

**Comment by kozistan** [comment]
Thanks I really apprciate your help. Just updated and tested, no hostnames.
Also checked the tag field and no mentioned any of those in the filter.

<img width="566" alt="Screenshot 2024-11-07 at 21 55 06" src="https://github.com/user-attachments/assets/778e04bd-b2bf-4c7f-8c79-c8de1be2e0b8">

**Comment by a3ilson** [comment]
@kozistan - That looks correct!
1) The `45-enhanced_private.pfelk` was initially intended to enrich logs from dhcp, unbound, squid and now kea. The discover view in your prior response is that of the firewall logs.
- Just realized one final issue... dhcp6, dhcp, kea and unbound contain variations to the `client.ip` (nesting) field
-- Will rewrite and test shortly

2) The [46-private-firewall.pfelk](https://raw.githubusercontent.com/pfelk/pfelk/refs/heads/main/etc/pfelk/conf.d/46-private-firewall.pfelk) file was just created...I've been testing it for a few hours and appears to enrich `firewall` logs just fine where the source or destination IP is private.
- <img width="528" alt="Screenshot 2024-11-07 at 17 17 29" src="https://github.com/user-attachments/assets/b7af4424-3371-44ab-a824-79ae210dd31d">

**Comment by a3ilson** [comment]
@kozistan 

1) Download and update with the following:

- [45-enhanced_private.pfelk](https://raw.githubusercontent.com/pfelk/pfelk/refs/heads/main/etc/pfelk/conf.d/45-enhanced_private.pfelk)
-- This will enrich dhcpv6, kea-dhcp, unbound and squid logs where the ip is private 
- [46-private-firewall.pfelk](https://raw.githubusercontent.com/pfelk/pfelk/refs/heads/main/etc/pfelk/conf.d/46-private-firewall.pfelk)
-- This will enrich firewall logs where the ip is private

**Comment by kozistan** [comment]
> @kozistan
> 
> 1. Download and update with the following:
> 
> * [45-enhanced_private.pfelk](https://raw.githubusercontent.com/pfelk/pfelk/refs/heads/main/etc/pfelk/conf.d/45-enhanced_private.pfelk)
>   -- This will enrich dhcpv6, kea-dhcp, unbound and squid logs where the ip is private
> * [46-private-firewall.pfelk](https://raw.githubusercontent.com/pfelk/pfelk/refs/heads/main/etc/pfelk/conf.d/46-private-firewall.pfelk)
>   -- This will enrich firewall logs where the ip is private

Updated both configs, and tested for some hrs. No luck with hostnames so far.
My firewall and kea logs are just fine, there is no issue at all. Also using rule-names.csv, also without an issue.

The only thing is the hostnames, I mean i can always look for it as my clients has static IP's based on MAC,  it's just cosmetics and as it was working before wanted to have it there.

**Comment by a3ilson** [comment]
What does your `private-hostnames.csv` look like?
<img width="420" alt="Screenshot 2024-11-08 at 05 16 40" src="https://github.com/user-attachments/assets/136d8a46-6d67-4100-91ca-e2f791b7478d">


I'm running both updated 45 & 46 files... with the above `private-hostnames.csv` which appears to be working
<img width="1448" alt="Screenshot 2024-11-08 at 05 15 34" src="https://github.com/user-attachments/assets/4f454012-dd31-4787-b50f-e9d7104f6ce4">

**Comment by kozistan** [comment]
Yes, now it started to work! Thank a lot a3ilson, really appreciate!
