### ISSUE TITLE
Did some debugging after code refactor

### ISSUE THREAD

**Issue by revere521** [pfelk/pfelk#57]
**Describe the bug**
minor code bugs - please feel free to review anything helpful

in 11-firewall.conf the "network.direction" field is now missing and replaced by simply "direction" - i think this is part of the grok pattern changes?:

```
 mutate {
      add_field => { "[event][dataset]" => "firewall"}
      update => { "[direction]" => "%{[direction]}bound" }
      update => { "[network][type]" => "ipv%{[network][type]}" }
    }
  }
}
```

in 13-snort.conf - the asn data part is missing and change syslog_program to pf_program in the last mutate statement
```
 }
        geoip {
         default_database_type => 'ASN'
         database => "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
         #cache_size => 5000
         source => "[ids_source][ip]"
         target => "[ids_source][as]"
        }
        mutate {
         rename => { "[ids_source][as][asn]" => "[ids_source][as][number]"}
         rename => { "[ids_source][as][as_org]" => "[ids_source][as][organization][name]"}
        }
      }
      if [pf_program] =~ /^snort/ {
        mutate {
          add_tag => [ "ET-Sig" ]
          add_field => [ "Signature_Info", "http://doc.emergingthreats.net/bin/view/Main/%{[ids_sig_id]}" ]
        }
      }
    }
  }
}

```

in 15-others.config - I added unbound as its common for pfBlockerNG but theres not really any patterns yet for DNS, and i chnaged apinger to dpinger - for my PFsense 2.4.4-release p3 its now dpinger. 

```
 }
    if [pf_program] =~ /^unbound/ {
      mutate {
        add_tag => [ "unbound" ]
      }
    }

}
    if [pf_program] =~ /^dpinger/ {
      mutate {
        add_tag => [ "dpinger" ]
      }
    }


```

for the new patterns i was getting _grokparserfailures for just some IGMP entries
The reason appears to be that the "rason" field value sometimes has a hyphen - i commonly see the alert value: "ip-option" which won't work with the standard WORD pattern - this is what i have found as a solution: (?<reason>\b[\w\-]+\b)
```
PF_LOG_DATA %{INT:rule_number},%{INT:sub_rule}?,,%{INT:tracker},%{DATA:interface},(?<reason>\b[\w\-]+\b),%{WORD:action},%{WORD:direction},
```

That was a huge refactor - I think its easier to read and digest whats happening this way - thanks!

**Comment by revere521** [comment]
[UpfdatedKibanaExport(dark+geo).zip](https://github.com/a3ilson/pfelk/files/3951848/UpfdatedKibanaExport.dark%2Bgeo.zip)

Here is the dashboard - i just updated terms in some of the visualizations to your new code

**Comment by a3ilson** [comment]
@revere521 - thanks!  all changes were incorporated.
