### ISSUE TITLE
Ansible playbook

### ISSUE THREAD

**Issue by fktkrt** [pfelk/pfelk#58]
**Is your feature request related to a problem? Please describe.**
I saw the card regarding scrip installer, and I was wondering if we should make an Ansible playbook to accelerate the deploy process. This could co-exist with a script solution.

**Describe the solution you'd like**
 - Prerequisite role to install java, Maxmind
 - Separate roles for Elasticsearch, Logstash, Kibana
 - Jinja templates for config files

**Describe alternatives you've considered**
Alternatives would be a simple script installer, but in my opinion they can co-exist.

**Additional context**
Proposed file structure for the ELK services:

```
common/roles/elasticsearch/
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── tasks
│   └── main.yml
└── templates
    └── elasticsearch.yml.j2
```

```
common/roles/logstash/
├── defaults
│   └── main.yml
├── files
│   ├── patterns
│       └── pf-12.2019.grok
├── handlers
│   └── main.yml
├── tasks
│   └── main.yml
└── templates
   ├── 01-input.conf.j2
   ├── 11-firewall.conf.j2
   ├── 12-suricata.conf.j2
   ├── 13-snort.conf.j2
   ├── 15-others.conf.j2
   └── 50-output.conf.j2
```

```
common/roles/kibana/
├── defaults
│   └── main.yml
├── files
│   └── dashboards
├── handlers
│   └── main.yml
├── tasks
│   └── main.yml
└── templates
    └── kibana.yml.j2
```

**Comment by fktkrt** [comment]
Just gave some more thought on the design and came across the following ideas/questions:
 - An install.yml would hold this together as a playbook to deploy the solution.
 - In the first run, I think this does not need Jinja2 templates, we should stick to generic conf files.
 - How would this affect the install instructions in README?

**Comment by a3ilson** [comment]
I agree on keeping it simple sticking to just the generic conf files.  As for the README, we can delineate install procedures leaving the instructions and providing a simple installer - thoughts?

**Comment by fktkrt** [comment]
So, I have made some progress.
I have a new branch with this feature at https://github.com/fktkrt/pfelk/tree/ansible-elk/ansible-elk

It is almost complete. Currently the maxmind role is missing, and the paths in the roles need to be checked. Feel free to play with it.

To deploy you should take a look at the official Ansible documentation beforehand: https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html

If you have everything installed and you have configured the `hosts` file with your target address, you can deploy the solution with a simple `ansible-playbook -i hosts install/install.yml`

**Comment by revere521** [comment]
i'll setup a VM and try it as soon as you think its complete enough

**Comment by fktkrt** [comment]
Currently I am not in front of my setup, but yesterday I have fixed some typos. Have not got the chance to deploy it in a container/vm just yet, but if you configure the maxmind manually for now, you should get it to work.

As I said, it is ready for testing if you want to play with it. In the next couple of days I will probably have time to fix/complete anything missing.

**Comment by revere521** [comment]
I just built an ubuntu 18.04.3 server in virtualbox, but i cant figure out how to get the files. i'm probably being dense, but cloning your fork does not pull down the folder, and using wget doesn't seem to work either.

**Comment by fktkrt** [comment]
You can download the repo from here: https://github.com/fktkrt/pfelk/archive/ansible-elk.zip

Extract it and find the referenced `ansible-elk` folder with the files in it.

**Comment by revere521** [comment]
thanks, for some reason when i tried to just clone it earlier the ansible-elk folder was exluded.  

Now, I am running through the ansible docs and etc. to try to get it to work.  

Just out of curiosity whats the normal use case for ansible? 

is it automated installs on the localhost from the localhost.....or is is deployments from the localhost -> to one or more external hosts?

Most of the issues I am trying to get through don't seem to be related to your install script, but rather getting ansible to understand i'm running the script from the machine i want to install ELK on; and then getting it the correct permissions information, etc. for the SSH part to work.

**Comment by fktkrt** [comment]
Alright, I should have given more explanation for the Ansible part, not just throw a link, sorry about that.
So, a normal use case for Ansible should be the following:
 - you have a dedicated ansible machine to deploy configurations
 - you have target machines eg. frontends, backends, mgmt, logger, etc.
 - you use the ansible machine to deploy playbooks to your specific servers/group of servers, Ansible is an agentless configuration management tool, it only uses SSH to access the target machines (huge advantage to other CM tools!)
 - you can have fancy wrappers to make this more comfortable, like Ansible Tower, Rundeck etc. but you should be fine with the aforementioned setup at bare minimum

Meanwhile, you can also use your source machine to deploy playbooks to itself, which can be useful for testing, or simple setups. 
To do this, 
 - you should have the appropriate packages in place, those are mentioned at the linked site.
 - install and setup `openssh`
 - if you choose not to use ssh keys, install `sshpass` for auth

I have just made a few adjustments, and have tested on a vm with the dry-run option, and have 0 errors, so you should fetch the newest files from my branch.

After that, you configure your IP address in the `hosts` file. If your are deploying locally, you should just type `localhost`, install the aforementioned packages, set a remote user to login via ssh at the `remote_user` line in `install.yml` then deploy the playbook with:
`ansible-playbook -i hosts --ask-pass --ask-become install/install.yml`

To have a verbose output (useful to debug errors if needed) you should include `-vvvv` and if you want to just test it without making any real changes on your system include `--check` to run it with dry-mode.

Deploying this way, you will have to enter the password for the remote user, then the root password to have sudo privileges.

Yes I know, now it seems much more complicated than setting it up manually, but in the long run, having a fully automated solution to deploy a setup like this with 1 line of code will benefit hugely. :)

**Comment by revere521** [comment]
Excellent explanation, i only used it once before to install a package - and it did seem like the use was similar to SCCM (which i have a cursory familiarity).  I will try again from scratch using your new files and report back.

**Comment by revere521** [comment]
the only thing i had to do in addition to what you explained is run the command

`export ANSIBLE_HOST_KEY_CHECKING=False`

and everything else seems to have installed correctly and is ready to be configured

**Comment by revere521** [comment]
the oonly issue i had with the config was with the host file (/etc/kibana/kibana.yml)

I had to comment out the line " elasticsearch.hosts: "localhost:9200" " - otherwise Kibana wouldn't start, all else was good though.

**Comment by fktkrt** [comment]
Alright, thank you for testing it. I’ll make some adjustments, and finalize the branch. If I am right, @a3ilson made some progress with the script solution as well. @a3ilson, should we include all three methods in the README then? Should I just make a pull request from my branch or upload the folder when it is finalized?

**Comment by revere521** [comment]
I do see that after some time i am seeing java errors in the VM, but i don't know if its because it doesn't have enough resources allocated.  I will troubleshoot some more and let you know. 

Edit - it does appear to be a resources issue in the VM with resources, and nothing more - I don't think i'm going to worry about finding the root of the issue because it seems specific to my setup here.  

Nice work getting this setup!

**Comment by fktkrt** [comment]
Just finalized it with adding Maxmind role, seems to work fine.

Yes, those java errors could be VM related, since I am not getting any.
I think the work here is quite finished. We should configure every deploy method to match each other though.

If all is right, I will make a proposition to the README.

**Comment by a3ilson** [comment]
> 
> 
> Alright, thank you for testing it. I’ll make some adjustments, and finalize the branch. If I am right, @a3ilson made some progress with the script solution as well. @a3ilson, should we include all three methods in the README then? Should I just make a pull request from my branch or upload the folder when it is finalized?

Thought on creating a wiki page?  I created one for the 'custom' install and figured we could capture installation and configuration within the wiki's while providing an overview within the README with links pointing to the installation and configuration methods?

**Comment by a3ilson** [comment]
@fktkrt I changed course from creating wiki pages to creating optional installation guides.  Reference the original README which redirects (install folder), based on the method.

**Comment by fktkrt** [comment]
OK, that is fine for me.
I will merge the branch and edit the `ansible.md` correspondingly.

**Comment by fktkrt** [comment]
A first version of Ansible instructions is in place at `ansible.md`
Closing this now, thank you for your co-operations.
