### ISSUE TITLE
Unable start logstash

### ISSUE THREAD

**Issue by iovcho** [pfelk/pfelk#60]
Hello. I have problems with logstash  running.
Software: CentOS 7 , logstash-7.5.0-1

I make all steps from documentation. The error I have is:

logstash: [2019-12-12T17:09:39,548][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.5.0"}
logstash: [2019-12-12T17:09:44,075][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [^\\]\\[,], \"]\" at line 322, column 23 (byte 10131) after filter {\n  if \"pf\" in [tags] {\n    if [pf_program] =~ /^dhcpd$/ {\n      mutate {\n        add_tag => [ \"dhcpd\" ]\n      }\n      grok {\n        patterns_dir => [\"/etc/logstash/conf.d/patterns\"]\n        match => [ \"pf_message\", \"%{DHCPD}\"]\n      }\n    }\n    if [pf_program] =~ /^charon$/ {\n      mutate {\n        add_tag => [ \"ipsec\" ]\n      }\n    }\n    if [pf_program] =~ /^barnyard2/ {\n      mutate {\n        add_tag => [ \"barnyard2\" ]\n      }\n    }\n    if [pf_program] =~ /^openvpn/ {\n      mutate {\n        add_tag => [ \"openvpn\" ]\n      }\n      grok {\n        patterns_dir => [\"/etc/logstas /conf.d/patterns\"]\n        match => [ \"pf_message\", \"%{OPENVPN}\"]\n      }\n    }\n    if [pf_program] =~ /^ntpd/ {\n      mutate {\n        add_tag => [ \"ntpd\" ]\n      }\n    }\n    if [pf_program] =~ /^php-fpm/ {\n      mutate {\n        add_tag => [ \"web_portal\" ]\n      }\n      grok {\n        patterns_dir => [\"/etc/logstash/conf.d/patterns\"]\n        match => [ \"pf_message\", \"%{PF_APP}%{PF_APP_DATA}\"]\n      }\n      mutate {\n        lowercase => [ 'pf_ACTION' ]\n      }\n    }\n    if [pf_program =~ /^unbound/ {\n        mutate {\n           add_tag => ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2584:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:156:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:26:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:326:in `block in converge_state'"]}

Somebody can help with this case?

Best wishes.

**Comment by iovcho** [comment]
# 01-inputs.conf
input {
  udp {
     port => 5140
  }
}
filter {
  #Adjust to match the IP address of pfSense or OPNsense
  if [host] =~ /192\.168\.100\.254/ {
    mutate {
      add_tag => ["pf", "Ready"]
    }
  }
}
filter {
  if "pf" in [tags] {
    grok {
      match => { "message" => ["%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}", "%{SYSLOGTIMESTAMP:syslog_timestamp} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}"] }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
    }
  }
}



# 11-firewall.conf
filter {
  if "pf" in [tags] and [pf_program] =~ /^filterlog$/ {
    grok {
      add_tag => [ "firewall" ]
      patterns_dir => ["/etc/logstash/conf.d/patterns"]
      match => ["pf_message", "%{PF_LOG_ENTRY}"]
    }
    # Change interface as desired
      if [interface] =~ /^igb0$/ {
        mutate {
          add_tag => [ "WAN" ]
      }
    }
     # Change interface as desired
      if [interface] =~ /^igb1$/ {
        mutate {
          add_tag => [ "DEV" ]
      }
    }
    # Change interface as desired
      if [interface] =~ /^igb2$/ {
        mutate {
          add_tag => [ "DMZ" ]
      }
    }
    # Change interface as desired
      if [interface] =~ /^igb3$/ {
        mutate {
          add_tag => [ "LAN" ]
      }
    }
    # Change interface as desired
      if [interface] =~ /^lo0$/ {
        mutate {
          add_tag => [ "Link-Local" ]
      }
    }
    if [source][ip] {
      # Check if source.ip address is private.
      cidr {
        address => [ "%{[source][ip]}" ]
        network => [ "0.0.0.0/32", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7", "127.0.0.0/8", "::1/128", "169.254.0.0/16", "fe80::/10", "224.0.0.0/4", "ff00::/8", "255.255.255.255/32", "::" ]
        add_field => { "[src_locality]" => "private" }
      }
      if ![src_locality] {
        geoip {
          add_tag => [ "GeoIP" ]
          source => "[source][ip]"
          database => "/usr/share/GeoIP/GeoLite2-City.mmdb"
          target => "[source][geo]"
        }
        geoip {
         default_database_type => 'ASN'
         database => "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
         #cache_size => 5000
         source => "[source][ip]"
         target => "[source][as]"
       }
       mutate {
         rename => { "[source][as][asn]" => "[source][as][number]"}
         rename => { "[source][as][as_org]" => "[source][as][organization][name]"}
       }
      }
    }
    if [destination][ip] {
      # Check if destination.ip address is private.
      cidr {
        address => [ "%{[destination][ip]}" ]
        network => [ "0.0.0.0/32", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7", "127.0.0.0/8", "::1/128", "169.254.0.0/16", "fe80::/10", "224.0.0.0/4", "ff00::/8", "255.255.255.255/32", "::" ]
        add_field => { "[dest_locality]" => "private" }
      }
      if ![dest_locality] {
        geoip {
          add_tag => [ "GeoIP" ]
          source => "[destination][ip]"
          database => "/usr/share/GeoIP/GeoLite2-City.mmdb"
          target => "[destination][geo]"
        }
        geoip {
         default_database_type => 'ASN'
         database => "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
         #cache_size => 5000
         source => "[destination][ip]"
         target => "[destination][as]"
       }
       mutate {
         rename => { "[destination][as][asn]" => "[destination][as][number]"}
         rename => { "[destination][as][as_org]" => "[destination][as][organization][name]"}
       }
      }
    }
    mutate {
      add_field => { "[event][dataset]" => "firewall"}
      update => { "[direction]" => "%{[direction]}bound" }
      update => { "[network][type]" => "ipv%{[network][type]}" }
    }
  }
}

# 12-suricata.conf
filter {
  if "pf" in [tags] and [pf_program] =~ /^suricata$/ {
    mutate {
      add_tag => [ "Suricata" ]
    }
    if [pf_message] =~ /^{.*}$/ {
      json {
        source => "pf_message"
        target => "[suricata][eve]"
      }
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => [ "pf_message", "%{SURICATA}"]
      }
    }
    if [suricata][eve][src_ip] and ![source][ip] {
      mutate {
        add_field => { "[source][ip]" => "%{[suricata][eve][src_ip]}"}
      }
    }
    if [suricata][eve][dest_ip] and ![destination][ip] {
      mutate {
        add_field => { "[destination][ip]" => "%{[suricata][eve][dest_ip]}"}
      }
    }
    if [suricata][eve][src_port] and ![source][port] {
      mutate {
        add_field => { "[source][port]" => "%{[suricata][eve][src_port]}"}
      }
    }
    if [suricata][eve][dest_port] and ![destination][port] {
      mutate {
        add_field => { "[destination][port]" => "%{[suricata][eve][dest_port]}"}
      }
    }
    if [source][ip] {
     # Check if source.ip address is private.
      cidr {
        address => [ "%{[source][ip]}" ]
        network => [ "0.0.0.0/32", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7", "127.0.0.0/8", "::1/128", "169.254.0.0/16", "fe80::/10", "224.0.0.0/4", "ff00::/8", "255.255.255.255/32", "::" ]
        add_field => { "[src_locality]" => "private" }
      }
      if ![src_locality] {
        geoip {
          add_tag => [ "GeoIP" ]
          source => "[source][ip]"
          database => "/usr/share/GeoIP/GeoLite2-City.mmdb"
          target => "[source][geo]"
        }
        geoip {
          default_database_type => 'ASN'
          database => "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
          #cache_size => 5000
          source => "[source][ip]"
          target => "[source][as]"
        }
        mutate {
          rename => { "[source][as][asn]" => "[source][as][number]"}
          rename => { "[source][as][as_org]" => "[source][as][organization][name]"}
        }
      }
    }
    if [destination][ip] {
      # Check if destination.ip address is private.
      cidr {
        address => [ "%{[destination][ip]}" ]
        network => [ "0.0.0.0/32", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7", "127.0.0.0/8", "::1/128", "169.254.0.0/16", "fe80::/10", "224.0.0.0/4", "ff00::/8", "255.255.255.255/32", "::" ]
        add_field => { "[dest_locality]" => "private" }
      }
      if ![dest_locality] {
        geoip {
          add_tag => [ "GeoIP" ]
          source => "[destination][ip]"
          database => "/usr/share/GeoIP/GeoLite2-City.mmdb"
          target => "[destination][geo]"
        }
        geoip {
          default_database_type => 'ASN'
          database => "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
          #cache_size => 5000
          source => "[destination][ip]"
          target => "[destination][as]"
        }
        mutate {
            rename => { "[destination][as][asn]" => "[destination][as][number]"}
            rename => { "[destination][as][as_org]" => "[destination][as][organization][name]"}
        }
      }
    }
    mutate {
      add_field => { "[event][module]" => "suricata"}
      add_field => { "[event][dataset]" => "suricata"}
    }
  }
}

# 13-snort.conf
filter {
  if "pf" in [tags] and [pf_program] =~ /^snort/ {
    mutate {
      add_tag => [ "Snort" ]
    }
    grok {
      patterns_dir => ["/etc/logstash/conf.d/patterns"]
      match => [ "pf_message", "%{SNORT}"]
    }
    if ![geoip] and [ids_source][ip] {
    # Check if source IP address is private.
      cidr {
        address => [ "%{[ids_source][ip]}" ]
        network => [ "0.0.0.0/32", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "fc00::/7", "127.0.0.0/8", "::1/128", "169.254.0.0/16", "fe80::/10", "224.0.0.0/4", "ff00::/8", "255.255.255.255/32", "::" ]
        add_field => { "[@metadata][ids_source][locality]" => "private" }
      }
    # Check to see if source.locality exists. If it doesn't the source.ip didn't match a private address space and locality must be public.
      if ![@metadata][ids_source][locality] {
        geoip {
          add_tag => [ "GeoIP" ]
          source => "[ids_source][ip]"
          database => "/usr/share/GeoIP/GeoLite2-City.mmdb"
          target => "[ids_source][geo]"
        }
        geoip {
          default_database_type => 'ASN'
          database => "/usr/share/GeoIP/GeoLite2-ASN.mmdb"
          #cache_size => 5000
          source => "[ids_source][ip]"
          target => "[ids_source][as]"
        }
        mutate {
          rename => { "[ids_source][as][asn]" => "[ids_source][as][number]"}
          rename => { "[ids_source][as][as_org]" => "[ids_source][as][organization][name]"}
        }
      }
      if [pf_program] =~ /^snort/ {
        mutate {
          add_tag => [ "ET-Sig" ]
          add_field => [ "Signature_Info", "http://doc.emergingthreats.net/bin/view/Main/%{[ids_sig_id]}" ]
        }
      }
    }
  }
}

# 15-others.conf
filter {
  if "pf" in [tags] {
    if [pf_program] =~ /^dhcpd$/ {
      mutate {
        add_tag => [ "dhcpd" ]
      }
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => [ "pf_message", "%{DHCPD}"]
      }
    }
    if [pf_program] =~ /^charon$/ {
      mutate {
        add_tag => [ "ipsec" ]
      }
    }
    if [pf_program] =~ /^barnyard2/ {
      mutate {
        add_tag => [ "barnyard2" ]
      }
    }
    if [pf_program] =~ /^openvpn/ {
      mutate {
        add_tag => [ "openvpn" ]
      }
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => [ "pf_message", "%{OPENVPN}"]
      }
    }
    if [pf_program] =~ /^ntpd/ {
      mutate {
        add_tag => [ "ntpd" ]
      }
    }
    if [pf_program] =~ /^php-fpm/ {
      mutate {
        add_tag => [ "web_portal" ]
      }
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => [ "pf_message", "%{PF_APP}%{PF_APP_DATA}"]
      }
      mutate {
        lowercase => [ 'pf_ACTION' ]
      }
    }
    if [pf_program =~ /^unbound/ {
        mutate {
           add_tag => [ "unbound" ]
        }
    }
    if [pf_program] =~ /^dpinger/ {
      mutate {
        add_tag => [ "dpinger" ]
      }
    }
  }
}

# 50-outputs.conf
output {
        elasticsearch {
                hosts => ["http://localhost:9200"]
                index => "pf-%{+YYYY.MM.dd}" }
}

**Comment by revere521** [comment]
there was a missing bracket in 15-others.conf - its fixed now

If you want to edit it rather than re-download, change this line
```
if [pf_program =~ /^unbound/ {
```    

To this:
```
if [pf_program] =~ /^unbound/ {
```

**Comment by fktkrt** [comment]
To debug these kind of errors you should test the config files separately. You can validate them this way:
```
logstash -f /etc/logstash/conf.d/15-others.conf --config.debug --log.level debug --config.test_and_exit
```
The output will give you an educated guess on the problematic line number. Notice that the log message you posted has a different line number, because in the final pipeline the config files are merged.

**Comment by iovcho** [comment]
> there was a missing bracket in 15-others.conf - its fixed now
> 
> If you want to edit it rather than re-download, change this line
> 
> ```
> if [pf_program =~ /^unbound/ {
> ```
> 
> To this:
> 
> ```
> if [pf_program] =~ /^unbound/ {
> ```
Really fast reply, great. Thanks a lot! 


> To debug these kind of errors you should test the config files separately. You can validate them this way:
> 
> ```
> logstash -f /etc/logstash/conf.d/15-others.conf --config.debug --log.level debug --config.test_and_exit
> ```
> 
> The output will give you an educated guess on the problematic line number. Notice that the log message you posted has a different line number, because in the final pipeline the config files are merged.

Thank you very much for this hint. Next time I will use it.
