### ISSUE TITLE
Updating the Suricata dashboards/visualizations

### ISSUE THREAD

**Issue by fktkrt** [pfelk/pfelk#61]
The old suricata json files are not not mapping well with the current indices. They are not in ndjson format either, and the support for json is going away.

Can you provide details about their former working states? Maybe export them to ndjson if you got them working, to accelerate the reworking process. 

An alternative solution I have considered is to dive into their json and put them all together from scratch.  I am planning to do this, just wondering maybe you have a better solution at hand.

**Comment by revere521** [comment]
Have a look at the Snort dashboard - you can probably use it as a launching point to build a Suricata dashboard.   Or you can just build searches, visualizations and a new dashboard to display what you want to see.

**Comment by fktkrt** [comment]
I don't want to fully discard the former ones if they are still relevant and/or if @a3ilson would want to use them in this repository. 

I have a few visualization in my mind eg. signatures, alert levels, destinations/services at risks, types of events, etc, but with this issue I just want to find common ground to contribute to this repo.

**Comment by revere521** [comment]
You'll probably need to update them manually, or recreate them so they work and export them as ndjson.   I would give it a shot, but without the Suricata setup, it doesn't make sense.   

Its actually pretty easy to do in the Kibana GUI, once you dive in

**Comment by a3ilson** [comment]
> The old suricata json files are not not mapping well with the current indices. They are not in ndjson format either, and the support for json is going away.
> 
> Can you provide details about their former working states? Maybe export them to ndjson if you got them working, to accelerate the reworking process.
> 
> An alternative solution I have considered is to dive into their json and put them all together from scratch. I am planning to do this, just wondering maybe you have a better solution at hand.

@fktkrt - the old suricata json files were from an early 2017 iteration running pfSense 2.3, and elastic v5.  Unfortunately, I am not a consumer of Suricata/Snort running on my OPNsense instance and utilize it interdependently utilizing Moloch.  I am happy to help and support expanding on this endeavor as the interest and appetite is certainly there.   Another though might be the SIEM module provided by Elastic...it requires the utilization of beats.

Prior configuration file:
```
filter {
  if [type] == "SuricataIDPS" {
    date {
      match => [ "timestamp", "ISO8601" ]
    }
    ruby {
      code => "if event['event_type'] == 'fileinfo'; event['fileinfo']['type']=event['fileinfo']['magic'].to_s.split(',')[0]; end;"
    }
  }
```

**Comment by a3ilson** [comment]
> I don't want to fully discard the former ones if they are still relevant and/or if @a3ilson would want to use them in this repository.
> 
> I have a few visualization in my mind eg. signatures, alert levels, destinations/services at risks, types of events, etc, but with this issue I just want to find common ground to contribute to this repo.

I have no objection.  I provided the prior Suricata dashboard as a reference.  If you have something newer/improved - feel free to purge the old and build upon a newer working iteration.

**Comment by fktkrt** [comment]
Alright, thanks!

So I have created an Alerts dashboards for Suricata mostly based on Elastic's Filebeat version to have an initial solution to start from. 
It contains the following visualizations: 
 - top alerting hosts, 
 - top alert signatures, 
 - top source/destinations (tags & maps), 
 - alert entries. 

Soon, I will move to the aforementioned functions as well.

You can find it under `Dashboard` as `SuricataAlertsDashboard.ndjson`, if anyone has a Suricata setup, feel free to review it.

Edit:

 - added alert severity over time visualization

**Comment by fktkrt** [comment]
Anyone, just reopen this or file a new issue if you have any problem/suggestion with the current implementation.
