### ISSUE TITLE
Redesign the index template for Maps support

### ISSUE THREAD

**Issue by fktkrt** [pfelk/pfelk#65]
**Is your feature request related to a problem? Please describe.**
Currently, we cannot use Maps in dashboards, because the current index patterns stores the geo fields as `float`. Which is a problem, if one would want to create point-to-point or grid aggregation layers in Maps.

**Describe the solution you'd like**
We should use [geo_point](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/geo-point.html) and/or [geo_shape](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/geo-shape.html) fields in the index pattern to have this ability.

**Comment by fktkrt** [comment]
I was not paying attention, using the GeoIP template could be almost all that is needed to achieve this. Testing a few functions, then I will update the README and any other relevant files. Finally, I will add a few Maps.

Alternatively we could add the `geo_point` fields without the index template, we can focus on that later, if needed.

**Comment by fktkrt** [comment]
Yes, the original template is working.

A Maps panel is now added to the Suricata dashboard with 3 layers:
* DEST location as point/heatmap
* SRC location as point/heatmap
* SRC -> DEST point-to-point lines

It can be added to the to pfSense dashboard as well, but the reason I used it in the Suricata one is it looks better suited for fewer data points, especially the point-to-point visualization.

**Comment by revere521** [comment]
Is this like the network map in the SIEM?  with points and connecting lines?

If we are filtering the GeoIP lookup to exclude the src/dest when its private - does it still work?

**Comment by fktkrt** [comment]
Yes, it is similar, although this way you can set up specific things with more flexibility. To have the full advantages of SIEM you have to use the "official" filebeat-to-suricata method.

**Comment by fktkrt** [comment]
If I have more time, I will try to create a generic Maps visualization for testing purposes.

**Comment by fktkrt** [comment]
This is a generic demo which visualizes the pf-* index in Maps format. It has the following layers:
 - SRC as points (source.geo.location)
 - DEST as heatmap (destination.geo.location)
 - SRC -> DEST as point-to-point (source.geo.location -> destination.geo.location)

with the Road Map (EMS Basemaps) under these.

Be advised: it visualizes everything in pf-* by default, you can modify/filter it to your needs.
[maps_demo_pf.zip](https://github.com/a3ilson/pfelk/files/4010070/maps_demo_pf.zip)

**Comment by revere521** [comment]
Thats super cool!   I already added it to my default dashboard and the snort dashboard to play with!   Since its just pulling from the geohash tables, all i seemed to need to do for snort was set a KQL filter of "tags : snort" to get it to filter just the snort stuff on that dashboard (i saved it as a copy).   For the main pf dashboard it picks up everything by default correctly.

Nice!

**Comment by revere521** [comment]
Crap - i didn't mean to close this - it was a mis-click - I'm sorry about that

**Comment by fktkrt** [comment]
I am glad that it seems useful to others as well. We should incorporate some default filtering for the main pf board, since it is just a showcase of features at the moment. 

Also we should be notified by the changes caused by  https://github.com/a3ilson/pfelk/issues/67

**Comment by revere521** [comment]
It seems to work great as is on the main dashboard.  Been using it for a few days now and I really like it.   I added it to the top of the board so it dominates the main view :)

Here is my layout (i kept the original maps as well for now) 


![Dash 1](https://user-images.githubusercontent.com/23560313/71735860-8e076500-2e1d-11ea-9ea7-25e9057b2836.png)
![Dash 2](https://user-images.githubusercontent.com/23560313/71735867-92338280-2e1d-11ea-961f-75e3760a3be2.png)
![Dash 3](https://user-images.githubusercontent.com/23560313/71735873-9495dc80-2e1d-11ea-8b41-bccc1ddde1c4.png)
![Dash 4](https://user-images.githubusercontent.com/23560313/71735876-965fa000-2e1d-11ea-8b68-59fe47baad8a.png)

**Comment by fktkrt** [comment]
Nice!
Your 'Connection Map' seems quite clear. Are you filtering the pf index, or is this your actual traffic?

**Comment by revere521** [comment]
I just renamed your panel to that to differentiate between this one and the one i added to my snort dash.  The dashboard filters on pf-* by default, so i did nothing other than add the panel.  for the snort dash, i filtered on `tags : snort` 

I did reduce the thickness and opacity of the line connections - and this is 1 hr of traffic, more than that and it does start getting very full at this level, but you can really dive into it with the zoom

**Comment by fktkrt** [comment]
So, should we include the Maps visualization in the main dashboard by default?

I can make a proposal for the main pf dashboard as well (the Suricata one already has it).

**Comment by fktkrt** [comment]
Could not think of a better layout than posted above, so for now, here it is. 
[KibanaExport.zip](https://github.com/a3ilson/pfelk/files/4025244/KibanaExport.zip)
 
If it seems fine, I can commit it, then close this issue.

**Comment by revere521** [comment]
That works for me just fine, once you do i can export my visually similar snort dashboard layout as well

**Comment by revere521** [comment]
[NewMap_KibanaExport(dark+geo).zip](https://github.com/a3ilson/pfelk/files/4035332/NewMap_KibanaExport.dark%2Bgeo.zip)
[NewMap_SnortDashboard(dark+geo).zip](https://github.com/a3ilson/pfelk/files/4035333/NewMap_SnortDashboard.dark%2Bgeo.zip)

I exported the view i posted above with your map and the similar snort one, if thats easier - up to you

**Comment by fktkrt** [comment]
It is fine with me.
@a3ilson, since this is your dashboard originally, what do you think?

**Comment by a3ilson** [comment]
I’m good and appreciate all the work and changes you all have made!

**Comment by fktkrt** [comment]
If someone can shoot a nice screenshot with the newly added Maps visualization, we can maybe switch the main image in README.

**Comment by revere521** [comment]
how's this?

![DashboardScreenCapture](https://user-images.githubusercontent.com/23560313/72526439-6ad4b080-3834-11ea-97d2-2fcca31a151c.png)

**Comment by a3ilson** [comment]
That’s perfect!
