### ISSUE TITLE
Newest releases of built in X-Pack functions

### ISSUE THREAD

**Issue by uhlhosting** [pfelk/pfelk#7]
Any plan to release a new updated version of configs for the latest ek stash? Especially on the x-pack side. I found that after upgrading to latest version, the old config I had seems to cause all kinds of weird issues. Unable to add users to login, unable to activate properly login function.

**Comment by a3ilson** [comment]
I have tested (clean install) of Ubuntu 18.04 running the latest ELK
stack.  The guide still works.... I’ll tweak for the latest version within
the next few weeks.  I’ll take a look at the x-pack plugin but steered away
due to cost.

**Comment by uhlhosting** [comment]
@a3ilson thanks

**Comment by uhlhosting** [comment]
@a3ilson the only thing that I cannot seem to make it work since they allowed free version of x-pack, I cannot seem to get the right accounts in Kibana to login.
