### ISSUE TITLE
Kibana Dashboard Basic Search Section Is Empty.

### ISSUE THREAD

**Issue by gokhansezen** [pfelk/pfelk#73]
Hi,
I completed the installation with Script Install. I completed the steps after the installation as you mentioned.

But the data in the basic search section is empty.

Ubuntu 18.04
Elasticsearch 7.6
Kibana 7.6
Logstash 7.6
Firewall pfsense 2.4.4-RELEASE-p3 (amd64)

![pf-  - Kibana](https://user-images.githubusercontent.com/16643176/75227439-3eab3880-57bf-11ea-9b51-64f9d1ba5b70.png)

![Dashboard - Kibana](https://user-images.githubusercontent.com/16643176/75227448-42d75600-57bf-11ea-97a9-2c99a6f3ba8b.png)

![firewall1 omega lan - Status  System Logs  Settings](https://user-images.githubusercontent.com/16643176/75227821-f3ddf080-57bf-11ea-8375-836e8b200e12.png)

**Comment by revere521** [comment]
Ok, it looks like you are getting some data ingested so a couple of things i can think of to check:
1. Did you setup the GeoIP (maxmind account etc.) - some of the visualizations on the dashboards require the geoip data

2. In addition to sending the log data to the remote syslog server, are you asking pfsense to collect the log data? 
![image](https://user-images.githubusercontent.com/23560313/75248458-34c70c80-57a2-11ea-9b5e-e1ee89906e54.png)
 
-- in addition, you may want to turn on logging for any individual firewall rules so that they collect the data to send to the ELK stack. 

![image](https://user-images.githubusercontent.com/23560313/75248587-6dff7c80-57a2-11ea-9148-ed63d09888b3.png)

**Comment by gokhansezen** [comment]
1. GeoIP maxmind data OK

![geoip](https://user-images.githubusercontent.com/16643176/75250497-8ba40480-57e9-11ea-8c78-40a14695d7dd.png)

![geoip2](https://user-images.githubusercontent.com/16643176/75250511-8fd02200-57e9-11ea-97b4-28233dfb6303.png)

2. Firewall Rules OK

![firewall rules](https://user-images.githubusercontent.com/16643176/75250819-4b915180-57ea-11ea-9cde-d1c4c513b11a.png)

**Comment by revere521** [comment]
Ok, good - You may want to remove or obscure your info int he GeoIP screencap. 

Are you getting a steady stream of data in discover?   If so you may want to go to settings -> index patterns -> pf-* -> click the refresh button in the upper right to refresh the field mappings. 

Also in the post install configuration, did you complete step "5a. Configuring Patterns"?

**Comment by gokhansezen** [comment]
Default index pattern

![index-pattern-1](https://user-images.githubusercontent.com/16643176/75253857-6e266900-57f0-11ea-8441-db675813018f.png)

Field 241

![index-pattern-2](https://user-images.githubusercontent.com/16643176/75253871-71b9f000-57f0-11ea-8ef3-352cf0378896.png)

Refresh Field Set

![index-pattern-3](https://user-images.githubusercontent.com/16643176/75253876-74b4e080-57f0-11ea-9ba5-63fe90e23d7d.png)

Now > Field 22

![index-pattern-4](https://user-images.githubusercontent.com/16643176/75253888-77afd100-57f0-11ea-9918-8d8ae34d5002.png)

**Comment by revere521** [comment]
try deleting your existing pf indices, and both of those pf-* index patterns, and recreate the pf-* from scratch. 

There shouldn't be two, something wonky happened there. 

The field count going down means there isn't data being assigned to those fields.   

If that doesn't help we'll need to look at journal output for logstash and/or elasticsearch for errors

**Comment by a3ilson** [comment]
@gokhansezen 
Please check step 2b and validate that you commented out OPNsense and enabled (uncommented) pfSense.  Next, can you provide the output for the logstash logs (/var/log/logstash).

**Comment by gokhansezen** [comment]
Hi, @a3ilson @revere521
I made a short video for the problem i was having.
Link: https://youtu.be/eHq6VojsDSU

**Comment by gokhansezen** [comment]
Linux 4.15.0-88-generic x86_64
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

![elk-version](https://user-images.githubusercontent.com/16643176/75346112-0aaf4080-58af-11ea-9f0a-891ad0859d4e.png)

![log-1](https://user-images.githubusercontent.com/16643176/75346453-cc665100-58af-11ea-9710-a4cdad80f262.png)

![log-2](https://user-images.githubusercontent.com/16643176/75346871-a7bea900-58b0-11ea-99a4-b462ae6ab808.png)

![log-3](https://user-images.githubusercontent.com/16643176/75346823-92e21580-58b0-11ea-91d0-eec8164bfc9b.png)

![log-4](https://user-images.githubusercontent.com/16643176/75346981-d89ede00-58b0-11ea-8b02-dfa9c945cf61.png)

![log-5](https://user-images.githubusercontent.com/16643176/75347131-303d4980-58b1-11ea-9289-e0e96040707d.png)

![log-6](https://user-images.githubusercontent.com/16643176/75347408-bb1e4400-58b1-11ea-9514-9638bb114365.png)

**Comment by revere521** [comment]
Ok, I watched the video, couple of things: 

1. changing the tag from "pf" to "firewall1" in 10-inputs.conf will definitely break the processing.  All the other configs use ' if "pf" in tags ' statements to further process the log data.  change it back to "pf" and test. 


2. in order for the GeoIP to work, there needs to be a post processor.  at the bottom of the scripted instruction page there is the step 4 "Complete Configuration --> Configuration"

you need to do this for the GeoIP to work (Many of the visualizations on that dashboard require GeoIP processed fields to work) : 

```
5a. Configuring Patterns

    In your web browser go to the ELK local IP using port 5601 (ex: 192.168.0.1:5601)
    Click the wrench (Dev Tools) icon in the left panel
    Input the following and press the click to send request button (triangle)
    https://raw.githubusercontent.com/a3ilson/pfelk/master/Dashboard/GeoIP(Template)

```
3. the extra pf-* index patters look like they come along with the dashboards, you can probably just delete them.  Elasticsearch should just be using the default one you created and set to default.

**Comment by gokhansezen** [comment]
@revere521 Thank you so much. As you said, the problem is because I use a different name instead of **pf**.
firewall1 > pf
firewall2 > pf-2
