### ISSUE TITLE
additonal field for suricata tls

### ISSUE THREAD

**Issue by tworth04** [pfelk/pfelk#74]
was hoping to have an additional field for OPNsense users... 

Currently there's a field labeled " suricata.eve.alert.signature.keyword " that displays messages similar to this " OPN_Mail - Gmail - Related TLS SNI (mail.google.com)"  

Can an additional field be added to pull just the application listing possible via regex...maybe call it suricata.eve.alert.signature.keyword.pretty (the field name doesn't matter to me at all). Something similar to this : 

^"sign.*?OPN_.*?\s}

Would like to add some additional graphs based off applications most used.  Similar feature could be used for suricata.eve.tls.sni.keyword to have a root domain field.

**Comment by a3ilson** [comment]
@tworth04 
Suricata logs are parsed with the "12-suricata.conf" file leveraging the GROK pattern on line 58 of the "pf-12.2019.grok" file.  The GROK file message is parsed out with the ...{GREEDYDATA:ids_desc}... pattern.  These descriptions vary and can be customized within the suricata rules files (https://suricata.readthedocs.io/en/suricata-5.0.2/rules/intro.html).  It is possible but what is it that you are attempting to accomplish as this appears very similar to mimicking DPI.  

Additionally, you could build/customize a Kibana element to visualize this field?  

Below is an example of DPI:
![image](https://user-images.githubusercontent.com/16884679/75609255-ffd5f500-5ad4-11ea-9725-a97865f63fe5.png)

**Comment by tworth04** [comment]
I'm trying to do exactly that...i really like the dashboard above...is that something i've missed?  I've tried to mess with the suricata and patterns file but it's a bit out of my range of talents

**Comment by a3ilson** [comment]
@tworth04 
The dashboard above is a screenshot of a Unifi Dream Machine Pro DPI.  Suricata and Snort (IDS/IPS) monitor traffic at Layer 3 and 4 whereas DPI monitors traffic in Layers 2-7. 

I would suggest/recommend an instance of ntop/nDPI (https://github.com/ntop/nDPI) or other alternative vs attempting to frankensteining this with pf+suricata.

**Comment by tworth04** [comment]
Gotcha.  I appreciate you following up...ndpi has been suggested for OPNsense but hasn't been added yet.  thanks for your work on this project!

**Comment by a3ilson** [comment]
@tworth04 - FYI the new dashboards are getting closer or more refined.
