### ISSUE TITLE
HeatMap (Source) and Suricatta Maps do not seem to work

### ISSUE THREAD

**Issue by fastxl** [pfelk/pfelk#76]
Followed the custom installation as I already had ELK up and running. For some reason I don't see any data in the HeatMap (Source) and Suricatta Maps. "Unable to load layer" in the maps with this error
`Elasticsearch search request failed, error: Request to Elasticsearch failed: {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to find geo_point field [destination.geo.location]","index_uuid":"vFsgFp95QZSjdZlpNWSN1Q","index":"pf-2020.03.13"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"pf-2020.03.13","node":"uSWwyS02QO6CeRic-NYzYw","reason":{"type":"query_shard_exception","reason":"failed to find geo_point field [destination.geo.location]","index_uuid":"vFsgFp95QZSjdZlpNWSN1Q","index":"pf-2020.03.13"}}]},"status":400}`

Any suggestions?

**Comment by revere521** [comment]
Did you do the Kibana setup in the final steps: https://github.com/3ilson/pfelk/blob/master/install/configuration.md
?

**Comment by fktkrt** [comment]
More precisely, you need to add the GeoIP template to access those fields. You can find this file here: https://raw.githubusercontent.com/3ilson/pfelk/master/Dashboard/GeoIP(Template)

The steps are detailed here: https://github.com/3ilson/pfelk/blob/master/install/configuration.md#--5a-configuring-patterns

Recreating your pf-* indices might be a good idea after these steps to avoid inconsistency.

**Comment by fastxl** [comment]
Just returning to this today and it appears that it is working. Maybe I had to wait a bit longer for data to populate?

**Comment by fktkrt** [comment]
You can investigate whether you had log entries with proper fields in yesterday's entries by comparing those to your latest entries at the Discover tab.

**Comment by fastxl** [comment]
For some reason I have 4 pf-* indices. I should probably delete them all and recreate

**Comment by fktkrt** [comment]
Yes, you should. Importing saved objects eg. dashboards can create duplicated indices.

**Comment by fastxl** [comment]
After deleting the 4 pf-* indices I recreated the pf-* index and notices a "Mapping Conflict" 
`6 fields are defined as several types (string, integer, etc) across the indices that match this pattern. You may still be able to use these conflict fields in parts of Kibana, but they will be unavailable for functions that require Kibana to know their type. Correcting this issue will require reindexing your data.`

Don't remember seeing this the first time.

**Comment by fktkrt** [comment]
Well, you can use the API to reindex as described here: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html

But this should not be needed if all related index/pattern/mapping/template is deleted beforehand.

**Comment by fastxl** [comment]
Ok, deleted everything. Re-Created the pf-* index, imported the dashboards and it seems to be working. I now have 3 pf-* index patterns, if I try to delete one it will cause the dashboard to not work.

**Comment by revere521** [comment]
IT only really uses the default pattern, the remaining ones can be left.  I also have extra ones from importing dashboards for testing, and they don't seem to cause any harm after several months.

**Comment by fktkrt** [comment]
I agree. The deletion is only a problem when the referenced index pattern is getting deleted. I could remove all unnecessary patterns without a problem. 
FWIW, leaving those there should not cause any problem too, as @revere521 said.

Are your indices being populated properly now?

**Comment by fastxl** [comment]
It seems to be working indices, dashboards and all. Great work by the way and thanks for making this available. I am a bit of a novice and enjoy the learning.

**Comment by fktkrt** [comment]
That's great, we are happy to help!
I'm closing this for now, but feel free to open a new one if you encounter any other issue.
