### ISSUE TITLE
 pattern %{PFSENSE_IPv4_SPECIFIC_DATA_ECN} not defined

### ISSUE THREAD

**Issue by PinkIAndBlue** [pfelk/pfelk#8]
@a3ilson  good morning!

Please, I need you support.  when I start the Logstash service, I receive this error.
How can I fix it?

**Comment by a3ilson** [comment]
Can you confirm your utilizing the latest *.conf files and the latest patterns file?  Next please confirm the location of your *.conf files and patterns file.
