### ISSUE TITLE
Shards failed with pfsense 2.4.4

### ISSUE THREAD

**Issue by codercrack** [pfelk/pfelk#81]
When opening the dashboard I have the following messages and when I click on "Show details" nothing happens

**Operating System (please complete the following information):**
Ubuntu 18.04 LTS
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK (7.6.1)
 
 **Elasticsearch, Logstash, Kibana logs:**
  - Elasticsearch logs
` at org.elasticsearch.action.ActionListener$1.onResponse(ActionListener.java:63) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:58) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:73) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.6.1.jar:7.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.6.1.jar:7.6.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) `[?:?]`

  - Logstash log
`[2020-03-27T14:24:34,975][INFO` ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-City.mmdb"}
[2020-03-27T14:24:35,142][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-ASN.mmdb"}
[2020-03-27T14:24:35,187][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-ASN.mmdb"}
[2020-03-27T14:24:35,271][WARN ][org.logstash.instrument.metrics.gauge.LazyDelegatingGauge][main] A gauge metric of an unknown type (org.jruby.specialized.RubyArrayOneObject) has been create for key: cluster_uuids. This may result in invalid serialization.  It is recommended to log an issue to the responsible developer/development team.
[2020-03-27T14:24:35,280][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>250, "pipeline.sources"=>["/etc/logstash/conf.d/01-inputs.conf", "/etc/logstash/conf.d/11-firewall.conf", "/etc/logstash/conf.d/12-suricata.conf", "/etc/logstash/conf.d/13-snort.conf", "/etc/logstash/conf.d/15-others.conf", "/etc/logstash/conf.d/20-geoip.conf", "/etc/logstash/conf.d/50-outputs.conf"], :thread=>"#<Thread:0x5849f4a1 run>"}
[2020-03-27T14:24:38,681][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2020-03-27T14:24:38,747][INFO ][logstash.inputs.udp      ][main] Starting UDP listener {:address=>"0.0.0.0:5140"}
[2020-03-27T14:24:38,787][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2020-03-27T14:24:38,859][INFO ][logstash.inputs.udp      ][main] UDP listener started {:address=>"0.0.0.0:5140", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2020-03-27T14:24:39,038][INFO ][logstash.agent           ] Successfully started Logstash API endpoint `{:port=>9600}`

  - Kibana logs 
`mars` 26 14:00:17 siemserver systemd[1]: Started Kibana.
mars 26 14:00:30 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:00:30Z","tags":["info","plugins-service"],"pid":6269,"message":"Plugin \"case\" is disabled."}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins-system"],"pid":6269,"message":"Setting up [37] plugins: [taskManager,siem,licensing,infra,>
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","taskManager"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","siem"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","licensing"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","infra"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","encryptedSavedObjects"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["warning","plugins","encryptedSavedObjects","config"],"pid":6269,"message":"Generating a random key for xp>
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","code"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","usageCollection"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","metrics"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","canvas"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","timelion"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","features"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","security"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["warning","plugins","security","config"],"pid":6269,"message":"Generating a random key for xpack.security.>
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["warning","plugins","security","config"],"pid":6269,"message":"Session cookies will be transmitted over in>
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","apm_oss"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","translations"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","data"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","share"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","home"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","spaces"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","cloud"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","apm"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","graph"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","plugins","bfetch"],"pid":6269,"message":"Setting up plugin"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","savedobjects-service"],"pid":6269,"message":"Waiting until all Elasticsearch nodes are compatible >
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","savedobjects-service"],"pid":6269,"message":"Starting saved objects migrations"}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","savedobjects-service"],"pid":6269,"message":"Creating index .kibana_task_manager_1."}
mars 26 14:01:29 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:29Z","tags":["info","savedobjects-service"],"pid":6269,"message":"Creating index .kibana_1."}
mars 26 14:01:30 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:30Z","tags":["info","savedobjects-service"],"pid":6269,"message":"Pointing alias .kibana_task_manager to .kibana_task_m>
mars 26 14:01:30 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:30Z","tags":["info","savedobjects-service"],"pid":6269,"message":"Pointing alias .kibana to .kibana_1."}
mars 26 14:01:30 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:30Z","tags":["info","savedobjects-service"],"pid":6269,"message":"Finished in 949ms."}
mars 26 14:01:30 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:30Z","tags":["info","savedobjects-service"],"pid":6269,"message":"Finished in 1009ms."}
mars 26 14:01:30 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:30Z","tags":["info","plugins-system"],"pid":6269,"message":"Starting [22] plugins: [taskManager,siem,licensing,infra,en>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:kibana@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uninitial>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:elasticsearch@7.6.1","info"],"pid":6269,"state":"yellow","message":"Status changed from u>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:elasticsearch@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from ye>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:xpack_main@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from unini>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:graph@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uninitiali>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["info","monitoring","kibana-monitoring"],"pid":6269,"message":"Starting monitoring stats collection"}
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:monitoring@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from unini>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:spaces@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uninitial>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:security@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uniniti>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:searchprofiler@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from u>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:ml@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uninitialized>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:tilemap@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uninitia>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:watcher@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uninitia>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:grokdebugger@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uni>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:dashboard_mode@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from u>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:logstash@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uniniti>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:beats_management@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:apm_oss@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uninitia>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:apm@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uninitialize>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:maps@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from uninitializ>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:interpreter@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from unin>
mars 26 14:01:47 siemserver kibana[6269]: {"type":"log","@timestamp":"2020-03-26T13:01:47Z","tags":["status","plugin:canvas@7.6.1","info"],"pid":6269,"state":"green","message":"Status changed from `uninitial>`                              

![Kibana](https://user-images.githubusercontent.com/37569280/77770831-2a6c8c80-7046-11ea-97ba-5d93a14bb4e6.PNG)

**Comment by revere521** [comment]
I don't necessarily see any explicit errors in the logs,  it may just need to collect data for a bit - and then look at your index patterns and refresh  to make sure it collects all the fields (in Kibana - Settings - Index Patterns - pf-* - refresh field list in the upper right).

**Comment by a3ilson** [comment]
@codercrack 
Could you please provide a few raw logs?  I noticed you upgraded to pfSense 2.4.4 which I have not tested.

**Comment by revere521** [comment]
@a3ilson 2.4.4-p3 was the current release, i just upgraded to 2.4.5 this morning and I'm testing - but all looks OK so far in general

**Comment by a3ilson** [comment]
@revere521 thanks for the clarification.  Any issues with the latest release? I didn't read anything regarding changes to logging.

**Comment by revere521** [comment]
@a3ilson , no sir - everything looks good with about 2 hrs of data collected - no grokparsefailures or strangeness at all

**Comment by a3ilson** [comment]
@codercrack have you had any luck getting this working?

**Comment by a3ilson** [comment]
@codercrack - were you able to resolve this issue?

**Comment by a3ilson** [comment]
Unable to duplicate error/did not hear back from the originator.
