### ISSUE TITLE
[OPNsense] Suricata index-pattern-field id's missing

### ISSUE THREAD

**Issue by rrosson** [pfelk/pfelk#82]
**Describe the bug**
Sending data from OPNsense version 20.1.3 to pfelk (latest version. Only loaded the latest dashboard (v4 (042020) Dashboard.ndjson) and I am getting two boxes with errors:
```
Could not locate that index-pattern-field (id: suricata.eve.alert.metadata.signature_severity.keyword)
Could not locate that index-pattern-field (id: suricata.eve.alert.category.keyword)
```
But I get a "Suricata Count"

**To Reproduce**
Fresh Install follow directions for OPNsense

**Screenshots**
![Screen Shot 2020-03-30 at 11 21 15 AM](https://user-images.githubusercontent.com/2329/77942337-b36b0a00-7278-11ea-968c-8e562bd8c8ab.png)

**Operating System (please complete the following information):**
Linux 4.15.0-91-generic x86_64
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic 

**Elasticsearch, Logstash, Kibana (please complete the following information):**
ii  elasticsearch                         7.6.1                                           amd64        Distributed RESTful search engine built for the cloud
ii  kibana                                7.6.1                                           amd64        Explore and visualize your Elasticsearch data
ii  logstash                              1:7.6.1-1                                       all          An extensible logging pipeline
 
 **Elasticsearch, Logstash, Kibana logs:**
Nothing in logs to indicate an issue

**Additional context**

**Comment by a3ilson** [comment]
I just did a fresh install on OPNsense (the last several upgrades seemed to have broken a few things).  Everything is looking good with the latest installation.  Initially, I had a number of blank visualizations but after pushing some traffic through they all populated.  I also had to enable a bunch or Suricata rules (you could also modify/create a rule to pick up on pings, for further testing).

**Comment by rrosson** [comment]
@a3ilson Viewing the last hour those two are still blank with the same error. Count is still increasing

Here is OPNsense Suricata config SS:
![Screen Shot 2020-03-30 at 3 00 23 PM](https://user-images.githubusercontent.com/2329/77961547-38fdb280-7297-11ea-9096-2536a93fe2f5.png)

Here is the SS of the settings for syslog:
![Screen Shot 2020-03-30 at 3 02 27 PM](https://user-images.githubusercontent.com/2329/77961898-d0630580-7297-11ea-8ddb-666d42f3a266.png)

**Comment by a3ilson** [comment]
@rrosson - I've been digging into this a a past hour.  My setup is configured exactly like your provided screenshots.  Additionally, I enabled all the rules to further troubleshoot.  I have noticed some logs are not being filtered:

![image](https://user-images.githubusercontent.com/16884679/77966122-6dca3380-72b0-11ea-8c19-456fb039f6bb.png)

However, I still have enough activity to populate the dashboard but agree additional refining is needed to address these events that are not being filtered properly.  I'll keep working at it and post an updated unless someone else beats me to it.

Thanks!

**Comment by rrosson** [comment]
@a3ilson Thank you. My Suricata is tuned to my environment and to limit the false positives. I also am giving my telemetry data to proofpoint in exchange for et-pro rules.

Let me know if there is anything I can do for you on my end.

**Comment by a3ilson** [comment]
@rrosson - I've made a number of changes and recreated the dashboard.  I'm working on the Suricata dashboard and should have it uploaded by the end of the week.

**Comment by a3ilson** [comment]
@rrosson - please update with the latest Dashboard (https://github.com/3ilson/pfelk/blob/master/Dashboard/v4.2%20(042020)%20Suricata%20Dashboard.ndjson.ndjson)

**Comment by rrosson** [comment]
Just added the dashboard.  Set time to last 24 hours and the only thing that populates is the "Map - Suricata".  

- In the box to the right of the 'Map - Suricata" I get the following error "Could not locate that index-pattern-field (id: suricata.alert.signature.keyword)". 
- In the "Suricata" box I get "No results found". 
- To the right of that I get "Could not locate that visualization (id: 9683efe0-812a-11ea-b070-b9217beb6af5)".  
- In the box "Suricata - Time" I get "No results found"
- To the of that I get "Could not locate that index-pattern-field (id: suricata.alert.signature.keyword)"

I hope this helps. All the inputs and configs are up to date with what you have in the repo.

**Comment by a3ilson** [comment]
@rrosson - Can you provide some raw (text format) messages from Suricata?

**Comment by rrosson** [comment]
xxx.xxx.xxx.xxx == my public IP
yyy.yyy.yyy.yyy == my internal ip logging to elastic

Log output grabbed from kibana
```
<173>Apr 19 08:28:46 myfirewall.mydomain.org suricata[12950]: [Drop] [1:2011716:3] ET SCAN Sipvicious User-Agent Detected (friendly-scanner) [Classification: Attempted Information Leak] [Priority: 2] {UDP} 188.214.132.23:5075 -> xxx.xxx.xxx.xxx:5060
```
JSON output grabbed from Kibana
```
@timestamp	Apr 19, 2020 @ 08:28:46.618
	@version	1
	_id	n7fXknEBAs3ZRXOYeMsA
	_index	pf-2020.04.19
	_score	 - 
	_type	_doc
	event.created	Apr 19 08:28:46
	event.id	173
	event.original	<173>Apr 19 08:28:46 myfirewall.mydomain.org suricata[12950]: [Drop] [1:2011716:3] ET SCAN Sipvicious User-Agent Detected (friendly-scanner) [Classification: Attempted Information Leak] [Priority: 2] {UDP} 188.214.132.23:5075 -> xxx.xxx.xxx.xxx:5060
	host	yyy.yyy.yyy.yyy
	labels	suricata
	observer.name	myfirewall.mydomain.org
	observer.type	firewall
	pf_pid	12950
	suricata.info	http://doc.emergingthreats.net/bin/view/Main/%{[suricata][rule][id]}
	tags	pf, suricata, _grokparsefailure, dns
```
log entries from /var/log/suricata/eve.json on OPNsense box 
```
{"timestamp":"2020-04-19T08:28:46.614378-0600","flow_id":786025724927978,"in_iface":"igb1","event_type":"alert","src_ip":"188.214.132.23","src_port":5075,"dest_ip":"xxx.xxx.xxx.xxx","dest_port":5060,"proto":"UDP","alert":{"action":"blocked","gid":1,"signature_id":2011716,"rev":3,"signature":"ET SCAN Sipvicious User-Agent Detected (friendly-scanner)","category":"Attempted Information Leak","severity":2,"metadata":{"updated_at":["2010_07_30"],"created_at":["2010_07_30"]}},"app_proto":"failed","flow":{"pkts_toserver":1,"pkts_toclient":0,"bytes_toserver":459,"bytes_toclient":0,"start":"2020-04-19T08:28:46.614378-0600"}}
{"timestamp":"2020-04-19T08:28:46.614378-0600","flow_id":786025724927978,"in_iface":"igb1","event_type":"drop","src_ip":"188.214.132.23","src_port":5075,"dest_ip":"xxx.xxx.xxx.xxx","dest_port":5060,"proto":"UDP","drop":{"len":445,"tos":80,"ttl":52,"ipid":34959,"udplen":425},"alert":{"action":"blocked","gid":1,"signature_id":2011716,"rev":3,"signature":"ET SCAN Sipvicious User-Agent Detected (friendly-scanner)","category":"Attempted Information Leak","severity":2}}
```
entries from /var/log/suricata.log on OPNsense box
```
Apr 19 08:28:46 myfirewall suricata[12950]: {"timestamp": "2020-04-19T08:28:46.614378-0600", "flow_id": 786025724927978, "in_iface": "igb1", "event_type": "alert", "src_ip": "188.214.132.23", "src_port": 5075, "dest_ip": "xxx.xxx.xxx.xxx", "dest_port": 5060, "proto": "UDP", "alert": {"action": "blocked", "gid": 1, "signature_id": 2011716, "rev": 3, "signature": "ET SCAN Sipvicious User-Agent Detected (friendly-scanner)", "category": "Attempted Information Leak", "severity": 2, "metadata": {"updated_at": ["2010_07_30"], "created_at": ["2010_07_30"]}}, "app_proto": "failed", "flow": {"pkts_toserver": 1, "pkts_toclient": 0, "bytes_toserver": 459, "bytes_toclient": 0, "start": "2020-04-19T08:28:46.614378-0600"}}
Apr 19 08:28:46 myfirewall suricata[12950]: [Drop] [1:2011716:3] ET SCAN Sipvicious User-Agent Detected (friendly-scanner) [Classification: Attempted Information Leak] [Priority: 2] {UDP} 188.214.132.23:5075 -> xxx.xxx.xxx.xxx:5060
```
In looking through kibana for the last 15 minutes I have 12 hits for 'suricata' and all of them have the tag of '_grokparsefailure' as well as 'pf' and 'dns'

Please let me know if there is anything else I can provide

**Comment by a3ilson** [comment]
@rrosson - Here is my setup, which is very similar to your configuration:

## OPNsense Suricata:
![OPNsense (suricata)](https://user-images.githubusercontent.com/16884679/79704166-06375080-827e-11ea-97b6-106640b1e463.png)

## OPNsense Remote Logging
![OPNsense Logging](https://user-images.githubusercontent.com/16884679/79704173-164f3000-827e-11ea-84e1-e2a4ccc5eaa0.png)
 
## Here is what my suricata logs look like in Kibana
![Kibana](https://user-images.githubusercontent.com/16884679/79704178-2535e280-827e-11ea-80f9-1562d6eed041.png)

## Here is what the raw traffic looks like within Moloch
![Moloch Capture](https://user-images.githubusercontent.com/16884679/79704189-354dc200-827e-11ea-99a0-27c83a3fe3c4.png)

## Here is the clear text of my suricata logs:

### Suricata Message:1
```
<174>Apr 19 20:16:34 firewall.3ilson.dev suricata[41362]: {"timestamp": "2020-04-19T20:16:34.453344-0400", "flow_id": 1737545828461280, "in_iface": "igb1", "event_type": "alert", "src_ip": "172.22.33.10", "src_port": 58656, "dest_ip": "8.8.4.4", "dest_port": 53, "proto": "UDP", "tx_id": 0, "alert": {"action": "allowed", "gid": 1, "signature_id": 2027865, "rev": 2, "signature": "ET INFO Observed DNS Query to .cloud TLD", "category": "Potentially Bad Traffic", "severity": 2, "metadata": {"updated_at": ["2019_09_28"], "created_at": ["2019_08_13"], "signature_severity": ["Major"], "deployment": ["Perimeter"], "attack_target": ["Client_Endpoint"], "affected_product": ["Any"], "former_category": ["INFO"]}}, "dns": {"query": [{"type": "query", "id": 38930, "rrname": "prod-tp.sumo.mozit.cloud", "rrtype": "AAAA", "tx_id": 0}]}, "app_proto": "dns", "flow": {"pkts_toserver": 1, "pkts_toclient": 0, "bytes_toserver": 95, "bytes_toclient": 0, "start": "2020-04-19T20:16:34.453344-0400"}}
```

### Suricata Message:2
```
<173>Apr 19 20:16:34 firewall.3ilson.dev suricata[41362]: [1:2027865:2] ET INFO Observed DNS Query to .cloud TLD [Classification: Potentially Bad Traffic] [Priority: 2] {UDP} 172.22.33.10:58656 -> 8.8.4.4:53
```
#### Suricata message:1 is handled by 30-suricata.conf lines 2-43 (JSON)
#### Suricata message:2 is handled by 30-suricata.conf lines 44-49 (Not JSON)

I am unable to duplicate your issue but wanted to provide you with my setup as it is very similar to yours.  I accomplished a clean install of OPNsense in mid-April and the pfelk was freshly installed today.  I am running the following:
- OPNsense w/Suricata
- Ubuntu 18.04 Server
- pfelk installed on my Ubuntu 18.04 Server

**Comment by rrosson** [comment]
@a3ilson In reviewing your configuration that you shared and what I have side by side I noticed that you are not in IPS mode. (Enable protection mode (block traffic).
Before enabling, please disable all hardware offloading first in advanced network.) I am curious if this could be the reason I am getting the _grokparsefailures. 

In being in IPS mode I also have the majority of my enabled rules to "Drop" for the action. Would it be possible for you to try and see if by switching to IPS mode if you get the same results as I?

Again many "thanks' for taking the time into looking in to this when it is just a hobby.

**Comment by a3ilson** [comment]
I am wondering if this issue is related to #91; update your suricata.conf file as follows:

```
# 20-suricata.conf
filter {
 if "pf" in [tags] and [labels] =~ /^suricata$/ {
   mutate {
     add_tag => [ "suricata" ]
   }
   if [pf_message] =~ /^{.*}$/ {
     json {
       source => "pf_message"
       target => "[suricata][eve]"
     }
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => [ "pf_message", "%{SURICATA}"]
      }
   }
   if [suricata][eve][src_ip] and ![source][ip] {
     mutate {
       add_field => { "[source][ip]" => "%{[suricata][eve][src_ip]}"}
     }
   }
   if [suricata][eve][dest_ip] and ![destination][ip] {
     mutate {
       add_field => { "[destination][ip]" => "%{[suricata][eve][dest_ip]}"}
     }
   }
   if [suricata][eve][src_port] and ![source][port] {
     mutate {
       add_field => { "[source][port]" => "%{[suricata][eve][src_port]}"}
     }
   }
   if [suricata][eve][dest_port] and ![destination][port] {
     mutate {
       add_field => { "[destination][port]" => "%{[suricata][eve][dest_port]}"}
     }
   }
   mutate {
     add_field => { "[event][module]" => "suricata"}
     add_field => { "[event][dataset]" => "suricata"}
   }
 }
}
``` 

Once updated, restart logstash and see if that works?

**Comment by rrosson** [comment]
That fixed the _grokparsefailure tags for the first two events suricata events that occurred after restart. Dashboard is still the same as above.   :(

**Comment by a3ilson** [comment]
@rrosson - Let's try another configuration file.  Once the suspected issue is identified, I'll likely need to regenerate another dashboard. 

Give this one a try

```
# 20-suricata.conf
filter {
  if "pf" in [tags] and [labels] =~ /^suricata$/ {
    mutate {
      add_tag => [ "suricata" ]
    }
    if [pf_message] =~ /^{.*}$/ {
      json {
        source => "pf_message"
        target => "[suricata]"
        add_tag => "suricata_json"
      }
    }
    mutate{
    }
    if [suricata][src_ip] and ![source][ip] {
      mutate {
        add_field => { "[source][ip]" => "%{[suricata][src_ip]}"}
      }
    }
    if [suricata][dest_ip] and ![destination][ip] {
      mutate {
        add_field => { "[destination][ip]" => "%{[suricata][dest_ip]}"}
      }
    }
    if [suricata][src_port] and ![source][port] {
      mutate {
        add_field => { "[source][port]" => "%{[suricata][src_port]}"}
      }
    }
    if [suricata][dest_port] and ![destination][port] {
      mutate {
        add_field => { "[destination][port]" => "%{[suricata][dest_port]}"}
      }
    }
    mutate {
#      rename => {"[suricata][src_ip]" => "[suricata][source][ip]"}
#      rename => {"[suricata][src_port]" => "[suricata][source][port]"}
#      rename => {"[suricata][dest_ip]" => "[suricata][destination][ip]"}
#      rename => {"[suricata][dest_port]" => "[suricata][destination][port]"}
      convert => { "[suricata][eve][alert][signature_id]" => "string"}
    }
    if "suricata_json" not in [tags] {
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => [ "pf_message", "%{SURICATA}"]
      }
    }
    mutate {
      remove_tag => "suricata_json"
      add_field => [ "[suricata][info]", "http://doc.emergingthreats.net/bin/view/Main/%{[suricata][rule][id]}" ]
    }
  }
}
```

If that doesn't work, commit out line 41 "convert =>..." and try again.  If that still doesn't work try the following:

```
# 20-suricata.conf
filter {
  if "pf" in [tags] and [labels] =~ /^suricata$/ {
    mutate {
      add_tag => [ "suricata" ]
    }
    if [pf_message] =~ /^{.*}$/ {
      json {
        source => "pf_message"
        target => "[suricata][eve]"
        add_tag => "suricata_json"
      }
    }
    mutate{
    }
    if [suricata][eve][src_ip] and ![source][ip] {
      mutate {
        add_field => { "[source][ip]" => "%{[suricata][eve][src_ip]}"}
      }
    }
    if [suricata][eve][dest_ip] and ![destination][ip] {
      mutate {
        add_field => { "[destination][ip]" => "%{[suricata][eve][dest_ip]}"}
      }
    }
    if [suricata][eve][src_port] and ![source][port] {
      mutate {
        add_field => { "[source][port]" => "%{[suricata][eve][src_port]}"}
      }
    }
    if [suricata][eve][dest_port] and ![destination][port] {
      mutate {
        add_field => { "[destination][port]" => "%{[suricata][eve][dest_port]}"}
      }
    }
    mutate {
#      rename => {"[suricata][src_ip]" => "[suricata][source][ip]"}
#      rename => {"[suricata][src_port]" => "[suricata][source][port]"}
#      rename => {"[suricata][dest_ip]" => "[suricata][destination][ip]"}
#      rename => {"[suricata][dest_port]" => "[suricata][destination][port]"}
      convert => { "[suricata][eve][alert][signature_id]" => "string"}
    }
    if "suricata_json" not in [tags] {
      grok {
        patterns_dir => ["/etc/logstash/conf.d/patterns"]
        match => [ "pf_message", "%{SURICATA}"]
      }
    }
    mutate {
      remove_tag => "suricata_json"
      add_field => [ "[suricata][info]", "http://doc.emergingthreats.net/bin/view/Main/%{[suricata][rule][id]}" ]
    }
  }
}
```

Thanks for helping with the troubleshooting... let me know which configurations successfully parse out both variants of the suricata messages.

**Comment by rrosson** [comment]
@a3ilson Trying variation 1 waiting for a suricata event.  :)

UPDATE: First iteration causes _grokparsefailure. :(

Trying 2nd variant (commenting out line 41

UPDATE: Second iteration causes _grokparsefailure. :(

Trying 3rd variant

**Comment by rrosson** [comment]
@a3ilson 3rd Iteration causes _grokparsefailure. Will hold with this til I hear from you.

**Comment by a3ilson** [comment]
@rrosson - So the first alternative (previous version) was able to parse the suricata json messages but unable to parse the suricata alert messages - is that accurate?


Can you providing the following:
 - How much ram is available?
 - How many processors are available?
 - How much ram is designated for logstash/elsatic?
 - How many pipeline-workers are allocated to logstash?

I have not been able to replicate and believe the issue by be another variable.

**Comment by rrosson** [comment]
> @rrosson - So the first alternative (previous version) was able to parse the suricata json messages but unable to parse the suricata alert messages - is that accurate?

Not sure since this all occurred when you released 4.2
> 
> Can you providing the following:
> 
> * How much ram is available?
6G
> * How many processors are available?
6 vCPU
> * How much ram is designated for logstash/elsatic?
Not sure where to look
> * How many pipeline-workers are allocated to logstash?
This elastic instance is standalone and is only receiving data from opnsense.
> 
> I have not been able to replicate and believe the issue by be another variable.

Please let me know if there is any more information that I can provide

**Comment by rrosson** [comment]
@a3ilson UPDATE: Went back through and compared what my conf.d files contained versus what was in the git repo. Needless to say I found some mismatched data. I have gone ahead and corrected all the files and the blocks on the left in the Suricata dashboard are now populated. This means that only the three boxes on the right side of the dashboard have the initial error I reported for this issue. I no longer have _grokparsefailure for suricata events.

Sorry for chasing you down the wrong rabbit hole when I thought my installation was in sync with the repository.

**Comment by a3ilson** [comment]
Which dashboard....can you provide a screenshot

**Comment by rrosson** [comment]
> Which dashboard....can you provide a screenshot

![Screen Shot 2020-04-22 at 11 27 54 AM](https://user-images.githubusercontent.com/2329/80013678-8501d880-848c-11ea-9b8e-7e11f0322104.png)

**Comment by a3ilson** [comment]
Check to see if both the alerts and json messages are being parsed - your using the latest 20-suricata.conf file correct?

**Comment by rrosson** [comment]
> your using the latest 20-suricata.conf file correct?

Yes I am using the latest copy from the repository Here is the latest suricata event. You will notice it gets log twice (both formats). 
Below is the event.original 

```
<173>Apr 22 14:37:24 myfirewall.mydomain.org suricata[662]: [Drop] [1:2001219:20] ET SCAN Potential SSH Scan [Classification: Attempted Information Leak] [Priority: 2] {TCP} 124.238.113.126:13004 -> xxx.xxx.xxx.xxx:22
```
```
<174>Apr 22 14:37:24 myfirewall.mydomain.org suricata[662]: {"timestamp": "2020-04-22T14:37:24.853581-0600", "flow_id": 824413251700301, "in_iface": "igb1", "event_type": "alert", "src_ip": "124.238.113.126", "src_port": 13004, "dest_ip": "xxx.xxx.xxx.xxx", "dest_port": 22, "proto": "TCP", "alert": {"action": "blocked", "gid": 1, "signature_id": 2001219, "rev": 20, "signature": "ET SCAN Potential SSH Scan", "category": "Attempted Information Leak", "severity": 2, "metadata": {"updated_at": ["2010_07_30"], "created_at": ["2010_07_30"]}}, "flow": {"pkts_toserver": 1, "pkts_toclient": 0, "bytes_toserver": 62, "bytes_toclient": 0, "start": "2020-04-22T14:37:24.853581-0600"}}
```
Please let me know if there is anything else I can provide

**Comment by a3ilson** [comment]
@rrosson are they both being parsed correctly? 

Thanks for providing the raw format.  I'll need to revise the grok pattern for IPS as there are different fields which is likely the reason for the empty/void dashboard elements.

**Comment by rrosson** [comment]
> @rrosson are they both being parsed correctly?

Yes, none of the suricata events are producing _grokparsefailure. :)
> 
> Thanks for providing the raw format. I'll need to revise the grok pattern for IPS as there are different fields which is likely the reason for the empty/void dashboard elements.

Glad the above helped

**Comment by a3ilson** [comment]
It appears one of the elements (visualizations) was inadvertenly omitted.  I updated the dashboard, please download and import the latest version.  Additionally, I checked the other visualizations and compared to the your referenced output above.  They contain the correct fields and should populate.  One item to note, the map within the dashboard is skewed.  The filter did not save, you may need to add a filter [tags.keyboards (operator "is") suricata].  You may need to let it run for a bit.

I also noted that your alert message contains one extra field (Drop). I added that to my list and will correct the grok pattern in the near future.

The dashboard should be working, please give it another try.

Thanks

**Comment by rrosson** [comment]
I was able to get the new dashboard loaded and I refreshed the indexes. Everything is now populated. Since there is one more item (updated grok pattern for IPS) I will leave this open at your discretion to close.

Please let me know if there is any more I can do to assist

**Comment by a3ilson** [comment]
Duplicate issues w/#103 & 91
Issues isolated/identified with #111 opened for further troubleshooting

**Comment by a3ilson** [comment]
@rrosson - this was also identified in #111 and a workaround provided until the dashboard can be rebuilt.  Thanks to @TehMuffinMoo
