### ISSUE TITLE
Error in 50-outputs.conf

### ISSUE THREAD

**Issue by gauthig** [pfelk/pfelk#83]
Using latest version of the script installer, there is a incorrect director in /etc/logstash/conf.d/50-outputs.conf

It has
/etc/logstash/conf.d/template/pf-geoip-template.json
Should be
/etc/logstash/conf.d/patterns/pf-geoip-template.json

Causes logstash to error when starting and go through very high CPU

**Comment by a3ilson** [comment]
@gauthig Thanks!  The issue was resolved. 

Fix:
Added direction creation of /etc/logstash/conf.d/template/

Please try again and if all is good, please close this issue.

**Comment by a3ilson** [comment]
Bug corrected.
