### ISSUE TITLE
Duplicate index patterns when importing

### ISSUE THREAD

**Issue by CinoNY** [pfelk/pfelk#85]
When importing dashboards, i'm not being prompted to link the pf-* index i've created. Instead, i'm seeing duplicate indexes. v4.1 (042020) Dashboard.ndjson and NewMap_SnortDashboard(dark+geo).ndjson are examples. 

v4 (042020) Dashboard.ndjson did prompt which index to use (which is now gone)

![image](https://user-images.githubusercontent.com/790943/78553254-f5470380-77d6-11ea-8348-fa4fc84ee4c9.png)

If this is by design, then ok but find it odd

**Comment by a3ilson** [comment]
@SPCulhane - Do you receive duplicate indexes, when importing only the v4.1 (042020) Dashboard.ndjson?  or is this a result snort imports? or v4.1 & snort?

**Comment by CinoNY** [comment]
@a3ilson Any dashboard I import from the Dashboard folder, adds a duplicate index. the only one that didn't, was the 4.0 dashboard

**Comment by a3ilson** [comment]
@SPCulhane - Give this exported [Dashboard](https://raw.githubusercontent.com/3ilson/pfelk/master/Dashboard/v4.2%20(042020)%20Dashboard.ndjson) a try.

**Comment by CinoNY** [comment]
that did it! Could this also be applied to the other dashboards you have shared?

![image](https://user-images.githubusercontent.com/790943/78560792-9daf9480-77e4-11ea-8d96-c03ca3556a4c.png)

**Comment by a3ilson** [comment]
@SPCulhane - Perfect!  
In regards to the other dashboards, I cannot say for certain.  Some of those were created by others.  I am currently working on a new Suricata Dashboard.  I am not utilizing Snort (OPNsense w/Suricata) and will need to seek assistance with an updated Snort Dashboard.

I'll add some instructions on exporting within the Dashboard folder.  Let me know if there is anything else specific to this issue, if not please close.

**Comment by CinoNY** [comment]
I think we're good. Thank you so much!! I really appericate it!
