### ISSUE TITLE
Issue pfelk

### ISSUE THREAD

**Issue by ounibassem** [pfelk/pfelk#87]
**Describe the bug**

I cannot see the dashboards of snort, sucurita, firewall etc, no data at the level of kibana 7.6.1, plz HELP ME

**Screenshots**

**Operating System (please complete the following information):**
 - OS Centos 7`:
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK : 7.6.1
 
 **Elasticsearch, Logstash, Kibana logs:**
  - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`)
![image](https://user-images.githubusercontent.com/47194967/78635732-c98f5080-789e-11ea-83e1-e21cb7631947.png)
![image](https://user-images.githubusercontent.com/47194967/78635952-34408c00-789f-11ea-9ad6-8c783ea4adc4.png)

  - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`)
![image](https://user-images.githubusercontent.com/47194967/78635685-afee0900-789e-11ea-85be-38ac2e1309f3.png)
![image](https://user-images.githubusercontent.com/47194967/78635902-1d019e80-789f-11ea-8087-c2aee6f0e43f.png)

  - Kibana logs (`journalctl -u kibana.service`)
![image](https://user-images.githubusercontent.com/47194967/78635774-da3fc680-789e-11ea-9820-1b3397232f8c.png)

**Additional context**
![image](https://user-images.githubusercontent.com/47194967/78636083-78cc2780-789f-11ea-817e-404081026b5e.png)
![image](https://user-images.githubusercontent.com/47194967/78636108-87b2da00-789f-11ea-8647-35c56fe13417.png)

**Comment by revere521** [comment]
OK, first step, in Kibana: go to Management (gear icon) -> Index Patterns -> pf-* -> in the upper right, refresh the field list. 

Once you do that, check the discovery to see if its parsing messages into individual fields

**Comment by a3ilson** [comment]
This issue was closed and created with issue #88

**Comment by a3ilson** [comment]
This issue was closed and created with issue #88
