### ISSUE TITLE
pfSense Suricata JSON Filtering Error

### ISSUE THREAD

**Issue by a3ilson** [pfelk/pfelk#88]
**Describe the bug**
pfSense Suricata JSON logs do not properly filter.  However, filtering works if not in the JSON format.  Seeking help for configuring pfSense+Suricata+JSON filtering.

**To Reproduce**
1. Configure pfSense+Suricata as follows:
![image](https://user-images.githubusercontent.com/16884679/78664901-f180b300-78a2-11ea-82a1-378bf611fe95.png)
2. Configure pfelk as prescribed in the default instructions 

**Screenshots**
Reference issue #84 and #87 
![image](https://user-images.githubusercontent.com/16884679/78665033-2d1b7d00-78a3-11ea-9b2c-16a4463da895.png)

![image](https://user-images.githubusercontent.com/16884679/78665091-43293d80-78a3-11ea-98e2-601d60d77802.png)

**Operating System (please complete the following information):**
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`): pfSense 2.4.4+
 
**Elasticsearch, Logstash, Kibana (please complete the following information):**
 - Version of ELK (`dpkg -l elasticsearch|logstash|kibana`) v7.6.1+
 
 **Elasticsearch, Logstash, Kibana logs:**
  - Elasticsearch logs (`tail -f /var/log/elasticsearch/[your-elk-cluster-name].log`) - no issues, working
  - Logstash logs (`tail -f /var/log/logstash/logstash-plain.log`) - no issues, working
  - Kibana logs (`journalctl -u kibana.service`) - no issues, working 

**Additional context**
Refer to issues #84 & #87

**Comment by a3ilson** [comment]
@revere521 - Have you had any issues with pfSense and the latest pfelk?

Thanks for adding the Snort Dashboard!  I am working to create a similar Suricata one.

**Comment by revere521** [comment]
After updating everything (elk 7.6.2, and pfsense 2.4.5) i did have to redo most of my visualizations, etc. 

So far so good...im monitoring.  I did delete all of my historical indices to eliminate field mapping issues.

I updated the old geo+dark dashboard along with the snort dashboard and map, i can upload that as an alternative to your new one if we want.

It will take a few days of data gathering to see if i need any tweaks

**Comment by a3ilson** [comment]
@ztroop and @ounibassem 
Please advise if you are still having issues.  It appears to be working and it may be specific to your setup and/or configuration.

**Comment by fktkrt** [comment]
Just checked your EVE output settings, all looks fine.
I am running ELK v7.6.1 and pfSense 2.4.4-p3, cannot repro the aforementioned filtering issue.

**Comment by a3ilson** [comment]
Unable to duplicate specified error.
