### ISSUE TITLE
Add rule description to indexed documents

### ISSUE THREAD

**Issue by gauthig** [pfelk/pfelk#89]
The logs from pfSense only have the rule ID and tracker number for all firewall rules which are not displayed in the firewall GUI

User Story,
In the firewall rule on screen of pfSense, only the rule and the description are displayed, not the rule number, but in the logs only the rule number and tracker ID are stored.  This makes it hard to understand which rule drove the event.action. I would like to see the rule description added to the index.  It must be a normal text attribute so that it can be queried or displayed in kibana.  

Technical solution.
Rules numbers can change with reordering rules, but tracker remains consistent with each rule in pfSense. 

1. Add a dictionary filter to lookup the tracker id in the document and add a field called rule_description with the visible description from pfSense.  

2. Provide instructions in the setup document to populate the logstash filter configuration file with the rule description from pfSense.

**Comment by a3ilson** [comment]
Added/thanks!
