### ISSUE TITLE
check logstash working proprly

### ISSUE THREAD

**Issue by repomanz** [pfelk/pfelk#92]
Hello - i followed your guide but not seeing any indexes showing up as pf-* when configuring kibana.  Can you give me some pointers to troubleshoot this? Something wrong with logstash config?

running debian 10, pfsense 2.4.5; snort and i have wan and vpn interfaces.

**Comment by a3ilson** [comment]
@repomanz Thanks for your inquire.  Can you validate the following:
(1) What installation method did you utilize
(2) Did you adjust 01-inputs.conf to reflect your pfSense/OPNsense IP address (line 12)
(3) Did you adjust 01-inputs,conf to parse syslog messages depending on your firewall (e.g. pfSense / OPNsense [you'll need to uncommit or commit out the correlating instances])
(4) Did you navigate to Kibana and create the index pattern (https://www.elastic.co/guide/en/kibana/current/tutorial-define-index.html)

If all the above seem in order and you are still not receiving parsed logs.  Please provide the output of your logstash logs (/etc/log/logstash/).

**Comment by repomanz** [comment]
(1) What installation method did you utilize
- used your manual install guide

(2) Did you adjust 01-inputs.conf to reflect your pfSense/OPNsense IP address (line 12)
  if [host] =~ /10\.180\.5\.1/ {
    mutate {
      add_tag => [ "pf", "Ready" ]
      add_field => [ "[observer][type]", "firewall" ]
    }
  }

(3) Did you adjust 01-inputs,conf to parse syslog messages depending on your firewall (e.g. pfSense / OPNsense [you'll need to uncommit or commit out the correlating instances])

  if "pf" in [tags] {
    grok {
      # OPNsense - Enable/Disable the line below based on firewall platform
      # match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{SYSLOGHOST:[observer][name]} %{DATA:labels}(?:\[%{POSI
NT:pf_pid}\])?: %{GREEDYDATA:pf_message}" }
      ########################################################################################################################################
      # pfSense - Enable/Disable the line below based on firewall platform
      match => { "message" => "<(?<[event][id]>.*)>%{SYSLOGTIMESTAMP:[event][created]} %{DATA:labels}(?:\[%{POSINT:[event][id]}\])?: %{GREEDYDATA
:pf_message}" }
    }
    mutate {
      rename => { "[message]" => "[event][original]"}
      remove_tag => "Ready"
    }
  }
}

(4) Did you navigate to Kibana and create the index pattern (https://www.elastic.co/guide/en/kibana/current/tutorial-define-index.html)

this is the part not working - creating index and typing pf doesn't show me a pattern. 

root@vmdeblog:/var/log/logstash# ls
logstash-deprecation.log  logstash-plain.log  logstash-slowlog-plain.log

I don't think logs are coming in properly.  logstash-plan.log doesn't show any firewall activity in the log

**Comment by a3ilson** [comment]
@repomanz - amend 01-inputs.conf line 12 as follows:
From:
```
if [host] =~ /10.180.5.1/ {
```
To This:
```
if [host] =~ /10\.180\.5\.1/ {
```

Next, you'll need to restart Logstash ```sudo systemctl restart logstash.service``` give it a few minutes to restart and start collecting some initial messages.  Then navigate to Kibana and create the pf-* index pattern.

**Comment by repomanz** [comment]
I'm not sure why that didn't paste correctly in the post here.   What else can i take a look at?

![image](https://user-images.githubusercontent.com/20090451/79626004-77e29380-80f2-11ea-8321-a39187b6730b.png)

**Comment by a3ilson** [comment]
@repomanz what is the IP address of your logstash instance?

**Comment by a3ilson** [comment]
Can you provide the output (contents) of: ```/var/log/logstash/logstash-plain.log```

**Comment by a3ilson** [comment]
Feel free to chat via Gitter (https://gitter.im/pfelk/community). I'll be finishing up a Suricata Dashboard (#82)

**Comment by repomanz** [comment]
10.180.5.40 is the ELK stack

[2020-04-17T20:23:16,498][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.6.2"}
[2020-04-17T20:23:25,401][INFO ][org.reflections.Reflections] Reflections took 111 ms to scan 1 urls, producing 20 keys and 40 values
[2020-04-17T20:23:27,979][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-City.mmdb"}
[2020-04-17T20:23:28,458][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-ASN.mmdb"}
[2020-04-17T20:23:28,479][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-ASN.mmdb"}
[2020-04-17T20:23:28,675][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-City.mmdb"}
[2020-04-17T20:23:28,828][WARN ][org.logstash.instrument.metrics.gauge.LazyDelegatingGauge][main] A gauge metric of an unknown type (org.jruby.Ru
byArray) has been created for key: cluster_uuids. This may result in invalid serialization.  It is recommended to log an issue to the responsible
 developer/development team.
[2020-04-17T20:23:28,837][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>1, "pipeline.batch
.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>125, "pipeline.sources"=>["/etc/logstash/conf.d/01-inputs.conf", "/etc/logstash
/conf.d/05-firewall.conf", "/etc/logstash/conf.d/25-snort.conf", "/etc/logstash/conf.d/30-geoip.conf", "/etc/logstash/conf.d/40-dns.conf"], :thre
ad=>"#<Thread:0x24c75d17 run>"}
[2020-04-17T20:23:28,905][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2020-04-17T20:23:29,101][INFO ][logstash.inputs.udp      ][main] Starting UDP listener {:address=>"0.0.0.0:5140"}
[2020-04-17T20:23:29,122][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]
}
[2020-04-17T20:23:29,504][INFO ][logstash.inputs.udp      ][main] UDP listener started {:address=>"0.0.0.0:5140", :receive_buffer_bytes=>"106496"
, :queue_size=>"2000"}
[2020-04-17T20:23:29,846][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

**Comment by a3ilson** [comment]
@repomanz - Alright...Logstash looks good.  Let's check pfSense:

(1) on your ELK instance, run ```sudo tcpdump -i eth0 -v -A -v port 5140``` replace eth0 with the network interface in use.  If pfSense is sending logs you'll see the traffic.

(2) on pfSense: navigate to Status>>System Logs>> Settings and ensure remote logging is configured.  Feel free to drop a screenshot:
![image](https://user-images.githubusercontent.com/16884679/79626245-a8c7c600-80fc-11ea-8c3b-7ab59ae6c142.png)

**Comment by repomanz** [comment]
![image](https://user-images.githubusercontent.com/20090451/79626362-41f2de80-80f5-11ea-95f8-1a485bcb9903.png)

**Comment by repomanz** [comment]
21:51:02.764544 IP (tos 0x0, ttl 64, id 8252, offset 0, flags [none], proto UDP (17), length 170)
    sixthSense.lan.syslog > vmdeblog.lan.5140: [udp sum ok] SYSLOG, length: 142
        Facility local0 (16), Severity info (6)
        Msg: Apr 17 21:51:02 filterlog: 360,,,1585954154,em1.20,match,pass,in,4,0x0,,64,56670,0,DF,17,udp,57,10.180.20.15,255.255.255.255,9999,9999,37
        0x0000:  3c31 3334 3e41 7072 2031 3720 3231 3a35
        0x0010:  313a 3032 2066 696c 7465 726c 6f67 3a20
        0x0020:  3336 302c 2c2c 3135 3835 3935 3431 3534
        0x0030:  2c65 6d31 2e32 302c 6d61 7463 682c 7061
        0x0040:  7373 2c69 6e2c 342c 3078 302c 2c36 342c
        0x0050:  3536 3637 302c 302c 4446 2c31 372c 7564
        0x0060:  702c 3537 2c31 302e 3138 302e 3230 2e31
        0x0070:  352c 3235 352e 3235 352e 3235 352e 3235
        0x0080:  352c 3939 3939 2c39 3939 392c 3337
E... <..@.:w

**Comment by repomanz** [comment]
Hey Andrew - I did a manual and auto install on to ubutu 18.04LTS and I'm getting content into logstash/kibana now.  If you have a moment, I think there are some fundamental issues with Debian 10 and the configurations, libraries or networking.   

I'll stay on ubuntu 18.04 LTS for now but would enjoy getting back to Debian 10 at some point.  You may want to also include a minimum spec.  I had to bump the VM memory to 4GB (which seems high) to get this to run.

**Comment by revere521** [comment]
i have a hardware server running my instance and it consistently consumes about 4Gb in its entirety.  I think elasticsearch is the culprit, but its parsing a huge amount of data even on just a homelab

**Comment by a3ilson** [comment]
Thanks!  I added the minimum RAM and will expanded on the memory configuration within the wiki section later.

**Comment by a3ilson** [comment]
@repomanz - Can you close this issue and open another specific to Debian?  Thanks!

**Comment by revere521** [comment]
Im going to close this for now, as it seems the core issue is resolved - and since we have the script to test the Debian 10.3 install
