### ISSUE TITLE
install script - java13 on ubuntu 18.04LTS

### ISSUE THREAD

**Issue by repomanz** [pfelk/pfelk#93]
**Describe the bug**
install script expects the repo to have oracle java 13.  Oracle Java 13 has been moved out of the main repo and errors that it can't find oracle java 13 during installation

**To Reproduce**
1. have ubuntu server 18.04lts installed
2. run the install script for pfelk

**Operating System (please complete the following information):**
Ubuntu server 18.04 LTS

**Comment by a3ilson** [comment]
@repomanz - Thanks!  I'll take a look at this later tonight.  I'll likely change to Java 8 throughout.

**Comment by a3ilson** [comment]
Fixed and updated to Java 11 LTS.
