### ISSUE TITLE
documentation instruction (step 5b import dashboard)

### ISSUE THREAD

**Issue by repomanz** [pfelk/pfelk#95]
Last step in configuration doesn't seem accurate or complete instructions.

- 5b. Import dashboards

    In your web browser go to the ELK local IP using port 5601 (ex: 192.168.0.1:5601)
    Click Management -> Saved Objects
    You can import the dashboards found in the Dashboard folder via the Import button in the top-right corner.

the version installed via auto script of kibana is 7.6.2

Downloaded this: 
https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/template/pf-geoip-template.json

Upon importing:
![image](https://user-images.githubusercontent.com/20090451/79641597-296ade80-815e-11ea-872f-6880763c1b88.png)

**Comment by repomanz** [comment]
can you attach your dashboards here? Would like to see if i can get them imported into kibana 7.6.2.  Do you have a snort dashboard as well?  I've added the snort logstash conf to my setup.

**Comment by revere521** [comment]
that file "https://raw.githubusercontent.com/3ilson/pfelk/master/conf.d/template/pf-geoip-template.json" is in the old json format; try one of these: 

https://github.com/3ilson/pfelk/tree/master/Dashboard

**Comment by revere521** [comment]
wait - if you are looking to import the dashboards, use one if the files in the link i posted. 

If you are looking to add the geoip template, I don't think you need to do that manually anymore - but thats not a dashboard

**Comment by repomanz** [comment]
The link you posted above was what i needed.    I can't seem to import the snort dashboard though, does nothing.  Do you have a working version of this?

**Comment by a3ilson** [comment]
@repomanz 
SNORT Dashboard: https://github.com/3ilson/pfelk/blob/master/Dashboard/v4.2%20(042020)%20Snort%20Dashboard.ndjson

Suricata Dashboard: https://github.com/3ilson/pfelk/blob/master/Dashboard/v4.2%20(042020)%20Suricata%20Dashboard.ndjson.ndjson

**Comment by repomanz** [comment]
This is the one I needed. 
![image](https://user-images.githubusercontent.com/20090451/79658198-faae3180-8178-11ea-92ea-e9400b14337c.png)

**Comment by revere521** [comment]
I just exported it again
[v4.2 (042020) Snort Dashboard.zip](https://github.com/3ilson/pfelk/files/4497341/v4.2.042020.Snort.Dashboard.zip)

If the one posted does not work for some reason, i'll re-upload it to the repo

**Comment by repomanz** [comment]
I tried the zip and the repo, neither import (with above no objects imported message).   I have the snort conf in my logstash conf.d folder, is there additional instructions i need for that?

**Comment by repomanz** [comment]
Additional snort / pfsense configurations?

**Comment by revere521** [comment]
you shouldn't need anything in the snort config.

I exported the snort dashboard again with saved objects included - but you may see artifacts (like additional pf-* indices)
[v4.2 (042020) Snort Dashboard Complete.zip](https://github.com/3ilson/pfelk/files/4497368/v4.2.042020.Snort.Dashboard.Complete.zip)

**Comment by repomanz** [comment]
that worked; seeing data now.

**Comment by repomanz** [comment]
Andrew / Revere521:

Thanks for the assists.  We have wargames up in here now. Look at all those russia blocks.   I'd be happy to beta the debian 10 rework at any time.  Let me know how to contact you guys.
![image](https://user-images.githubusercontent.com/20090451/79668661-1830ca80-817c-11ea-85ac-aeb246989849.png)

**Comment by revere521** [comment]
you may or may not be surprised by how much dubious traffic comes from RU...

I re-uploaded the snort dashboard with all the visualizations selected, but no related objects... i may or may not have remembered to export all the visualizations... 

anyway, i'm getting old...we'll go with that

**Comment by a3ilson** [comment]
@repomanz - Can this issues be closed? Has your issue been resolved?  

The tempalte is downloaded within step 19 and 20.  The 50-outputs.conf imports the template into Elasticsearch upon starting Logstash, which adjusted the GeoIP fields to be recognized as geo_point for mapping.

The dashboards are imported in step 5b...it appears you attempted to import the template into Kibana, which resulted in the error.  Based on the traffic above, it appears you got it working.  If so please close this issue.
