### ISSUE TITLE
Can you set location for "home" IP address instead of using Maxminds?

### ISSUE THREAD

**Issue by fastxl** [pfelk/pfelk#97]
Maxmind (GeoLite2) is showing my home IP location in the wrong place. Is there anyway I can set a "home" location using coordinates rather than using Maxminds location?

**Comment by revere521** [comment]
I don't think there is a straightforward way of doing this unfortunately.   You would have to write a script to find external IP addresses and replace them in the the elastic field data with one that aligns more closely with your physical location.    I think Maxmind just returns the location values for the IP address queried with no other logic.

**Comment by a3ilson** [comment]
The location is based off MaxMinds GeoIP data.  You can submit a change with MaxMind via the following link: https://support.maxmind.com/correction-faq/submit-a-correction/how-do-i-submit-a-correction-to-geoip-data/

**Comment by fastxl** [comment]
It's odd MaxMinds [webpage](https://www.maxmind.com/en/locate-my-ip-address) finds the location a whole lot closer than the GeoLite2 seems to. I will submit a request to correct. Anyway to test where the GeoLite2 database outside of Logstash or Kibana?

**Comment by a3ilson** [comment]
You can input the lat/long into google maps.

**Comment by fastxl** [comment]
Got it. I will submit to MaxMind for a correction. Thanks for the help.
